### ISSUE TITLE
突然一个报错，然后又没了

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1003]
2017-06-06 10:32:33,137 ERROR 6752 nodejs.unhandledExceptionError: "toString()" failed
    at Buffer.toString (buffer.js:509:11)
    at JSON.parse (<anonymous>)
    at Function.decode (C:\Users\Cat\Desktop\server\node_modules\cluster-client\lib\protocol\packet.js:87:26)
    at Socket.onReadable (C:\Users\Cat\Desktop\server\node_modules\cluster-client\lib\server.js:135:29)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at emitReadable_ (_stream_readable.js:434:10)
    at emitReadable (_stream_readable.js:428:7)
    at onEofChunk (_stream_readable.js:413:3)
    at readableAddChunk (_stream_readable.js:155:5)
name: 'unhandledExceptionError'
pid: 6752
hostname: DESKTOP-O8B9TF2

**Comment by okoala** [comment]
@acodercat  提供下能重新的代码或项目吧

**Comment by dead-horse** [comment]
ping @acodercat 能否提供一些详细的信息

**Comment by popomore** [comment]
如果还有问题再 reopen，信息比较少无法排查。
