### ISSUE TITLE
[egg-rest] Can not find plugin rest in ...

### ISSUE THREAD

**Issue by Quinton** [eggjs/egg#1019]
```
2017-06-08 10:39:39,192 INFO 70774 [master] agent_worker#1:70775 start with clusterPort:62374
/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg-core/lib/loader/mixin/plugin.js:340
    throw new Error(`Can not find plugin ${name} in "${lookupDirs.join(', ')}"`);
    ^

Error: Can not find plugin rest in "/Users/xuqifeng/Documents/Code/g-qrcode/node_modules, /Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg/node_modules, /Users/xuqifeng/Documents/Code/g-qrcode/node_modules"
    at AgentWorkerLoader.getPluginPath (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg-core/lib/loader/mixin/plugin.js:340:11)
    at AgentWorkerLoader.loadPlugin (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg-core/lib/loader/mixin/plugin.js:105:26)
    at AgentWorkerLoader.loadConfig (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg/lib/loader/agent_worker_loader.js:15:10)
    at EggApplication (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg/lib/egg.js:46:17)
    at Agent (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg/lib/agent.js:21:5)
    at Object.<anonymous> (/Users/xuqifeng/Documents/Code/g-qrcode/node_modules/egg-cluster/lib/agent_worker.js:19:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```
`yarn add egg-rest`
按照egg-rest文档配置，但是会报以上错误

* **Node Version**: 8.0.0
* **Egg Version**: 1.9.2
* **Plugin Name**: egg-rest
* **Plugin Version**: 1.3
* **Platform**: OSX
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
贴下你的 plugin.js, 然后在看看你的 node_modules 目录下有没有 egg-rest 这个目录

**Comment by atian25** [comment]
我知道了， egg-rest 现在不是内置插件了。

你的 plugin.js 应该写为：

```js
// config/plugin.js
exports.rest = {
  package: 'egg-rest',
}
```

我去修改下文档

**Comment by Quinton** [comment]
@atian25 ok了，谢了

**Comment by Quinton** [comment]
@atian25 
`Controllers in files matching ${baseDir}/app/apis/**.js will be loaded automatically according to routing rules.`
我觉得这个配置还起作用吗？我这边还是会自动加载 ${baseDir}/app/controller/**.js文件下的**.js 而非文档的 ${baseDir}/app/apis/**.js

**Comment by atian25** [comment]
这个插件我没用过， @dead-horse @popomore 看看？

**Comment by popomore** [comment]
Controller 一直会加载的，你可以给一个能复现的例子

**Comment by Quinton** [comment]
这边没问题了，启用这个插件，默认约定很多都不一样了。

**Comment by atian25** [comment]
具体指?

**Comment by popomore** [comment]
是的，我们建议使用 `app.resources` https://eggjs.org/zh-cn/basics/router.html#restful-风格的-url-定义
