### ISSUE TITLE
egg-socket.io引入报错

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1021]
2017-06-08 15:49:26,336 ERROR 1464 nodejs.AppWorkerDiedError: [master] app_worker#9:10508 died (code: 1, signal: 1, suicide: false, state: dead), current workers: []
    at Master.onAppExit (C:\Users\Cat\Desktop\server\node_modules\egg-cluster\lib\master.js:318:19)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (C:\Users\Cat\Desktop\server\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (C:\Users\Cat\Desktop\server\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at EventEmitter.cluster.on (C:\Users\Cat\Desktop\server\node_modules\egg-cluster\lib\master.js:215:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:179:13)
    at Object.onceWrapper (events.js:312:19)
name: 'AppWorkerDiedError'
pid: 1464
hostname: DESKTOP-O8B9TF2

**Comment by acodercat** [comment]
app.config.env = local
C:\Users\Cat\Desktop\server\node_modules\egg\lib\application.js:40
      throw e;
      ^

TypeError: Cannot convert undefined or null to object
    at Namespace.use (C:\Users\Cat\Desktop\server\node_modules\socket.io\lib\namespace.js:103:21)
    at initNsp (C:\Users\Cat\Desktop\server\node_modules\egg-socket.io\lib\io.js:80:9)
    at module.exports.app (C:\Users\Cat\Desktop\server\node_modules\egg-socket.io\lib\io.js:55:5)
    at AppWorkerLoader.loadFile (C:\Users\Cat\Desktop\server\node_modules\egg-core\lib\loader\egg_loader.js:269:30)
    at getLoadUnits.forEach.unit (C:\Users\Cat\Desktop\server\node_modules\egg-core\lib\loader\mixin\custom.js:25:29)
    at Array.forEach (native)
    at AppWorkerLoader.loadCustomApp (C:\Users\Cat\Desktop\server\node_modules\egg-core\lib\loader\mixin\custom.js:25:8)
    at AppWorkerLoader.load (C:\Users\Cat\Desktop\server\node_modules\egg\lib\loader\app_worker_loader.js:33:10)
    at new Application (C:\Users\Cat\Desktop\server\node_modules\egg\lib\application.js:36:19)
    at Object.<anonymous> (C:\Users\Cat\Desktop\server\node_modules\egg-cluster\lib\app_worker.js:13:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by dead-horse** [comment]
dump #997
