### ISSUE TITLE
restful Api用egg-validate的问题

### ISSUE THREAD

**Issue by jeremy16601** [eggjs/egg#1121]
直接调用  this.validate(createRule);  
为何报这个错误啊？
2017-06-28 11:23:18,988 WARN 21012 [-/127.0.0.1/-/79ms POST /api/v1/user] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\nodejs-Project\Exposure\node_modules\koa\lib\context.js:89:23)
    at Object.validate (D:\nodejs-Project\Exposure\node_modules\egg-validate\app\extend\context.js:14:17)
    at Object.exports.create (D:\nodejs-Project\Exposure\app\controller\v1\user.js:12:8)
    at exports.create.next (<anonymous>)
    at onFulfilled (D:\nodejs-Project\Exposure\node_modules\co\index.js:65:19)
    at D:\nodejs-Project\Exposure\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (D:\nodejs-Project\Exposure\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\nodejs-Project\Exposure\node_modules\co\index.js:118:63)
    at next (D:\nodejs-Project\Exposure\node_modules\co\index.js:99:29)
    at onFulfilled (D:\nodejs-Project\Exposure\node_modules\co\index.js:69:7)
    at D:\nodejs-Project\Exposure\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (D:\nodejs-Project\Exposure\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\nodejs-Project\Exposure\node_modules\co\index.js:118:63)
    at next (D:\nodejs-Project\Exposure\node_modules\co\index.js:99:29)
message: 'Validation Failed'
文档上写的不是 返回
{
  "error": "Validation Failed",
  "detail": [ { "message": "required", "field": "title", "code": "missing_field" } ]
}
求解，入门级菜鸟

**Comment by dead-horse** [comment]
`this.validate` 会直接将这个错误 throw 出去。

![image](https://user-images.githubusercontent.com/985607/27618349-70036706-5bee-11e7-9467-9334fd76d8e3.png)

**Comment by acodercat** [comment]
怎么在中间件捕获这个错误呢

**Comment by chaochao-zhang** [comment]
> 怎么在中间件捕获这个错误呢

RESTful API 部分有介绍，定义错误中间件，在catch里可以捕获这个错误。然后就可以定义返回的错误结构，示例代码也有。如果在其他中间件中利用egg-validate产生了这个错误,就去修改egg-validate 的this.throw部分
`validate(rules, data) {
    data = data || this.request.body;
    const errors = this.app.validator.validate(rules, data);
    if (errors) {
      this.throw(422, 'Validation Failed', {
        code: 'invalid_param',
        errors,
      });
    }
  }`
