### ISSUE TITLE
egg-sequelize频繁的查找超时报错

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#1128]
* **Node Version**: v8.1.2
* **Egg Version**: v1.5.0
* **egg-sequelize Version**: v3.0.1

查询代码
`
yield this.ctx.model.Natures.findAll({
        include: [{ model: this.ctx.model.NatureValue, required: true }],
        where: { is_sales: 0 },
      });
`

报错代码
`2017-06-30 10:33:01,839 ERROR 2877 [-/127.0.0.1/-/40337ms GET /api/nature/rule] nodejs.SequelizeDatabaseErr
or: read ETIMEDOUT
    at Query.formatError (/Users/TDiDa/ChainService/node_modules/sequelize/lib/dialects/mysql/query.js:222:
16)
    at Query.connection.query [as onResult] (/Users/TDiDa/ChainService/node_modules/sequelize/lib/dialects/
mysql/query.js:55:23)
    at Connection._notifyError (/Users/TDiDa/ChainService/node_modules/mysql2/lib/connection.js:212:25)
    at Connection._handleFatalError (/Users/TDiDa/ChainService/node_modules/mysql2/lib/connection.js:172:14
)
    at Connection._handleNetworkError (/Users/TDiDa/ChainService/node_modules/mysql2/lib/connection.js:177:
8)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at Query.run (/Users/TDiDa/ChainService/node_modules/sequelize/lib/dialects/mysql/query.js:44:12)
    at retry (/Users/TDiDa/ChainService/node_modules/sequelize/lib/sequelize.js:529:32)
    at /Users/TDiDa/ChainService/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/Users/TDiDa/ChainService/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/TDiDa/ChainService/node_modules/sequelize/lib/sequelize.js:529:1
4)
From previous event:
    at Sequelize.query (/Users/TDiDa/ChainService/node_modules/sequelize/lib/sequelize.js:526:8)
    at QueryInterface.select (/Users/TDiDa/ChainService/node_modules/sequelize/lib/query-interface.js:671:2
7)
    at Promise.try.then.then.then (/Users/TDiDa/ChainService/node_modules/sequelize/lib/model.js:1551:34)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Function.findAll (/Users/TDiDa/ChainService/node_modules/sequelize/lib/model.js:1548:8)
    at Nature.queryNoSale (/Users/TDiDa/ChainService/app/service/nature.js:23:51)
    at queryNoSale.next (<anonymous>)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/co/index.js:65:19)
    at /Users/TDiDa/ChainService/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/TDiDa/ChainService/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/TDiDa/ChainService/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/TDiDa/ChainService/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/TDiDa/ChainService/node_modules/co/index.js:50:10)
name: 'SequelizeDatabaseError'`

**Comment by dead-horse** [comment]
要么是 sequelize 的问题，要么是网络问题（这个可能性更大）
