### ISSUE TITLE
egg在windows的iisnode上跑出现错误 其他nodejs程序正常运行。

### ISSUE THREAD

**Issue by a741762308** [eggjs/egg#1159]
iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

2017-07-05 15:20:54,912 ERROR 5556 nodejs.AgentWorkerDiedError: [master] agent_worker#1:4088 died (code: 1, signal: null)
    at Master.onAgentExit (C:\Program Files\iisnode\www\app\node_modules\egg-cluster\lib\master.js:274:17)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (C:\Program Files\iisnode\www\app\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (C:\Program Files\iisnode\www\app\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at ChildProcess.agentWorker.once (C:\Program Files\iisnode\www\app\node_modules\egg-cluster\lib\master.js:181:22)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
name: 'AgentWorkerDiedError'
pid: 5556
hostname: iZtuhjiusgs8rmZ

2017-07-05 15:20:54,912 ERROR 5556 [master] agent_worker#1:4088 start fail, exiting with code:1

2017-07-05 15:20:54,912 ERROR 5556 [master] exit with code:1

**Comment by atian25** [comment]
前面的日志呢? 你的启动脚本是?

**Comment by a741762308** [comment]
没有任何stderr.log记录 。

**Comment by a741762308** [comment]
执行这句话EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &
                           stdout.log记录：'EGG_SERVER_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by atian25** [comment]
win 要改为 set 来配置环境变量

**Comment by a741762308** [comment]
运行没有任何输出。。。

**Comment by popomore** [comment]
Windows 支持重定向吗，这个是给 linux 部署用的，重来没部署过 Windows 的应用。

**Comment by a741762308** [comment]
支持啊  但是我用命令行直接是可以运行的

**Comment by popomore** [comment]
查了下支持的，看起来就环境变量不一样了

**Comment by ngot** [comment]
windows有 nohup ？

**Comment by ngot** [comment]
Windows部署一般是安装到系统服务器，然后以服务的方式来运行的。如果，对windows部署不熟悉，建议别在windows上做服务的部署，用 linux 简单一些

**Comment by ngot** [comment]
好像 `start /b ` 也可以

**Comment by liuhuanhui** [comment]
客户的机器  诶诶 没法说用linux啊

**Comment by ngot** [comment]
也许这个会有一些帮助： http://codetunnel.com/hosting-nodejs-applications-on-windows-server-2012-complete-with-git-deployment-and-remote-debugging-part-3/

**Comment by popomore** [comment]
这个自己研究下好了

**Comment by liuhuanhui** [comment]
谢谢 好的~

**Comment by atian25** [comment]
启动服务是一方面，他这个日志不全，只能看到是启动的时候， agent 挂掉了。

你可以试试 egg-init 一个 simple 项目丢上去跑跑看，然后逐个排查下是哪里出问题了，尤其是 agent 那里是不是有语法错误啥的。

**Comment by liuhuanhui** [comment]
但是这个项目我用npm run dev or npm start 是可以启动的啊

**Comment by atian25** [comment]
你看能否本地找到类似的环境再试试复现吧，这样没有日志，也没有复现方式，我们爱莫能助。

**Comment by liuhuanhui** [comment]
我刚重新egg init了一个项目，记录下来的错误日志是：
-------------------------第一个文件
2017-07-05 19:00:56,149 ERROR 2988 nodejs.AgentWorkerDiedError: [master] agent_worker#1:7644 died (code: 1, signal: null)
    at Master.onAgentExit (C:\Program Files\iisnode\www\egg-example\node_modules\egg-cluster\lib\master.js:274:17)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (C:\Program Files\iisnode\www\egg-example\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (C:\Program Files\iisnode\www\egg-example\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at ChildProcess.agentWorker.once (C:\Program Files\iisnode\www\egg-example\node_modules\egg-cluster\lib\master.js:181:22)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
name: 'AgentWorkerDiedError'
pid: 2988
hostname: iZtuhjiusgs8rmZ


2017-07-05 19:00:56,149 ERROR 2988 [master] agent_worker#1:7644 start fail, exiting with code:1

2017-07-05 19:00:56,149 ERROR 2988 [master] exit with code:1



--------------------第二个文件

2017-07-05 19:00:55,743 INFO 2988 [master] =================== egg start =====================

2017-07-05 19:00:55,743 INFO 2988 [master] egg version 1.6.0

2017-07-05 19:00:55,743 INFO 2988 [master] start with options: {"framework":"C:\\Program Files\\iisnode\\www\\egg-example\\node_modules\\egg","baseDir":"C:\\Program Files\\iisnode\\www\\egg-example","port":null,"workers":2,"plugins":null,"https":false,"key":"","cert":""}

2017-07-05 19:00:55,743 INFO 2988 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: undefined

2017-07-05 19:00:55,759 INFO 2988 [master] agent_worker#1:7644 start with clusterPort:52596
