### ISSUE TITLE
egg-mysql connect ECONNREFUSED

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#116]
centos服务器，数据库全部打包到docker中，本地数据库连接都没什么问题，放到服务器上无法启动，这是什么问题？

Message
connect ECONNREFUSED 127.0.0.1:3306 (code: ECONNREFUSED)
Full Trace
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    --------------------
    at Protocol._enqueue (/data/admin/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/data/admin/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/data/admin/node_modules/mysql/lib/Connection.js:136:18)
    at Pool.getConnection (/data/admin/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/data/admin/node_modules/mysql/lib/Pool.js:200:8)
    at Object.<anonymous> (/data/admin/node_modules/ali-rds/lib/client.js:28:10)
    at /data/admin/node_modules/co/index.js:136:8
    at Object.thunkToPromise (/data/admin/node_modules/co/index.js:135:10)
    at Object.toPromise (/data/admin/node_modules/co/index.js:119:55)
    at next (/data/admin/node_modules/co/index.js:99:29)
    sql: SELECT * FROM `admin` WHERE `username` = 'test@test.com' LIMIT 0, 1

**Comment by jtyjty99999** [comment]
使用https://github.com/mysqljs/mysql 写一个最简单的例子能连上吗，现在无法确定是插件还是环境问题

**Comment by zhoudaqing** [comment]
不好意思不是egg-mysql的问题

**Comment by qiwang97** [comment]
> centos服务器，数据库全部打包到docker中，本地数据库连接都没什么问题，放到服务器上无法启动，这是什么问题？
> 
> Message
> connect ECONNREFUSED 127.0.0.1:3306 (code: ECONNREFUSED)
> Full Trace
> Error: connect ECONNREFUSED 127.0.0.1:3306
> at Object.exports._errnoException (util.js:1036:11)
> at exports._exceptionWithHostPort (util.js:1059:20)
> at TCPConnectWrap.afterConnect as oncomplete
> --------------------
> at Protocol._enqueue (/data/admin/node_modules/mysql/lib/protocol/Protocol.js:141:48)
> at Protocol.handshake (/data/admin/node_modules/mysql/lib/protocol/Protocol.js:52:41)
> at PoolConnection.connect (/data/admin/node_modules/mysql/lib/Connection.js:136:18)
> at Pool.getConnection (/data/admin/node_modules/mysql/lib/Pool.js:48:16)
> at Pool.query (/data/admin/node_modules/mysql/lib/Pool.js:200:8)
> at Object. (/data/admin/node_modules/ali-rds/lib/client.js:28:10)
> at /data/admin/node_modules/co/index.js:136:8
> at Object.thunkToPromise (/data/admin/node_modules/co/index.js:135:10)
> at Object.toPromise (/data/admin/node_modules/co/index.js:119:55)
> at next (/data/admin/node_modules/co/index.js:99:29)
> sql: SELECT * FROM `admin` WHERE `username` = '[test@test.com](mailto:test@test.com)' LIMIT 0, 1

解决了么
