### ISSUE TITLE
初始化项目报错

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#1163]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

egg-init tradev1 --type=simple
[egg-init] use registry: https://registry.cnpmjs.org
[egg-init] target dir is /Users/joe/dev/eggv2/tradev1
[egg-init] fetching npm info of egg-init-config
[egg-init] use boilerplate: simple(egg-boilerplate-simple)
[egg-init] fetching npm info of egg-boilerplate-simple
[egg-init] downloading https://r.cnpmjs.org/egg-boilerplate-simple/download/egg-boilerplate-simple-2.7.0.tgz
ResponseTimeoutError: Response timeout for 5000ms, GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/egg-boilerplate-simple/-/egg-boilerplate-simple-2.7.0.tgz -1 (connected: true, keepalive socket: false)
headers: {}
    at Timeout._onTimeout (/usr/local/lib/node_modules/egg-init/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
zouyongliangdeMacBook-Pro:eggv2 joe$
zouyongliangdeMacBook-Pro:eggv2 joe$ egg-init tradev2 --type=simple
[egg-init] use registry: https://registry.cnpmjs.org
[egg-init] target dir is /Users/joe/dev/eggv2/tradev2
[egg-init] fetching npm info of egg-init-config
[egg-init] use boilerplate: simple(egg-boilerplate-simple)
[egg-init] fetching npm info of egg-boilerplate-simple
[egg-init] downloading https://r.cnpmjs.org/egg-boilerplate-simple/download/egg-boilerplate-simple-2.7.0.tgz
[egg-init] extract to /var/folders/1q/x7mttqrn4_79vt0kjwnd66kc0000gn/T/egg-init-boilerplate
[egg-init] collecting boilerplate config...
? project name tradev2
? project description
? project author
? cookie security keys 1499333122332_3831
AssertionError: Trying to copy from a source that does not exist: /var/folders/1q/x7mttqrn4_79vt0kjwnd66kc0000gn/T/egg-init-boilerplate/package/boilerplate/_.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:57:3)
    at files.forEach.file (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (native)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at files.forEach.file (/usr/local/lib/node_modules/egg-init/lib/init_command.js:202:16)
    at Array.forEach (native)
    at Command.processFiles (/usr/local/lib/node_modules/egg-init/lib/init_command.js:199:11)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/egg-init/node_modules/_co@4.6.0@co/index.js:65:19)

**Comment by Ailein** [comment]
多次重试如下

zouyongliangdeMacBook-Pro:eggv2 joe$ egg-init tradev3 --type=simple
[egg-init] use registry: https://registry.cnpmjs.org
[egg-init] target dir is /Users/joe/dev/eggv2/tradev3
[egg-init] fetching npm info of egg-init-config
[egg-init] use boilerplate: simple(egg-boilerplate-simple)
[egg-init] fetching npm info of egg-boilerplate-simple
[egg-init] downloading https://r.cnpmjs.org/egg-boilerplate-simple/download/egg-boilerplate-simple-2.7.0.tgz
[egg-init] extract to /var/folders/1q/x7mttqrn4_79vt0kjwnd66kc0000gn/T/egg-init-boilerplate
[egg-init] collecting boilerplate config...
? project name tradev3
? project description
? project author
? cookie security keys 1499333280156_2906
AssertionError: Trying to copy from a source that does not exist: /var/folders/1q/x7mttqrn4_79vt0kjwnd66kc0000gn/T/egg-init-boilerplate/package/boilerplate/_.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:57:3)
    at files.forEach.file (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (native)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/egg-init/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at files.forEach.file (/usr/local/lib/node_modules/egg-init/lib/init_command.js:202:16)
    at Array.forEach (native)
    at Command.processFiles (/usr/local/lib/node_modules/egg-init/lib/init_command.js:199:11)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/egg-init/node_modules/_co@4.6.0@co/index.js:65:19)

**Comment by atian25** [comment]
> ResponseTimeoutError: Response timeout for 5000ms

你的网络问题，多重试几次。

删除下 `/var/folders/1q/x7mttqrn4_79vt0kjwnd66kc0000gn/T/egg-init-boilerplate/` 这个目录

**Comment by Ailein** [comment]
找到原因了，  cnpm 和npm 的问题，
cnpm 是通过npm install -g cnpm --registry=https://registry.npm.taobao.org安装的,
然后也用cnpm 安装过egg-init
然后 我用npm 更新了egg-init , 接着egg-init初始化项目就报错，
最后 重新安装 一次  cnpm i egg-init -g 
 

就可以，不报错了。

**Comment by atian25** [comment]
你上面的过程可以复现么?

**Comment by Ailein** [comment]
现在复现不出来了,奇怪的问题。

**Comment by Timson020** [comment]
# egg-init(error)

## os: 

mac

## node: 

10.15.0

## global node_module:

babel-cli gulp-cli react-native-cli vue-cli eslint-cli yarn n npm egg-init

## error_msg: 
```
/usr/local/lib/node_modules/egg-init/node_modules/errlop/index.js:4
module.exports = require('editions').requirePackage(__dirname, require)
                                     ^

TypeError: require(...).requirePackage is not a function
```

**Comment by atian25** [comment]
执行了什么指令？

**Comment by Timson020** [comment]
egg-init Ex --type=simple

**Comment by atian25** [comment]
重新安装下 egg-init 看看，这是一个很底层的类库报错。
我本地试了下没复现。

PS：如果你是 npm@6 node@10 的话，可以直接 `npm init egg showcase --type=simple` 不用安装 egg-init 了。

**Comment by Timson020** [comment]
重新 install 就没事了
安装的时候报warning

```
deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
```
