### ISSUE TITLE
docker容器内调用nanomsg库失败

### ISSUE THREAD

**Issue by StephenSeraph** [eggjs/egg#1188]
* **Node Version**: 8.1.4
* **Egg Version**: 1.6.0
* **Docker Base Image**: node:8.1.4-alpine

### 正常情形
- 不使用框架的node项目，调用nanomsg库，本机环境下，运行正常；
- 不使用框架的node项目，调用nanomsg库，docker环境下，运行正常；
- 使用egg框架的node项目，调用nanomsg库，本机环境下，运行正常；
### 报错情形
- 使用egg框架的node项目，调用nanomsg库，docker环境下，当调用`nano.socket('req')`函数时，程序报错。
- 错误提示如下：
```
[Thu Jul 13 2017 09:39:27 GMT+0000 (UTC)] [cfork:master:27] worker:43 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false)
[Thu Jul 13 2017 09:39:27 GMT+0000 (UTC)] [cfork:master:27] don't fork new work (refork: false)
2017-07-13 09:39:27,690 INFO 27 [master] app_worker#1:43 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[Thu Jul 13 2017 09:39:27 GMT+0000 (UTC)] [cfork:master:27] worker:43 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true)
2017-07-13 09:39:27,692 ERROR 27 nodejs.AppWorkerDiedError: [master] app_worker#1:43 died (code: null, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/usr/src/app/node_modules/egg-cluster/lib/master.js:326:19)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (/usr/src/app/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/usr/src/app/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/usr/src/app/node_modules/egg-cluster/lib/master.js:223:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:169:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
```
### 复现步骤
1. 用`egg-init --type=simple`建一个项目，
2. 安装nano库`npm i nanomsg`，
3. 在docker容器内运行，
4. 在任意地方调用`nano.socket('req')`时，程序报错
### 最小复现仓库
[egg-nano-test](https://github.com/StephenSeraph/egg-nano-test)

**Comment by ngot** [comment]
这个issue 我觉得应该要作为最赞模范issue👍

**Comment by atian25** [comment]
对 docker 不是很熟，看你的步骤，有点怀疑是 nanomsg 这个原生插件的问题，你是在寄主机器上安装的，但跑在 alpine 里面，试下在 docker 里面才安装依赖？

**Comment by jtyjty99999** [comment]
没有docker环境，我给个建议你看行不行：

- 在app.js里初始化 nanomsg，挂载到 app.nanomsg上，如果你有pub sub的需求就在app 上挂两个，并且 connect/bind起来
- 在controller里使用 app.nanomsg 去调用试试？

另外你这个报错信息有点少。。。

**Comment by popomore** [comment]
写个 dockerfile 吧，应该可以重现

**Comment by StephenSeraph** [comment]
- 昨天忙些其他事，没来得及看，感谢各位的关注和建议！
- @atian25 说的alpine再次提醒了我，今天我重新把测试项目clone下来，确实不行，然后我把基础镜像由`node:8.1.4-apline`改为`node:8.1.4`，好吧，通过了……然后我回过头来，翻找了一下之前所谓的不使用框架的测试项目，发现我用的镜像是`node:8.1.2`……(晚上睡觉前先面壁10分钟)。
记得之前确实一开始就想过可能是系统镜像精简的问题，但是印象中我是第一时间就通过在原项目里切换基础镜像来测试的，没有通过，然后才有了后来的另外开项目专门测试。
- 那么
**结论** ：基础镜像由`node:8.1.4-alpine`切换为`node:8.1.4`，就是不要用alpine这个极度精简版的镜像。
简单分析一下：nanomsg这个c写的通信库依赖的有系统底层的某些库(至于是哪些，这个嘛，我对C不是很熟悉，也没看过nano源码)，这些库在alpine中被精简掉了。
- 再次感谢各位！应该可以关掉了。
