### ISSUE TITLE
egg-jsonp 插件报错 Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by DoranYun** [eggjs/egg#1219]
使用的是 begg ，打印了一下，`ctx.get('referrer')` 取不到值。

begg@3.2.0
egg-jsonp@1.1.1
tnpm@4.22.3 
npm@3.10.10 
node@8.1.3
npminstall@3.0.1

路由配置方式

```
module.exports = app => {
  const jsonp = app.jsonp();

  app.get('/common/getUser.jsonp', jsonp, 'common.user.doGetUserInfos');
};
```

错误日志：

```
2017-07-21 11:51:17,802 ERROR 24647 [-/111030/::1/1e08492015006090777991001d6047/16ms GET /common/getUser.jsonp] nodejs.TypeError: Cannot read property 'endsWith' of null
    at /Users/YunDong/Projects/magic-data/node_modules/_egg-jsonp@1.1.1@egg-jsonp/app/extend/application.js:99:18
    at securityAssert (/Users/YunDong/Projects/magic-data/node_modules/_egg-jsonp@1.1.1@egg-jsonp/app/extend/application.js:54:31)
    at Object.jsonp (/Users/YunDong/Projects/magic-data/node_modules/_egg-jsonp@1.1.1@egg-jsonp/app/extend/application.js:65:7)
    at next (native)
    at Object.dispatch (/Users/YunDong/Projects/magic-data/node_modules/_koa-router@5.4.2@koa-router/lib/router.js:334:12)
    at next (native)
    at onFulfilled (/Users/YunDong/Projects/magic-data/node_modules/_co@4.6.0@co/index.js:65:19)
    at /Users/YunDong/Projects/magic-data/node_modules/_co@4.6.0@co/index.js:54:5
    at Object.co (/Users/YunDong/Projects/magic-data/node_modules/_co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/YunDong/Projects/magic-data/node_modules/_co@4.6.0@co/index.js:118:63)
```

**Comment by dead-horse** [comment]
根据 https://github.com/koajs/koa/blob/7294eae07890b2cf07f7f6fc2b7f234423064203/lib/request.js#L630 来看，ctx.get('referrer') 不可能是 null

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-jsonp/blob/master/app/extend/application.js#L87

应该是 parse 出来的 hostname 为 null 吧

**Comment by dead-horse** [comment]
已修复，重新安装依赖就好了

**Comment by DoranYun** [comment]
👍🏼

**Comment by mayaohan** [comment]
代码：
const { router, controller,jsonp } = app; 
router.post('/jsonpDemo',jsonp(callback:'oramt'),controller.validate.create)
报错：
Cannot read property 'config' of undefined
    at jsonp (D:\my\egg-example\node_modules\egg-jsonp\app\extend\application.js:16:33)
    at module.exports.app (D:\my\egg-example\app\router.js:4:17)
。。。

**Comment by mayaohan** [comment]
代码：
const { router, controller,jsonp } = app;
router.post('/jsonpDemo',jsonp({callback:'oramt'}),controller.validate.create)
报错：
Cannot read property 'config' of undefined
at jsonp (D:\my\egg-example\node_modules\egg-jsonp\app\extend\application.js:16:33)
at module.exports.app (D:\my\egg-example\app\router.js:4:17)
。。。

**Comment by atian25** [comment]
jsonp(options, app)
要传递第二个参数
