### ISSUE TITLE
使用yield*比yield能获得更完整的call stack

### ISSUE THREAD

**Issue by FF-Mercurial** [eggjs/egg#1251]
`egg`的文档，以及网上看到大多数对于`co`的使用，都是用`yield`而不是`yield*`来串联异步流，而实际上用`yield*`能在捕获异常时获得更完整的call stack（`yield`只能获得抛出层的调用信息，父级调用信息被丢失）

===附上case===
使用`yield`：
```
const co = require('co');

co(function* () {
    yield foo1();
}).catch(err => {
    console.log(err);
});

function* foo1() {
    return yield foo2();
}

function* foo2() {
    throw new Error('f**k');
}
```
异常信息中丢失了`foo1`的调用信息：
```
Error: f**k
    at foo2 (/home/ff-mercurial/wm-tools/foo2.js:14:11)
    at next (native)
    at onFulfilled (/home/ff-mercurial/wm-tools/node_modules/co/index.js:65:19)
    at /home/ff-mercurial/wm-tools/node_modules/co/index.js:54:5
    at co (/home/ff-mercurial/wm-tools/node_modules/co/index.js:50:10)
    at toPromise (/home/ff-mercurial/wm-tools/node_modules/co/index.js:118:63)
    at next (/home/ff-mercurial/wm-tools/node_modules/co/index.js:99:29)
    at onFulfilled (/home/ff-mercurial/wm-tools/node_modules/co/index.js:69:7)
    at /home/ff-mercurial/wm-tools/node_modules/co/index.js:54:5
    at co (/home/ff-mercurial/wm-tools/node_modules/co/index.js:50:10)
```
使用`yield*`：
```
const co = require('co');

co(function* () {
    yield* foo1();
}).catch(err => {
    console.log(err);
});

function* foo1() {
    return yield* foo2();
}

function* foo2() {
    throw new Error('f**k');
}
```
异常信息中包含了完整的`foo1`>`foo2`的调用信息：
```
Error: f**k
    at foo2 (/home/ff-mercurial/wm-tools/foo2.js:14:11)
    at next (native)
    at foo1 (/home/ff-mercurial/wm-tools/foo2.js:10:19)
    at next (native)
    at /home/ff-mercurial/wm-tools/foo2.js:4:12
    at next (native)
    at onFulfilled (/home/ff-mercurial/wm-tools/node_modules/co/index.js:65:19)
    at /home/ff-mercurial/wm-tools/node_modules/co/index.js:54:5
    at co (/home/ff-mercurial/wm-tools/node_modules/co/index.js:50:10)
    at Object.<anonymous> (/home/ff-mercurial/wm-tools/foo2.js:3:1)
```

**Comment by popomore** [comment]
主要是不一定 yield 一个 generator

**Comment by FF-Mercurial** [comment]
@popomore 
yield*不能处理的场景有几类：
1. Function：由于不是异步操作，用yield也不会切断call stack
2. Promise：会切断call stack，但通常Promise封装的异步操作只会出现在偏下层（上层用Generator-Function）
3. Array/Object：用于实现并发（本身也有语法糖作用），会切断call stack，但这是少数场景

结合上述分析可以得到以下实践（同时使用yield和yield*）：
1. Function：用yield
2. Promise：用yield，且尽量将Promise封装的异步操作沉底，上层使用Generator-Function
3. Array/Object：用yield
4. Generator：用yield*

如此一来，相比统一用yield的方案，通过牺牲一点复杂度（本来只有yield现在多了yield*，理解generator&co原理的前提下这个其实也不能算增加了复杂度），在大多数异步流中都能获得完整的call stack（不完整的情况包括偏下层的Promise和少数并发场景下的Array/Object，call stack被截底），我认为这种实践是利大于弊的

**Comment by popomore** [comment]
这个不必讨论了，提供这种方式就是为了一般开发者不用理解 generator，明白的人直接用就好了。而且很快就迎来 Node8 LTS，可以观察下 async function 的堆栈。

**Comment by dead-horse** [comment]
关掉了，koa 团队也不建议使用 yield *，为以后迁移 async function 做准备。

**Comment by JacksonTian** [comment]
yield* 确实可以获得更好的 stack，不过往前看吧，async functions 会更好。
