### ISSUE TITLE
同样的逻辑，为什么在 service 里面一个执行，一个又不执行？

### ISSUE THREAD

**Issue by MiYogurt** [eggjs/egg#1258]
* **Node Version**:  v8.1.2
* **Egg Version**: 1.6.1
* **Platform**: mac os

这是 service/user.js

```js
    class UserService extends app.Service {
        // 登录判断
        async login({
            email,
            password
        }) {
            const {
                ctx
            } = this;
            try{
                const user = await this.findByEmail(email);
                this.userLoginCheck(user, ctx, password)
                ctx.session.user = user
                user.last_login_time = new Date()
                await user.save()
                ctx.fsuccess('登陆成功', '欢迎回来。', '/')
            }catch(e){
                console.log(e)
            }

        }

        userLoginCheck(user, ctx, password) {
            if (!user) ctx.ferror('出错了', '不存在当前用户', '/login')

            if (!user.email_verified) {
                console.log("没有验证的邮箱")
                ctx.ferror('请先验证邮箱', '没有验证的邮箱', '/activate')
            }

            if (!user.checkPwd(password)) {
                console.log("密码不匹配")
                ctx.ferror('出错了', '密码不匹配！', '/login')
            }
        }
}
```

context.js

```js
function msgBuilder(type) {
    return (title, text, to) =>{
        this.flash = { type, title, text };
        console.log(this.redirect)
        if ( to ) this.redirect(to);
    }
}

module.exports = {
    ferror(title, text, to, ctx){
        if (!ctx) ctx = this;
        let error = msgBuilder.call(ctx, 'error')
        error(title, text, to);
    },
    fsuccess(title, text, to, ctx){
        if (!ctx) ctx = this;
        let success = msgBuilder.call(ctx, 'success');
        success(title, text, to);
    }
}
```

后面2个没有执行。

打印出来的信息像这样

```bash
没有验证的邮箱
[Function]
密码不匹配
[Function]
......
[Function]
```
为什么不进行跳转呢？怎么这么迷呢？我新建一个最小的仓库无法复现这个 bug，有一次清空浏览器缓存就好了。

调试日志如下：
![image](https://user-images.githubusercontent.com/10082395/28741812-f826c1b6-7451-11e7-951a-1957c2aacb90.png)

![image](https://user-images.githubusercontent.com/10082395/28741822-48bbafc4-7452-11e7-94d9-815a7fd42d29.png)
我发现进入这里的时候，这里的 this 指向 global，但是打印出来的是 Function，

![image](https://user-images.githubusercontent.com/10082395/28741829-7346eb1e-7452-11e7-93ba-c25094f197d7.png)

global 下面是没有 redirect 方法的。

![image](https://user-images.githubusercontent.com/10082395/28741890-78651656-7453-11e7-810f-066bc8eb22a2.png)

鼠标放上来，好像还是有的，指向也是正确的。

![image](https://user-images.githubusercontent.com/10082395/28741902-9ea90d36-7453-11e7-9e5e-bb5ff1ef90e5.png)

然后也没发生跳转，也没报错。

然后 cluster 给了这么一个错误，我估计是调试太久的原因

```js
2017-07-29 11:35:32,489 ERROR 6838 nodejs.ClusterClientNoResponseError: client no response in 78689ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/Yugo/Desktop/nodelover/node_modules/cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
name: 'ClusterClientNoResponseError'
pid: 6838
```

写成这样也是这2个也是无法正常工作的。

```js
                if (!user) ctx.ferror('出错了', '不存在当前用户', '/login') // 可以跳转

                if (!user.email_verified) {
                    console.log("没有验证的邮箱")
                    // ctx.ferror('请先验证邮箱', '没有验证的邮箱')
                    ctx.flash = { title:'a', text: 'b', type: 'error' }
                    ctx.redirect('/activate') // 没反应
                }

                if (!user.checkPwd(password)) {
                    console.log("密码不匹配")
                    // ctx.ferror('出错了', '密码不匹配！')
                    ctx.flash = { title:'a', text: 'b', type: 'error' }
                    ctx.redirect('/activate') // 没反应
                }

                ctx.session.user = user
                user.last_login_time = new Date()
                await user.save()
                ctx.fsuccess('登陆成功', '欢迎回来。', '/') // 可以跳转
```

**Comment by popomore** [comment]
为啥不能return

**Comment by MiYogurt** [comment]
@popomore  可以 return啊.
```js
            const {
                ctx
            } = this;
            const user = await this.findByEmail(email);

            if (!user) return ctx.ferror('出错了', '不存在当前用户', '/login')
            if (!user.email_verified) return ctx.ferror('请先验证邮箱', '没有验证的邮箱', '/activate')
            if (!user.checkPwd(password)) return ctx.ferror('出错了', '密码不匹配！', '/login')

            ctx.session.user = user
            user.last_login_time = new Date()
            await user.save()
            return ctx.fsuccess('登陆成功', '欢迎回来。', '/') 
```

这样就可以正常工作了，假如把这三个 单独拿出来，再做一次抽象的话，供 service 的其他方法复用的话就又没法正常工作了。

**Comment by popomore** [comment]
因为你主流程没 return 啊

**Comment by MiYogurt** [comment]
就算没有 return 为什么有一个可以正常工作，而其他2个又不行呢？

**Comment by popomore** [comment]
校验出错要直接返回，不要继续往下执行，没时间看你具体逻辑，你继续调试吧。
