### ISSUE TITLE
egg-sequelize和egg-mongoose一起用，我看了之前的issues还没是搞懂怎么实现

### ISSUE THREAD

**Issue by barretzhi** [eggjs/egg#1290]
* **Node Version**:8.1.0
* **Egg Version**:1.7.0
* **Plugin Name**:egg-sequelize/egg-mongoose
* **Plugin Version**:3.1.0/2.1.0
* **Platform**:Win 10
* **Mini Showcase Repository**:
我尝试使用两个插件，我看了以前提交的问题，去找解决问题的办法。但是尝试了好多种不行。

# 我尝试
```js
           sequelize: {
                dialect: 'mysql',
                port: 3306,
                host: '',
                database: '',
                username: '',
                password: '',
                modelDir: 'app/model/mysql'
            },
            //mongoee
            mongoose: {
                url: '',
                modelDir: 'app/model/mongoose',
            }
```

# 但是出现

```bash
PS F:\MYCODE\movieservice> npm run dev

> movieservice@1.0.0 dev F:\MYCODE\movieservice
> egg-bin dev

2017-08-04 15:29:33,428 INFO 6808 [master] egg version 1.7.0
F:\MYCODE\movieservice\app\model\user.js:2
    const { STRING, INTEGER, DATE } = app.Sequelize;
                                         ^

TypeError: Cannot match against 'undefined' or 'null'.
    at module.exports.app (F:\MYCODE\movieservice\app\model\user.js:2:42)
    at getExports (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\file_loader.js:214:15)
    at FileLoader.parse (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\file_loader.js:152:25)
    at FileLoader.load (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\file_loader.js:67:24)
    at AgentWorkerLoader.loadToApp (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\egg_loader.js:335:25)
    at loadModel (F:\MYCODE\movieservice\node_modules\egg-mongoose\lib\mongoose.js:61:14)
    at module.exports.app (F:\MYCODE\movieservice\node_modules\egg-mongoose\lib\mongoose.js:42:3)
    at module.exports.agent (F:\MYCODE\movieservice\node_modules\egg-mongoose\agent.js:4:28)
    at AgentWorkerLoader.loadFile (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\egg_loader.js:269:30)
    at getLoadUnits.forEach.unit (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\mixin\custom.js:33:29)
    at Array.forEach (native)
    at AgentWorkerLoader.loadCustomAgent (F:\MYCODE\movieservice\node_modules\egg-core\lib\loader\mixin\custom.js:33:8)
    at AgentWorkerLoader.load (F:\MYCODE\movieservice\node_modules\egg\lib\loader\agent_worker_loader.js:21:10)
    at new Agent (F:\MYCODE\movieservice\node_modules\egg\lib\agent.js:25:17)
    at Object.<anonymous> (F:\MYCODE\movieservice\node_modules\egg-cluster\lib\agent_worker.js:22:15)
    at Module._compile (module.js:569:30)
2017-08-04 15:29:34,037 ERROR 6808 nodejs.AgentWorkerDiedError: [master] agent_worker#1:15132 died (code: 1, signal: null)
    at Master.onAgentExit (F:\MYCODE\movieservice\node_modules\egg-cluster\lib\master.js:281:17)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (F:\MYCODE\movieservice\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (F:\MYCODE\movieservice\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at ChildProcess.agentWorker.once (F:\MYCODE\movieservice\node_modules\egg-cluster\lib\master.js:188:22)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
name: 'AgentWorkerDiedError'
pid: 6808
hostname: USER-20160428OY

2017-08-04 15:29:34,037 ERROR 6808 [master] agent_worker#1:15132 start fail, exiting with code:1
2017-08-04 15:29:34,038 ERROR 6808 [master] exit with code:1
⚠️  Error: F:\MYCODE\movieservice\node_modules\egg-bin\lib\start-cluster {"baseDir":"F:\\MYCODE\\movieservice","framework":"F:\\MYCODE\\movieservice\\node_modules\\egg","workers":1} exit wit
h code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! movieservice@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the movieservice@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by atian25** [comment]
贴下 app\model\user.js

**Comment by barretzhi** [comment]
```js
module.exports = app => {
    const { STRING, DATE } = app.Sequelize;

    const User = app.model.define('users', {
        username: STRING,
        name: STRING(30),
        password: STRING(32),
        created_at: DATE,
        updated_at: DATE,
    });

    return User;
};
```

**Comment by atian25** [comment]
> at module.exports.app (F:\MYCODE\movieservice\node_modules\egg-mongoose\lib\mongoose.js:42:3)

我感觉是你没配置对目录，这里这句 log 是用 `egg-mongoose` to 加载 sequelize 的文件了。

**Comment by iyuq** [comment]
egg-mongoose和egg-sequelize都会去加载model文件夹下的所有文件，目前应该两个插件不可以一起用。

**Comment by barretzhi** [comment]
@atian25   我也发了那个modelDir  感觉不起作用

**Comment by atian25** [comment]
还不支持这个特性吧，我看了源码。
- https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L60
- https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L48

印象中之前好像提过不要混用的。

**Comment by barretzhi** [comment]
好的谢谢，我爬虫的获取的数据不规则放在了MongoDB， 其他的都放在了MySQL,所以需要两个都用到

**Comment by iyuq** [comment]
@atian25 感觉可以在egg-mongoose和egg-sequelize中加两个配置项，配置model加载的文件夹和挂载到app上的名字，这样就可以两个一起用了。

**Comment by atian25** [comment]
有请 @huacnlee @jtyjty99999 ，印象中讨论过的。

**Comment by popomore** [comment]
这个会过滤啊，返回实例匹配才会挂载

**Comment by lifengzhai** [comment]
目前自己改 egg-mongoose 的加载目录

**Comment by jtyjty99999** [comment]
不会同时加载的。。我们这边就有这种用法，有过滤器的

**Comment by barretzhi** [comment]
@jtyjty99999  
```js
 sequelize: {
                dialect: 'mysql',
                port: 3306,
                host: '',
                database: '',
                username: '',
                password: '',
                modelDir: 'app/model/mysql'
            },
            //mongoee
            mongoose: {
                url: '',
                modelDir: 'app/model/mongoose',
            }
```
这种形式配置吗？

**Comment by popomore** [comment]
感觉 sequelize 插件没开，不然 app.Sequelize 不会为 null

**Comment by popomore** [comment]
提供可重新的 demo 再 reopen

**Comment by IEfucker** [comment]
感觉这种场景也挺常见的，关注

**Comment by LeoFengFromChina** [comment]
在config/config.default.js文件中的：
config.sequelize = {
...
    delegate: 'model/sequelize', //指定你的model路径
    baseDir: 'model/sequelize', //指定你的model路径
};
 参考插件文档的说明：https://github.com/eggjs/egg-sequelize

**Comment by LeoFengFromChina** [comment]
### 关于多类型数据源支持（sequelize和mongoose）
> 一个egg项目要同时支持sequelize和mongoose，需要做特殊的配置。</br>

- 由于mongoose支持的默认加载model的路径无法修改（`app/model`),所以只能修改sequelize的model加载路径；

- 修改配置：
```
config.sequelize = {
    dialect: 'mysql',
    host: '...',
    port: 3306,
    database: '...',
    username: 'root',
    password: '...',
    delegate: 'sequelizeModel', //挂载到app上的model名称，此配置后可以通过app.sequelizeModel访问
    baseDir: 'model/sequelize', //由于mongoose已占用了默认的model路径，所以新增一个sequelize文件夹来存储sequelize要检测的model文件
  };    
```
- 调用方式：`ctx.sequelizeModel.User.findAll()`
