### ISSUE TITLE
OpenShift线上部署egg:core:ready_timeout的问题。

### ISSUE THREAD

**Issue by zhangming0305** [eggjs/egg#1298]
* **Node Version**: 6.11.2
* **Egg Version**: 1.7.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: 
* **Mini Showcase Repository**:

本地运行或者本地docker运行没有任何问题。递交给客户以后上线有问题。客户使用openshift部署。所有的plugin都不能安装。请大神帮忙看一下。

npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.2
npm info lifecycle node-less-api@1.0.0~prestart: node-less-api@1.0.0
npm info lifecycle node-less-api@1.0.0~start: node-less-api@1.0.0
> node-less-api@1.0.0 start /var/www
> node index.js
2017-08-07 11:03:56,653 INFO 20 [master] =================== egg start =====================
2017-08-07 11:03:56,655 INFO 20 [master] egg version 1.7.0
2017-08-07 11:03:56,656 INFO 20 [master] start with options: {"framework":"/var/www/node_modules/egg","baseDir":"/var/www","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":""}
2017-08-07 11:03:56,656 INFO 20 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: staging
2017-08-07 11:03:56,669 INFO 20 [master] agent_worker#1:26 start with clusterPort:41444
2017-08-07 11:03:57,274 INFO 20 [master] agent_worker#1:26 started (612ms)
2017-08-07 11:03:57,275 INFO 20 [master] start appWorker with args ["{\"framework\":\"/var/www/node_modules/egg\",\"baseDir\":\"/var/www\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"clusterPort\":41444}"]
2017-08-07 11:03:57,283 INFO 20 [master] app_worker#1:36 start, state: none, current workers: ["1"]
2017-08-07 11:04:14,453 WARN 36 [egg:core:ready_timeout] 10 seconds later /var/www/node_modules/egg-watcher/app.js:15:7 was still unable to finish.
2017-08-07 11:04:14,460 INFO 20 [master] app_worker#1:36 started at 7001, remain 0 (17185ms)
2017-08-07 11:04:14,461 INFO 20 [master] egg started on http://127.0.0.1:7001 (17805ms)

**Comment by atian25** [comment]
> 2017-08-07 11:04:14,453 WARN 36 [egg:core:ready_timeout] 10 seconds later /var/www/node_modules/egg-watcher/app.js:15:7 was still unable to finish.

难道是 wt 读文件的平台兼容性问题？ cc @shaoshuai0102

**Comment by zhangming0305** [comment]
备注：客户拿到的是docker image

**Comment by popomore** [comment]
EGG_SERVER_ENV: undefined, NODE_ENV: staging

环境变量不对

**Comment by zhangming0305** [comment]
这两个没有填对，对系统有怎么大影响么？必须使用 
- "NODE_ENV=production"
- "EGG_SERVER_ENV=prod"
么？

**Comment by popomore** [comment]
不然变成了本地开发环境

**Comment by zhangming0305** [comment]
我试试。

**Comment by zhangming0305** [comment]
让客户设置了
"NODE_ENV=production"
"EGG_SERVER_ENV=prod"
参数。情况变的更奇怪了：有时候启动很快，有时候就像下面的log所述 timeout，有的时候就直接启动不了。客户估计是cluster的问题。请大神们帮忙诊断一下。


2017-08-07 14:38:19,993 WARN 36 [egg:core:ready_timeout] 10 seconds later /var/www/node_modules/egg-watcher/app.js:15:7 was still unable to finish.
2017-08-07 14:38:47,525 WARN 36 nodejs.ResponseTimeoutError: Server no response in 3000ms, address#127.0.0.1:38479
   at Timeout._invokes.set.timer.setTimeout [as _onTimeout] (/var/www/node_modules/tcp-base/lib/base.js:223:21)
   at ontimeout (timers.js:386:14)
   at tryOnTimeout (timers.js:250:5)
   at Timer.listOnTimeout (timers.js:214:5)
socketMeta: { id: 2, dataLength: 75, bufferSize1: 0, bufferSize2: 0, startTime: 1502116713603, endTime: 1502116714495, writeSuccess: true }
name: 'ResponseTimeoutError'
pid: 36
hostname: mandantencss-service-39-jv9xq
2017-08-07 14:38:52,961 INFO 36 [egg-watcher:app] watcher start success
2017-08-07 14:38:53,093 INFO 20 [master] app_worker#1:36 started at 7001, remain 0 (46120ms)
2017-08-07 14:38:53,117 INFO 20 [master] egg started on http://127.0.0.1:7001 (46964ms)

**Comment by zhangming0305** [comment]
有没有非cluster启动application的方式？

**Comment by popomore** [comment]
是不是之前起了个服务没杀掉

**Comment by zhangming0305** [comment]
准备在openshift自己调试一下。

**Comment by zhangming0305** [comment]
更新一下： 在本公司的openshift上运行没有任何问题。看来是客户的openshift的安全设置的问题。
