### ISSUE TITLE
剩下的不稳定的用例

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#134]
## logger

logger 是有缓冲的，需要等待更长时间

```
 1) test/app/extend/context.test.js ctx.logger env=prod: level => info:
     AssertionError: expected '2016-10-28 13:21:40,526 ERROR 2966 [-/127.0.0.1/-/2ms GET /logger?message=foo] nodejs.Error: error foo\n    at Object.module.exports (/home/travis/build/eggjs/egg/test/fixtures/apps/demo/app/controller/logger.js:9:21)\n    at module.exports.next (<anonymous>)\n    at Object.dispatch (/home/travis/build/eggjs/egg/node_modules/.5.4.0@koa-router/lib/router.js:336:14)\n    at dispatch.next (<anonymous>)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:65:19)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at /home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:54:5\n    at Object.co (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:50:10)\n    at Object.toPromise (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:118:63)\n    at next (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:99:29)\n    at onFulfilled (/home/travis/build/eggjs/egg/node_modules/.4.6.0@co/index.js:69:7)\n    at process._tickCallback (internal/process/next_tick.js:103:7)\n\npid: 2966\nhostname: testing-worker-linux-docker-417833d8-3457-linux-12\n\n' to contain 'nodejs.Error: core error foo'
      at Assertion.fail (node_modules/.11.1.1@should/cjs/should.js:205:17)
      at Assertion.value [as containEql] (node_modules/.11.1.1@should/cjs/should.js:277:19)
      at Context.<anonymous> (test/app/extend/context.test.js:89:27)
      at Generator.next (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
## curl

应该换成 google 之类的

```
  1) test/app/extend/context.test.js ctx.curl() should curl ok:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at Timeout.<anonymous> (node_modules/.3.1.2@mocha/lib/runnable.js:232:19)
```
## schedule

```
  1) test/lib/plugins/schedule.test.js should schedule work:
     AssertionError: expected 0 to be within 1..2
      at Assertion.fail (node_modules/.11.1.1@should/cjs/should.js:205:17)
      at Assertion.value [as within] (node_modules/.11.1.1@should/cjs/should.js:277:19)
      at Context.<anonymous> (test/lib/plugins/schedule.test.js:16:34)
      at Generator.next (<anonymous>)
```

**Comment by popomore** [comment]
@dead-horse schedule 那个看要怎么改？还不知道为啥会没有

**Comment by popomore** [comment]
logger 和 curl 都修了

**Comment by atian25** [comment]
logger 有没有办法直接在内存里面校验, 不要等写磁盘

**Comment by popomore** [comment]
那就没有测试的意义了

**Comment by atian25** [comment]
在其他地方, 如 schedule 的 cluster 测试, 只能通过验证日志的方式.

**Comment by popomore** [comment]
在这里跟进吧 https://github.com/eggjs/egg/issues/29
