### ISSUE TITLE
ctx.curl 请求图片遇到的一些问题

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1341]
### 需求是这样的：
在egg中请求一张图片的buffer。
### 代码中是这样写的：
```javascript
module.exports = app => {
  class Test extends app.Service {
    * getImageBuffer(url) {
      const { ctx } = this;
      const result = yield ctx.curl(url, {
        timeout: 20000,
      });
      
      return result.data;
    }
  }

  return Test;
}
```
### 实际遇到的问题：
在本地开发的时候，可以获取到图片的buffer，
但是在线上环境。请求就会报出以下错误。
```
2017-08-22 13:10:08,747 ERROR 16631 [-/182.201.174.232/-/72184ms POST /api/v1/event/image?id=22] nodejs.RequestError: socket hang up (req "error"), GET http://24liveblog.tradingfront.cn/watermark/e4da3b7fbbce2345d7772b0674a318d5.png -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":9,"createSocketErrorCount":0,"closeSocketCount":9,"errorSocketCount":0,"timeoutSocketCount":9,"requestCount":8,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
code: 'ECONNRESET'
name: 'RequestError'
data: undefined
path: '/watermark/e4da3b7fbbce2345d7772b0674a318d5.png'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 30004, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://24liveblog.tradingfront.cn/watermark/e4da3b7fbbce2345d7772b0674a318d5.png' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 16631
hostname: li1242-25.members.linode.com
```
### 另外补充：
图片的路径可以尝试使用： `https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503414433116&di=75e06c91392d4b185a33dc9785a02587&imgtype=0&src=http%3A%2F%2Fimage.tupian114.com%2F20140718%2F11020173.jpg.thumb.jpg`
对于httpClient的相关配置都是默认的。

**Comment by liujinyang1994** [comment]
@fengmk2

**Comment by popomore** [comment]
你服务器能访问这个域名吗

**Comment by liujinyang1994** [comment]
@popomore 可以的

**Comment by fengmk2** [comment]
ECONNRESET 可以看到网络错误了。`rt: 30004` 代表这次请求发出到拿到 ECONNRESET 异常耗时了 30秒。

最好你自己手动执行 curl -v your-image-url 测试看看，特别是在你的线上环境。

**Comment by liujinyang1994** [comment]
通过你说的方法，我试了一下。
```
* About to connect() to 24liveblog.tradingfront.cn port 80 (#0)
*   Trying 2400:cb00:2048:1::6812:37f7... connected
* Connected to 24liveblog.tradingfront.cn (2400:cb00:2048:1::6812:37f7) port 80 (#0)
> GET /watermark/e4da3b7fbbce2345d7772b0674a318d5.png HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 24liveblog.tradingfront.cn
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 24 Aug 2017 01:46:32 GMT
< Content-Type: image/png
< Content-Length: 3394
< Connection: keep-alive
< Set-Cookie: __cfduid=d47d607505482ed319ce59da0c94f49eb1503539191; expires=Fri, 24-Aug-18 01:46:31 GMT; path=/; domain=.tradingfront.cn; HttpOnly
< X-Source: C/200
< Content-Disposition: inline; filename="e4da3b7fbbce2345d7772b0674a318d5.png"; filename*=utf-8' 'e4da3b7fbbce2345d7772b0674a318d5.png
< X-Reqid: b3IAADN2CBe01twU
< Cache-Control: max-age=2592000
< ETag: "FkZcDSDQZg2IL5YW2ZSzO6bnJfkh"
< Last-Modified: Mon, 21 Aug 2017 10:47:22 GMT
< X-M-Log: QNM:xs476;SRCPROXY:xs486;SRCPROXY:215;QNM2:217
< Content-Transfer-Encoding: binary
< X-Qnm-Cache: Miss,Proxy,Cache
< Access-Control-Expose-Headers: X-Log, X-Reqid
< Access-Control-Allow-Origin: *
< X-M-Reqid: b3IAADN2CBe01twU
< X-Qiniu-Zone: na0
< Access-Control-Max-Age: 2592000
< X-Log: mc.g/404;mc.g/500;rs1_1.sel;rwro.get;RS.dbs;mc.s/500;RS:1;mc.s;s.gh;PFDS;IO:3
< Accept-Ranges: bytes
< Expires: Wed, 20 Sep 2017 10:50:00 GMT
< Age: 226750
< X-Request-Id: b1331dea8ea3ec4540f6ec88ac1daf18; fb82cc532cc89d866d3860eb3587f89a
< Via: S.ntt-cn-hkg-008, T.2327.M.1, V.ntt-cn-hkg-007, T.51100.H.2, T.51100.H.1, M.gtt-de-fra-103
< Server: cloudflare-nginx
< CF-RAY: 3932a36d97b021a4-EWR

文件内容...

real	0m0.953s
user	0m0.003s
sys	0m0.003s
```

**Comment by fengmk2** [comment]
那就是可以的啊，ECONNRESET 是一直大量出现还是少量出现？

**Comment by liujinyang1994** [comment]
稳定出现。只要在线上就会出现这个问题。

**Comment by liujinyang1994** [comment]
我在想是不是因为网络问题？

**Comment by atian25** [comment]
自己排查下网络问题吧，或者是防盗链了，egg 这块没啥问题。

发自我的 iPhone

**Comment by liujinyang1994** [comment]
好的，谢谢。

**Comment by fengmk2** [comment]
@liujinyang1994 你可以将 ua 在代码里面伪造一下，然后看看是否跟 curl 命令后一致。

```
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
```

**Comment by liujinyang1994** [comment]
@fengmk2  谢谢，前几天一直在忙，今天下午试一下。

**Comment by 1019272778** [comment]
这个问题解决了吗？

**Comment by jinyang1994** [comment]
@1019272778 解决了，是我依赖的一个库里面的问题，那个库需要安装一个C++的安装包，安装之后就有问题。
