### ISSUE TITLE
egg-security 关闭之后，post请求还是出现invalid csrf token

### ISSUE THREAD

**Issue by ivwitxsc** [eggjs/egg#1397]
//plugin.js
`
'use` strict';
exports.validate = {
  enable: true,
  package: 'egg-validate',
};
exports.static = true;
exports.security = {
  xframe: {
    enable: false,
  },
};
`
就把cnode-api项目在本地运行之后，修改了这个安全验证，关闭之。但是我post请求还是会出现invalid csrf token的问题。还有我需要注意的地方吗？

**Comment by atian25** [comment]
exports.security = {
  xframe: {
  enable: false,
},

这段是配置，放到 config.default.js

发自我的 iPhone

> 在 2017年9月8日，14:39，放荡年华 <notifications@github.com> 写道：
> 
> exports.security = {
> xframe: {
> enable: false,
> },
> };

**Comment by ivwitxsc** [comment]
//config.default.js
```
'use strict';

module.exports = {
  middleware: [ 'errorHandler' ],
  errorHandler: {
    match: '/api',
  },
  security: {
    xframe: {
      enable: false,
    },
  },
};
```
这种也试过，我是用postman  post 请求的
```
Please set config.keys first, now using mock keys for dev env (E:\FrontEndWorkspace\egg\cnode-api)
2017-09-08 14:48:50,540 WARN 8716 [-/127.0.0.1/-/26ms POST /api/v2/topics/getRecord] invalid csrf token. See https://eggjs.org/zh-cn/core/security.html#安全威胁csrf的防范
2017-09-08 14:48:50,543 WARN 8716 [-/127.0.0.1/-/28ms POST /api/v2/topics/getRecord] nodejs.ForbiddenError: invalid csrf token
    at Object.throw (E:\FrontEndWorkspace\egg\cnode-api\node_modules\koa\lib\context.js:89:23)
    at Object.assertCsrf (E:\FrontEndWorkspace\egg\cnode-api\node_modules\egg-security\app\extend\context.js:148:17)
    at Object.csrf (E:\FrontEndWorkspace\egg\cnode-api\node_modules\egg-security\lib\middlewares\csrf.js:31:10)
    at csrf.next (<anonymous>)
    at Object.<anonymous> (E:\FrontEndWorkspace\egg\cnode-api\node_modules\koa-compose\index.js:28:19)
    at Generator.next (<anonymous>)
    at onFulfilled (E:\FrontEndWorkspace\egg\cnode-api\node_modules\co\index.js:65:19)
    at E:\FrontEndWorkspace\egg\cnode-api\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (E:\FrontEndWorkspace\egg\cnode-api\node_modules\co\index.js:50:10)
message: 'invalid csrf token'
pid: 8716
```

**Comment by atian25** [comment]
可是你关的是 xframe 

发自我的 iPhone

**Comment by jtyjty99999** [comment]
关闭csrf是 

`exports.security = {
  csrf: {
  enable: false,
},`

**Comment by lazyyman** [comment]
楼主最后怎么搞定的，求告知

**Comment by kenuyx** [comment]
我也遇到同样的问题，`egg-security` 关了却还是报 403 forbidden。`egg` 版本是 2.2.1。

config/config.default.js
```
'use strict';

module.exports = appInfo => {
  const config = (exports = {});

  // use for cookie sign key, should change to your own and keep security
  config.keys = MY_OWN_KEY;

  // add your config here
  config.middleware = [];

  config.redis = {
    client: {
      port: 6379,
      host: '127.0.0.1',
      password: null,
      db: 2,
    },
  };

  config.security = {
    csrf: {
      enable: false,
    },
  };
  
  return config;
};

```

app/router.js
```
'use strict';

/**
 * @param {Egg.Application} app - egg application
 */
module.exports = app => {
  const { router, controller } = app;
  router.resources('sessions', '/sessions', 'sessions');
  router.get('/', controller.home.index);
};

```

`curl` 的结果是
```
$ curl -vX POST http://127.0.0.1:7001/sessions --data '{"code":"code"}' --header 'Content-Type:application/json'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 7001 (#0)
> POST /sessions HTTP/1.1
> Host: 127.0.0.1:7001
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 15
>
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 403 Forbidden
< Accept-Ranges: bytes
< set-cookie: csrfToken=goMYHBP1HI35qaNGBBULS5kI; path=/
< content-type: text/html; charset=utf-8
< content-length: 22
< Date: Mon, 05 Mar 2018 06:11:01 GMT
< Connection: keep-alive
<
* Connection #0 to host 127.0.0.1 left intact
<h2>403 Forbidden</h2>%   
```

看过运行时的最终配置和配置文件的参数相符，但就是一直报403。试过文档提到的例子 `examples/cnode-api` 倒是可以的，但例子的 `egg` 版本是 1.13.0 。

**Comment by guozefei** [comment]
我也是用Postman发送的请求，关闭了csrf后还是报invalid csrf token，求问楼主解决了吗

**Comment by Stupidism** [comment]
@guozefei @ghost 你们不会在 plugin 里面 关 csrf 的吧?
应该要在 config.default 或者 config.local 里面

**Comment by guozefei** [comment]
我是enable写错了 写成enabled 导致出错 不好意思 @Stupidism
