### ISSUE TITLE
egg.js 生产环境部署第二天12点发生运行错误

### ISSUE THREAD

**Issue by jamescheng16** [eggjs/egg#1402]
* **Node Version**:v8.4.0
* **Egg Version**: V1.7.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: ubuntu
* **Mini Showcase Repository**:

生产环境ubuntu 部署 egg.js服务，发现第二天12点会程序会出错，不知道是不是因为没有 sudo 运行？

错误日志 ： 

> common-error.log

`2017-09-08 00:00:00,027 ERROR 19440 nodejs.ENOENTError: ENOENT: no such file or directory,       scandir '/home/ge/logs/data-api'
ENOENTError: ENOENT: no such file or directory, scandir '/home/ge/logs/data-api'
errno: -2
code: 'ENOENT'
syscall: 'scandir'
path: '/home/ge/logs/data-api'
name: 'ENOENTError'
pid: 19440
hostname: ubuntu`

> master-stderr.log

`[Fri Sep 08 2017 00:00:30 GMT+0800 (CST)] [cfork:master:19419] worker:19440 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true)
2017-09-08 00:00:30,049 ERROR 19419 nodejs.AppWorkerDiedError: [master] app_worker#2:19440 died (code: 1, signal: 1, suicide: true, state: dead), current workers: ["61"]
    at Master.onAppExit (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/master.js:333:19)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/master.js:230:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
pid: 19419
hostname: ubuntu

/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg@1.7.0@egg/lib/application.js:39
      throw e;
      ^

Error: EACCES: permission denied, mkdir '/home/ge/logs'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_mkdirp@0.5.1@mkdirp/index.js:71:13)
    at Function.sync (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_mkdirp@0.5.1@mkdirp/index.js:77:24)
    at FileBufferTransport._createStream (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/transports/file.js:97:12)
    at FileBufferTransport.reload (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/transports/file.js:46:25)
    at FileBufferTransport.FileTransport (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/transports/file.js:29:10)
    at FileBufferTransport (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/transports/file_buffer.js:21:5)
    at Map.EggLogger (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/egg/logger.js:36:27)
    at ErrorLogger (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/egg/error_logger.js:17:5)
    at new Loggers (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-logger@1.6.0@egg-logger/lib/egg/loggers.js:66:25)
[Fri Sep 08 2017 00:00:30 GMT+0800 (CST)] [cfork:master:19419] worker:19972 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false)
[Fri Sep 08 2017 00:00:30 GMT+0800 (CST)] [cfork:master:19419] worker died too fast (total 61 disconnect, 0 unexpected exit)
[Fri Sep 08 2017 00:00:30 GMT+0800 (CST)] [cfork:master:19419] don't fork new work (refork: true)
[Fri Sep 08 2017 00:00:30 GMT+0800 (CST)] [cfork:master:19419] worker:19972 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true)
2017-09-08 00:00:30,073 ERROR 19419 nodejs.AppWorkerDiedError: [master] app_worker#61:19972 died (code: 1, signal: 1, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/master.js:333:19)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/usr/local/ge/data-service/ge-repository/Service-api/data-api/node_modules/_egg-cluster@1.9.2@egg-cluster/lib/master.js:230:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
pid: 19419
hostname: ubuntu
`

**Comment by atian25** [comment]
报错信息： `Error: EACCES: permission denied, mkdir '/home/ge/logs'`

[egg-logrotator](https://github.com/eggjs/egg-logrotator) 自动切割日志时，创建目录失败，没权限。
