### ISSUE TITLE
--out-dir dist --source-maps --presets env

### ISSUE THREAD

**Issue by YAO-JSON** [eggjs/egg#1412]
/usr/local/bin/babel app/controller/home.js --out-dir dist --source-maps --presets env
Error: Couldn't find preset "env" relative to directory "app/controller"
    at /usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:50:22)

Process finished with exit code 1

**Comment by atian25** [comment]
看起来是 babel 这个 env presets 的问题，你可以去查查

**Comment by YAO-JSON** [comment]
不影响 我开发 但是 总是报错 看着不爽

**Comment by YAO-JSON** [comment]
我是使用 egg-init 脚手架 初始化的项目，在webstorm output中总是提示 这个错误；全局配置 好像也不行

**Comment by atian25** [comment]
> Error: Couldn't find preset "env" relative to directory "app/controller"

egg 的脚骨架没有配置 babel 的，我们也不推荐用 babel 来转译后端代码。
如果有问题的话，需要你自己排查下 WebStorm 和 Babel 的逻辑。

**Comment by YAO-JSON** [comment]
安装 babel-preset-env 即可
