### ISSUE TITLE
post 数据过大怎么设置的让它大一些呢

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#1422]
2017-09-13 13:32:00,038 WARN 22934 [-/192.168.30.121/-/1ms POST /api/article/update] nodejs.PayloadTooLargeError: request entity too large
    at readStream (/mydata/code/zhengshi/egg-back/node_modules/raw-body/index.js:155:17)
    at executor (/mydata/code/zhengshi/egg-back/node_modules/raw-body/index.js:112:5)
    at getRawBody (/mydata/code/zhengshi/egg-back/node_modules/raw-body/index.js:111:10)
    at /mydata/code/zhengshi/egg-back/node_modules/co-body/lib/json.js:41:14
message: 'request entity too large'
expected: 115753
length: 115753
limit: 102400
type: 'entity.too.large'
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 22934

**Comment by whxaxes** [comment]
可以通过配置来设置大小：

```js
  exports.bodyParser = {
    jsonLimit: '5mb',
    formLimit: '6mb',
  };
```

**Comment by buzai** [comment]
@whxaxes thank u
