### ISSUE TITLE
alinode使用问题

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#1474]
使用egg-alinode时，在扩展配置里面已经配置完毕，APPID和App secret都已配置，环境变量也已配置，但是无法在alinode控制台显示目前服务器的情况。

**Comment by tong3jie** [comment]
已经通过npm i egg-alinode 安装，但是启动报错。
···
Error: Can not find plugin alinode in "/home/hangye/201709241550/node_modules, /home/hangye/201709241550/node_modules/egg/node_modules, /home/hangye/201709241550/node_modules"
    at AgentWorkerLoader.getPluginPath (/home/hangye/201709241550/node_modules/egg-core/lib/loader/mixin/plugin.js:341:11)
    at AgentWorkerLoader.loadPlugin (/home/hangye/201709241550/node_modules/egg-core/lib/loader/mixin/plugin.js:105:26)
    at AgentWorkerLoader.loadConfig (/home/hangye/201709241550/node_modules/egg/lib/loader/agent_worker_loader.js:15:10)
    at EggApplication (/home/hangye/201709241550/node_modules/egg/lib/egg.js:48:17)
    at Agent (/home/hangye/201709241550/node_modules/egg/lib/agent.js:21:5)
    at Object.<anonymous> (/home/hangye/201709241550/node_modules/egg-cluster/lib/agent_worker.js:22:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)

···

**Comment by atian25** [comment]
贴下你的 plugin.js ，然后确认下 `ls node_modules/egg-alinode` 是否安装成功。

**Comment by tong3jie** [comment]
![_20170929001704](https://user-images.githubusercontent.com/14191774/30977928-9ca811d4-a4ab-11e7-876b-deedfc5ce7b6.png)


//plugin.js
exports.alinode = true;

// config/config.default.js
exports.alinode = {
  enable: true,
  appid: 'XXX',
  secret: 'XXXXX',
};

**Comment by atian25** [comment]
exports.alinode = {
  enable: true,
  package: 'egg-alinode',
}

发自我的 iPhone

> 在 2017年9月29日，00:19，juju <notifications@github.com> 写道：
> 
> exports.alinode

**Comment by tong3jie** [comment]
非常感谢。
建议egg-alinode的文档修改一下。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-alinode/pull/8 已经改完了

**Comment by tong3jie** [comment]
@atian25   启用了alinode，egg的worker进程无法启动了
2017-09-30 13:24:26,752 ERROR 32010 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:32010)
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at listenOnMasterHandle (net.js:1410:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 32010
hostname: iZwz985sjvpojhmx4x5kjuZ

2017-09-30 13:24:26,762 ERROR 32009 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:32009)
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at listenOnMasterHandle (net.js:1410:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 32009
hostname: iZwz985sjvpojhmx4x5kjuZ

2017-09-30 13:24:27,521 ERROR 32033 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:32033)
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at listenOnMasterHandle (net.js:1410:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 32033
hostname: iZwz985sjvpojhmx4x5kjuZ

**Comment by atian25** [comment]
跟 alinode 无关，你的端口冲突了 `bind EADDRINUSE null:7001`
