### ISSUE TITLE
不知道是否 eggjs  还是 Sequelize  还是co包的问题. 批量操作会出现重复插入问题 

### ISSUE THREAD

**Issue by callmez** [eggjs/egg#1485]
# 这是我们项目一个同步以太坊数据的 计划任务.  大大们可以忽略细节部分.  大概看下流程.
# 行注释里我有给出一些解释或者提问.  请帮review下 谢谢了 

```js
const _ = require('lodash')
const co = require('co')
/**
 * key的驼峰格式转下划线
 * @param data
 * @returns {*}
 */
function humpToUnderline(data) {
    if (_.isObjectLike(data)) {
        _.forEach(data, function(v, k) {
            delete data[k]
            k = k.replace(/([A-Z])/g, '_$1').toLowerCase()
            data[k] = v
        })
    }
    return data
}
// 保存区块 block数据
function saveBlock(block) {
    const app = this
    var data = _.extend({}, {
        id: block.number,
        transaction_count: block.transactions.length
    }, humpToUnderline(block))
    co(function * () {
        yield app.model.EthBlock.create(data)
        for (var v of data.transactions) {
            saveTransaction.call(app, v)
            saveAccount.call(app, yield app.web3.eth.getTransactionReceipt(v.hash))
        }
    })
}
// 保存区块 交易数据
function saveTransaction(transaction) {
    const app = this
    var data = _.extend({}, {
        block_id: transaction.blockNumber,
    }, humpToUnderline(transaction))
    co(function * () {
        yield app.model.EthTransaction.create(data)
    })
}
// 保存区块交易里 涉及到的账户数据
function saveAccount(receipt) {
    const app = this
    const { web3 } = app
    var addresses = [receipt.from, receipt.to]
    var logAddresses = _.map(receipt.logs, function(log) {
        return log.address
    })
    var data = {}
    co(function * () {
        for (let address of _.uniq(addresses.concat(logAddresses))) {
            var _data = {
                address: address,
                balance: yield web3.eth.getBalance(address),
                type: app.model.EthAccount.TYPE_NORMAL
            }
            if ((yield web3.eth.getCode(address)).length > 2) { // 判断合约
                _data.type = app.model.EthAccount.TYPE_CONTRACT
                var token = new web3.eth.Contract(web3.defaultTokenAbi, address)
                try { // 函数调用错误  则判断为非token
                    var symbol = yield token.methods.symbol().call()
                } catch(e) { }

                if (symbol) { // 通过symbol()判断是否token合约
                    _.extend(_data, {
                        type: app.model.EthAccount.TYPE_TOKEN,
                        token_name: yield token.methods.name().call(),
                        token_symbol: symbol,
                        token_decimals: yield token.methods.decimals().call()
                    })
                    yield app.model.EthAccount.create(_data)
                    for (var account of _.uniq(addresses, address)) { // 记录账号余额
                        var result = yield app.model.EthTokenBalance.findOrInitialize({
                            where: {
                                address: account,
                                token_address: address
                            },
                            defaults: {
                                address: account,
                                token_address: address,
                            }
                        })
                        if (result[1]) {
                            var model = result[0]
                            model.set('token_balance', yield token.methods.balanceOf(account).call())
                            yield model.save()
                        }
                    }
                }
            }
        }
    })
}

var isruning = false
module.exports = {
    // 通过 schedule 属性来设置定时任务的执行间隔等配置
    schedule: {
        interval: '15s', // 15秒一次
        type: 'all', // 指定所有的 worker 都需要执行
    },
    // task 是真正定时任务执行时被运行的函数，第一个参数是一个匿名的 context 实例
    * task(ctx) {

        if (isruning) return // 用来防止重复运行,   可否做个加锁选项?
        isruning = true

        const { app } = ctx

        var start = (yield app.model.EthBlock.max('id')) || 0
        var blockNumber = (yield app.web3.eth.getBlockNumber()) || 0 // 目前以太坊有430w数据, 几千万交易, 是个大的任务.

        var block
        for (var i = start + 1; i <= blockNumber; i++) { 
            block = yield app.web3.eth.getBlock(i, true) // 从客户端拉去block数据
            app.model.transaction(() => {
                saveBlock.call(ctx.app, block); // 开始保存
            })
        }

        isRuning = false
    },
};

```

### 错误日志
```
2017-09-30 18:19:21,954 INFO 3677 [model] COMMIT; (13ms)
2017-09-30 18:19:21,969 INFO 3677 [model] INSERT INTO `tz_eth_block` (`id`,`hash`,`parent_hash`,`miner`,`gas_limit`,`gas_used`,`difficulty`,`total_difficulty`,`transactions_count`,`transactions_root`,`uncles_count`,`receipts_root`,`sha3_uncles`,`nonce`,`mix_hash`,`extra_data`,`logs_bloom`,`size`,`timestamp`,`created_at`) VALUES (4000025,'0x4e2290892bbb973bd5bb4453277a57b2e1464ac0ca1cd6990e3450bb90fc4322','0x7a5465b5f1efd9946f196388d6c8118bb2ef0bb13605e096ae23949223b857b5','0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8',6712392,576095,'1106928909229140','469052541224814191998','0','0x9089155739a7ecf5471693911de32bbe3a83839c5a337f72379576960067435c','0','0x62de3c90795aec99dffb17e77c0e28b59a915e082d2654e443d309ef6823a62b','0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347','0xa62af5dd90d6d94f','0xd26b830f3f12e0114696a2cc65c7fcabc8a3f688cdb6b52ec503f9288a050502','0x65746865726d696e652d757333','0x0000000000000000000001000000000000000000040000000000800000000000000000010020000000000000008000010800000000000080000000400000004000000000000000008000000c000000000001000000000402000000080000000820080000020000080000010000000800004009200000000000400010004000008000000100000000000000000400000100000040400000000000000000000000400000004000000000000000800000010000000000000020000000000000000000000002000000000000000000800000000000000000000108100040000021000000000000100000000080000000000400080100400000000000000000000000',2465,1499633844,'2017-09-30 10:19:21'); (20ms)
(node:3677) Warning: a promise was created in a handler but was not returned from it
2017-09-30 18:19:21,975 ERROR 3677 nodejs.SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Volumes/File/go/chacha/node_modules/sequelize/lib/dialects/mysql/query.js:201:16)
    at Query.connection.query [as onResult] (/Volumes/File/go/chacha/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/Volumes/File/go/chacha/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/Volumes/File/go/chacha/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
From previous event:
    at Query.run (/Volumes/File/go/chacha/node_modules/sequelize/lib/dialects/mysql/query.js:44:12)
    at retry (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:533:32)
    at /Volumes/File/go/chacha/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Volumes/File/go/chacha/node_modules/retry-as-promised/index.js:29:10)
    at Promise.try.then.connection (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:533:14)
From previous event:
    at Sequelize.query (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:529:8)
    at QueryInterface.insert (/Volumes/File/go/chacha/node_modules/sequelize/lib/query-interface.js:837:27)
    at Promise.try.then.then.then (/Volumes/File/go/chacha/node_modules/sequelize/lib/model.js:3579:56)
From previous event:
    at model.save (/Volumes/File/go/chacha/node_modules/sequelize/lib/model.js:3555:8)
    at Function.create (/Volumes/File/go/chacha/node_modules/sequelize/lib/model.js:1986:8)
    at /Volumes/File/go/chacha/app/schedule/ethereum_sync.js:26:34
    at Generator.next (<anonymous>)
    at onFulfilled (/Volumes/File/go/chacha/node_modules/co/index.js:65:19)
    at /Volumes/File/go/chacha/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at co (/Volumes/File/go/chacha/node_modules/co/index.js:50:10)
    at Application.saveBlock (/Volumes/File/go/chacha/app/schedule/ethereum_sync.js:25:5)
    at app.model.transaction (/Volumes/File/go/chacha/app/schedule/ethereum_sync.js:122:27)
    at transaction.prepareEnvironment.then (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:960:21)
From previous event:
    at Sequelize._clsRun (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:960:10)
    at Function._clsRun (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:1004:21)
    at Sequelize.transaction (/Volumes/File/go/chacha/node_modules/sequelize/lib/sequelize.js:958:22)
    at task (/Volumes/File/go/chacha/app/schedule/ethereum_sync.js:121:23)
    at task.next (<anonymous>)
    at onFulfilled (/Volumes/File/go/chacha/node_modules/co/index.js:65:19)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
name: 'SequelizeUniqueConstraintError'
errors: [ ValidationErrorItem { message: 'PRIMARY must be unique', type: 'unique violation', path: 'PRIMARY', value: '4000025' } ]
fields: { PRIMARY: '4000025' }
parent: { Error: Duplicate entry '4000025' for key 'PRIMARY' at Packet.asError (/Volumes/File/go/chacha/node_modules/mysql2/lib/packets/packet.js:703:13) at Query.Command.execute (/Volumes/File/go/chacha/node_modules/mysql2/lib/commands/command.js:28:22) at Connection.handlePacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:515:28) at PacketParser.onPacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:94:16) at PacketParser.executeStart (/Volumes/File/go/chacha/node_modules/mysql2/lib/packet_parser.js:77:14) at Socket.<anonymous> (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:102:29) at emitOne (events.js:115:13) at Socket.emit (events.js:210:7) at addChunk (_stream_readable.js:266:12) at readableAddChunk (_stream_readable.js:253:11) at Socket.Readable.push (_stream_readable.js:211:10) at TCP.onread (net.js:585:20) code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '#23000', sql: 'INSERT INTO `tz_eth_block` (`id`,`hash`,`parent_hash`,`miner`,`gas_limit`,`gas_used`,`difficulty`,`total_difficulty`,`transactions_count`,`transactions_root`,`uncles_count`,`receipts_root`,`sha3_uncles`,`nonce`,`mix_hash`,`extra_data`,`logs_bloom`,`size`,`timestamp`,`created_at`) VALUES (4000025,\'0x4e2290892bbb973bd5bb4453277a57b2e1464ac0ca1cd6990e3450bb90fc4322\',\'0x7a5465b5f1efd9946f196388d6c8118bb2ef0bb13605e096ae23949223b857b5\',\'0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8\',6712392,576095,\'1106928909229140\',\'469052541224814191998\',\'0\',\'0x9089155739a7ecf5471693911de32bbe3a83839c5a337f72379576960067435c\',\'0\',\'0x62de3c90795aec99dffb17e77c0e28b59a915e082d2654e443d309ef6823a62b\',\'0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\',\'0xa62af5dd90d6d94f\',\'0xd26b830f3f12e0114696a2cc65c7fcabc8a3f688cdb6b52ec503f9288a050502\',\'0x65746865726d696e652d757333\',\'0x0000000000000000000001000000000000000000040000000000800000000000000000010020000000000000008000010800000000000080000000400000004000000000000000008000000c000000000001000000000402000000080000000820080000020000080000010000000800004009200000000000400010004000008000000100000000000000000400000100000040400000000000000000000000400000004000000000000000800000010000000000000020000000000000000000000002000000000000000000800000000000000000000108100040000021000000000000100000000080000000000400080100400000000000000000000000\',2465,1499633844,\'2017-09-30 10:19:21\');' }
original: { Error: Duplicate entry '4000025' for key 'PRIMARY' at Packet.asError (/Volumes/File/go/chacha/node_modules/mysql2/lib/packets/packet.js:703:13) at Query.Command.execute (/Volumes/File/go/chacha/node_modules/mysql2/lib/commands/command.js:28:22) at Connection.handlePacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:515:28) at PacketParser.onPacket (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:94:16) at PacketParser.executeStart (/Volumes/File/go/chacha/node_modules/mysql2/lib/packet_parser.js:77:14) at Socket.<anonymous> (/Volumes/File/go/chacha/node_modules/mysql2/lib/connection.js:102:29) at emitOne (events.js:115:13) at Socket.emit (events.js:210:7) at addChunk (_stream_readable.js:266:12) at readableAddChunk (_stream_readable.js:253:11) at Socket.Readable.push (_stream_readable.js:211:10) at TCP.onread (net.js:585:20) code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '#23000', sql: 'INSERT INTO `tz_eth_block` (`id`,`hash`,`parent_hash`,`miner`,`gas_limit`,`gas_used`,`difficulty`,`total_difficulty`,`transactions_count`,`transactions_root`,`uncles_count`,`receipts_root`,`sha3_uncles`,`nonce`,`mix_hash`,`extra_data`,`logs_bloom`,`size`,`timestamp`,`created_at`) VALUES (4000025,\'0x4e2290892bbb973bd5bb4453277a57b2e1464ac0ca1cd6990e3450bb90fc4322\',\'0x7a5465b5f1efd9946f196388d6c8118bb2ef0bb13605e096ae23949223b857b5\',\'0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8\',6712392,576095,\'1106928909229140\',\'469052541224814191998\',\'0\',\'0x9089155739a7ecf5471693911de32bbe3a83839c5a337f72379576960067435c\',\'0\',\'0x62de3c90795aec99dffb17e77c0e28b59a915e082d2654e443d309ef6823a62b\',\'0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\',\'0xa62af5dd90d6d94f\',\'0xd26b830f3f12e0114696a2cc65c7fcabc8a3f688cdb6b52ec503f9288a050502\',\'0x65746865726d696e652d757333\',\'0x0000000000000000000001000000000000000000040000000000800000000000000000010020000000000000008000010800000000000080000000400000004000000000000000008000000c000000000001000000000402000000080000000820080000020000080000010000000800004009200000000000400010004000008000000100000000000000000400000100000040400000000000000000000000400000004000000000000000800000010000000000000020000000000000000000000002000000000000000000800000000000000000000108100040000021000000000000100000000080000000000400080100400000000000000000000000\',2465,1499633844,\'2017-09-30 10:19:21\');' }
sql: 'INSERT INTO `tz_eth_block` (`id`,`hash`,`parent_hash`,`miner`,`gas_limit`,`gas_used`,`difficulty`,`total_difficulty`,`transactions_count`,`transactions_root`,`uncles_count`,`receipts_root`,`sha3_uncles`,`nonce`,`mix_hash`,`extra_data`,`logs_bloom`,`size`,`timestamp`,`created_at`) VALUES (4000025,\'0x4e2290892bbb973bd5bb4453277a57b2e1464ac0ca1cd6990e3450bb90fc4322\',\'0x7a5465b5f1efd9946f196388d6c8118bb2ef0bb13605e096ae23949223b857b5\',\'0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8\',6712392,576095,\'1106928909229140\',\'469052541224814191998\',\'0\',\'0x9089155739a7ecf5471693911de32bbe3a83839c5a337f72379576960067435c\',\'0\',\'0x62de3c90795aec99dffb17e77c0e28b59a915e082d2654e443d309ef6823a62b\',\'0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\',\'0xa62af5dd90d6d94f\',\'0xd26b830f3f12e0114696a2cc65c7fcabc8a3f688cdb6b52ec503f9288a050502\',\'0x65746865726d696e652d757333\',\'0x0000000000000000000001000000000000000000040000000000800000000000000000010020000000000000008000010800000000000080000000400000004000000000000000008000000c000000000001000000000402000000080000000820080000020000080000010000000800004009200000000000400010004000008000000100000000000000000400000100000040400000000000000000000000400000004000000000000000800000010000000000000020000000000000000000000002000000000000000000800000000000000000000108100040000021000000000000100000000080000000000400080100400000000000000000000000\',2465,1499633844,\'2017-09-30 10:19:21\');'
pid: 3677
hostname: callmezdeiMac.local

(node:3677) Warning: a promise was created in a handler but was not returned from it
(node:3677) Warning: a promise was created in a handler but was not returned from it
2017-09-30 18:19:21,994 INFO 3677 [model] INSERT INTO `tz_eth_transaction` (`hash`,`block_id`,`block_hash`,`from`,`to`,`value`,`gas`,`gas_price`,`nonce`,`input`,`transaction_index`,`v`,`r`,`s`,`created_at`) VALUES ('0x6758552f4a0e9305019863dcf320ab5bc5807c71aac538201f0560041a0cbe95',4000025,'0x4e2290892bbb973bd5bb4453277a57b2e1464ac0ca1cd6990e3450bb90fc4322','0xf29e3b8585cB8D217F368Defa317abF500d2652d','0xF881bCB3705926cEa9C598aB05a837cf41a833a9','200028110000000000',21000,'41000000000',21,'0x',0,'0x25','0xf42170b5e76bc77babc7f58111aa8fe038af301db0f8997a3f7ad9ccf5f9f8a5','0x4208aa796ec6685e6ee72424005004f242ccc4b1b12b8b7ff9a985414ed7fcd','2017-09-30 10:19:21'); (26ms)
(node:3677) Warning: a promise was created in a handler but was not returned from it
(node:3677) Warning: a promise was created in a handler but was not returned from it
(node:3677) Warning: a promise was created in a handler but was not returned from it
(node:3677) Warning: a promise was created in a handler but was not returned from it
(node:3677) Warning: a promise was created in a handler but was not returned from it
2017-09-30 18:19:22,099 INFO 3677 [model] INSERT INTO `tz_eth_transaction` (`hash`,`block_id`,`block_hash`,`from`,`to`,`value`,`gas`,`gas_price`,`nonce`,`input`,`transaction_index`,`v`,`r`,`s`,`created_at`) VALUES ('0x1ab898c8883e2bac82c35d300510537929f9e67510346f9a85357ad6086b4936',4000007,'0x038ee902ab5f5fd1951374acdfff41b440cd826a6aa7dfba5026c6e4daea12e6','0x645dB031d6Ac9f3a69566123Bf26878A4990ebef','0xd59dcC5f650e766D5Ee75664E7FA5877AE408b9d','1135596370000000000',23101,'21000000000',15303,'0x',8,'0x25','0x6fb536a8a0c679e747f1a44f1e750f77e2493e2220042105fb29c3be12b366ff','0x7a1d344536cdd489b49c9d01f4ce7f0f2b888bc4832e1cf93b4ad0fb89f79255','2017-09-30 10:19:22'); (17ms)

```
## 给个截图 看的清楚点
![image](https://user-images.githubusercontent.com/1625891/31044956-1d579338-a59f-11e7-8679-e2b5ca830a8b.png)
![image](https://user-images.githubusercontent.com/1625891/31045035-b0d67b28-a5a0-11e7-8406-8edf2fbaf78d.png)

总结下我的理解:   
这个问题 按正常逻辑来说  加了`yield`之后  从流程来说 差不多等同线性执行逻辑了
`block -> transaction -> account` , 即使乱序也不会影响插入数据. 
但是执行后 就是频繁出现 ` [ ValidationErrorItem { message: 'PRIMARY must be unique', type: 'unique violation', path: 'PRIMARY', value: '4000025' } ]`
插入表数据主键重复插入的问题.   但是明明循环里一次只执行了一条数据插入.   

因为确实循环太多,并且问题出现无规律,技能不够.  不能定位是否co, sequelize, eggjs的一些机制影响.

**Comment by popomore** [comment]
你的主键要唯一，重复了吧

**Comment by popomore** [comment]
这里根本没必要 co 吧，transaction 可以 yield

**Comment by callmez** [comment]
这边要说明下 以太坊的hash是唯一的. 重复的原因也是重复插入同一条数据.

**Comment by callmez** [comment]
所以说区块链这么敏感的hash值重复是不可能的.  而且sql也重复两次执行插入才报错...
```
for (var i = start + 1; i <= blockNumber; i++) { 
            // 是按照区块排列数字来取得,  目前有400多W数据, 循环400W次,  不可能会存在重复获取数据
            block = yield app.web3.eth.getBlock(i, true) 
            app.model.transaction(() => {
                saveBlock.call(ctx.app, block); // 开始保存
            })
        }
```

**Comment by callmez** [comment]
更新下  替换成 async/await方案后 跑通了.   诡异的问题

**Comment by atian25** [comment]
@callmez 我感觉是你写的逻辑有问题

```js
app.model.transaction(() => {
  // 这里你是并行的，虽然里面有 co，但是你没 return 出来，这里也没 yield
  saveBlock.call(ctx.app, block); 
})
```
