### ISSUE TITLE
使用 HttpClient请求接口的时候,有部分linux机器会报这个错误这是什么情况？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#1515]
```
    Stack: Error: "value" required in setHeader("cookie", value), POST https://api.text.com/api/getFragment -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2753,"createSocketErrorCount":0,"closeSocketCount":2752,"errorSocketCount":0,"timeoutSocketCount":2750,"requestCount":10359,"freeSockets":{"shop.wtoip.com:443::::::::":1},"sockets":{},"requests":{}})
headers: {}
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Object.requestWithCallback (/www/web/Statistics/node_modules/_urllib@2.25.0@urllib/lib/urllib.js:755:19)
    at /www/web/Statistics/node_modules/_urllib@2.25.0@urllib/lib/urllib.js:139:13
    at Object.request (/www/web/Statistics/node_modules/_urllib@2.25.0@urllib/lib/urllib.js:138:10)
    at HttpClient.request.HttpClient.curl (/www/web/Statistics/node_modules/_urllib@2.25.0@urllib/lib/httpclient.js:45:17)
    at HttpClient.request (/www/web/Statistics/node_modules/_egg@1.9.0@egg/lib/core/httpclient.js:36:18)
    at Application.curl (/www/web/Statistics/node_modules/_egg@1.9.0@egg/lib/egg.js:239:28) 
```

**Comment by atian25** [comment]
「我今天肚子痛，你能告诉我是什么情况么？」

我只想问一句

![image](https://user-images.githubusercontent.com/227713/31476662-32bc3d14-aecd-11e7-99cd-86d3a6df3a45.png)

不符合格式的，直接关了，补充必要信息后再自己开启吧。
