### ISSUE TITLE
客户端中断上传的error信息无法通过stream.Readable类中的error事件获取

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1530]
* **Node Version**:8.6
* **Egg Version**:1.9
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:https://github.com/newcomein/Wakeup-OS

控制台报错信息:

  第一个错误:
```
2017-10-14 00:53:46,195 ERROR 13124 [-/undefined/-/1491ms POST /post] nodejs.HPE_INVALID_EOF_STATEError: Parse Error
    at socketOnEnd (_http_server.js:417:20)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
bytesParsed: 0
code: 'HPE_INVALID_EOF_STATE'
headerSent: true
name: 'HPE_INVALID_EOF_STATEError'
pid: 13124
hostname: rockeyµÄ±Ê¼Ç±¾
```

第二个错误信息:

```
2017-10-14 00:53:48,252 ERROR 10144 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1019:11)
    at TCP.onread (net.js:608:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 10144
hostname: rockeyµÄ±Ê¼Ç±¾
```

代码:
```
"use strict";
const co = require('co'),
    fs = require('fs'),
    path = require('path'),
    crypto = require('crypto');
module.exports = app => {
    return class uploadFiles extends app.Service {
        async index() {
            const baseUrl = './app/storage/';
            //头信息
            const headers = this.ctx.get('content-type');//application/x-www-form-urlencoded
            //获取上传实例
            const files = this.ctx.multipart();
            return co(function* () {
                let files2;
                while (files2 = yield files) {
                    //文件扩展名
                    const extName = files2.filename.slice(files2.filename.lastIndexOf('.'));
                    if (!extName) {
                        //如果上传的文件没有扩展民,直接消费流,不处理该流数据
                        files2.resume();
                    } else {
                        //否则对合规的流数据进行处理
                        //获取html input标签定义的name属性值
                        //根据name属性,创建对应的文件目录,并把文件存放在对应的目录
                        const fieldname = files2.fieldname + '/';
                        try {
                            fs.accessSync(baseUrl + fieldname, fs.constants.F_OK)
                        }
                        catch (err) {
                            fs.mkdirSync(baseUrl + fieldname, (err) => {
                                throw err
                            })
                        }
                        const ws = fs.createWriteStream(baseUrl + fieldname + new Date().toLocaleDateString() + '_' + Math.random() + extName);

                        //想从这里得到用户中断上传的报错信息,但是失败
                        files2.on('error', (data) => {
                            console.log('错误')
                        });

                        files2.pipe(ws);
                    }
                }
                return;
            }).then(() => {
                return;
            }, (err) => {
                console.error(err.stack);
            });
        }
    }
};
```

项目演示:https://github.com/newcomein/Wakeup-OS/tree/master/app/service/uploadFiles.js
直接打开https://github.com/newcomein/Wakeup-OS/tree/master/app/view/default/pc/index.html
点击上传文件,即可重现这个问题

**Comment by popomore** [comment]
https://github.com/eggjs/examples/pull/43 看看这个例子
