### ISSUE TITLE
Can not auto detect update condition, please set options.where, or make sure obj.id exists

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1533]
* **Node Version**:8.60
* **Egg Version**:1.9
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

报错信息:

```
2017-10-15 02:45:41,084 ERROR 6420 [-/127.0.0.1/-/4ms POST /post] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (E:\WebstormProjects\Wakeup-OS\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\WebstormProjects\Wakeup-OS\node_modules\co\index.js:65:19)
    at E:\WebstormProjects\Wakeup-OS\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at RDSClient.co (E:\WebstormProjects\Wakeup-OS\node_modules\co\index.js:50:10)
    at RDSClient.createPromise [as update] (E:\WebstormProjects\Wakeup-OS\node_modules\co\index.js:30:15)
    at sqlWrite.update (E:\WebstormProjects\Wakeup-OS\app\service\sqlWrite.js:22:47)
    at PostController.index (E:\WebstormProjects\Wakeup-OS\app\controller\post.js:48:57)
    at <anonymous>
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6420
hostname: rockeyµÄ±Ê¼Ç±¾

{ uid: 1, uSession: 'fengmk2' }
```

相关代码:

```
        async update(table){

            const values = {
                uid: 1,
                uSession: 'fengmk2',
                //modifiedAt: this.app.mysql.literals.now, // `now()` on db server
            };

            console.log(values);

            let result = await this.app.mysql.update(table, values); // 更新 posts 表中的记录
            console.log(result);
            return;
        }
```

数据库主键名称为 uid
想修改的user中的uid为1的数据,uSession值改成:fengmk2

然而失败

**Comment by popomore** [comment]
please set options.where, or make sure obj.id exist

设置 where

**Comment by newcomein** [comment]
@popomore 已经设置  即使我完完整整复制官网的demo  一样会这样

**Comment by popomore** [comment]
那应该用 id

**Comment by newcomein** [comment]
@popomore 如果用id  显示找不到column

**Comment by newcomein** [comment]
@popomore Unknown column 'id' in 'where clause'

**Comment by superpig** [comment]
@popomore 主键为什么必须用 id ?

**Comment by superpig** [comment]
@newcomein 如果主键不是 id, 需要加 where 条件，[https://github.com/ali-sdk/ali-rds](文档)
