### ISSUE TITLE
正式部署和定时任务冲突。

### ISSUE THREAD

**Issue by nxycdl** [eggjs/egg#1539]
# 我再使用npm start 之后发现程序没有部署成功！

- [package.json ] 

```
"scripts": { 
    "start":"egg-scripts start --port=7001 --daemon --workers=2 --title=egg-server-showcase",
    "stop": "egg-scripts stop",
    "dev": "egg-bin dev --port 
}
```
### 发现有一个定时任务 
```
module.exports = {
    // 通过 schedule 属性来设置定时任务的执行间隔等配置
    schedule: {
        interval: '10s', // 1 分钟间隔
        type: 'worker', // 指定所有的 worker 都需要执行,
        disable: true
    },
    // task 是真正定时任务执行时被运行的函数，第一个参数是一个匿名的 Context 实例
    async task(ctx) {
        console.log('start task2');
        // 注释一下2句可以部署成功！
        const res = await ctx.curl('http://localhost:7001/getDemo/getone?id=1&name=dl');
        console.log(ctx.helper.moment().format('YYYY MM DD HH:mm:ss'), res.data.toString());
        ctx.app.cache = {}
    },
}
```

### 如果不注释，在master-stderr 里面会出现 
```
2017-10-17 14:51:46,476 ERROR 33404 [-/127.0.0.1/-/2ms GET /] nodejs.RequestError: connect ECONNREFUSED 127.0.0.1:7001 (req "error"), GET http://localhost:7001/getDemo/getone?id=1&name=dl -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"localhost:7001:":1},"requests":{}})
headers: {}
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '127.0.0.1'
port: 7001
name: 'RequestError'
data: undefined
path: '/getDemo/getone?id=1&name=dl'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 1013, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://localhost:7001/getDemo/getone?id=1&name=dl' ], timing: null, remoteAddress: '127.0.0.1', remotePort: '' }
pid: 33404
```

**Comment by popomore** [comment]
定时任务是在启动后才执行的，master 进程也不应该挂。

而且你这个实现有点奇怪，直接调用 service 不就好了。

**Comment by atian25** [comment]
学习下 markdown 格式化吧... 正文非常难阅读

**Comment by atian25** [comment]
你更新下依赖再试试：

```bash
$ npm run autod
$ rm -rf package-lock.json
$ rm -rf node_modules
$ npm install
```

**Comment by nxycdl** [comment]
似乎是cnpm惹的祸 我删除了node_modules 执行了cnpm 发现每次都有莫名其妙的问题。
我先用npm install 试试看。

**Comment by atian25** [comment]
cnpm 不会有问题的，我们一直在用

发自我的 iPhone

**Comment by okoala** [comment]
这个 Lock 文件真是蛋痛

**Comment by nxycdl** [comment]
#  没有发现package-lock.json 
### 执行
```
$ npm run autod
$ rm -rf node_modules
$ npm install
```
npm start 之后就变成
```
D:\project\egg\eggstudy>npm start

> eggstudy@1.0.0 start D:\project\egg\eggstudy
> egg-scripts start --port=7001 --daemon --workers=2 --title=egg-server-showcase

[egg-scripts] Starting egg application at D:\project\egg\eggstudy
[egg-scripts] Run node D:\project\egg\eggstudy\node_modules\egg-scripts\lib\start-cluster {"port":7001,"workers":2,"title":"egg-server-showcase","timeout":300000,"framework":"D:\\project\\egg\\eggstudy\\node_modules\\egg","stdout":"C:\\Users\\dl\\logs\\master-stdout.log","stderr":"C:\\Users\\dl\\logs\\master-stderr.log","baseDir":"D:\\project\\egg\\eggstudy"} --title=egg-server-showcase
[egg-scripts] Save log file to C:\Users\dl\logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
......
```
### 使用npm run dev 没有此问题。

**Comment by popomore** [comment]
这个看起来正常

**Comment by atian25** [comment]
这日志没报错了啊

发自我的 iPhone

**Comment by atian25** [comment]
> D:\project\egg\eggstudy>npm start

咦，突然发现是 windows， `egg-scripts` 2.x 的 README 有写了，不支持 windows。一般部署环境都是 linux。

**Comment by nxycdl** [comment]
### 我再ubuntu上 使用了npm start 最后提示的,和Windows 上是同一个错误。
@atian25 有空帮我看下。https://github.com/nxycdl/eggstudy.git
```
@ubuntu:~/project/eggstudy$ npm start

> eggstudy@1.0.0 start /home/dl/project/eggstudy
> egg-scripts start --port=7001 --daemon --workers=2 --title=egg-server-showcase

[egg-scripts] Starting egg application at /home/dl/project/eggstudy
[egg-scripts] Run node /home/dl/project/eggstudy/node_modules/_egg-scripts@2.1.0@egg-scripts/lib/start-cluster {"port":7001,"workers":2,"title":"egg-server-showcase","timeout":300000,"framework":"/home/dl/project/eggstudy/node_modules/egg","stdout":"/home/dl/logs/master-stdout.log","stderr":"/home/dl/logs/master-stderr.log","baseDir":"/home/dl/project/eggstudy"} --title=egg-server-showcase
[egg-scripts] Save log file to /home/dl/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts]     at Object._errnoException (util.js:1021:11)
[egg-scripts]     at _exceptionWithHostPort (util.js:1043:20)
[egg-scripts]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
[egg-scripts] code: 'ECONNREFUSED'
[egg-scripts] errno: 'ECONNREFUSED'
[egg-scripts] syscall: 'connect'
[egg-scripts] address: '127.0.0.1'
[egg-scripts] port: 7001
[egg-scripts] name: 'RequestError'
[egg-scripts] data: undefined
[egg-scripts] path: '/getDemo/getone?id=1&name=dl'
[egg-scripts] status: -1
[egg-scripts] headers: {}
[egg-scripts] res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 93, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://127.0.0.1:7001/getDemo/getone?id=1&name=dl' ], timing: null, remoteAddress: '', remotePort: '' }
[egg-scripts] pid: 15536
```

**Comment by popomore** [comment]
https://github.com/nxycdl/eggstudy/blob/master/app.js#L11

这里调用了 runSchedule

**Comment by nxycdl** [comment]
的确是这个问题。没有注意到这里，在dev 模式没有抛出这个错误。 我还以为和部署有什么关系。
