### ISSUE TITLE
egg-socket.io 示例运行出错。

### ISSUE THREAD

**Issue by yichangle** [eggjs/egg#1568]
* **Node Version**:
6.11.0
* **Egg Version**:
1.4.0
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
2.0.0
* **Platform**:
win10 x64
* **Mini Showcase Repository**:

git clone egg-socket.io后，进入example目录，npm install安装依赖，再运行npm run start,程序运行出错。以下是出错信息：
E:\learn\egg-socket.io\example>npm run start

> socket.io-example@1.0.0 start E:\learn\egg-socket.io\example
> egg-bin dev --cluster --sticky

2017-10-26 14:17:12,829 INFO 10084 [master] egg version 1.10.0
2017-10-26 14:17:13,635 INFO 10084 [master] agent_worker#1:11084 started (797ms)

E:\learn\egg-socket.io\example\node_modules\egg\lib\application.js:39
      throw e;
      ^
AssertionError: handler must be generatorFunction or asyncFunction!
    at Namespace.route (E:\learn\egg-socket.io\example\node_modules\egg-socket.io\lib\socket.io\namespace.js:12:3)
    at Server.SocketIO.route (E:\learn\egg-socket.io\example\node_modules\egg-socket.io\lib\socket.io\index.js:8:29)
    at module.exports.app (E:\learn\egg-socket.io\example\app\router.js:5:10)
    at AppWorkerLoader.loadFile (E:\learn\egg-socket.io\example\node_modules\egg-core\lib\loader\egg_loader.js:289:30)
    at AppWorkerLoader.loadRouter (E:\learn\egg-socket.io\example\node_modules\egg-core\lib\loader\mixin\router.js:15:10)
    at AppWorkerLoader.load (E:\learn\egg-socket.io\example\node_modules\egg\lib\loader\app_worker_loader.js:41:10)
    at new Application (E:\learn\egg-socket.io\example\node_modules\egg\lib\application.js:35:19)
    at Object.<anonymous> (E:\learn\egg-socket.io\example\node_modules\egg-cluster\lib\app_worker.js:13:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
[2017-10-26 14:17:14.717] [cfork:master:10084] worker:13468 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2017-10-26 14:17:14.717] [cfork:master:10084] don't fork, because worker:13468 will be kill soon
2017-10-26 14:17:14,718 INFO 10084 [master] app_worker#1:13468 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2017-10-26 14:17:14.721] [cfork:master:10084] worker:13468 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)

**Comment by atian25** [comment]
@ngot 看看.

@yichangle 试下 

```bash
$ npm run autod
$ rm -rf package-lock.json
$ npm i
```

再试试。

**Comment by nxycdl** [comment]
是不是node版本太低了.

**Comment by yichangle** [comment]
app目录下router.js文件中定义路由的第二个参数app.io.controllers.chat.index为undefined，所以出错。不知道如何修正呢？

**Comment by ngot** [comment]
@yichangle 请用最新版本
