### ISSUE TITLE
egg-socket.io 启动报错。 

### ISSUE THREAD

**Issue by yule333444** [eggjs/egg#1575]
* **Node Version**:
8.0.0
* **Egg Version**:
1.10.0
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
2.1.0
* **Platform**:
windows:
* **Mini Showcase Repository**:

进的是官方代码仓库的example 代码一行都没改过。
使用客户端JS 连接 。 
第一步没问题。
然后就开始不断的报  如下错误 。 循环很快， 一直在控制台中刷屏 

2017-10-27 10:55:42,687 ERROR 9576 nodejs.TypeError: Cannot read property 'emit' of null (uncaughtException throw 1 times on pid:9576)
    at Socket.socketOnTimeout (_http_server.js:386:34)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:401:8)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

[Fri Oct 27 2017 10:55:42 GMT+0800 (中国标准时间)] [graceful:worker:9576:uncaughtException] throw error 1 times
TypeError: Cannot read property 'emit' of null (uncaughtException throw 1 times on pid:9576)
    at Socket.socketOnTimeout (_http_server.js:386:34)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:401:8)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

作为小白玩家 感觉很无助。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-socket.io/blob/master/example/package.json#L10

这里改为 `^3.0.0` 试试。

@ngot example 是不是没升级？

**Comment by yule333444** [comment]
已经把 egg-socket.io  升级成 3.0.0  了  错误信息是一样的。

**Comment by ngot** [comment]
node 8.0.0有bug，请升级到最新node

**Comment by atian25** [comment]
@ngot example 还是要改下

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/27

**Comment by ngot** [comment]
是的。两个问题都有。这个合并了就好了。不过 node 要用 6 的LTS，或者8的最新版本。
