### ISSUE TITLE
middleware中间件名字带下划线报错

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1588]
middleware文件定义了一个req_json.js
```javascript
const reqjson = require('koa-json');
module.exports = reqjson;
```
config/config.default.js
```javascript
config.middleware = [ 'req_json' ];
```
TypeError: Middleware req_json not found
    at AppWorkerLoader.loadMiddleware (/Users/tusm/github/mygithub/cherryshop-api/node_modules/egg-core/lib/loader/mixin/middleware.js:64:15)
    at AppWorkerLoader.load (/Users/tusm/github/mygithub/cherryshop-api/node_modules/egg/lib/loader/app_worker_loader.js:37:10)
    at new Application (/Users/tusm/github/mygithub/cherryshop-api/node_modules/egg/lib/application.js:35:19)
    at Object.<anonymous> (/Users/tusm/github/mygithub/cherryshop-api/node_modules/egg-cluster/lib/app_worker.js:13:13)
    at Module._compile (module.js:609:14)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
<img width="1289" alt="2017-10-31 9 37 27" src="https://user-images.githubusercontent.com/15979948/32203586-2867d2cc-be1f-11e7-9ec4-1ed9b289cb9d.png">

去掉下划线就不会报错了；是不是名称规定了不能用下划线吗

**Comment by atian25** [comment]
> 框架的加载器会将文件名中的各种分隔符都修改成驼峰形式的变量名

`config.middleware = [ 'reqJson' ];`

**Comment by chenyulun** [comment]
刚刚反应过来了改试过了，想关掉这个问题，你手快，谢谢
