### ISSUE TITLE
新手：关于prod环境的common-error.log的疑惑

### ISSUE THREAD

**Issue by w567675** [eggjs/egg#1606]
**win10 系统**。

```js
//${app}/app/service/news.js
module.exports = app => class NewService extends app.Service {
    async world () {
        throw new Error('this is error');
    }
}
```

运行  **egg-bin dev**
会在日志中记录 
```text
2017-11-03 16:57:38,501 ERROR 1872 [-/127.0.0.1/-/3ms GET /api/news] nodejs.Error: this is error
    at NewService.world (D:\zhanghaiyang\works\test\bhw1-egg\app\service\news.js:47:15)
    at NewsController.list (D:\zhanghaiyang\works\test\bhw1-egg\app\controller\news.js:4:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 1872
hostname: DESKTOP-B79743Q
```

运行 **egg-scripts start --daemon** 
或者 **set EGG_SERVER_ENV=prod & egg-bin dev**
在日志中没有记录。

请问除了local环境会自动记录错误，其他环境要 **logger.error** 记录么？

**Comment by atian25** [comment]
`egg-scripts` 不支持 windows.

所有环境都会记录日志，可以再看下官网文档关于日志章节。

**Comment by okoala** [comment]
用 docker 吧

**Comment by w567675** [comment]
ok

**Comment by w567675** [comment]
我用docker试试
