### ISSUE TITLE
egg-mysql 超时

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#1613]
* **Node Version**:v8.8.1
* **Egg Version**:1.9.0
* **Plugin Name**:egg-mysql
* **Plugin Version**:3.0.0
* **Platform**:windows 7 x64
* **Mini Showcase Repository**: 

2017-11-06 14:23:56,081 WARN 8400 [egg:core:ready_timeout] 10 seconds later D:\code\demo\node\egg-example\node_modules\egg-mysql\lib\mysql.js:20:7 was still unable to finish.
2017-11-06 14:23:56,196 ERROR 8400 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\code\demo\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:105:13)
    at Handshake.emit (events.js:207:7)
    at Handshake._onTimeout (D:\code\demo\node\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
    --------------------
    at Protocol._enqueue (D:\code\demo\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\code\demo\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\code\demo\node\egg-example\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\code\demo\node\egg-example\node_modules\mysql\lib\Pool.js:48:16)
    at D:\code\demo\node\egg-example\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\code\demo\node\egg-example\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\code\demo\node\egg-example\node_modules\pify\index.js:56:34)
    at Pool.query (D:\code\demo\node\egg-example\node_modules\mysql\lib\Pool.js:202:8)
    at D:\code\demo\node\egg-example\node_modules\pify\index.js:29:7
    sql: select now() as currentTime;
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 8400
hostname: sj-PC

我用Navicat可以连上，如何修改超时时间？我希望能把TIMEOUT自定义设置

**Comment by liangklfangl** [comment]
我也遇到这个问题，有解决方法了吗

**Comment by liangklfangl** [comment]
找到了解决方法，详见 https://github.com/liangklfangl/react-article-bucket/blob/master/others/nodejs-QA/egg-QA.md#7egg中如何配置数据库连接池信息，但是感觉这个egg-mysql的文档可以好好写写了

**Comment by atian25** [comment]
@liangklfangl 赞，欢迎 PR 给 egg-mysql 文档优化下文档

**Comment by luogeng2017** [comment]
我也遇到这个问题了，你们都是怎么解决的，设置了connectTimeout也不起作用，貌似10s就会默认超时

**Comment by wang-weifeng** [comment]
解决办法呢？愁人

**Comment by wang-weifeng** [comment]
> > 我也遇到这个问题了，你们都是怎么解决的，设置了connectTimeout也不起作用，貌似10s就会默认超时
> 
> https://github.com/mysqljs/mysql
> 设置acquireTimeout, 默认为10s

设置不行啊

**Comment by donghj93** [comment]
请问是否有解决方案呢？现在也遇到这个问题了，默认是30s超时，怎么修改呢？
