### ISSUE TITLE
跨域请求报错：nodejs.MethodNotAllowedError: Method Not Allowed,需要怎么处理？！

### ISSUE THREAD

**Issue by ycyoes** [eggjs/egg#1614]
2017-11-06 16:22:40,474 WARN 11200 [-/172.16.139.79/-/2ms OPTIONS /shareList] nodejs.MethodNotAllowedError: Method Not Allowed
    at Object.throw (D:\WebstormProjects\datavisual_test\node_modules\koa\lib\context.js:89:23)
    at Object.notAllow (D:\WebstormProjects\datavisual_test\node_modules\egg-security\lib\middlewares\methodnoallow.js:18:17)
    at notAllow.next (<anonymous>)
    at Object.<anonymous> (D:\WebstormProjects\datavisual_test\node_modules\koa-compose\index.js:28:19)
    at Generator.next (<anonymous>)
    at onFulfilled (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:65:19)
    at D:\WebstormProjects\datavisual_test\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at co (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:50:10)
    at toPromise (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:118:63)
    at next (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:99:29)
    at onFulfilled (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:69:7)
    at D:\WebstormProjects\datavisual_test\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at co (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:50:10)
    at toPromise (D:\WebstormProjects\datavisual_test\node_modules\co\index.js:118:63)
message: 'Method Not Allowed'

在路由里添加如下代码，不起作用：
 app.options('*', function() {
    console.log('-----------------request options---------------');
  });

**Comment by popomore** [comment]
使用 https://github.com/eggjs/egg-cors
