### ISSUE TITLE
egg-session-redis npm run test-local error

### ISSUE THREAD

**Issue by lidianhao123** [eggjs/egg#1624]
* **Node Version**:
v6.11.3
* **Egg Version**:
v1.10.0
* **Plugin Name**:
egg-session-redis
* **Plugin Version**:
1.0.0
* **Platform**:
osx 10.11.6
* **Mini Showcase Repository**:
[egg-session-redis](https://github.com/eggjs/egg-session-redis)

download egg-session-redis master branch

```shell
npm i
npm run test-local
```
Then show below error log

```shell
> egg-session-redis@1.0.0 test-local /Users/ld/Downloads/egg-session-redis-master
> egg-bin test



  1) "before all" hook

  0 passing (478ms)
  1 failing

  1)  "before all" hook:
     PluginSequencifyError: sequencify plugins has problem, missing: [redis], recursive: []
	>> Plugin [redis] is disabled or missed, but is required by [sessionRedis]
      at AgentWorkerLoader.getOrderPlugins (node_modules/egg/node_modules/egg-core/lib/loader/mixin/plugin.js:271:19)
      at AgentWorkerLoader.loadPlugin (node_modules/egg/node_modules/egg-core/lib/loader/mixin/plugin.js:131:30)
      at AgentWorkerLoader.loadConfig (node_modules/egg/lib/loader/agent_worker_loader.js:15:10)
      at EggApplication (node_modules/egg/lib/egg.js:48:17)
      at Agent (node_modules/egg/lib/agent.js:21:5)
      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:62:33)
      at next (native)
      at onFulfilled (node_modules/egg-mock/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)
      at run (bootstrap_node.js:389:7)
      at startup (bootstrap_node.js:149:9)
      at bootstrap_node.js:502:3



[common-bin] run test with [] at /Users/ld/Downloads/egg-session-redis-master error:
Error: /Users/ld/Downloads/egg-session-redis-master/node_modules/egg-bin/node_modules/mocha/bin/_mocha --timeout,30000,--require,/Users/ld/Downloads/egg-session-redis-master/node_modules/egg-bin/node_modules/co-mocha/lib/co-mocha.js,--require,/Users/ld/Downloads/egg-session-redis-master/node_modules/egg-bin/node_modules/intelli-espower-loader/intelli-espower-loader.js,/Users/ld/Downloads/egg-session-redis-master/test/app.test.js exit with code 1
    at ChildProcess.<anonymous> (/Users/ld/Downloads/egg-session-redis-master/node_modules/egg-bin/node_modules/common-bin/lib/helper.js:31:21)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

I'm developing a egg plugin. when I test myself plugin error log show which same to above info.
I think mybe plugin dependencies logic in egg-bin package have some error.

**Comment by popomore** [comment]
you should enable redis plugin first.

**Comment by lidianhao123** [comment]
@popomore 
I'm use the eggjs offcial repository [egg-session-redis](https://github.com/eggjs/egg-session-redis). Please help check egg-session-redis test is correct? I'm think plugin.js file in the test folder is not load correct or egg-mock package load plugin.js file error.

redis plugin is enable [plugin.js](https://github.com/eggjs/egg-session-redis/blob/master/test/fixtures/single/config/plugin.js)
```js
exports.redis = {
  enable: true,
  package: 'egg-redis',
};
```

**Comment by lidianhao123** [comment]
I know where is error. because I require 'egg-mock/bootstrap'. Thanks!

app.test.js
```js
// const assert = require('assert');
const { assert } = require('egg-mock/bootstrap');
```

**Comment by atian25** [comment]
ahhh, `bootstrap` is use for app, not for plugin and framework.
