### ISSUE TITLE
egg-socket.io 报错: Cannot set property 'args' of undefined

### ISSUE THREAD

**Issue by pengkobe** [eggjs/egg#1629]
* **Node Version**:
v7.9.0
* **Egg Version**:
v1.9.0
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
v3.0.0
* **Platform**:
windows 10 或者 centos7
* **Mini Showcase Repository**:
暂无

报错堆栈信息如下
```
TypeError: Cannot set property 'args' of undefined (uncaughtException throw 1 times on pid:9992)
    at Socket.socket.on.args (/mnt/myRepo/node_modules/egg-socket.io/lib/io.js:68:37)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Socket.emit (/mnt/myRepo/node_modules/socket.io/lib/socket.js:140:10)
    at Socket.onclose (/mnt/myRepo/node_modules/socket.io/lib/socket.js:452:8)
    at Client.onclose (/mnt/myRepo/node_modules/socket.io/lib/client.js:233:24)
    at emitTwo (events.js:111:20)
    at Socket.emit (events.js:194:7)
    at Socket.onClose (/mnt/myRepo/node_modules/engine.io/lib/socket.js:318:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.Transport.onClose (/mnt/myRepo/node_modules/engine.io/lib/transport.js:127:8)
    at WebSocket.internalOnClose (/mnt/myRepo/node_modules/uws/uws.js:199:17)
    at process.nextTick (/mnt/myRepo/node_modules/uws/uws.js:445:27)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
```

出现这个错误后，重启服务端后，客户端不刷新，一切正常;
出现这个错误后，按 F5 刷新客户时则会出现，根据堆栈初步判断是这里 `at Socket.socket.on.args (/mnt/myRepo/node_modules/egg-socket.io/lib/io.js:68:37)` 没有考虑到可能出现的所有情形？
所以我稍微改动了点东西，将这段代码
```javascript
 if (nsp[RouterConfigSymbol]) {
        for (const [ event, handler ] of nsp[RouterConfigSymbol].entries()) {
          socket.on(event, (...args) => {
            const ctx = args.splice(-1)[0];
            ctx.args = ctx.req.args = args;
            co.wrap(handler).call(ctx)
              .then(() => ctx[CtxEventSymbol].emit('finshed'))
              .catch(e => {
                e.message = '[egg-socket.io] controller execute error: ' + e.message;
                ctx[CtxEventSymbol].emit('finshed', e);
              });
          });
        }
      }
```
改为以下这样子，
```javascript
 if (nsp[RouterConfigSymbol]) {
        for (const [ event, handler ] of nsp[RouterConfigSymbol].entries()) {
          socket.on(event, (...args) => {
            const ctx = args.splice(-1)[0];
            // 这里是新增内容
            if(!args || !ctx.req){
              return;
            }
            ctx.args = ctx.req.args = args;
            co.wrap(handler).call(ctx)
              .then(() => ctx[CtxEventSymbol].emit('finshed'))
              .catch(e => {
                e.message = '[egg-socket.io] controller execute error: ' + e.message;
                ctx[CtxEventSymbol].emit('finshed', e);
              });
          });
        }
      }
```
然后就没有再出现。

求帮，不胜感激！@ngot

**Comment by ngot** [comment]
提供一个复现的代码仓库吧，这个凭空的改，没法验证。

**Comment by pengkobe** [comment]
@ngot 庄少大大，我这边新建了一个 Repo 来演示. 帮忙看看哈，地址:    
https://github.com/pengkobe/egg-socket.io-error-showcase

**Comment by atian25** [comment]
ping @ngot

**Comment by ngot** [comment]
找到原因了，是这一行导致的：https://github.com/pengkobe/egg-socket.io-error-showcase/blob/master/app/router.js#L9

这一样监听了断开连接事件，而统一的ctrl处理器，并没有考虑这种情况。

我来看看怎么兼容一下。

**Comment by ngot** [comment]
根据文档：https://socket.io/docs/server-api/#event-disconnect

socket 对象除了可以 on eventName 之外，还有另外三个事件：

- disconnect
- error
- disconnecting

这三个事件属于框架事件，目前的 egg-socket.io 的 api 用户是可以自定义的去监听这几个事件。需要额外处理好，或者限制住。

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/1848

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/30

**Comment by ngot** [comment]
fixed at + egg-socket.io@4.0.2
