### ISSUE TITLE
最新 egg-multipart 1.5.1 按照官方最新文档出错

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1635]
* **Node Version**:8.9.0
* **Egg Version**:1.10.1
* **Plugin Name**:egg-multipart
* **Plugin Version**:1.5.1
* **Platform**:
* **Mini Showcase Repository**:

放在service层的上传代码:
```
"use strict";
const fs = require('fs'),
    path = require('path');
module.exports = app => {
    return class uploadFiles extends app.Service {
        async index() {
            const parts = this.ctx.multipart();
            let result;
            while ((result = await parts()) !== null) {
                console.log(result)
            }
        }
    }
};
```
报错信息:
```
2017-11-08 23:20:50,989 WARN 14940 [-/127.0.0.1/-/16ms POST /post] nodejs.Error: Invalid filename: aaa.png
    at checkFile (E:\WebstormProjects\Wakeup-OS\node_modules\egg-multipart\app.js:72:23)
    at Busboy.onFile (E:\WebstormProjects\Wakeup-OS\node_modules\co-busboy\index.js:101:17)
    at emitMany (events.js:147:13)
    at Busboy.emit (events.js:224:7)
    at Busboy.emit (E:\WebstormProjects\Wakeup-OS\node_modules\busboy\lib\main.js:38:33)
    at PartStream.<anonymous> (E:\WebstormProjects\Wakeup-OS\node_modules\busboy\lib\types\multipart.js:213:13)
    at emitOne (events.js:116:13)
    at PartStream.emit (events.js:211:7)
    at HeaderParser.<anonymous> (E:\WebstormProjects\Wakeup-OS\node_modules\dicer\lib\Dicer.js:51:16)
    at emitOne (events.js:116:13)
status: 400
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 14940
hostname: rockeyµÄ±Ê¼Ç±¾
```

multipart插件配置:
```
    config.multipart = {
        autoFields: true,
        defaultCharset: 'utf8',
        fieldNameSize: 100,
        fieldSize: '100kb',
        fields: 100,
        fileSize: '2048mb',
        files: 100,
        fileExtensions: [],
        whitelist: ['.pptx','.ppt'],
    };
```

根据官方最新文档实例:
https://github.com/eggjs/examples/blob/master/multipart/app/controller/multiple.js

**Comment by atian25** [comment]
用 `fileExtensions` 而不是 `whitelist`

**Comment by newcomein** [comment]
@atian25   删了whitelist居然就没问题了 虽然不知道是什么神秘力量在推动 但是还是感谢大佬深夜答疑

**Comment by atian25** [comment]
其实源码很短，看看就知道了。文档也提到了，whitelist 是覆盖的，你原来覆盖了，不允许上传 png 啊

发自我的 iPhone

**Comment by newcomein** [comment]
原来如此 Thanks♪(･ω･)ﾉ
