### ISSUE TITLE
--sticky 模式运行一段时间莫名挂掉，无法重启

### ISSUE THREAD

**Issue by tinyhill** [eggjs/egg#1641]
* **Node Version**: 6.11.5
* **Egg Version**: 1.10.1
* **Plugin Name**: egg-socket.io, egg-ons
* **Plugin Version**: 3.0.0
* **Platform**: OS X
* **Mini Showcase Repository**:

1. egg 应用部署到生产环境，--sticky 模式运行一段时间后会莫名挂掉，没有自动重启；
2. 登录机器手工 npm start，提示 7001 端口被占用，说明 7001 端口在进程退出时，并没有释放；

启用了 egg-socket.io 和 egg-ons 插件，不知道是不是这俩插件导致的原因。

---

类似问题：https://github.com/eggjs/egg/issues/1055

**Comment by popomore** [comment]
现象是什么，ps 看看进程在不在，stderr 日志呢

**Comment by tinyhill** [comment]
@popomore 运行一段时间后，master-stderr.log 里全是：

`
[2017-11-10 10:56:34.355] [cfork:master:6848] master uncaughtException: TypeError: Cannot read property 'length' of undefined
    at Master.stickyWorker (/home/admin/app/big-screen-server/node_modules/egg-cluster/lib/master.js:147:27)
    at Server.require.createServer.connection (/home/admin/app/big-screen-server/node_modules/egg-cluster/lib/master.js:137:27)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at TCP.onconnection (net.js:1552:8)
TypeError: Cannot read property 'length' of undefined
    at Master.stickyWorker (/home/admin/app/big-screen-server/node_modules/egg-cluster/lib/master.js:147:27)
    at Server.require.createServer.connection (/home/admin/app/big-screen-server/node_modules/egg-cluster/lib/master.js:137:27)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at TCP.onconnection (net.js:1552:8)
(total 0 disconnect, 0 unexpected exit)
`

**Comment by ngot** [comment]
看起来是 `connection.remoteAddress` 这个 `remoteAddress` 字段不存在导致的。


> socket.remoteAddress#
Added in: v0.5.10
The string representation of the remote IP address. For example, '74.125.127.100' or '2001:4860:a005::68'. Value may be undefined if the socket is destroyed (for example, if the client disconnected).

客户端断开，可能为 undefined .

这里可以判断是否为空，为空的话，直接不处理，可以保证不挂掉。

不过 socket 对象应被销毁了断开了，客户端的连接还是无法工作的，真真的原因要从客户端去找了。

**Comment by tinyhill** [comment]
@popomore 我看到 cfork 有重试上限，是否 cfork 超过了限制，不再 fork 了，而此时 master 正常，worker 无法启启来？

**Comment by atian25** [comment]
@tinyhill cfork 是异常重启处理了，一般情况不应该走到那的。
现在的问题应该是排查 @ngot 提到那个客户端问题

**Comment by tinyhill** [comment]
现在的表象是，7001 端口的 http 服务，curl 下为 (52) Empty from server

**Comment by tinyhill** [comment]
应该是 egg-socket.io 插件的问题，我使用 socket.io 模块通过 app.js 自行实现 socket 服务，不再出现运行一段时间后宕机的问题。

**Comment by ngot** [comment]
https://github.com/eggjs/egg-cluster/pull/50
