### ISSUE TITLE
通过curl转发大文件时出错

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1677]
通过curl转发大文件时出错，小文件是可以的。业务代码如下：
```
* uploader(ctx) {

            const form = new FormStream();
            const stream = yield ctx.getFileStream();
            // 设置普通的 key value
            form.field('foo', 'bar');
            form.stream('file', stream, stream.filename);

            const result = yield ctx.curl(`${app.config['xjzx'].apiHost.tool}/phoneNumSplit/uploadFileSuper`, {
                // const result = yield ctx.curl(`${app.config['xjzx'].apiHost.tool}/webTest/fileUpload.web`, {
                // 必须指定 method，支持 POST，PUT
                method: 'POST',
                // 生成符合 multipart/form-data 要求的请求 headers
                headers: form.headers(),
                // 以 stream 模式提交
                stream: form,
                // 明确告诉 HttpClient 以 JSON 格式处理响应 body
                dataType: 'json',
                timing: true,
                timeout: 60000,
            });

            ctx.logger.info(result.res.timing);
            ctx.body = result.data;
        }
```

egg报错日志如下：
```
2017-11-17 16:25:52,545 ERROR 28750 [-/127.0.0.1/-/14859ms POST /nodeApi/tool/phoneNumSplit/uploadFileSuper] nodejs.ResponseError: socket hang up (req "error"), POST http://60.120.141.94:18801/phoneNumSplit/uploadFileSuper -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"60.120.141.94:18801:":1},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
code: 'ECONNRESET'
name: 'ResponseError'
data: undefined
path: '/phoneNumSplit/uploadFileSuper'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 14836, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://60.120.141.94:18801/phoneNumSplit/uploadFileSuper' ], timing:  { queuing: 8, dnslookup: 0, connected: 30, requestSent: 0, waiting: 0, contentDownload: 14836 }, remoteAddress: '60.120.141.94', remotePort: 18801 }
pid: 28750
hostname: xxxxxx
```
后端日志提示：
```
Caused by: java.io.EOFException: Unexpected EOF read on the socket
```

**Comment by popomore** [comment]
form 形式，dataType 为啥是 json

**Comment by popomore** [comment]
你用其他客户端是如何上传的？

**Comment by StephenSeraph** [comment]
小文件行，大文件不行？是不是内置插件[egg-multipart](https://github.com/eggjs/egg-multipart)的缘故？它的默认大小限制为10M。

**Comment by popomore** [comment]
大小文档有说明

**Comment by popomore** [comment]
题者未回复，先关闭。

**Comment by xjchenhao** [comment]
不好意思， 身体不适休假了两天。。

@popomore dataType不是“预期服务器返回的数据类型”吗，文件上传以后后端是返回我json数据啊。而且如果这里设置有问题的话，理论上小文件是上传不上去的啊。

@StephenSeraph 文件大小我已经写了，如下：

```
// config.default.js
'use strict';

module.exports = appInfo => {
    const config = {};

    config.notfound = {
        pageUrl: '/404',
    };

    config.bodyParser={
        jsonLimit: '100mb',
        formLimit: '100mb',
    };

    config.multipart = {
        fileSize: '100mb',
        fileExtensions: ['.xls', '.xlsx'],
    };

    config.middleware = ['notfoundHander', 'errorHandler'];

    // should change to your own
    config.keys = appInfo.name + '_1504059477161333_2297';

    // add your config here

    return config;
};
```

**Comment by xjchenhao** [comment]
经排查是服务器的环境问题，不是node服务导致的。

感谢各位回复，开发人员辛苦了！☕️
