### ISSUE TITLE
egg升级到2.x时报错

### ISSUE THREAD

**Issue by 156520783** [eggjs/egg#1756]
有两个问题请教，
1.如何查看目前egg的版本号，是egg-init的版本吗，npm list egg-init -g 吗？
2.参考了 #1742 的回答，在输入命令npm run autod后，报错，错误信息如下。另外，在项目目录下，输入命令node ./node_modules/egg-bin autod后，什么提示都没有，现象就好像我什么命令都没有输入直接按回车一样。

npm run autod命令的报错信息如下：
/Users/majiajun/MJJ/nodejs/eggjs/hugyoung-wx-plus/node_modules/autod/index.js:51
      throw new Error('plugin ' + options.plugin + ' not exist!');
      ^

Error: plugin autod-egg not exist!
    at new Autod (/Users/majiajun/MJJ/nodejs/eggjs/hugyoung-wx-plus/node_modules/autod/index.js:51:13)
    at Autod (/Users/majiajun/MJJ/nodejs/eggjs/hugyoung-wx-plus/node_modules/autod/index.js:19:12)
    at Object.<anonymous> (/Users/majiajun/MJJ/nodejs/eggjs/hugyoung-wx-plus/node_modules/autod/bin/autod.js:94:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugyoung-wx-plus@1.0.0 autod: `autod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hugyoung-wx-plus@1.0.0 autod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/majiajun/.npm/_logs/2017-11-28T13_37_18_189Z-debug.log

**Comment by popomore** [comment]
修改 package.json 的 egg 版本即可

**Comment by popomore** [comment]
@atian 文档改改，别用 autod 升级了

**Comment by atian25** [comment]
https://github.com/eggjs/egg/pull/1713/files

改了
