### ISSUE TITLE
自定义异常处理bug

### ISSUE THREAD

**Issue by jasonchou3** [eggjs/egg#1784]
* **Node Version**:8.9.1
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

//config/config.default.js

`
  config.onerror = {
    all (err, ctx) {
      ctx.body = {errcode:500,debug:err.stack}
    }
  }
`

错误：

2017-12-05 22:50:48,352 ERROR 26739 nodejs.TypeError: First argument must be a string or Buffer
    at ServerResponse.end (_http_outgoing.js:737:13)
    at Object.app.context.onerror (/Users/zhou/code/demo/wsjs_egg/node_modules/koa-onerror/index.js:87:14)
    at onerror (/Users/zhou/code/demo/wsjs_egg/node_modules/koa/lib/application.js:147:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by popomore** [comment]
body 要返回一个字符串

**Comment by YL2014** [comment]
这里如果想返回一个json呢，该怎么处理
