### ISSUE TITLE
运行npm stop命令后报错

### ISSUE THREAD

**Issue by Eddie104** [eggjs/egg#1811]
报错如下，求解决方法
```
⚠️  Error: Run "sh -c ps -eo "pid,command"" error, exit code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
```

**Comment by atian25** [comment]
运行环境？

发自我的 iPhone

**Comment by Eddie104** [comment]
Linux DiskStation 3.10.35 #1 SMP Sat Dec 12 17:01:14 MSK 2015 x86_64 GNU/Linux synology_bromolow_3615xs
node 8.9.1
egg ^2.0.0

**Comment by atian25** [comment]
是不是你的操作系统禁止执行 ps ?

用 `DEBUG=common-bin npm stop` 看看输出，再不行的话，自己试下 `sh -c ps -eo "pid,command` 这条指令排查下。

**Comment by Eddie104** [comment]
手动执行 sh -c ps -eo "pid,command"  是没问题的，现在只能通过这个命令找出pid，然后kill掉。

**Comment by atian25** [comment]
用 DEBUG=common-bin npm stop 看看输出

**Comment by Eddie104** [comment]
```
common-bin [EggScripts] origin argument `stop` +0ms
  common-bin [EggScripts] add command `start` from `/root/NAS/node_modules/_egg-scripts@2.4.0@egg-scripts/lib/cmd/start.js` +48ms
  common-bin [EggScripts] add command `stop` from `/root/NAS/node_modules/_egg-scripts@2.4.0@egg-scripts/lib/cmd/stop.js` +2ms
  common-bin [EggScripts] loaded command `start,stop` from directory `/root/NAS/node_modules/_egg-scripts@2.4.0@egg-scripts/lib/cmd` +0ms
  common-bin [EggScripts] dispatch to subcommand `stop` -> `StopCommand` with [] +343ms
  common-bin [StopCommand] origin argument `` +1ms
  common-bin [StopCommand] exec run command +16ms
[egg-scripts] stopping egg application
⚠️  Error: Run "sh -c ps -eo "pid,command"" error, exit code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
  common-bin args  +81ms
  common-bin Error: Run "sh -c ps -eo "pid,command"" error, exit code 1
  common-bin     at ChildProcess.proc.on.code (/root/NAS/node_modules/_runscript@1.3.0@runscript/index.js:74:21)
  common-bin     at emitTwo (events.js:126:13)
  common-bin     at ChildProcess.emit (events.js:214:7)
  common-bin     at maybeClose (internal/child_process.js:925:16)
  common-bin     at Socket.stream.socket.on (internal/child_process.js:346:11)
  common-bin     at emitOne (events.js:116:13)
  common-bin     at Socket.emit (events.js:211:7)
  common-bin     at Pipe._handle.close [as _onclose] (net.js:554:12) +2ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NAS@1.0.0 stop: `egg-scripts stop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NAS@1.0.0 stop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-14T14_47_17_801Z-debug.log
```

**Comment by atian25** [comment]
可能是你的权限问题。

发自我的 iPhone

**Comment by atian25** [comment]
检查下是不是启动 egg 的那个进程没有权限执行 sh 吧。

**Comment by peterzhai** [comment]
@atian25 您好，请问如何解决这个权限问题？

**Comment by atian25** [comment]
提供下你的  package
