### ISSUE TITLE
在发起6000左右的websocket时，egg就异常

### ISSUE THREAD

**Issue by ztiandan** [eggjs/egg#1927]
在发起6000左右的websocket时，egg就异常退出了，请问怎么才能不让egg退出？我在config里面加了捕获异常，但还是退出了，我这些websocket不是每个都需要成功的，但异常整个程序都崩溃了，求解。
process.on('uncaughtException', (err) => {
    console.log(err);
  });
  process.on('unhandledRejection', (reason, p) => {
    console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  });

Uncaught Error: read ECONNRESET

FROM
TLSSocket.emit (events.js:1:1)
emitErrorNT (internal/streams/destroy.js:1:1)
process._tickCallback (internal/process/next_tick.js:138:11)
[2018-01-06 10:32:39.778] [cfork:master:3889] worker:3891 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-01-06 10:32:39.788] [cfork:master:3889] new worker:4037 fork (state: none)
[2018-01-06 10:32:39.791] [cfork:master:3889] worker:3891 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2018-01-06 10:32:39,794 ERROR 3889 nodejs.AppWorkerDiedError: [master] app_worker#1:3891 died (code: null, signal: SIGILL, suicide: false, state: dead), current workers: ["2"]
    at Master.onAppExit (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/master.js:384:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/master.js:263:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 3889
hostname: Danny.local

Uncaught channel closed

FROM
process.emit (events.js:1:1)
process.target.send (internal/child_process.js:1:1)
Messenger.sendToParent (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:1:1)
Messenger.send (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:1:1)
Master.onAppExit (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/master.js:1:1)
emitOne (events.js:1:1)
Master.emit (events.js:1:1)
Messenger.sendToMaster (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:1:1)
Messenger.send (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/utils/messenger.js:1:1)
EventEmitter.cluster.on (/Users/DannyTian/Code/Server/K1m7.Avalokitesvara/node_modules/egg-cluster/lib/master.js:1:1)
emitThree (events.js:1:1)
EventEmitter.emit (events.js:1:1)
ChildProcess.worker.process.once (internal/cluster/master.js:1:1)
Object.onceWrapper (events.js:1:1)
emitTwo (events.js:1:1)
ChildProcess.emit (events.js:1:1)
Process.ChildProcess._handle.onexit (internal/child_process.js:1:1)
2018-01-06 10:32:39,808 ERROR 3890 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-01-06 10:32:39,809 ERROR 3890 [agent_worker] exit with code:110
2018-01-06 10:32:41,762 ERROR 4037 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false

**Comment by solarhell** [comment]
记得捕获一下 `on('error')`
