### ISSUE TITLE
socket is closed by other side while there were still unhandled data in the socket buffer

### ISSUE THREAD

**Issue by wencheng1990** [eggjs/egg#1929]
**背景：我用for循环里面curl请求地址解析处理，用的egg定时任务，跑几秒就报错了。**

**小demo：**
`
const Subscription = require('egg').Subscription;
var cheerio = require('cheerio');

class UpdateCache extends Subscription {
    static get schedule() {
        return {
            cron: '* 50 18 * * *',
            type: 'all', 
        };
    }

    async subscribe() {
        const app = this.app;

        let all = await app.mysql.select('fund', {});
        for(let i=0;i<all.length;i++){
            try {
                var result = await this.ctx.curl('http://xxx.com/123.html', {
                method: 'GET',
                timeout: [ 1000*9, 1000*30 ],
                });
            } catch (error) {
                console.log(error);
            }
        
        let body = result.data.toString("utf8");
        var $ = cheerio.load(body);
        
        // 下面就是cheerio解析网页处理
        $('#Li2 tbody tr').each(async function(i2, elem) {
	    if(i2>0){
            var gpmc = $(this).children('.alignLeft').text();
            var cczb = $(this).children('.alignLeft').next().text();
            
            let data = {stock_name:gpmc,cczb:cczb};
            await app.mysql.insert('position', data);
		}
	}
}
`

**报错提示：**

<--- Last few GCs --->

[14828:0000023A4147C4B0]    74308 ms: Mark-sweep 1410.5 (1447.0) -> 1410.3 (1447.0) MB, 1589.0 / 0.0 ms  last resort

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000009B9D41CEA9 <JSObject>
    1: new Node [C:\Users\egg-example\node_modules\parse5\lib\tree_adapters\htmlparser2.js:~25] [pc=000000DCB83FED74](this=000002E1D16E11D9 <Node map = 0000037960DE7A39>,props=000002E1D16E1171 <Object map = 0000037960DE7931>)
    3: START_TAG_TOKEN(aka startTagInBody) [C:\Users\egg-example\node_modules\parse5\lib\parse...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[2018-01-06 18:51:10.012] [cfork:master:19952] worker:14828 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-01-06 18:51:10.012] [cfork:master:19952] don't fork new work (refork: false)
2018-01-06 18:51:10,012 INFO 19952 [master] app_worker#1:14828 disconnect, suicide: false, state: disconnected, current workers: ["1"]
2018-01-06 18:51:10,012 WARN 21148 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2018-01-06 18:51:10.228] [cfork:master:19952] worker:14828 exit (code: 3, exitedAfterDisconnect: false, state: dead,
isDead: true, isExpected: true, worker.disableRefork: false)
2018-01-06 18:51:10,228 ERROR 19952 nodejs.AppWorkerDiedError: [master] app_worker#1:14828 died (code: 3, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (C:\Users\egg-example\node_modules\egg-cluster\lib\master.js:381:21)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (C:\Users\egg-example\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (C:\Users\egg-example\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at EventEmitter.cluster.on (C:\Users\egg-example\node_modules\egg-cluster\lib\master.js:260:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
pid: 19952
hostname: DESKTOP-B4T5FEJ

**Comment by dead-horse** [comment]
内存泄漏了，找找代码原因吧
