### ISSUE TITLE
windows下升级到egg2.2 无法启动项目

### ISSUE THREAD

**Issue by beginnor** [eggjs/egg#1937]
* **Node Version**:v8.9.2
* **Egg Version**: 2.2.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows
* **Mini Showcase Repository**:

之前用egg 0.9开发的，项目，升级到了2.2 ，无法启动
在windows 下开发，由于win下无法使用egg script ,
在index.js 用 egg-cluster 进行启动，报错

```
require('egg').startCluster({
  require('egg-cluster').startCluster({
  baseDir: __dirname,
  port: process.env.PORT || 8000,
  workers:3  ,
});
```

报错

```
D:\pis-egg\node_modules\mkdirp\index.js:92
                if (!stat.isDirectory()) throw err0;
Error: EEXIST: file already exists, mkdir 'D:\pis-egg\config\config.default.js'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (D:\pis-egg\node_modules\mkdirp\index.js:71:13)
    at sync (D:\pis-egg\node_modules\mkdirp\index.js:77:24)
    at sync (D:\pis-egg\node_modules\mkdirp\index.js:77:24)
    at sync (D:\pis-egg\node_modules\mkdirp\index.js:77:24)
    at Function.sync (D:\pis-egg\node_modules\mkdirp\index.js:77:24)
    at FileTransport._createStream (D:\pis-egg\node_modules\egg-logger\lib\transports\file.js:97:12)
    at FileTransport.reload (D:\pis-egg\node_modules\egg-logger\lib\transports\file.js:46:25)
    at new FileTransport (D:\pis-egg\node_modules\egg-logger\lib\transports\file.js:29:10)
    at new EggLogger (D:\pis-egg\node_modules\egg-logger\lib\egg\logger.js:36:27)
```

**Comment by beginnor** [comment]
将 env 内去掉后，又报以下错误

```
AssertionError [ERR_ASSERTION]: should pass config.logger.dir
    at new Loggers (D:\pis-egg\node_modules\egg-logger\lib\egg\loggers.js:60:5)
    at createLoggers (D:\pis-egg\node_modules\egg\lib\core\logger.js:13:19)
    at Agent.get loggers [as loggers] (D:\pis-egg\node_modules\egg\lib\egg.js:266:23)
    at Agent.getLogger (D:\pis-egg\node_modules\egg\lib\egg.js:278:17)
    at Agent.get coreLogger [as coreLogger] (D:\pis-egg\node_modules\egg\lib\egg.js:296:17)
    at Agent._wrapMessenger (D:\pis-egg\node_modules\egg\lib\agent.js:58:51)
    at new Agent (D:\pis-egg\node_modules\egg\lib\agent.js:23:10)
    at Object.<anonymous> (D:\pis-egg\node_modules\egg-cluster\lib\agent_worker.js:22:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
2018-01-09 15:28:00,513 ERROR 2788 [master] exit with code:1
```

**Comment by okoala** [comment]
需要提供可重现的仓库

**Comment by atian25** [comment]
feel free to reopen if more information is provided.
