### ISSUE TITLE
升级到最新 egg2 版本，中间件 this.abort() 失效

### ISSUE THREAD

**Issue by devrsi0n** [eggjs/egg#1966]
* **Node Version**: v8.9.3
* **Egg Version**: 2.2.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS 10.12.6
* **Mini Showcase Repository**:

之前有个插件跑在 egg 1.12.0，在升级到 egg2 过程中遇到在中间件使用的 this.abort() 方法失效，换成 ctx.abort() 提示 `TypeError: ctx.abort is not a function`，搜了 egg 整个仓库和文档都没有发现这个 API，请问这个 API 已经移除了吗？如果已移除推荐使用什么 API 替换呢？
代码：
```js
'use strict';

const url = require('url');
const request = require('request');
const debug = require('debug')('beidou-plugin:webpack');

module.exports = function (options, app) {
  return async function (ctx, next) {
    let webpackUrl = ctx.request.href.replace(
      url.parse(ctx.request.href).port,
      app.webpackServerPort
    );

    // force to use `http` protocol, because webpack does not support https
    webpackUrl = webpackUrl.replace(/^https/, 'http');
    const webpackRequest = request(webpackUrl);
    const notFound = await new Promise((resolve) => {
      webpackRequest.on('response', (res) => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          debug('redirect request to webpack with url: %s', webpackUrl);
          ctx.res.statusCode = res.statusCode;
          for (const key in res.headers) {
            ctx.res.setHeader(key, res.headers[key]);
          }
          res.pipe(ctx.res).on('finish', resolve);
          return;
        }
        ctx.abort();
        resolve(true);
      });
    });
    if (notFound) {
      await next();
    }
  };
};
```
报错：
```
TypeError: ctx.abort is not a function (uncaughtException throw 1 times on pid:58871)
    at Request.webpackRequest.on.res (/Users/devrsi0n/code/beidou/packages/beidou-plugin-webpack/app/middleware/webpack.js:28:13)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/Users/devrsi0n/code/beidou/packages/beidou-plugin-webpack/node_modules/request/request.js:1068:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```

**Comment by devrsi0n** [comment]
不好意思，已找到代码问题，是 function 的 this 引用问题。
