### ISSUE TITLE
eggjs-view-handlebars 在没有 partials 目录时会导致 egg 无法启动

### ISSUE THREAD

**Issue by yiliangt5** [eggjs/egg#1967]
* **Node Version**:
8.9.3
* **Egg Version**:
2.2.0
* **Plugin Name**:
egg-view-handlebars
* **Plugin Version**:
2.0.0
* **Platform**:
macOS
* **Mini Showcase Repository**:

```
yiliangmbp:egg-example:% npm run dev

> inewsletter@0.0.1 dev /Users/yiliangt5/Developer/egg-example
> egg-bin dev

2018-01-15 21:25:12,360 INFO 64100 [master] node version v8.9.3
2018-01-15 21:25:12,362 INFO 64100 [master] egg version 2.2.0
2018-01-15 21:25:12,810 INFO 64100 [master] agent_worker#1:64101 started (445ms)
/Users/yiliangt5/Developer/egg-example/node_modules/egg/lib/application.js:55
      throw e;
      ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports.app (/Users/yiliangt5/Developer/egg-example/node_modules/egg-view-handlebars/app.js:11:28)
    at AppWorkerLoader.loadFile (/Users/yiliangt5/Developer/egg-example/node_modules/egg-core/lib/loader/egg_loader.js:292:30)
    at getLoadUnits.forEach.unit (/Users/yiliangt5/Developer/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:29)
    at Array.forEach (<anonymous>)
    at AppWorkerLoader.loadCustomApp (/Users/yiliangt5/Developer/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:8)
    at AppWorkerLoader.load (/Users/yiliangt5/Developer/egg-example/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
    at new Application (/Users/yiliangt5/Developer/egg-example/node_modules/egg/lib/application.js:51:19)
    at Object.<anonymous> (/Users/yiliangt5/Developer/egg-example/node_modules/egg-cluster/lib/app_worker.js:13:13)
    at Module._compile (module.js:635:30)
[2018-01-15 21:25:13.385] [cfork:master:64100] worker:64102 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-01-15 21:25:13.385] [cfork:master:64100] don't fork, because worker:64102 will be kill soon
2018-01-15 21:25:13,386 INFO 64100 [master] app_worker#1:64102 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-01-15 21:25:13.386] [cfork:master:64100] worker:64102 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-01-15 21:25:13,388 ERROR 64100 nodejs.AppWorkerDiedError: [master] app_worker#1:64102 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/yiliangt5/Developer/egg-example/node_modules/egg-cluster/lib/master.js:384:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/Users/yiliangt5/Developer/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/yiliangt5/Developer/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/Users/yiliangt5/Developer/egg-example/node_modules/egg-cluster/lib/master.js:263:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 64100
hostname: yiliangmbp.local

2018-01-15 21:25:13,389 ERROR 64100 [master] app_worker#1:64102 start fail, exiting with code:1
2018-01-15 21:25:13,389 ERROR 64100 [master] exit with code:1
2018-01-15 21:25:13,394 ERROR 64101 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-01-15 21:25:13,395 ERROR 64101 [agent_worker] exit with code:110
⚠️  Error: /Users/yiliangt5/Developer/egg-example/node_modules/egg-bin/lib/start-cluster {"baseDir":"/Users/yiliangt5/Developer/egg-example","framework":"/Users/yiliangt5/Developer/egg-example/node_modules/egg","workers":1} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inewsletter@0.0.1 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inewsletter@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yiliangt5/.npm/_logs/2018-01-15T13_25_13_412Z-debug.log
```

**Comment by yiliangt5** [comment]
merged

**Comment by atian25** [comment]
next time, just add `close https://github.com/eggjs/egg/issues/1967` to your PR, then when it merged, this issue will auto close.

**Comment by yiliangt5** [comment]
Sure I will. Thanks.
