### ISSUE TITLE
egg.js运行一段时间，经常会报ResourceRequest timed out

### ISSUE THREAD

**Issue by nlove518** [eggjs/egg#1970]
最近一段时间经常受到timed out 困扰，报错信息如下
2018-01-15 16:51:36,820 ERROR 2126 [-/127.0.0.1/-/30006ms 
GET /api/wj_library_detail/oKVL71UmaW0UtYN9L-M-yGkwYe04] 
nodejs.TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/www/wj_server/node_modules/generic-pool/lib/ResourceRequest.js:58:17)
    at Timeout.bound (/www/wj_server/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'TimeoutError'
每次出现这个错误服务必须重启，才能正常运行。
请问造成timeout 的原因是什么？ 有什么解决方法吗？

**Comment by atian25** [comment]
`generic-pool` 这个库是你引入的吧？检查下是不是哪里有问题。

**Comment by kylezhang** [comment]
对，我也遇到了
是 sequelize的问题。

**Comment by nlove518** [comment]
@kylezhang 那这个问题你是怎么解决的？

**Comment by nlove518** [comment]
@atian25 升级sequelize版本 系统运行一段时间还是报timeout

**Comment by airyland** [comment]
https://github.com/sequelize/sequelize/issues/8877

今天清除 node_modules 重新安装所有依赖进行单元测试时就报错了，之前完全正常，还不能确定是具体哪个版本问题。

**Comment by leosj** [comment]
@nlove518 老哥解决了吗

**Comment by acodercat** [comment]
求解

**Comment by leosj** [comment]
@acodercat 应该是事务的问题，看看事务那边是不是没有commit或者rollback，或者就不用事务

**Comment by imsjw** [comment]
同样问题

**Comment by imsjw** [comment]
遇到同样问题了   难受

**Comment by hugeshi** [comment]
@nlove518 问题解决了吗？求解

**Comment by hugeshi** [comment]
感谢回复，问题已经解决，代码有BUG，resource没有release

Wade.ze <notifications@github.com> 于2019年8月22日周四 下午2:55写道：
