### ISSUE TITLE
egg-mysql报错

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#2018]
* **Node Version**:6.11.4
* **Egg Version**:1.8.0
* **Plugin Name**:egg-mysql
* **Plugin Version**:3.0.0
* **Platform**:linux
* **Mini Showcase Repository**:

2018-01-24 17:45:49,044 ERROR 19366 nodejs.unhandledRejectionError: Handshake inactivity timeout
    at Handshake.<anonymous> (/root/tokenapi/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (/root/tokenapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/root/tokenapi/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/root/tokenapi/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/root/tokenapi/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/root/tokenapi/node_modules/mysql/lib/Pool.js:48:16)
    at /root/tokenapi/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/root/tokenapi/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/root/tokenapi/node_modules/pify/index.js:56:34)
    at Pool.query (/root/tokenapi/node_modules/mysql/lib/Pool.js:202:8)
    at /root/tokenapi/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/root/tokenapi/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/root/tokenapi/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/root/tokenapi/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/root/tokenapi/node_modules/ali-rds/lib/operator.js:54:29)
    at next (native)
    at onFulfilled (/root/tokenapi/node_modules/co/index.js:65:19)
    at /root/tokenapi/node_modules/co/index.js:54:5
    at RDSClient.co (/root/tokenapi/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as query] (/root/tokenapi/node_modules/co/index.js:30:15)
    at /root/tokenapi/app/schedule/revied2.js:264:65
    at process._tickCallback (internal/process/next_tick.js:109:7)
    sql: update blockheight set _value = _value+10 where id = 11
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
name: 'unhandledRejectionError'
pid: 19366
hostname: localhost

经常报这个错的原因是什么？超时？如何修改这个超时时间

**Comment by atian25** [comment]
为什么这条 SQL 执行十秒这么久？

**Comment by Ailein** [comment]
我也很奇怪，我服务器是国外服务器，然后数据库是aws,但是 整个网站的其他sql也没这样，这个是在定时任务执行的

**Comment by dead-horse** [comment]
这是 mysql 的报错，看起来像是链接问题
