### ISSUE TITLE
linux 环境无法通过egg-scripts启动，其他 os 一切正常

### ISSUE THREAD

**Issue by jamescheng16** [eggjs/egg#2024]
* **Node Version**: node@v9.2.0
* **Egg Version**:2.0.0 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: linux
* **Mini Showcase Repository**:
 "dependencies": {
    "egg": "^2.0.0",
    "egg-mongoose": "^2.1.1",
    "egg-scripts": "^2.1.0",
    "egg-validate": "^1.0.0",
    "egg-view-ejs": "^2.0.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.13.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^5.1.0",
    "webstorm-disable-index": "^1.2.0"
  },

在 mac 上可以正常通过egg-scripts启动 ， 但是 linux 上无法启动 ， 错误 log 如下
`root@ubuntu:~/geneseeq_report/Report/Front_End/ReportSys# sudo npm run test-start

0 info it worked if it ends with ok

1 verbose cli [ '/usr/local/bin/node',

1 verbose cli   '/usr/local/bin/npm',

1 verbose cli   'run',

1 verbose cli   'test-start' ]

2 info using npm@5.5.1

3 info using node@v9.2.0

4 verbose run-script [ 'pretest-start', 'test-start', 'posttest-start' ]

5 info lifecycle ReportSys@1.0.0~pretest-start: ReportSys@1.0.0

6 info lifecycle ReportSys@1.0.0~test-start: ReportSys@1.0.0

7 verbose lifecycle ReportSys@1.0.0~test-start: unsafe-perm in lifecycle true

8 verbose lifecycle ReportSys@1.0.0~test-start: PATH: /usr/local/lib/node_modul
es/npm/bin/node-gyp-bin:/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

9 verbose lifecycle ReportSys@1.0.0~test-start: CWD:/root/geneseeq_report/Report/Front_End/ReportSys

10 silly lifecycle ReportSys@1.0.0~test-start: Args: [ '-c',

10 silly lifecycle   'egg-scripts start --daemon --port=7006 --env=sit --title=egg-lims-front-test' ]

11 silly lifecycle ReportSys@1.0.0~test-start: Returned: code: 1  signal: null

12 info lifecycle ReportSys@1.0.0~test-start: Failed to exec test-start script

13 verbose stack Error: ReportSys@1.0.0 test-start: `egg-scripts start --daemon --port=7006 --env=sit --title=egg-lims-front-test`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid ReportSys@1.0.0
15 verbose cwd /root/geneseeq_report/Report/Front_End/ReportSys
16 verbose Linux 4.4.0-31-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-start"
18 verbose node v9.2.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error ReportSys@1.0.0 test-start: `egg-scripts start --daemon --port=7006 --env=sit --title=egg-lims-front-test`
22 error Exit status 1`

**Comment by atian25** [comment]
不用加 verbose，去掉 --daemon 看下日志输出是啥

**Comment by jamescheng16** [comment]
如果不加 --deamon 一切正常启动 
部分 log 如下

`
seeq_report/Report/Front_End/ReportSys"} --title=egg-lims-front-test

2018-01-24 21:44:06,628 INFO 22966 [master] =================== egg start =====================

2018-01-24 21:44:06,629 INFO 22966 [master] node version v9.2.0

2018-01-24 21:44:06,629 INFO 22966 [master] egg version 2.2.1

2018-01-24 21:44:06,629 INFO 22966 [master] start with options:

{
  "framework": "/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/egg",
  "baseDir": "/root/geneseeq_report/Report/Front_End/ReportSys",
  "port": 7006,
  "workers": 8,
  "plugins": null,
  "https": false,
  "key": "",
  "cert": "",
  "title": "egg-lims-front-test"
}

2018-01-24 21:44:06,629 INFO 22966 [master] start with env: isProduction: true, EGG_SERVER_ENV: sit, NODE_ENV: production

2018-01-24 21:44:06,635 INFO 22966 [master] agent_worker#1:22972 start with clusterPort:39156

2018-01-24 21:44:06,842 WARN 22972 plugin i18n has been defined that is {"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js"}, but you define again in /root/geneseeq_report/Report/Front_End/ReportSys/config/plugin.js

2018-01-24 21:44:06,845 INFO 22972 Plugin development is disabled by env unmatched, require env(local) but got env is sit

2018-01-24 21:44:06,854 INFO 22972 [egg:core] App root: /root/geneseeq_report/Report/Front_End/ReportSys

2018-01-24 21:44:06,854 INFO 22972 [egg:core] All *.log files save on "/root/logs/ReportSys"

2018-01-24 21:44:06,854 INFO 22972 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-session@3.1.0@egg-session","version":"3.1.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-security@2.0.0@egg-security","version":"2.0.0"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-jsonp@2.0.0@egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-onerror@2.0.0@egg-onerror","version":"2.0.0"},{"enable":true,"name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/config/plugin.js","package":"egg-i18n","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-i18n@2.0.0@egg-i18n","version":"2.0.0"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-watcher@3.0.0@egg-watcher","version":"3.0.0"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-multipart@2.0.0@egg-multipart","version":"2.0.0"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-schedule@3.1.1@egg-schedule","version":"3.1.1"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-logrotator@3.0.1@egg-logrotator","version":"3.0.1"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-static@2.1.0@egg-static","version":"2.1.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg@2.2.1@egg/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-view@2.0.0@egg-view","version":"2.0.0"},{"enable":true,"package":"egg-mongoose","name":"mongoose","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-mongoose@2.1.1@egg-mongoose","version":"2.1.1"},{"enable":true,"package":"egg-validate","name":"validate","dependencies":[],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-validate@1.0.0@egg-validate","version":"1.0.0"},{"enable":true,"package":"egg-view-ejs","name":"ejs","dependencies":["view"],"optionalDependencies":[],"env":[],"from":"/root/geneseeq_report/Report/Front_End/ReportSys/config/plugin.js","path":"/root/geneseeq_report/Report/Front_End/ReportSys/node_modules/_egg-view-ejs@2.0.0@egg-view-ejs","version":"2.0.0"}]

2018-01-24 21:44:06,858 INFO 22972 [egg:logger] init all loggers with options: {"dir":"/root/logs/ReportSys","encoding":"utf8","env":"sit","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"ReportSys-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":true,"type":"agent"}

2018-01-24 21:44:07,046 INFO 22972 [egg-mongoose] connecting 

2018-01-24 21:44:07,080 INFO 22972 [egg-mongoose] starting...

2018-01-24 21:44:07,083 INFO 22972 [egg-watcher:agent] watcher start success
`

**Comment by atian25** [comment]
不用加 verbose 但保留  --daemon 看看

**Comment by jamescheng16** [comment]
@atian25  怎么样启动可以是不加 verbose 但是保留 daemon

现在的命令是 

`
egg-scripts start --daemon --port=7006 --env=sit --title=egg-front-test
`

**Comment by atian25** [comment]
你的 `sudo npm run test-start` 为什么会输出这么多的 verbose 日志？却没有 egg-scripts 的执行日志。` test-start` 里面的内容是啥？

提供下最小可复现仓库？

**Comment by jamescheng16** [comment]
我发出来的日志是/usr/local/node-v9.2.0/node_cache/_logs/2018-01-25T06_00_18_009Z-debug.log  中的 node 的完整日志， 启动时屏幕上egg 的日志是这样的

仓库的话因为是公司的项目不方便放出来


`

npm run test-start

  ReportSys@1.0.0 test-start /usr/local/testEgg/ReportSys

  egg-scripts start --daemon --port=7006 --env=sit --title=egg--front-test

[egg-scripts] Starting egg application at /usr/local/testEgg/ReportSys

[egg-scripts] Run node /usr/local/testEgg/ReportSys/node_modules/_egg-scripts@2.5.0@egg-scripts/lib/start-cluster {"port":7006,"title":"egg-front-test","framework":"/usr/local/testEgg/ReportSys/node_modules/egg","baseDir":"/usr/local/testEgg/ReportSys"} --title=egg-front-test

[egg-scripts] Save log file to /root/logs

[egg-scripts] Wait Start: 1...

[egg-scripts] Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

[egg-scripts]
[egg-scripts] Start got error, see /root/logs/master-stderr.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ReportSys@1.0.0 test-start: `egg-scripts start --daemon --port=7006 --env=sit --title=egg-lims-front-test `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReportSys@1.0.0 test-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by atian25** [comment]
早放这个出来嘛...

启动指令增加一个 `--ignore-stderr` 即可。

**Comment by jamescheng16** [comment]
谢谢指导，
能否讲解一下是什么样的 stderr 造成的？

**Comment by jamescheng16** [comment]
是不是因为egg-mongoose的那条报错?

**Comment by jamescheng16** [comment]
@atian25 等大佬一个回复

**Comment by atian25** [comment]
嗯，可以看下 egg-scripts 源码，默认会检测 stderr 有没有错误日志，有的话就退出。

**Comment by jamescheng16** [comment]
@atian25 感谢！
