### ISSUE TITLE
mysql 插入中文失败

### ISSUE THREAD

**Issue by GSBL** [eggjs/egg#2040]
* **Node Version**:v8.9.4
* **Egg Version**:2.0.0
* **Plugin Name**:egg-mysql
* **Plugin Version**:3.0.0
* **Platform**:mac os
* **Mini Showcase Repository**:
egg-mysql 插入中文失败,提示 ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value, mysql配置全是uft-8,
代码如下
```
const toolbox = await this.app.mysql.insert('product',{
      name: '工具集',
      project: 'toolbox',
      publish_time: Date.now()
    })
```
![image](https://user-images.githubusercontent.com/11496924/35429194-ee9721be-02ad-11e8-9684-5c91abc6c566.png)

2018-01-26 15:13:50,168 ERROR 45938 [-/::1/-/32ms POST /toolbox/login] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE5\xB7\xA5\xE5\x85\xB7...' for column 'name' at row 1
    at Query.Sequence._packetToError (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/co/index.js:65:19)
    at /Users/huangguanghui/Desktop/repos/smart-analytics/node_modules/co/index.js:54:5
    sql: INSERT INTO `product`(`name`, `project`, `publish_time`) VALUES('工具集', 'toolbox', 1516950830164)
code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD'
errno: 1366
sqlMessage: 'Incorrect string value: \'\\xE5\\xB7\\xA5\\xE5\\x85\\xB7...\' for column \'name\' at row 1'
sqlState: 'HY000'
index: 0
sql: 'INSERT INTO `product`(`name`, `project`, `publish_time`) VALUES(\'工具集\', \'toolbox\', 1516950830164)'
name: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError'
pid: 45938

**Comment by dead-horse** [comment]
请去查询 mysql 相关资料
