### ISSUE TITLE
热更新重启服务时报错

### ISSUE THREAD

**Issue by DragWeb** [eggjs/egg#2066]
```bash
2018-01-31 21:45:43,136 ERROR 74253 nodejs.unhandledExceptionError: listen EADDRINUSE 127.0.0.1:3042
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'listen'
address: '127.0.0.1'
port: 3042
name: 'unhandledExceptionError'
pid: 74253
```
本地调试虽然不影响程序异常，但是命令行看起来很不舒服

**Comment by dead-horse** [comment]
从端口号看起来与 egg 网关
