### ISSUE TITLE
follower closed, and try to init it again

### ISSUE THREAD

**Issue by jianggaocheng** [eggjs/egg#2080]
Node Version:
9.4.0
Egg Version:
2.3.0
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:

启动一段时间后就会产生这条信息，可能是什么原因产生的。
现在就在app.js里面写了连接数据库（mongodb）的语句，以及在agent中启动了一个TCP客户端

2018-02-02 18:56:23,951 WARN 39983 [ClusterClient:Watcher] follower closed, and try to init it again
2018-02-02 18:56:23,951 ERROR 39982 nodejs.ClusterClientNoResponseError: client no response in 196534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Documents/work/bolang/room-control-system/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
name: 'ClusterClientNoResponseError'
pid: 39982

**Comment by atian25** [comment]
mongodb 直接用 egg-mongoose

现在的错误日志上看不出原因。

TCP 那边做了啥

**Comment by jianggaocheng** [comment]
把Agent里面的代码注释掉了也会报错误，排除了TCP那边的原因了。
为了兼容原来的数据库连接方式（原来使用node-orm2连接），在app.js里面做了数据库连接

```
module.exports = app => {
  app.beforeStart(async () => {
    // 数据库连接
    let db = await orm.connectAsync(app.config.database);
    require('./app/model').init(orm, db);
    await db.syncPromise();
    app.models = db.models;
  });
};
```

**Comment by gxcsoccer** [comment]
@jianggaocheng 能够提供一个复现的仓库吗？

**Comment by gxcsoccer** [comment]
没有其他的报错吗？ @jianggaocheng

**Comment by acodercat** [comment]
我也遇到这个错误，新项目，开着什么不管过一会就这个错
2018-07-03 18:44:59,740 WARN 11349 [ClusterClient:Watcher] follower closed, and try to init it again
2018-07-03 18:44:59,743 ERROR 11348 nodejs.ClusterClientNoResponseError: client no response in 1615469ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/codercat/Desktop/iot/4.0/server/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 11348
hostname: codercatdeMacBook-Pro.local

**Comment by acodercat** [comment]
我也遇到这个错误，新项目，开着什么不管过一会就这个错

```
2018-07-03 18:44:59,740 WARN 11349 [ClusterClient:Watcher] follower closed, and try to init it again
2018-07-03 18:44:59,743 ERROR 11348 nodejs.ClusterClientNoResponseError: client no response in 1615469ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/codercat/Desktop/iot/4.0/server/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 11348
hostname: codercatdeMacBook-Pro.local
```

**Comment by acodercat** [comment]
给出详细信息
```
codercatdeMacBook-Pro:server codercat$ npm run dev

> server@1.0.0 dev /Users/codercat/Desktop/iot/4.0/server
> egg-bin dev

2018-07-03 13:29:19,585 INFO 11347 [master] node version v8.11.2
2018-07-03 13:29:19,587 INFO 11347 [master] egg version 2.9.1
2018-07-03 13:29:20,097 INFO 11347 [master] agent_worker#1:11348 started (508ms)
2018-07-03 13:29:20,767 INFO 11347 [master] egg started on http://127.0.0.1:7001 (1180ms)
2018-07-03 18:44:59,740 WARN 11349 [ClusterClient:Watcher] follower closed, and try to init it again
2018-07-03 18:44:59,743 ERROR 11348 nodejs.ClusterClientNoResponseError: client no response in 1615469ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/codercat/Desktop/iot/4.0/server/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 11348
hostname: codercatdeMacBook-Pro.local
```

**Comment by acodercat** [comment]
给出项目package.json  新项目，代码没动
``` js
{
  "name": "server",
  "version": "1.0.0",
  "description": "iot",
  "private": true,
  "dependencies": {
    "egg": "^2.2.1",
    "egg-scripts": "^2.5.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.14.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-server",
    "stop": "egg-scripts stop --title=egg-server-server",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
  "ci": {
    "version": "8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "codercat",
  "license": "MIT"
}
```

**Comment by acodercat** [comment]
找到原因了，只要电脑休眠几分钟再打开就会复现。我发现楼主也是mac，可能跟mac有关系

**Comment by fengmk2** [comment]
@gxcsoccer 可以考虑在本地环境，不是连续出现，就忽略掉这个因为临时休眠而出现的异常。

**Comment by jianggaocheng** [comment]
是的，后来发现是mac休眠了再打开就会出现，在生产环境下面没有问题。 @acodercat

**Comment by fhj857676433** [comment]
@gxcsoccer 还是会出现这个问题啊  centos和mac环境每次都出现了 怎么解决 ，node版本 8.9.4,
`{
  "name": "JSGAN",
  "version": "1.0.0",
  "description": "mobile game",
  "dependencies": {
    "@alicloud/pop-core": "^1.7.7",
    "@ntbl/handle": "^1.0.2",
    "apidoc": "^0.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-register": "^6.26.0",
    "bluebird": "^3.7.2",
    "debug": "^4.1.1",
    "egg": "^2.10.0",
    "egg-alinode": "^2.0.1",
    "egg-cors": "^2.2.3",
    "egg-jwt": "^3.1.6",
    "egg-onerror": "^2.1.0",
    "egg-redis": "^2.4.0",
    "egg-scripts": "^2.11.1",
    "egg-sequelize": "^4.3.1",
    "egg-session-redis": "^2.1.0",
    "egg-shell-decorators": "^1.0.7",
    "egg-snowflake": "^1.2.0",
    "egg-swagger2": "^1.0.4",
    "egg-tx": "^1.0.4",
    "egg-validate-plus": "^1.1.6",
    "egg-view-assets": "^1.6.0",
    "egg-view-handlebars": "^2.0.1",
    "handlebars": "^4.5.3",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.15",
    "mathjs": "^6.2.5",
    "md5": "^2.2.1",
    "moment": "^2.24.0",
    "mysql2": "^2.0.0",
    "randomstring": "^1.1.5",
    "redis": "^2.8.0",
    "redis-lock": "^0.1.4",
    "simpleflakes": "^2.1.0",
    "util": "^0.12.1",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-register": "^6.26.0",
    "egg-bin": "^4.14.0",
    "egg-mock": "^3.19.2",
    "eslint": "^4.18.1",
    "eslint-config-egg": "^7.0.0",
    "factory-girl": "^5.0.2",
    "sequelize-cli": "^4.1.1"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "scripts": {
    "debug": "egg-bin debug",
    "dev": "egg-bin dev",
    "autod": "autod",
    "lint": "eslint .",
    "test": "egg-bin test",
    "cov": "egg-bin cov",
    "ci": "npm run lint && NODE_ENV=test npx sequelize db:migrate && npm run cov",
    "start": "egg-scripts start --daemon",
    "stop": "egg-scripts stop",
    "deploy": "egg-deploy"
  },
  "ci": {
    "version": "8"
  },
  "eslintIgnore": [
    "coverage",
    "dist"
  ],
  "repository": {
    "type": "git",
    "url": ""
  },
  "files": [
    "lib",
    "index.js"
  ],
  "author": "ChaoShuangGame",
  "private": true
}
`
