### ISSUE TITLE
关闭csrf后 mysql 没法用...

### ISSUE THREAD

**Issue by lx3238443k** [eggjs/egg#2082]
为啥关闭csrf之后 mysql语句就出错了？

2018-02-05 12:24:20,141 ERROR 10544 [-/127.0.0.1/-/173ms GET /saveUserInfo?js_code=003srj612rk7rX04fE612AQn612srj6G] nodejs.TypeError: this.app.mysql.insert is not a function
    at UserController.saveUserInfo (D:\work\todo-server\app\controller\user.js:6:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10544
hostname: cs-171127

**Comment by atian25** [comment]
贴下你的 plugin.js 和 config.default.js

**Comment by lx3238443k** [comment]
//config.default.js
exports.keys = '123'
exports.mysql = {
    client: {
      host: '127.0.0.1',
      port: '3306',
      user: 'root',
      password: '',
      database: 'tododemo',
    },
    app: true,
    // load into agent, default is close
    agent: false,
  };
module.exports = {
    security: {
      csrf: {
        enable: false,
      },
    },
  };

//plugin.js
exports.mysql = {
    enable: true,
    package: 'egg-mysql',
  };

**Comment by atian25** [comment]
因为你的 `module.exports` 把前面的 `exports` 覆盖了。
哎。。。第 15 次回答这个问题了。
