### ISSUE TITLE
egg-script 执行发布失败 AppWorkerDiedError 错误

### ISSUE THREAD

**Issue by andylei18** [eggjs/egg#2138]
内容如下：
ERROR 4721 nodejs.AppWorkerDiedError: [master] app_worker#1:4723 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["2","3","4","5","6","7","8"]

**Comment by atian25** [comment]
请提供更多日志

**Comment by andylei18** [comment]
@atian25 
> fe-uak-project@0.0.9 start /Users/dinglei/Documents/work/Git/fe-uak-project
> eggctl start --port=8080 --daemon --framework=@uak/dl-test-node --env=prod --title=egg-server-fe-uak-project --ignore-stderr

[egg-scripts] Starting @uak/dl-test-node application at /Users/dinglei/Documents/work/Git/fe-uak-project
[egg-scripts] Run node /Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/egg-scripts/lib/start-cluster {"port":8080,"framework":"/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/@uak/dl-test-node","title":"egg-server-fe-uak-project","baseDir":"/Users/dinglei/Documents/work/Git/fe-uak-project"} --title=egg-server-fe-uak-project
[egg-scripts] Save log file to /var/root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Got error when startup:
[egg-scripts] 2018-02-26 18:36:28,251 ERROR 5509 nodejs.AppWorkerDiedError: [master] app_worker#1:5511 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["2","3","4","5","6","7","8"]
[egg-scripts]     at Master.onAppExit (/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/egg-cluster/lib/master.js:384:21)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Master.emit (events.js:211:7)
[egg-scripts]     at Messenger.sendToMaster (/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
[egg-scripts]     at Messenger.send (/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
[egg-scripts]     at EventEmitter.cluster.on (/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/egg-cluster/lib/master.js:263:22)
[egg-scripts]     at emitThree (events.js:141:20)
[egg-scripts]     at EventEmitter.emit (events.js:217:7)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
[egg-scripts]     at Object.onceWrapper (events.js:317:30)
[egg-scripts] name: 'AppWorkerDiedError'
[egg-scripts] pid: 5509
[egg-scripts] hostname: dingleideMacBook-Pro-2.local
[egg-scripts]
[egg-scripts] 2018-02-26 18:36:28,252 ERROR 5509 [master] app_worker#1:5511 start fail, exiting with code:1
[egg-scripts] 2018-02-26 18:36:28,252 ERROR 5509 [master] exit with code:1
[egg-scripts] 2018-02-26 18:36:28,257 ERROR 5510 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2018-02-26 18:36:28,257 ERROR 5510 [agent_worker] exit with code:110
[egg-scripts]
[egg-scripts] Start got error, see /var/root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.

**Comment by atian25** [comment]
[egg-scripts] Save log file to /var/root/logs

下面的 common-error

**Comment by andylei18** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dinglei/.nvm/versions/node/v8.9.3/bin/node',
1 verbose cli   '/Users/dinglei/.nvm/versions/node/v8.9.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fe-uak-project@0.0.9~prestart: fe-uak-project@0.0.9
6 info lifecycle fe-uak-project@0.0.9~start: fe-uak-project@0.0.9
7 verbose lifecycle fe-uak-project@0.0.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle fe-uak-project@0.0.9~start: PATH: /Users/dinglei/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dinglei/Documents/work/Git/fe-uak-project/node_modules/.bin:/Users/dinglei/.nvm/versions/node/v8.9.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/ImageMagick/bin
9 verbose lifecycle fe-uak-project@0.0.9~start: CWD: /Users/dinglei/Documents/work/Git/fe-uak-project
10 silly lifecycle fe-uak-project@0.0.9~start: Args: [ '-c',
10 silly lifecycle   'eggctl start --port=8080 --daemon --framework=@uak/dl-test-node --env=prod --title=egg-server-fe-uak-project' ]
11 silly lifecycle fe-uak-project@0.0.9~start: Returned: code: 1  signal: null
12 info lifecycle fe-uak-project@0.0.9~start: Failed to exec start script
13 verbose stack Error: fe-uak-project@0.0.9 start: `eggctl start --port=8080 --daemon --framework=@uak/dl-test-node --env=prod --title=egg-server-fe-uak-project`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dinglei/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dinglei/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid fe-uak-project@0.0.9
15 verbose cwd /Users/dinglei/Documents/work/Git/fe-uak-project
16 verbose Darwin 17.3.0
17 verbose argv "/Users/dinglei/.nvm/versions/node/v8.9.3/bin/node" "/Users/dinglei/.nvm/versions/node/v8.9.3/bin/npm" "start"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error fe-uak-project@0.0.9 start: `eggctl start --port=8080 --daemon --framework=@uak/dl-test-node --env=prod --title=egg-server-fe-uak-project`
22 error Exit status 1
23 error Failed at the fe-uak-project@0.0.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by andylei18** [comment]
common-error.log 没有错

**Comment by popomore** [comment]
应该是 master-stderr?

**Comment by andylei18** [comment]
@atian25 
解决了 我们线上环境 是prod 我没有写 conf.production.js，所有报错了，然后我加了 daemon 屏蔽了报错，所以没找到

这是我的命令内容：
eggctl start --port=8080 --daemon --framework=@uak/dl-test-node --env=prod --title=egg-server-fe-uak-project --ignore-stderr

感觉prod没生效

**Comment by andylei18** [comment]
@popomore 我暂时关了吧，我自己查查 为什么prod没生效

**Comment by popomore** [comment]
是 config.prod.js

**Comment by atian25** [comment]
没有 `config.prod.js` 也不会报错的。
你的启动命令中 `--framework=` 和  `--env=prod` 是没必要的

**Comment by henjing** [comment]
我也遇到了同样的问题，但是没有解决，npm start就会报AppWorkerDiedError，请问怎么解决呢？

**Comment by atian25** [comment]
see master-stderr.log

**Comment by atian25** [comment]
让我来帮你找下关键词：

**[app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE**
**[app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE**
**[app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE**

**Comment by henjing** [comment]
@atian25 谢谢，刚刚找到了

**Comment by onweer** [comment]
Nginx按着官网教程配置的: 
location /socket.io {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            # proxy_bind  $remote_addr transparent;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://some_server:7002;
            error_log /var/log/nginx/log/abc.log;
            break;
        }

前端的ws://请求会报502错误,看了node后端发现错误如下:

[2018-06-01 03:25:33.786] [cfork:master:26] worker:87 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-06-01 03:25:33.789] [cfork:master:26] new worker:97 fork (state: none)
[2018-06-01 03:25:33.790] [cfork:master:26] worker:87 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2018-06-01 03:25:33,790 ERROR 26 nodejs.AppWorkerDiedError: [master] app_worker#5:87 died (code: null, signal: SIGSEGV, suicide: false, state: dead), current workers: ["1","6"]
    at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:384:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/app/node_modules/egg-cluster/lib/master.js:263:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 26
hostname: 5781ad28bf5c

@atian25  请大神帮忙看看

**Comment by atian25** [comment]
跟 nginx 应该没啥关系，你这是一个服务端错误导致 worker 挂掉，看 error 日志

**Comment by onweer** [comment]
@atian25  common-error.log 是空的,但是每次socket请求 第一次是成功的, 后面3次都失败了,每次work挂掉就又重启了

**Comment by onweer** [comment]
![image](https://user-images.githubusercontent.com/11755669/40836917-233e7edc-65cb-11e8-9a8e-0616f79d1858.png)

**Comment by sunfeng90** [comment]
at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
name: "AppWorkerDiedError"
pid: 83004
hostname: FrankdeMacBook-Pro.local

2019-03-15 11:02:09,358 ERROR 83004 [master] app_worker#1:83011 start fail, exiting with code:1
2019-03-15 11:02:09,366 ERROR 83004 [master] exit with code:1
2019-03-15 11:02:09,388 ERROR 83006 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
⚠️  Error: /Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book/node_modules/egg-bin/lib/start-cluster {"typescript":true,"env":"test","port":3017,"baseDir":"/Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book","workers":1,"framework":"/Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book/node_modules/egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
2019-03-15 11:02:09,395 ERROR 83006 [agent_worker] exit with code:110

**Comment by sunfeng90** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.0
3 info using node@v10.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle queue-book@1.0.0~predev: queue-book@1.0.0
6 info lifecycle queue-book@1.0.0~dev: queue-book@1.0.0
7 verbose lifecycle queue-book@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle queue-book@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book/node_modules/.bin:/usr/local/etc/apache-maven-3.5.3/bin:/bin:/usr/local/Cellar/zookeeper/bin:/usr/bin/python2.7/bin:/Users/sunfeng/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin
9 verbose lifecycle queue-book@1.0.0~dev: CWD: /Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book
10 silly lifecycle queue-book@1.0.0~dev: Args: [ '-c',
10 silly lifecycle   'egg-bin dev --env=test -r egg-ts-helper/register --port 3017' ]
11 silly lifecycle queue-book@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle queue-book@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: queue-book@1.0.0 dev: `egg-bin dev --env=test -r egg-ts-helper/register --port 3017`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid queue-book@1.0.0
15 verbose cwd /Users/sunfeng/Project/NodeProject/project/mwbyd/queue-book
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.5.0
19 verbose npm  v6.4.0
20 error code ELIFECYCLE
21 error errno 1
22 error queue-book@1.0.0 dev: `egg-bin dev --env=test -r egg-ts-helper/register --port 3017`
22 error Exit status 1
23 error Failed at the queue-book@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sunfeng90** [comment]
common-error是空的，不知道为什么

**Comment by atian25** [comment]
看下文档，egg-scripts start 的日志是在 home 下的，不是项目目录下

**Comment by sunfeng90** [comment]
launch.json:

{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Egg Debug",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "npm",
            "runtimeArgs": [ "run", "debug"],
            "console": "integratedTerminal",
            "protocol": "auto",
            "restart": true,
            "port": 7001
          }
    ]
}

package.json:

  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-bin": "^4.11.0",
    "egg-ci": "^1.11.0",
    "egg-mock": "^3.21.0",
    "eslint": "^5.13.0",
    "eslint-config-egg": "^7.1.0",
    "webstorm-disable-index": "^1.2.0"
  }

问题：VSC中，打了断点，不进断点，直接输出结果。

利用：打开attach，并且运行npm run debug

**Comment by sunfeng90** [comment]
@atian25 atian25

**Comment by atian25** [comment]
你这个问题跟这个 issue 没啥关系，有问题重新提一个，带上最小可复现方式

**Comment by 854770857** [comment]
@henjing 怎么解决的啊我也遇到了
error: bind EADDRINUSE null:7001, code: EADDRINUSE

**Comment by atian25** [comment]
EADDRINUSE 不是写的非常清楚了么？ Google 下不就知道它的含义了？

**Comment by sun-zy** [comment]
> 我也遇到了同样的问题，但是没有解决，npm start就会报AppWorkerDiedError，请问怎么解决

这个最终是怎么解决的？

**Comment by atian25** [comment]
AppWorkerDiedError 就是 Worker 因为某些原因挂了，具体什么原因，要看你们具体的详细的报错日志，而不是找到一个 issue 就往上**空回复**。

**Comment by alanwon** [comment]
我把node_modules整个文件夹删掉了重新npm install 后就没问题了

**Comment by kinm** [comment]
> 我把node_modules整个文件夹删掉了重新npm install 后就没问题了

万能的 rm -rf node_modules 。。。。😂

**Comment by EasonYou** [comment]
2019-12-22 16:56:36,247 INFO 1294 [master] start with env: isProduction: true, EGG_SERVER_ENV: undefined, NODE_ENV: production
2019-12-22 16:56:36,539 INFO 1294 [master] agent_worker#1:1300 start with clusterPort:41105
2019-12-22 16:56:46,248 INFO 1300 Plugin development is disabled by env unmatched, require env(local) but got env is prod
trident warn: 框架模式启动时，不会加载默认配置
2019-12-22 16:56:46,944 INFO 1300 [egg:core] App root: /yisee/yisee-code
2019-12-22 16:56:46,944 INFO 1300 [egg:core] All *.log files save on "./logs"
2019-12-22 16:56:46,944 INFO 1300 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-session","version":"3.1.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-security","version":"2.5.0"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-onerror","version":"2.1.0"},{"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-i18n","version":"2.1.1"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-watcher","version":"3.1.0"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-schedule","version":"3.6.2"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":["schedule"],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-multipart","version":"2.5.0"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-logrotator","version":"3.1.0"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-static","version":"2.2.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/egg/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-view","version":"2.1.2"},{"enable":true,"package":"egg-view-vue-ssr","name":"vuessr","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/@zhuiyi/trident/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-view-vue-ssr","version":"3.3.0"},{"package":"egg-validate","enable":true,"name":"validate","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/@zhuiyi/trident/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-validate","version":"1.1.1"},{"enable":true,"package":"egg-redis","name":"redis","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/@zhuiyi/trident/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-redis","version":"2.3.2"},{"enable":true,"package":"egg-graphql","name":"graphql","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/@zhuiyi/trident/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-graphql","version":"2.4.0"},{"enable":true,"package":"egg-cors","name":"cors","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/node_modules/@zhuiyi/trident/config/plugin.js","path":"/yisee/yisee-code/node_modules/egg-cors","version":"2.2.3"},{"enable":true,"package":"@zhuiyi/god-eyes","name":"godeyes","dependencies":[],"optionalDependencies":[],"env":[],"from":"/yisee/yisee-code/config/plugin.js","path":"/yisee/yisee-code/node_modules/@zhuiyi/god-eyes","version":"0.8.7"}]
2019-12-22 16:56:51,443 ERROR 1294 nodejs.AgentWorkerDiedError: [master] agent_worker#1:1300 died (code: null, signal: SIGKILL)
    at Master.onAgentExit (/yisee/yisee-code/node_modules/egg-cluster/lib/master.js:341:17)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/yisee/yisee-code/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/yisee/yisee-code/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at ChildProcess.agentWorker.once (/yisee/yisee-code/node_modules/egg-cluster/lib/master.js:232:22)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
name: "AgentWorkerDiedError"
pid: 1294
hostname: see-web-deployment-6d9f4555f6-qcgvw

2019-12-22 16:56:51,444 ERROR 1294 [master] agent_worker#1:1300 start fail, exiting with code:1
2019-12-22 16:56:51,444 ERROR 1294 [master] exit with code:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yi-see@2.8.0 prod: `cross-env NODE_ENV=production node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yi-see@2.8.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/yibot/.npm/_logs/2019-12-22T08_56_51_741Z-debug.log

@atian25 同样遇到了AppWorkerDiedError，但是日志没有记录任何错误。
错误是在k8s上跑的，同样的容器，同样的代码，不走k8s直接走docker就不会有这问题，会是什么原因呢

**Comment by YUxiangLuo** [comment]
> 我把node_modules整个文件夹删掉了重新npm install 后就没问题了

it works...thank you

**Comment by rmlzy** [comment]
我遇到了同样的问题, 原因是 router 的指向写错了

路由配置:
```javascript
router.get("/quoter/release-demand.html", controller.viewCtrl.quoterReleaseDemand);
```

而控制器的名字是 `controller/viewCtr.js`

😅多了个 `l`, 后面的兄弟们注意检查下代码哈

**Comment by xuxia2013** [comment]
我也遇到这个问题 然而，taskkill -PID 【your pid 】-F 
正常运行了
