### ISSUE TITLE
egg-oss 删除文件的问题

### ISSUE THREAD

**Issue by honestxll** [eggjs/egg#2151]
* **Node Version**:  v8.9.4
* **Egg Version**: v2.2.1
* **Plugin Name**: egg-oss
* **Plugin Version**: 1.1.0

从 `egg-oss` 文档中找到了 `ali-oss`，连接查找资源都正常，删除的时候出现了如下错误: 
```javascript
{
"message":"Cannot read property 'replace' of undefined",
"stack":"TypeError: Cannot read property 'replace' of undefined at Client.proto._objectName (/Users/honest/Desktop/web/projects/appAdmin/node_modules/ali-oss/lib/object.js:528:15) at Client.proto._objectRequestParams (/Users/honest/Desktop/web/projects/appAdmin/node_modules/ali-oss/lib/object.js:511:15) at Client._delete [as delete] (/Users/honest/Desktop/web/projects/appAdmin/node_modules/ali-oss/lib/object.js:229:21) at _delete.next (<anonymous>) at onFulfilled (/Users/honest/Desktop/web/projects/appAdmin/node_modules/co/index.js:65:19) at /Users/honest/Desktop/web/projects/appAdmin/node_modules/co/index.js:54:5 at new Promise (<anonymous>) at Client.co (/Users/honest/Desktop/web/projects/appAdmin/node_modules/co/index.js:50:10) at Client.createPromise (/Users/honest/Desktop/web/projects/appAdmin/node_modules/co/index.js:30:15) at MediaService.remove (/Users/honest/Desktop/web/projects/appAdmin/app/service/media.js:47:45)",
"name":"TypeError",
"status":500
}
```

删除代码如下：
```javascript
// 删除资源
async remove(name) {
  const result = await this.ctx.oss.delete(name);
  this.ctx.body = result;
}
```

**Comment by honestxll** [comment]
非常抱歉，我自己的问题，在调用 `remove` 方法的时候，传 name 的时候把 name 丢掉了。
