### ISSUE TITLE
运行时会遇到这样的问题 无法启动

### ISSUE THREAD

**Issue by cswww** [eggjs/egg#2174]
2018-03-07 09:51:37,034 ERROR 6304 nodejs.AppWorkerDiedError: [master] app_worker#1:6320 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/home/csw/egg/egg-wechat/node_modules/egg-cluster/lib/master.js:387:21)
    at Master.emit (events.js:159:13)
    at Messenger.sendToMaster (/home/csw/egg/egg-wechat/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/home/csw/egg/egg-wechat/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/home/csw/egg/egg-wechat/node_modules/egg-cluster/lib/master.js:264:22)
    at EventEmitter.emit (events.js:164:20)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
name: 'AppWorkerDiedError'
pid: 6304
hostname: csw-desktop

2018-03-07 09:51:37,036 ERROR 6304 [master] app_worker#1:6320 start fail, exiting with code:1
2018-03-07 09:51:37,037 ERROR 6304 [master] exit with code:1
2018-03-07 09:51:37,046 ERROR 6310 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
⚠️  Error: /home/csw/egg/egg-wechat/node_modules/egg-bin/lib/start-cluster {"port":2222,"baseDir":"/home/csw/egg/egg-wechat","framework":"/home/csw/egg/egg-wechat/node_modules/egg","workers":1} exit with code 1
2018-03-07 09:51:37,059 ERROR 6310 [agent_worker] exit with code:110
⚠️  Command Error, enable `DEBUG=common-bin` for detail

**Comment by atian25** [comment]
日志不全。如果能提供最小可复现仓库更好

**Comment by yumeiqiang** [comment]
这种情况就是你哪个地方写错了，检查下自己的代码吧
