### ISSUE TITLE
mongoose 在生成覆盖率报告时尝试连接，导致无法 CI 通过

### ISSUE THREAD

**Issue by seekcx** [eggjs/egg#2207]
* **Node Version**:9.4.0
* **Egg Version**:2.4.1
* **Plugin Name**:egg-mongoose
* **Plugin Version**:2.20

在 Gitlab 中配置 CI
```yml
image: node:9.4.0

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - yarn
    - npm run ci

test:
  stage: test
  script:
    - yarn
    - npm test
```

运行起来后，发现在生成覆盖率报告时尝试连接了 mongodb 的服务器，导致无法通过。

```
$ yarn
yarn install v1.3.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 48.44s.
$ npm run ci

> seek-serve@1.0.0 ci /builds/seekcx/node-serve
> npm run lint && npm run cov


> seek-serve@1.0.0 lint /builds/seekcx/node-serve
> eslint .


> seek-serve@1.0.0 cov /builds/seekcx/node-serve
> egg-bin cov



2018-03-12 16:34:49,103 ERROR 113 [egg-mongoose] mongodb://localhost/seek disconnected
2018-03-12 16:34:49,111 ERROR 113 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/builds/seekcx/node-serve/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:160:13)
    at Connection.<anonymous> (/builds/seekcx/node-serve/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:255:19)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/builds/seekcx/node-serve/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]'
pid: 113
hostname: runner-e11ae361-project-5729214-concurrent-0

2018-03-12 16:34:58,764 WARN 113 [egg:core:ready_timeout] 10 seconds later /builds/seekcx/node-serve/node_modules/egg-mongoose/lib/mongoose.js:74:7 was still unable to finish.
  1) "before all" hook

  0 passing (1m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      [use `--full-trace` to display the full stack trace]

```

**Comment by thonatos** [comment]
## GitLab CI Services

- [Using Other Services](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#how-to-use-other-images-as-services)
- https://github.com/cnodejs/egg-cnode/blob/master/.travis.yml
- https://github.com/ImplementsIO/dockerizer/blob/master/.travis.yml
