### ISSUE TITLE
单元测试中，异常响应经过onerror处理之后任然打印在了终端

### ISSUE THREAD

**Issue by seekcx** [eggjs/egg#2262]
* **Node Version**: 8.9.0
* **Egg Version**:2.4.1
* **Platform**: osx
* **Showcase**:

在 config 中，配置了onerror统一处理全部异常：

```js
// config.default.js
exports.onerror = {
    json:  (err, ctx) => {
        ctx.body = {
            message: ctx.__(err.message.toLowerCase()),
        };
    
        // 还有其它更多的错误处理
        // ...
    }
}

// router.js 
router.get('/test/error', controller.test.error);

// controller/test.js
'use strict';

const Controller = require('egg').Controller;

class TestController extends Controller {
    error() {
        throw new Error('on error');
    }
}

module.exports = TestController;
```

在测试中：

```js
it('error', async () => {
    await app.httpRequest()
        .get('/test/error')
        .set('Accept', 'application/json')
        .expect(500);
});
```

运行这个测试时，直接在终端输出了这个错误。
```sh
npm test -- -- -g error

> seek-serve@1.0.0 test /Users/abel/Desktop/seek/node-serve
> npm run lint -- --fix && npm run test-local "--" "-g" "error"


> seek-serve@1.0.0 lint /Users/abel/Desktop/seek/node-serve
> eslint . "--fix"


> seek-serve@1.0.0 test-local /Users/abel/Desktop/seek/node-serve
> egg-bin test "-g" "error"



  test/app/controller/user.test.js
2018-03-23 23:53:59,294 ERROR 10455 [-/127.0.0.1/-/5ms GET /test/error] nodejs.Error: on error
    at TestController.error (/Users/abel/Desktop/seek/node-serve/app/controller/test.js:7:15)
    at Object.callFn (/Users/abel/Desktop/seek/node-serve/node_modules/egg-core/lib/utils/index.js:44:21)
// ...
```

测试时，异常信息被打印在了终端，截断了测试反馈结果。

**Comment by seekcx** [comment]
从新测试了一下，应该是 终端中输出的错误信息误导了我，实际上是经过了onerror处理的，但是终端中还是输出了这个错误信息，测试结果页不是太友好。

**Comment by popomore** [comment]
可以把 consoleLevel 关了

**Comment by popomore** [comment]
不过错误应该打出来，不然真遇到错了，会说不打出来体验真差。

**Comment by seekcx** [comment]
开发中还是打开，测试中关闭吧。

开始想在 config 中：
```js
consoleLevel: process.env.NODE_ENV === 'test' ? 'NONE' : 'DEBUG',
```

发现测试的配置走的不是这一套，翻了一下代码，找到了：
```js
const { app, mock } = require('egg-mock/bootstrap');

mock.consoleLevel('NONE');
```

解决了问题，谢谢 @popomore
