### ISSUE TITLE
cnode-api的例子中执行单元测试出现许多warn信息可以过滤掉吗？

### ISSUE THREAD

**Issue by ohblue** [eggjs/egg#2273]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

单元测试返回的结果返回了许多warn信息可以过滤掉吗？

```
❯ npm run test

> cnode-api@1.0.0 test /Users/chenm/projects/cnode-api
> npm run lint -- --fix && npm run test-local


> cnode-api@1.0.0 lint /Users/chenm/projects/cnode-api
> eslint . "--fix"


> cnode-api@1.0.0 test-local /Users/chenm/projects/cnode-api
> egg-bin test



  test/app/controller/topics.test.js
    ✓ should GET /api/v2/topics
2018-03-26 22:33:22,599 WARN 30330 [-/127.0.0.1/-/0ms GET /] nodejs.Error: client error
    at Context.<anonymous> (/Users/chenm/projects/cnode-api/test/app/controller/topics.test.js:29:17)
    at callFn (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runnable.js:378:21)
    at Test.Runnable.run (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runnable.js:370:7)
    at Test.Runnable.run (/Users/chenm/projects/cnode-api/node_modules/co-mocha/lib/co-mocha.js:42:16)
    at Runner.runTest (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:442:10)
    at /Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:560:12
    at next (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:356:14)
    at /Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:366:7
    at next (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:290:14)
    at Immediate._onImmediate (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
status: 400
pid: 30330
hostname: BendeMBP

    ✓ should GET /api/v2/topics error
2018-03-26 22:33:22,603 WARN 30330 [-/127.0.0.1/-/0ms GET /] nodejs.Error: not found error
    at Context.<anonymous> (/Users/chenm/projects/cnode-api/test/app/controller/topics.test.js:39:17)
    at callFn (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runnable.js:378:21)
    at Test.Runnable.run (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runnable.js:370:7)
    at Test.Runnable.run (/Users/chenm/projects/cnode-api/node_modules/co-mocha/lib/co-mocha.js:42:16)
    at Runner.runTest (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:442:10)
    at /Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:560:12
    at next (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:356:14)
    at /Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:366:7
    at next (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:290:14)
    at Immediate._onImmediate (/Users/chenm/projects/cnode-api/node_modules/egg-bin/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
status: 404
pid: 30330
hostname: BendeMBP

    ✓ should GET /api/v2/topics/:id 404
2018-03-26 22:33:22,633 WARN 30330 [-/127.0.0.1/-/0ms GET /] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (/Users/chenm/projects/cnode-api/node_modules/koa/lib/context.js:93:11)
    at Object.validate (/Users/chenm/projects/cnode-api/node_modules/egg-validate/app/extend/context.js:14:17)
    at TopicsController.create (/Users/chenm/projects/cnode-api/app/controller/topics.js:46:9)
    at Object.callFn (/Users/chenm/projects/cnode-api/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chenm/projects/cnode-api/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chenm/projects/cnode-api/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chenm/projects/cnode-api/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chenm/projects/cnode-api/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chenm/projects/cnode-api/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at /Users/chenm/projects/cnode-api/app/middleware/error_handler.js:6:13
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at i18n (/Users/chenm/projects/cnode-api/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at dta (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at xframe (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at xssProtection (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at nosniff (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/nosniff.js:7:11)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at noopen (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/noopen.js:8:11)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at notAllow (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/methodnoallow.js:20:12)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at csrf (/Users/chenm/projects/cnode-api/node_modules/egg-security/lib/middlewares/csrf.js:32:12)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at /Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at createGenerator (/Users/chenm/projects/cnode-api/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at onFulfilled (/Users/chenm/projects/cnode-api/node_modules/co/index.js:65:19)
    at /Users/chenm/projects/cnode-api/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/chenm/projects/cnode-api/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/chenm/projects/cnode-api/node_modules/co/index.js:118:63)
    at next (/Users/chenm/projects/cnode-api/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/chenm/projects/cnode-api/node_modules/co/index.js:69:7)
    at /Users/chenm/projects/cnode-api/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/chenm/projects/cnode-api/node_modules/co/index.js:50:10)
    at converted (/Users/chenm/projects/cnode-api/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at session (/Users/chenm/projects/cnode-api/node_modules/koa-session/index.js:41:13)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at overrideMethod (/Users/chenm/projects/cnode-api/node_modules/koa-override/index.js:38:12)
    at dispatch (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:42:32)
    at next (/Users/chenm/projects/cnode-api/node_modules/koa-compose/index.js:43:18)
    at bodyParser (/Users/chenm/projects/cnode-api/node_modules/koa-bodyparser/index.js:86:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
message: 'Validation Failed'
code: 'invalid_param'
errors: [ { message: 'required', field: 'title', code: 'missing_field' }, { message: 'required', field: 'content', code: 'missing_field' } ]
pid: 30330
hostname: BendeMBP

    ✓ should POST /api/v2/topics/ 422 (53ms)
    ✓ should POST /api/v2/topics/ 201
    ✓ should PUT /api/v2/topics/1 204

  test/app/service/topics.test.js
    show()
      ✓ should with render success
      ✓ should without render success
      ✓ should response 404 when topic id not exist
    list()
      ✓ should with render, limit and tab success
    create()
      ✓ should create failed by accesstoken error
      ✓ should create success
    update()
      ✓ should update failed by accesstoken error
      ✓ should update success


  14 passing (1s)
```

**Comment by popomore** [comment]
可以，把 consoleLevel 关掉，具体看日志文档
