### ISSUE TITLE
egg-socket.io error: The super constructor to "inherits" must not be null or undefined 什么原因？

### ISSUE THREAD

**Issue by DragWeb** [eggjs/egg#2284]
* **Node Version**: 8.9.3
    "egg": "^2.0.0",
    "egg-mongoose": "^2.1.1",
    "egg-redis": "^1.0.2",
    "egg-scripts": "^2.1.0",
    "egg-session-redis": "^1.0.0",
    "egg-socket.io": "^4.0.7",
    "jsonwebtoken": "^8.1.0",
    "koa-body": "^2.5.0",
    "moment": "^2.20.1",
    "node-uuid": "^1.4.8",
    "vm2": "^3.5.2"

egg-socket.io 在线上报错
```javascript
2018-03-28 17:30:+08:00: /data/online/open-api/node_modules/egg/lib/application.js:55
      throw e;
      ^

TypeError: [egg-core] load file: /data/online/open-api/node_modules/egg-socket.io/app.js, error: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:971:11)
    at Object.<anonymous> (/data/online/open-api/node_modules/redis/lib/customErrors.js:42:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/online/open-api/node_modules/redis/index.js:9:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
```

**Comment by ngot** [comment]
可复现的代码仓库提供下。
