### ISSUE TITLE
npm run test 失败了

### ISSUE THREAD

**Issue by Andyliwr** [eggjs/egg#2303]
代码里并没有涉及到ts，`npm test`的时候为啥会有这种错误呢
```
$ npm run test

> soft_paper@1.0.0 test C:\Users\lidikang\Documents\project\soft-paper
> npm run lint -- --fix && npm run test-local


> soft_paper@1.0.0 lint C:\Users\lidikang\Documents\project\soft-paper
> eslint . "--fix"


> soft_paper@1.0.0 test-local C:\Users\lidikang\Documents\project\soft-paper
> egg-bin test



  1) "before all" hook

  0 passing (1s)
  1 failing

  1) "before all" hook:
     AssertionError [ERR_ASSERTION]: `require.extensions` should contains `.ts` while
`options.typescript` was true
      at new FileLoader (node_modules\egg-core\lib\loader\file_loader.js:54:7)
      at new ContextLoader (node_modules\egg-core\lib\loader\context_loader.js:55:5)
      at AppWorkerLoader.loadToContext (node_modules\egg-core\lib\loader\egg_loader.js:377:5)
      at AppWorkerLoader.loadService (node_modules\egg-core\lib\loader\mixin\service.js:22:10)
      at AppWorkerLoader.load (node_modules\egg\lib\loader\app_worker_loader.js:35:10)      at new Application (node_modules\egg\lib\application.js:55:19)
      at new MeesengerApplication (node_modules\egg-mock\lib\app.js:237:7)
      at MockApplication.[init] (node_modules\egg-mock\lib\app.js:68:29)
      at EventEmitter.next (<anonymous>)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
      [use `--full-trace` to display the full stack trace]



⚠️  Error: C:\Users\lidikang\Documents\pr
oject\soft-paper\node_modules\egg-bin\node_modules\mocha\bin\_mocha --require=C:\Users\lidikang\Documents\project\soft-paper\node_modules\egg-bin\lib\mocha-clean.js,--require=C:\Users\lidikang\Documents\project\soft-paper\node_modules\co-mocha\lib\co-mocha.js,--require=C:\Users\lidikang\Documents\project\soft-paper\node_modules\intelli-espower-loader\intelli-espower-loader.js,--timeout=60000,--exit,test/app/controller/home.test.js exit with code 1
⚠️  Command Error, enable `DEBUG=common-b
in` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soft_paper@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soft_paper@1.0.0 test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be
found in:
npm ERR!     C:\Users\lidikang\AppData\Roaming\npm-cache\_logs\2018-03-30T10_40_27_737Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soft_paper@1.0.0 test: `npm run lint -- --fix && npm run test-local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soft_paper@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be
found in:
npm ERR!     C:\Users\lidikang\AppData\Roaming\npm-cache\_logs\2018-03-30T10_40_27_770Z-debug.log
```

**Comment by atian25** [comment]
贴下 package.json 或提供最小可复现仓库

**Comment by popomore** [comment]
是不是已经解决了

**Comment by atian25** [comment]
昨天修复那个是 cov 的。

**Comment by Andyliwr** [comment]
@atian25 package.json如下：
```
{
  "name": "soft_paper",
  "version": "1.0.0",
  "description": "软文编写",
  "private": true,
  "dependencies": {
    "egg": "^2.2.1",
    "egg-scripts": "^2.5.0",
    "egg-view-nunjucks": "^2.2.0",
    "gm": "^1.23.1",
    "moment": "^2.21.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.14.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-soft_paper",
    "stop": "egg-scripts stop --title=egg-server-soft_paper",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
  "ci": {
    "version": "8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "andyliwr",
  "license": "MIT"
}
```

**Comment by atian25** [comment]
@Andyliwr 

删除依赖重新安装下看看。

用 `egg-init --type=simple` 提供个最小可复现仓库？

**Comment by jinmincr** [comment]
我也遇到了类似的问题，egg-init --type=simple 初始化一个项目，执行npm run test，没有问题，但是我修改了下test内容，如下：
```
  it('should assert', function* () {
    // const pkg = require('../../../package.json');
    assert(app.config.keys.startsWith('test'));

    // const ctx = app.mockContext({});
    // yield ctx.service.xx();
  });
```

然后就报错了
```
Error: E:\gitserver\auth-node-server\node_modules\egg-bin\node_modules\mocha\bin\_mocha --declarations,--timeout=60000,--exit,--require=E:\gitserver\auth-node-server\node_
modules\egg-bin\lib\mocha-clean.js,--require=E:\gitserver\auth-node-server\node_modules\co-mocha\lib\co-mocha.js,--require=E:\gitserver\auth-node-server\node_modules\intelli-espower-loader\intelli-espower-loader.js,test/app/controller/home.test.js exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! auth-node-server@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the auth-node-server@1.0.0 test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hzjinmin\AppData\Roaming\npm-cache\_logs\2019-04-24T03_40_55_059Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! auth-node-server@1.0.0 test: `npm run lint -- --fix && npm run test-local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the auth-node-server@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by atian25** [comment]
@jinmincr 你这个跟主题不是一个问题。按提示加个 `DEBUG=common-bin` 启动看看具体报错呗。

另，提供最小可复现仓库。
