### ISSUE TITLE
应该是我环境问题，但我已经重新装了node，重启并重新install了。求助。。

### ISSUE THREAD

**Issue by tworry** [eggjs/egg#2311]
* **Node Version**:node version v8.11.1
* **Egg Version**:egg version 2.5.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我只是下载了example跑了一下assets-with-roadhog。
install是成功的，只是run dev的时候就会报这个。
查了一下好像是说没有路径或者spawn方法参数不对？
前几天win10更新把很多东西弄乱了，所以我又重新装了一下node
但就是启动不了。

日志：
> 2018-04-03 11:47:07,920 INFO 6220 [master] node version v8.11.1
2018-04-03 11:47:07,920 INFO 6220 [master] egg version 2.5.0
2018-04-03 11:47:08,748 INFO 6220 [master] agent_worker#1:4588 started (828ms)
2018-04-03 11:47:08,763 ERROR 4588 nodejs.ENOENTError: spawn roadhog ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn roadhog'
path: 'roadhog'
spawnargs: [ 'dev' ]
name: 'ENOENTError'
pid: 4588
hostname: PC-201612252354
2018-04-03 11:47:09,798 INFO 6220 [master] egg started on http://127.0.0.1:7001 (1878ms)
2018-04-03 11:48:10,299 ERROR 4588 [egg-view-assets] Run "roadhog dev" failed after 60s

**Comment by popomore** [comment]
有可能 win 没支持好

**Comment by atian25** [comment]
看起来是 roadhog 的报错，可以去那边报下 bug

**Comment by jakehu** [comment]
上Ubuntu 哈哈

**Comment by tworry** [comment]
刚刚把docker装上跑，不会报ENOENTError了，但是roadhog dev还是启动不了呢。确认过眼神，不是egg-view-assets的问题吗？

> 2018-04-03 08:41:32,841 INFO 28 [master] node version v8.11.1
2018-04-03 08:41:32,843 INFO 28 [master] egg version 2.5.0
2018-04-03 08:41:34,636 INFO 28 [master] agent_worker#1:34 started (1790ms)
2018-04-03 08:41:38,952 INFO 28 [master] egg started on http://127.0.0.1:7001 (6109ms)
2018-04-03 08:42:34,743 ERROR 34 [egg-view-assets] Run "roadhog dev" failed after 60s

**Comment by popomore** [comment]
可以把 debug 打开
