### ISSUE TITLE
茶叶蛋 test 错误

### ISSUE THREAD

**Issue by waitingsong** [eggjs/egg#2334]
* **Node Version**: 8.10.0
* **Egg Version**: 2.6.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: win7 64bit
* **Mini Showcase Repository**:

```
npx egg-init --type=ts showcase
cd showcase && npm i
npm run dev
```
以上代码没问题，执行 `npm run test` 出错:
```
$ npm run test

> showcase@1.0.0 test E:\project\tt\showcase
> npm run lint -- --fix && npm run test-local


> showcase@1.0.0 lint E:\project\tt\showcase
> tslint . "--fix"


> showcase@1.0.0 test-local E:\project\tt\showcase
> egg-bin test -r egg-ts-helper/register

[egg-ts-helper] E:\project\tt\showcase\typings\app\controller\index.d.ts created
[egg-ts-helper] E:\project\tt\showcase\typings\config\index.d.ts created
[egg-ts-helper] E:\project\tt\showcase\typings\app\service\index.d.ts created


  test/app/controller/home.test.ts
    √ should GET /

  test/app/service/Test.test.js
    √ sayHi


  2 passing (1s)

2018-04-07 17:49:29,173 ERROR 7976 nodejs.unhandledExceptionError: kill ENOSYS
    at _errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:13)
    at process.close (E:\project\tt\showcase\node_modules\egg-ts-helper\src\register.ts:20:10)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (E:\project\tt\showcase\node_modules\source-map-support\source-map-support.js:452:21)
    at process.emit (E:\project\tt\showcase\node_modules\espower-loader\node_modules\source-map-support\source-map-support.js:439:21)
    at process.exit (internal/process.js:157:15)
    at done (E:\project\tt\showcase\node_modules\egg-bin\node_modules\mocha\bin\_mocha:61:15)
    at afterWrite (_stream_writable.js:464:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOSYS'
errno: 'ENOSYS'
syscall: 'kill'
name: 'unhandledExceptionError'
pid: 7976


2018-04-07 17:49:29,173 ERROR 7976 nodejs.unhandledExceptionError: kill ENOSYS (uncaughtException throw 1 times on pid:7976)
    at _errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:13)
    at process.close (E:\project\tt\showcase\node_modules\egg-ts-helper\src\register.ts:20:10)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (E:\project\tt\showcase\node_modules\source-map-support\source-map-support.js:452:21)
    at process.emit (E:\project\tt\showcase\node_modules\espower-loader\node_modules\source-map-support\source-map-support.js:439:21)
    at process.exit (internal/process.js:157:15)
    at done (E:\project\tt\showcase\node_modules\egg-bin\node_modules\mocha\bin\_mocha:61:15)
    at afterWrite (_stream_writable.js:464:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOSYS'
errno: 'ENOSYS'
syscall: 'kill'
name: 'unhandledExceptionError'
pid: 7976




```

**Comment by waitingsong** [comment]
参照 https://github.com/atian25/blog/issues/27 过程执行

**Comment by whxaxes** [comment]
看来是 windows 上的错误，我看一下

**Comment by whxaxes** [comment]
升级一下 egg-ts-helper 到 1.5.2 再试试

**Comment by waitingsong** [comment]
@whxaxes  egg-ts-helper 到 1.5.2   问题解决了
