### ISSUE TITLE
官方multipart示例代码有问题，while后再也不出来

### ISSUE THREAD

**Issue by phper-chen** [eggjs/egg#2366]
* **Node**: 8.7
* **Egg**: 2.1
* **Plugin**: egg-multipart
* **Plugin**:  2.0.0
* **Platform**: macOS
* **Mini Showcase Repository**: none

依然是官方的多文件上传示例
1.我consume了流，我上传了三个php文件，信息都打印出来了
2.貌似是进入了while循环后再也不出来了，也就是说while外部后部分代码没有执行
3.看issue很多人都出现过这个问题
4.解锁了各种异步姿势依然如此
5.怀疑是状态挂起了，没有响应和终止
```
const sendToWormhole = require('stream-wormhole');
const Controller = require('egg').Controller;

module.exports = Class UploadController extends Controller {
  async upload() {
    const ctx = this.ctx;
    const parts = ctx.multipart();
    let part;
    while ((part = await parts()) != null) {
      if (part.length) {
        // arrays are busboy fields
        console.log('field: ' + part[0]);
        console.log('value: ' + part[1]);
        console.log('valueTruncated: ' + part[2]);
        console.log('fieldnameTruncated: ' + part[3]);
      } else {
        if (!part.filename) {
          // user click `upload` before choose a file,
          // `part` will be file stream, but `part.filename` is empty
          // must handler this, such as log error.
          return;
        }
        // otherwise, it's a stream
        console.log('field: ' + part.fieldname);  // 此处执行
        console.log('filename: ' + part.filename); // 此处执行
        console.log('encoding: ' + part.encoding); // 此处执行
        console.log('mime: ' + part.mime); // 此处执行
        await sendToWormhole(part); // 此处执行 我直接把流消费了 并不上传
      }
    }
    console.log('and we are done parsing the form!');  // 此处不执行
  }
};
```
只会打印这些信息，while外面的 "console.log('and we are done parsing the form!'); " 不打印
```
field: 0
filename: Conf.php
encoding: binary
mime: application/octet-stream
field: 1
filename: xx1.php
encoding: binary
mime: application/octet-stream
field: 2
filename: xx2.php
encoding: binary
mime: application/octet-stream
field: 3
filename: xx3.php
encoding: binary
mime: application/octet-stream

```
文件信息都会打印，但是等很久很久，最后会出现这些错误信息
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at Socket.socketOnEnd (_http_client.js:421:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

```

**Comment by phper-chen** [comment]
header
```
{ 
  accept: '*/*',
  'user-agent': 'Needle/2.2.0 (Node.js v8.7.0; darwin x64)',
  'content-type': 'multipart/form-data; boundary=--------------------NODENEEDLEHTTPCLIENT',
  'content-length': '12991',
  host: 'localhost:7001',
  connection: 'close' 
}

```

**Comment by popomore** [comment]
你是不是应该先把示例跑下，再换成 Needle

**Comment by phper-chen** [comment]
呃 我是服务端模拟前端做的图片流转发，也许demo不符合我的场景，或者说needle本身修改的header等等对不上multipart这边了

**Comment by popomore** [comment]
那你就要看服务器发送的是否符合接口标准。

**Comment by phper-chen** [comment]
我换了multiparty这个模块后就没问题了，也许egg-multipart只适合前端传输文件的接收

**Comment by atian25** [comment]
哪来什么前端层面后端层面传输文件，就是一个 HTTP 协议，跟是不是前后端一点关系都没有。

**Comment by phper-chen** [comment]
@atian25 呃 谢赐教  我是后端模拟多个文件流传输到别的服务器    不清楚    没精力看busboy源码了   虽然都是http协议，但属性值设置不同或者缺了什么，协议就对不上了

**Comment by phper-chen** [comment]
@popomore 嗯 谢谢

**Comment by atian25** [comment]
1. 全都升级为 egg 3，用最新的 multipart
2. 不熟悉的直接用 filemode，尽可能不用 stream
3. 要用 stream 的等 https://github.com/eggjs/egg-multipart/pull/57
