### ISSUE TITLE
egg-ant-design-pro 示例在windows下运行出错

### ISSUE THREAD

**Issue by denzw** [eggjs/egg#2384]
* **Node Version**: v8.10.0
* **Egg Version**: v2.6.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**:  Win10
* **Mini Showcase Repository**:

从官方版本库中同步的egg-ant-design-pro

错误信息
``` shell
PS D:\project\egg-ant-design-pro> npm run dev

> egg-ant-design-pro@1.0.0 dev D:\project\egg-ant-design-pro
> egg-bin dev

2018-04-13 16:40:43,175 INFO 23512 [master] node version v8.10.0
2018-04-13 16:40:43,181 INFO 23512 [master] egg version 2.6.0
2018-04-13 16:40:43,856 INFO 23512 [master] agent_worker#1:30116 started (670ms)
2018-04-13 16:40:43,881 ERROR 30116 nodejs.ENOENTError: spawn roadhog ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn roadhog'
path: 'roadhog'
spawnargs: [ 'dev' ]
name: 'ENOENTError'
pid: 30116
hostname: DESKTOP-GB7SOFU

2018-04-13 16:40:44,654 INFO 23512 [master] egg started on http://127.0.0.1:7001 (1470ms)
```

同时经测试 `examples\assets-with-roadhog`， `examples\assets-with-umi`等示例在windows下也出现类似的错误。

初步估计是与`egg-view-assets`设置子进程环境变量不对有关

**Comment by sansroman** [comment]
尝试用库cross_spawn代替egg-view-assets插件devServer中child_process对象的spawn可以解决问题

**Comment by popomore** [comment]
egg-view-assets has use cross-spawn instead of spawn, you can have a try.
