### ISSUE TITLE
egg-scripts启动和停止报错

### ISSUE THREAD

**Issue by llsldwy** [eggjs/egg#2385]
您好，我在部署生产环境的时候，启动项目egg-scripts start 出现了如下问题，手动删除 node_modules 之后，在执行 npm install，然后在执行egg-scripts start 就没问题，我想问问，这个应该什么原因导致的！

egg-scripts start --env=prod --workers=4 --daemon --title=XXXXX-permission-system-node

module.js:491
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/export/content/XXXXX-permission-system-node-20180413T1625/node_modules/.bin/egg-scripts:5:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! XXXXX-permission-system-node@1.0.0 server_prod: `egg-scripts start --env=prod --workers=4 --daemon --title=XXXXX-permission-system-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the XXXXX-permission-system-node@1.0.0 server_prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by atian25** [comment]
大概率是打包的问题，你们 zip 或 tar 的时候，多了一个参数，导致 `node_modules/.bin/egg-script` 软链变为硬链了。

**Comment by madongming3** [comment]
遇到类似的问题。
是因为node_modules挪动位置的原因。

**Comment by salamander-mh** [comment]
@atian25
我用jenkins发布代码到服务器上运行也是这个问题
```
Error: Cannot find module '..'
```
怎么解决好呢？？

**Comment by atian25** [comment]
仔细看上面的讨论

**Comment by LLEmily** [comment]
> 仔细看上面的讨论

老哥，这个问题咋解决啊， 上面只提到软链接变硬链接了

**Comment by atian25** [comment]
你让它不变为硬链接就好了，看你们的打包脚本的帮助文档，多了参数

**Comment by zhoujingang** [comment]
> @atian25 我用jenkins发布代码到服务器上运行也是这个问题
> 
> ```
> Error: Cannot find module '..'
> ```
> 
> 怎么解决好呢？？

我也有一样的情况，npm start 之前执行一下 npm rebuild
