### ISSUE TITLE
egg-logrotator 零点时发生日志切割错误

### ISSUE THREAD

**Issue by ZQun** [eggjs/egg#2405]
* **Node Version**: 8.9.3
* **Egg Version**: 2.4.0
* **Plugin Name**: egg-logrotator
* **Plugin Version**: 3.0.2

egg-logrotator 零点时发生日志切割错误

```
2018-04-15 23:59:57,311 ERROR 70441 nodejs.Error: [egg-logrotator] rename /Users/Qun/Project/tongxunlu/logs/common-error.log, found exception: targetFile /Users/Qun/Project/tongxunlu/logs/common-error.log.2018-04-14 exists!!!
    at renameOrDelete (/Users/Qun/Project/tongxunlu/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
    at <anonymous>

pid: 70441
hostname: Qun-2.local

2018-04-15 23:59:57,312 ERROR 70441 nodejs.Error: [egg-logrotator] rename /Users/Qun/Project/tongxunlu/logs/xcxVideoProject-web.log, found exception: targetFile /Users/Qun/Project/tongxunlu/logs/xcxVideoProject-web.log.2018-04-14 exists!!!
    at renameOrDelete (/Users/Qun/Project/tongxunlu/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
    at <anonymous>

pid: 70441
hostname: Qun-2.local

2018-04-15 23:59:57,312 ERROR 70441 nodejs.Error: [egg-logrotator] rename /Users/Qun/Project/tongxunlu/logs/egg-web.log, found exception: targetFile /Users/Qun/Project/tongxunlu/logs/egg-web.log.2018-04-14 exists!!!
    at renameOrDelete (/Users/Qun/Project/tongxunlu/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
    at <anonymous>

pid: 70441
hostname: Qun-2.local

2018-04-15 23:59:57,313 ERROR 70441 nodejs.Error: [egg-logrotator] rename /Users/Qun/Project/tongxunlu/logs/xcxVideoProject/egg-schedule.log, found exception: targetFile /Users/Qun/Project/tongxunlu/logs/xcxVideoProject/egg-schedule.log.2018-04-14 exists!!!
    at renameOrDelete (/Users/Qun/Project/tongxunlu/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
    at <anonymous>

pid: 70441
hostname: Qun-2.local

2018-04-15 23:59:57,313 ERROR 70441 nodejs.Error: [egg-logrotator] rename /Users/Qun/Project/tongxunlu/logs/egg-agent.log, found exception: targetFile /Users/Qun/Project/tongxunlu/logs/egg-agent.log.2018-04-14 exists!!!
    at renameOrDelete (/Users/Qun/Project/tongxunlu/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
    at <anonymous>

pid: 70441
hostname: Qun-2.local
```

**Comment by duncup** [comment]
翻了翻源码，似乎日志时间比日志切割的时间早了三秒？按源码内的配置，应该是零时整执行才对。

**Comment by duncup** [comment]
有没有最小重现呢？

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/1616

**Comment by popomore** [comment]
Is You application deployed on local?

**Comment by ZQun** [comment]
是本地的开发环境    @popomore

**Comment by popomore** [comment]
Feal free to open this issue If you have issue on production. We don’t have a solution about the timer of nodejs.

**Comment by tong3jie** [comment]
出现同样问题。
