### ISSUE TITLE
Starting inspector on 127.0.0.1:5800 failed: permission denied

### ISSUE THREAD

**Issue by zuosc** [eggjs/egg#2432]
* **Node Version**:v8.9.4
* **Egg Version**:2.7.1
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**:windows10 15063
* **Mini Showcase Repository**:

I use vscode-eggjs plugin debug。

this is setting:

```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [      
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Debug",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug",
                "--",
                "--inspect-brk"
            ],
            "console": "integratedTerminal",
            "restart": true,
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Test",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "test-local",
                "--",
                "--inspect-brk"
            ],
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Egg Attach to remote",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/usr/src/app",
            "address": "localhost",
            "protocol": "auto",
            "port": 9999
        }
    ]
}
```

but there was an error:
```
PS D:\Code\xxx\xxx\xxx.console> cd 'd:\Code\xxx\xxx\xxx.console'; & 'C:\Program Files\nodejs\npm.cmd' 'run' 'debug' '--' '--inspect-brk'

> xxx.console@1.0.0 debug D:\Code\xxx\xxx\xxx.console
> egg-bin debug "--inspect-brk"

Debugger listening on ws://127.0.0.1:9229/01dea4e0-697a-4369-aadc-97ee5777fa9b
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
2018-04-19 10:30:25,590 INFO 12556 [master] node version v8.9.4
2018-04-19 10:30:25,592 INFO 12556 [master] egg version 2.7.1
Starting inspector on 127.0.0.1:5800 failed: permission denied
2018-04-19 10:30:25,847 ERROR 12556 nodejs.AgentWorkerDiedError: [master] agent_worker#1:5948 died (code: 12, signal: null)
    at Master.onAgentExit (D:\Code\xxx\xxx\xxx.console\node_modules\egg-cluster\lib\master.js:317:17)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (D:\Code\xxx\xxx\xxx.console\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (D:\Code\xxx\xxx\xxx.console\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at ChildProcess.agentWorker.once (D:\Code\xxx\xxx\xxx.console\node_modules\egg-cluster\lib\master.js:216:22)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
name: 'AgentWorkerDiedError'
pid: 12556
hostname: xxxxxxxx

2018-04-19 10:30:25,848 ERROR 12556 [master] agent_worker#1:5948 start fail, exiting with code:1
2018-04-19 10:30:25,850 ERROR 12556 [master] exit with code:1
Waiting for the debugger to disconnect...
PS D:\Code\xxx\xxx\xxx.console>
```
And wait for a while, this prompt box will pop up
![xxx.jpg](https://i.loli.net/2018/04/19/5ad80160f2f01.jpg)

Then I use administrator privileges to start vscode，Still the same mistake~

**Comment by atian25** [comment]
`Starting inspector on 127.0.0.1:5800 failed: permission denied`

os permission problem, we can't help.

**Comment by zuosc** [comment]
@atian25  But  I use administrator start vscode, still  the same mistake

**Comment by atian25** [comment]
god know, windows is not friendly to developer, you told it to use `admin` but who known

**Comment by zuosc** [comment]
的确是， 我的5800端口被VNC占用了。 5800和5900默认被VNC占用。

你们或许可以考虑换一个端口，装VNC还是蛮常见的。



然后又出现了这个错误，[![无标题.png](https://i.loli.net/2018/04/19/5ad8062c89408.png)](https://i.loli.net/2018/04/19/5ad8062c89408.png)

**Comment by ewinchen** [comment]
我也遇到这个端口冲突的问题，debug方式启动不了。

不过我找到一个可行的方案，就是用docker来开发，在docker里面跑，然后把9999端口映射出来就好了。

https://github.com/ewinchen/awesome-egg

不太了解为什么会用5800这个端口，如果能自定义就不用折腾了。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/pull/70

**Comment by atian25** [comment]
landed

**Comment by wzgy** [comment]
Firstly, check if the port is in used by command "netstat -ano | findstr [port]".
The last column is the pid of the process, just close it.

首先，用命令"netstat -ano | findstr [端口号]"检查端口是否被占用。
最后一列是进程pid，关掉就好。

Secondly, check if the port is in the excludedportrange by command "netsh int ipv4 show excludedportrange protocol=tcp".
Then check the dynamicport range by command "netsh int ipv4 show dynamicport tcp".
Set the start of dynamicport by command "netsh int ipv4 set dynamicport tcp start=49152 num=16384"

其次，用命令"netsh int ipv4 show excludedportrange protocol=tcp"检查是否在被排除的端口范围内。
然后用命令"netsh int ipv4 show dynamicport tcp"检查动态端口范围。
用命令"netsh int ipv4 set dynamicport tcp start=49152 num=16384"设置起始动态端口。
