### ISSUE TITLE
egg-ts 使用 assert 断言报错

### ISSUE THREAD

**Issue by arvinxx** [eggjs/egg#2480]
* **Node Version**:8.11
* **Egg Version**:2.6
* **Platform**:windows
* **Mini Showcase Repository**:

![default](https://user-images.githubusercontent.com/28616219/39406484-f4878d2c-4be9-11e8-8687-7fc10d5df802.png)

Controller
```js
import { Controller } from 'egg';
import { bp } from 'egg-blueprint';

export default class UserController extends Controller {
  @bp.get('/api/currentUser')
  public async user() {
    const { ctx } = this;
    ctx.body = { code: 1 };
  }
}
```

Test
```js
import * as assert from 'assert';
import { app } from 'egg-mock/bootstrap';
describe('test/app/controller/home.test.ts', () => {
  it('should GET /api/currentUser', async () => {
    const res = await app
      .httpRequest()
      .get('/api/currentUser')
      .expect(200)
      .expect({ code: 1 });
    assert(res.body === { code: 1 });
  });
}
```

报错信息:

```bash
1) test/app/controller/home.test.ts
       should GET /api/currentUser:

      AssertionError [ERR_ASSERTION]:   # user.test.ts:11
  
  assert(res.body === { code: 1 })
         |   |    |   |           
         |   |    |   Object{code:1}
         |   |    false           
         |   Object{code:1}       
         Response{domain:null,_events:#Object#,_eventsCount:0,_maxListeners:undefined,res:#IncomingMessage#,request:#EggTest#,req:#ClientRequest#,text:"{\"code\":1}",body:#Object#,files:undefined,buffered:true,headers:#Object#,header:#Object#,statusCode:200,status:200,statusType:2,info:false,ok:true,redirect:false,clientError:false,serverError:false,error:false,accepted:false,noContent:false,badRequest:false,unauthorized:false,notAcceptable:false,forbidden:false,notFound:false,type:"application/json",charset:"utf-8",links:#Object#,setEncoding:#function#,redirects:#Array#}
  
  [Object] { code: 1 }
  => Object{code:1}
  [Object] res.body
  => Object{code:1}
  
      + expected - actual

      -false
      +true
      
      at Context.it (test\app\controller\user.test.ts:33:9)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
      [use `--full-trace` to display the full stack trace]
```

去掉 assert 后测试通过。
![default](https://user-images.githubusercontent.com/28616219/39406541-904f574e-4bea-11e8-8411-d643e96f2353.png)

**Comment by atian25** [comment]
maybe you need to learn JavaScript again.

you can't use `===` as `object compare`, use `assert.deepEquals` instead

**Comment by arvinxx** [comment]
Thanks a lot.
