### ISSUE TITLE
egg-sequelize: migrate tool is unable to read config from typescript project

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#2499]
* **Node Version**: 8.9.0
* **Egg Version**: 2.8.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.4
* **Platform**: Windows 10 1803
* **Mini Showcase Repository**:

After I migrate my egg project to typescript, I run ``egg-sequelize db:migrate`` to do database migration but it seems that my database config isn't parse correctly and I get these message
```
Loaded configuration file "node_modules\egg-sequelize\lib\database.js".
Using environment "test".
Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (node_modules\sequelize\lib\sequelize.js:181:13)
    at getSequelizeInstance (node_modules\sequelize-cli\lib\tasks\db.js:394:12)
    at getMigrator (node_modules\sequelize-cli\lib\tasks\db.js:403:21)
    at Object.task (node_modules\sequelize-cli\lib\tasks\db.js:23:14)
    at node_modules\sequelize-cli\lib\helpers\gulp-helper.js:17:23
    at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
'db:migrate' errored after 11 ms
```

And i read the source code of ``egg-sequelize`` and found that it doesn't read config.[env].ts or config.[env].js(compiled by tsc into es module)

**Comment by THaGKI9** [comment]
two suggestion:
1. add ts support to egg-sequelize
2. add es module loader to egg-sequelize

**Comment by popomore** [comment]
You should run tsc first before migration.

**Comment by THaGKI9** [comment]
@popomore I did run tsc. Error is still occurred.

```
// config.default.ts
export default {
  sequelize: {}
}
```

compiled into 
```
// config.default.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {}
```

in ``egg-sequelize``, it use ``require`` to import config file, so fail~

**Comment by aprilandjan** [comment]
@THaGKI9 You are right. In order to match `egg-sequelize`,  config export need to be like this: 

```javascript
// config.default.ts
export = () => {
  return {
     sequelize: {
        //...
    }
  }
}
```

**Comment by THaGKI9** [comment]
@aprilandjan Nice solution! thank you.

But it's a little bit hacky and I think a file loader is needed to fix this.
