### ISSUE TITLE
egg-bin dev 报错如何解决

### ISSUE THREAD

**Issue by Chryseis** [eggjs/egg#2604]
```
2018-05-28 13:08:09,032 INFO 1573 [master] node version v9.8.0
2018-05-28 13:08:09,034 INFO 1573 [master] egg version 2.8.1
2018-05-28 13:08:09,447 INFO 1573 [master] agent_worker#1:1574 started (411ms)
/Users/chrys/Projects/yylc-official-website/node_modules/egg/lib/application.js:69
      throw e;
      ^

TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
    at Function.defineProperty (<anonymous>)
    at AppWorkerLoader.loadExtend (/Users/chrys/Projects/yylc-official-website/node_modules/egg-core/lib/loader/mixin/extend.js:144:16)
    at AppWorkerLoader.loadContextExtend (/Users/chrys/Projects/yylc-official-website/node_modules/egg-core/lib/loader/mixin/extend.js:58:10)
    at AppWorkerLoader.load (/Users/chrys
/Projects/yylc-official-website/node_modules/egg/lib/loader/app_worker_loader.js:29:10)
    at new Application (/Users/chrys/Projects/yylc-official-website/node_modules/egg/lib/application.js:65:19)
    at Object.<anonymous> (/Users/chrys/Projects/yylc-official-website/node_modules/egg-cluster/lib/app_worker.js:13:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
[2018-05-28 13:08:09.902] [cfork:master:1573] worker:1575 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-05-28 13:08:09.902] [cfork:master:1573] don't fork, because worker:1575 will be kill soon
2018-05-28 13:08:09,903 INFO 1573 [master] app_worker#1:1575 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-05-28 13:08:09.903] [cfork:master:1573] worker:1575 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-05-28 13:08:09,904 ERROR 1573 nodejs.AppWorkerDiedError: [master] app_worker#1:1575 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/chrys/Projects/yylc-official-website/node_modules/egg-cluster/lib/master.js:389:21)
    at Master.emit (events.js:180:13)
    at Messenger.sendToMaster (/Users/chrys/Projects/yylc-official-website/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/chrys/Projects/yylc-official-website/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/Users/chrys/Projects/yylc-official-website/node_modules/egg-cluster/lib/master.js:266:22)
    at EventEmitter.emit (events.js:185:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:191:13)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
name: 'AppWorkerDiedError'
pid: 1573
hostname: ChrysFengdeMacBook-Pro.local
```

**Comment by popomore** [comment]
Check app/extend/context.js first.

**Comment by TimuJiang** [comment]
有一样的问题
extend/context.js 

module.exports = app => {} 报类似的错
module.exports ={} 不报错

**Comment by atian25** [comment]
因为不支持这种语法
