### ISSUE TITLE
egg router 支持多层路由吗

### ISSUE THREAD

**Issue by clancytom** [eggjs/egg#2606]
* **Node Version**:  v8.9.2
* **Egg Version**: 2.8.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

> code 

```js
import { Application } from 'egg';
const Router = require('koa-router');

export default (app: Application) => {
    const {  controller, router, config  } = app;
    const webroot = config.webroot;
    const extRouter = new Router();

    extRouter.post(`/builder/:tenantID/:projectID/gadget`,
        controller.gadget.addGadget);
    router.use(`/${webroot}`, extRouter.routes(), extRouter.allowedMethods());
    app.use(router.routes()).use(router.allowedMethods());
}
```

> error message
```js
2018-05-28 19:59:54,638 ERROR 9700 [-/::1/-/19ms POST /uee/u-route/ui-builder/t/p/flow/page?source=s] nodejs.TypeError: Cannot read property 'app' of undefined
    at new BaseContextClass (G:\code\egg-study\dev-server\node_modules\egg-core\lib\utils\base_context_class.js:25:20)
    at new BaseContextClass (G:\code\egg-study\dev-server\node_modules\egg\lib\core\base_context_class.js:13:1)
    at new FlowController (G:\code\egg-study\dev-server\app\controller\flow.ts:10:1)
    at classControllerMiddleware (G:\code\egg-study\dev-server\node_modules\egg-core\lib\loader\mixin\controller.js:80:26)
    at dispatch (G:\code\egg-study\dev-server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (G:\code\egg-study\dev-server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at G:\code\egg-study\dev-server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (G:\code\egg-study\dev-server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at G:\code\egg-study\dev-server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (G:\code\egg-study\dev-server\node_modules\koa-router\lib\router.js:351:31)
```

**Comment by clancytom** [comment]
我的子路由 可能很多，我想分层，当前egg 框架下，代码如何写

**Comment by atzcl** [comment]
[egg-router-plus](https://github.com/eggjs/egg-router-plus)

**Comment by atian25** [comment]
that's what `koa-router` did,  if you care about the performance, you could choose or write your own router
