### ISSUE TITLE
app-worker异常退出

### ISSUE THREAD

**Issue by WuStardust** [eggjs/egg#2620]
* **Node Version**: v8.7.0
* **Egg Version**: v1.7.0
* **pm2 Version**: v2.7.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: CentOS
* **Mini Showcase Repository**:

服务器最近增加了阿里云的心跳健康检查的接口，上线一段时间之后就会出现app-worker退出的现象。不太确定是否是心跳检查造成的。错误具体如下：

**启动脚本**
`pm2 start ./server.js --name=server`

**运行环境**
查看`./run/application_config.json`发现`env=local`

**心跳检查的代码**
``` node.js
    * health() {
      this.ctx.body = {
        code: 0
      };
      return ;
    }
```

**errolog**
截图：
![image](https://user-images.githubusercontent.com/30644603/40757135-a1a8563e-64b9-11e8-9d88-a14af5d7043e.png)
文本：
```
Wed, 30 May 2018 06:41:22 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:237:13
[Wed May 30 2018 15:15:12 GMT+0800 (CST)] [cfork:master:1486] worker:1522 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false)
[Wed May 30 2018 15:15:12 GMT+0800 (CST)] [cfork:master:1486] don't fork new work (refork: false)
[Wed May 30 2018 15:15:12 GMT+0800 (CST)] [cfork:master:1486] (total 0 disconnect, 1 unexpected exit) WorkerDiedUnexpectedError: worker:1522 died unexpected (code: null, signal: SIGKILL, exitedAfterDisconnect: false, state: dead)
    at EventEmitter.onUnexpected (/admin/merchantserver/node_modules/cfork/index.js:210:15)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at EventEmitter.<anonymous> (/admin/merchantserver/node_modules/cfork/index.js:130:13)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
2018-05-30 15:15:12,965 ERROR 1486 nodejs.AppWorkerDiedError: [master] app_worker#1:1522 died (code: null, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/admin/merchantserver/node_modules/egg-cluster/lib/master.js:333:19)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (/admin/merchantserver/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/admin/merchantserver/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/admin/merchantserver/node_modules/egg-cluster/lib/master.js:230:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
pid: 1486
hostname: device2-wechat-pay

Wed, 30 May 2018 07:17:43 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:237:13
```

**Comment by atian25** [comment]
是否心跳这个不确定。

但 `env=local` 肯定是不正常的，我们是推荐直接用 egg-scripts 启动的，如果你用 PM2 的话，需自行看下 egg-scripts 源码，做对应的环境变量等处理

**Comment by WuStardust** [comment]
谢谢，这个问题我意识到了，准备下次上线的时候改用prod环境。
没理解错的话如果worker异常退出应该会重启的吧？但是没有重启可能是什么原因呢？
最后还是可以帮忙看看从errorlog中能否确定问题的原因吗？如果问题确定不了还是不敢上线。
有一个疑问就是心跳接口中的`return`是否必要？会不会导致什么异常？
非常感谢！

**Comment by atian25** [comment]
local 是本地开发环境，为了尽早暴露问题，故意的遇到异常不会自动重启。

**Comment by WuStardust** [comment]
原来如此，受教了。那看来改成prod环境应该可以避免服务长时间挂掉对吧？
不过感觉这就是治标不治本了。。。

**Comment by atian25** [comment]
根本原因还是要查下为啥会异常退出。
从你给的日志看不出问题，要看下 error 日志。

**Comment by WuStardust** [comment]
您有什么建议或者说可能的猜想吗？比如出现上述日志的一般可能情形是啥，还是说这段日志其实是正常现象？
服务器只增加了心跳检查的接口，频率约是1次/2s
error日志里是空的，发生异常退出的时候也没有其他的接口访问，目前可以找到的可能和异常退出相关的只有上述的那一段日志了
感觉有点抓不到，还请大佬帮忙诊断，谢谢~

**Comment by atian25** [comment]
看下 common-error 日志，在  home 目录下的，不是项目目录。

**Comment by atian25** [comment]
1. 确认下日志是否真的配置对
2. 提供完整的控制台日志
3. 提供最小可复现仓库，现在给出的信息无法判断。
