### ISSUE TITLE
Property 'session' does not exist on type 'Context'

### ISSUE THREAD

**Issue by superlbr** [eggjs/egg#2644]
* **Node Version**: 9.11.1 or 10.0.3
* **Egg Version**: 2.8.4 or 2.9.1
* **Platform**: MacOs 10.13.5 (17F77)

1. use https://github.com/eggjs/examples/blob/master/hackernews-async-ts
2. add ctx.session = null in whatever a controller function
3. run dev and then error

```
/private/tmp/examples/hackernews-async-ts/node_modules/_ts-node@5.0.1@ts-node/src/index.ts:327
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: [egg-core] load file: /private/tmp/examples/hackernews-async-ts/app/controller/news.ts, error: ⨯ Unable to compile TypeScript
app/controller/news.ts (27,9): Property 'session' does not exist on type 'Context'. (2339)
    at getOutput (/private/tmp/examples/hackernews-async-ts/node_modules/_ts-node@5.0.1@ts-node/src/index.ts:327:15)
    at Object.compile (/private/tmp/examples/hackernews-async-ts/node_modules/_ts-node@5.0.1@ts-node/src/index.ts:513:11)
    at Module.m._compile (/private/tmp/examples/hackernews-async-ts/node_modules/_ts-node@5.0.1@ts-node/src/index.ts:400:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/examples/hackernews-async-ts/node_modules/_ts-node@5.0.1@ts-node/src/index.ts:403:12)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

I doubt it's something happened in MacOs 10.13.5

**Comment by whxaxes** [comment]
Because the new version of koa has removed `[key: string]: any` from `koa.Context`, I would create a pr to fix this later.

Now you can add `[key: string]: any` to `typings/index.d.ts` like this: 

```ts
// typings/index.d.ts

declare module 'egg' {
  interface Context {
    [key: string]: any;
  }
}
```

**Comment by whxaxes** [comment]
PR has merged, So I closed this.
