### ISSUE TITLE
多进程研发模式增强 问题

### ISSUE THREAD

**Issue by yangchongduo** [eggjs/egg#2669]
```
2018-06-10 07:39:58,730 WARN 10006 nodejs.ResponseTimeoutError: register to channel: RegistryClient failed, will retry after 3s, Server no response in 60000ms, address#127.0.0.1:49951
    at Timeout._invokes.set.timer.setTimeout [as _onTimeout] (/Users/qitmac000068/Documents/examples2/static/node_modules/tcp-base/lib/base.js:225:21)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
socketMeta: { id: 37, dataLength: 82, bufferSize1: 0, bufferSize2: 0, startTime: 1528587538727, endTime: 1528587538728, writeSuccess: true }
name: 'Respo

```

**Comment by fengmk2** [comment]
https://github.com/node-modules/cluster-client/pull/43
