### ISSUE TITLE
egg启动出错

### ISSUE THREAD

**Issue by 8-shen** [eggjs/egg#2682]
npm run dev可以正常启动并访问
egg-scripts start --daemon启动出错

日志如下:
vim /root/logs/master-stderr.log

2018-06-12 17:12:38,681 ERROR 29453 [app_worker] exit with code:1
2018-06-12 17:12:38,694 ERROR 29431 nodejs.AppWorkerDiedError: [master] app_worker#1:29453 died (code: 1, signal: null, suicide:
false, state: dead), current workers: []
    at Master.onAppExit (/opt/egg-nuxt-demo/node_modules/egg-cluster/lib/master.js:384:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/opt/egg-nuxt-demo/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/opt/egg-nuxt-demo/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/opt/egg-nuxt-demo/node_modules/egg-cluster/lib/master.js:263:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 29431
hostname: izj6c801p3wpc7xm3sb55nz

2018-06-12 17:12:38,695 ERROR 29431 [master] app_worker#1:29453 start fail, exiting with code:1
2018-06-12 17:12:38,695 ERROR 29431 [master] exit with code:1
2018-06-12 17:12:38,702 ERROR 29441 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-06-12 17:12:38,702 ERROR 29441 [agent_worker] exit with code:110

**Comment by atian25** [comment]
please provide `common-error.log`

**Comment by 8-shen** [comment]
/root/kigs/egg-nuxt-demo/common-error.log is empty

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by 8-shen** [comment]
感谢回复\(^o^)/~
### demo地址:
   https://github.com/doubi-NO1/egg-nuxt-demo
### 依赖插件地址:
   https://github.com/doubi-NO1/egg-nuxt

**Comment by atian25** [comment]
```js
[nuxt] Building error TypeError: Cannot read property 'build' of undefined
    at app.beforeStart (/Users/tz/Workspaces/tmp/egg-nuxt-demo/node_modules/_egg-nuxt-lib@1.1.13@egg-nuxt-lib/app.js:8:27)
    at Object.callFn (/Users/tz/Workspaces/tmp/egg-nuxt-demo/node_modules/_egg-core@4.8.0@egg-core/lib/utils/index.js:36:42)
    at process.nextTick (/Users/tz/Workspaces/tmp/egg-nuxt-demo/node_modules/_egg-core@4.8.0@egg-core/lib/egg.js:226:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

你的插件报错了

**Comment by 8-shen** [comment]
sorry,有个判断写错了，感谢你的回复

**Comment by atian25** [comment]
cc @popomore  daemon 下，错误日志确实没了

**Comment by popomore** [comment]
可能退出了还没 flush 吧

**Comment by atian25** [comment]
能否强制下

**Comment by popomore** [comment]
这里是强制退出没有等吧

**Comment by atian25** [comment]
看到有等了 1s

https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L227
