### ISSUE TITLE
npm start error in bind EADDRINUSE null:port

### ISSUE THREAD

**Issue by Penggggg** [eggjs/egg#2693]
* **Node Version**: v8.11.1
* **Egg Version**: b2.8.1
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: MacOS 10.13.3 (17D47)
* **Mini Showcase Repository**:

> package.json

```
"scripts": {
    "start": "egg-scripts start --daemon --ignore-stderr",
}
```

> error

when I run "npm start", there is an error as follow 

```
> egg-scripts start --port=3000 --daemon --ignore-stderr

[egg-scripts] Starting egg application at /Users/hezhuopeng/Desktop/cvte-like-mobile
[egg-scripts] Run node --require /Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/source-map-support/register.js /Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg-scripts/lib/start-cluster {"port":3000,"title":"egg-server-cvte-like-mobile","framework":"/Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg","baseDir":"/Users/hezhuopeng/Desktop/cvte-like-mobile"} --title=egg-server-cvte-like-mobile
[egg-scripts] Save log file to /Users/hezhuopeng/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Got error when startup:
[egg-scripts] 2018-06-14 10:10:38,690 ERROR 93210 [app_worker] server got error: bind EADDRINUSE null:3000, code: EADDRINUSE
[egg-scripts] 2018-06-14 10:10:38,690 ERROR 93208 [app_worker] server got error: bind EADDRINUSE null:3000, code: EADDRINUSE
[egg-scripts] 2018-06-14 10:10:38,691 ERROR 93210 [app_worker] exit with code:1
[egg-scripts] 2018-06-14 10:10:38,691 ERROR 93208 [app_worker] exit with code:1
[egg-scripts] 2018-06-14 10:10:38,710 ERROR 93205 nodejs.AppWorkerDiedError: [master] app_worker#3:93210 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1","2","4"]
[egg-scripts]     at Master.onAppExit (/Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg-cluster/lib/master.js:389:21)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Master.emit (events.js:211:7)
[egg-scripts]     at Messenger.sendToMaster (/Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
[egg-scripts]     at Messenger.send (/Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
[egg-scripts]     at EventEmitter.cluster.on (/Users/hezhuopeng/Desktop/cvte-like-mobile/node_modules/egg-cluster/lib/master.js:266:22)
[egg-scripts]     at emitThree (events.js:141:20)
[egg-scripts]     at EventEmitter.emit (events.js:217:7)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:186:13)
[egg-scripts]     at Object.onceWrapper (events.js:317:30)
[egg-scripts] name: 'AppWorkerDiedError'
[egg-scripts] pid: 93205
[egg-scripts] hostname: hezhuopengdeMacBook-Pro.local
[egg-scripts]
[egg-scripts] 2018-06-14 10:10:38,711 ERROR 93205 [master] app_worker#3:93210 start fail, exiting with code:1
[egg-scripts] 2018-06-14 10:10:38,711 ERROR 93205 [master] exit with code:1
[egg-scripts] 2018-06-14 10:10:38,718 ERROR 93206 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2018-06-14 10:10:38,722 ERROR 93206 [agent_worker] exit with code:110
[egg-scripts] 2018-06-14 10:10:38,729 ERROR 93211 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2018-06-14 10:10:38,730 ERROR 93209 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts]
[egg-scripts] Start got error, see /Users/hezhuopeng/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
```

**Comment by atian25** [comment]
EADDRINUSE = Error Address in use
