### ISSUE TITLE
运行npm run dev命令后报错

### ISSUE THREAD

**Issue by assmdx** [eggjs/egg#2704]
代码地址：https://github.com/assmdx/WaterExquisite_server
```2018-06-18 15:59:43,753 ERROR 40356 nodejs.AppWorkerDiedError: [master] app_worker#1:42660 died (code: 1, signal: null, suicide: false, sta
te: dead), current workers: []
    at Master.onAppExit (E:\WaterExquisite_server\node_modules\egg-cluster\lib\master.js:391:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (E:\WaterExquisite_server\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (E:\WaterExquisite_server\node_modules\egg-cluster\lib\utils\messenger.js:87:12)

    at EventEmitter.cluster.on (E:\WaterExquisite_server\node_modules\egg-cluster\lib\master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 40356
hostname: USER-2HIDLMTKUJ

2018-06-18 15:59:43,755 ERROR 40356 [master] app_worker#1:42660 start fail, exiting with code:1
2018-06-18 15:59:43,757 ERROR 40356 [master] exit with code:1
⚠  Error: E:\WaterExquisite_server\node_modules\egg-bin\lib\start-cluster {"baseDir":"E:\\WaterExquisite_server","framework":"E:\\WaterE
xquisite_server\\node_modules\\egg","workers":1} exit with code 1
⚠  Command Error, enable `DEBUG=common-bin` for detail```

**Comment by assmdx** [comment]
通过
```DEBUG=common-bin npm run dev```
找到了问题 ==

**Comment by mragon1997** [comment]
> 通过
> `DEBUG=common-bin npm run dev`
> 找到了问题 ==

能告诉一下是什么问题么？

**Comment by KableShow** [comment]
@mragon1997 看看是不是mongodb的端口不对，默认是27017，项目上是27019
