### ISSUE TITLE
ctx.render 查找 view 路径错误

### ISSUE THREAD

**Issue by shauvet** [eggjs/egg#2709]
* **Node Version**: 9.9.0
* **Egg Version**: 2.9.0
* **Plugin Name**: egg-view-nunjucks
* **Plugin Version**: 2.2.0
* **Platform**: osx 10.13.5
* **Mini Showcase Repository**: https://github.com/shauvet/egg-hackernews

在 app/controller/news.js 文件里

```javascript
const Controller = require('egg').Controller;

class NewsController extends Controller {
  async list() {
    const dataList = {
      list: [
        { id: 1, title: 'this is news 1', url: '/news/1' },
        { id: 2, title: 'this is news 2', url: '/news/2' }
      ]
    };
    await this.ctx.render('news/list.tpl', dataList);
    // this.ctx.body = 'this is news'
  }
}

module.exports = NewsController;
```
一直报错：
```
ERROR 39401 [-/127.0.0.1/-/14ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find news/list.tpl from 
    at Map.resolve (/Users/xiaowei/Desktop/workspace/nodejs/egg-hackernews/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: undefined
expected: true
operator: '=='
pid: 39401
hostname: appledeMacBook-Pro.local
```

找不到 news/list.tpl 文件，然而实际上是有的。

config/plugin.js

```javascript
exports.nunjucks = {
  enable: true,
  package: 'egg-view-nunjucks'
};
```

config/config.default.js

```javascript
module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1529244024422_8455';

  config.view = {
    defaultViewEngine: 'nunjucks',
    defaultExtension: '.tpl',
    mapping: {
      '.tpl': 'nunjucks'
      // '.xtpl': 'xtpl'
    }
  };

  // config.xtpl = {};

  // add your config here
  config.middleware = [];

  return config;
};
```

已经提到 github，麻烦大佬看下什么原因。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view#root

`app/view` not `app/views`
