### ISSUE TITLE
文件上传bug,https://github.com/eggjs/examples/tree/master/multipart

### ISSUE THREAD

**Issue by z5614036** [eggjs/egg#2726]
当使用 demo 测试上传文件，
class UploadMultipleController extends Controller {
  async show() {
    await this.ctx.render('page/multiple.html');
  }

  async upload() {
    const parts = this.ctx.multipart({ autoFields: true });
    const files = [];

    let stream;
    while ((stream = await parts()) != null) {
      const filename = stream.filename.toLowerCase();
      const target = path.join(this.config.baseDir, 'app/public', filename);
      const writeStream = fs.createWriteStream(target);
      try {
        await awaitWriteStream(stream.pipe(writeStream));
      } catch (err) {
        await sendToWormhole(stream);
        throw err;
      }
      files.push(filename);
    }

    await this.ctx.render('page/multiple_result.html', {
      fields: Object.keys(parts.field).map(key => ({ key, value: parts.field[key] })),
      files,
    });
  }
}
此upload 函数如果只接受到一个文件，就会报下面的错误

2018-06-24 10:52:27,819 ERROR 3959 nodejs.EISDIRError: EISDIR: illegal operation on a directory, open '/Users/mac/Desktop/develop/examples/multipart/app/public' (uncaughtException throw 1 times on pid:3959)
EISDIRError: EISDIR: illegal operation on a directory, open '/Users/mac/Desktop/develop/examples/multipart/app/public' (uncaughtException throw 1 times on pid:3959)
errno: -21
code: 'EISDIR'
syscall: 'open'
path: '/Users/mac/Desktop/develop/examples/multipart/app/public'
name: 'EISDIRError'
pid: 3959
hostname: macdeiMac.local

[Sun Jun 24 2018 10:52:27 GMT+0800 (CST)] [graceful:worker:3959:uncaughtException] throw error 1 times
{ EISDIRError: EISDIR: illegal operation on a directory, open '/Users/mac/Desktop/develop/examples/multipart/app/public' (uncaughtException throw 1 times on pid:3959)
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/Users/mac/Desktop/develop/examples/multipart/app/public',
  name: 'EISDIRError' }
EISDIRError: EISDIR: illegal operation on a directory, open '/Users/mac/Desktop/develop/examples/multipart/app/public' (uncaughtException throw 1 times on pid:3959)
[Sun Jun 24 2018 10:52:27 GMT+0800 (CST)] [graceful:worker:3959] will exit after 30000ms
[Sun Jun 24 2018 10:52:27 GMT+0800 (CST)] [graceful:worker:3959] close server#0, _connections: 1
[Sun Jun 24 2018 10:52:27 GMT+0800 (CST)] [graceful:worker:3959] close 1 servers!
[Sun Jun 24 2018 10:52:27 GMT+0800 (CST)] [graceful:worker:3959] worker disconnect!
[2018-06-24 10:52:27.827] [cfork:master:3957] worker:3959 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-06-24 10:52:27.827] [cfork:master:3957] don't fork new work (refork: false)
2018-06-24 10:52:27,828 INFO 3957 [master] app_worker#1:3959 disconnect, suicide: true, state: disconnected, current workers: ["1"]
[Sun Jun 24 2018 10:52:57 GMT+0800 (CST)] [graceful:worker:3959] kill timeout, exit now.
2018-06-24 10:52:57,824 ERROR 3959 [app_worker] exit with code:1
[2018-06-24 10:52:57.830] [cfork:master:3957] worker:3959 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2018-06-24 10:52:57,831 ERROR 3957 nodejs.AppWorkerDiedError: [master] app_worker#1:3959 died (code: 1, signal: null, suicide: true, state: dead), current workers: []
    at Master.onAppExit (/Users/mac/Desktop/develop/examples/multipart/node_modules/_egg-cluster@1.18.0@egg-cluster/lib/master.js:391:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/Users/mac/Desktop/develop/examples/multipart/node_modules/_egg-cluster@1.18.0@egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/mac/Desktop/develop/examples/multipart/node_modules/_egg-cluster@1.18.0@egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/Users/mac/Desktop/develop/examples/multipart/node_modules/_egg-cluster@1.18.0@egg-cluster/lib/master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: 'AppWorkerDiedError'
pid: 3957
hostname: macdeiMac.local

**Comment by BaffinLee** [comment]
看你的错误信息，应该是 `stream.filename` 为空，可能是你没有选文件就提交表单了
可以这样避免一下
```javascript
if (!stream.filename) {
  continue;
}
```
