### ISSUE TITLE
nodejs.ClusterRequestTypeError: unsupport data type: register_channel

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#2732]
程序线上启动后一直报这个错误，但页面是可以访问的，偶尔获取不到config.default.js中的参数。

* **Node Version**:v8.9.3
* **Egg Version**:^1.3.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:centos7
* **Mini Showcase Repository**:

2018-06-26 11:47:01,463 ERROR 1377 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (/sunqfrs/frs_frontend_optest/node_modules/cluster-client/lib/leader.js:354:23)
    at Connection.conn.on (/sunqfrs/frs_frontend_optest/node_modules/cluster-client/lib/leader.js:261:43)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at process.nextTick (/sunqfrs/frs_frontend_optest/node_modules/cluster-client/lib/connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'ClusterRequestTypeError'
pid: 1377

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
