### ISSUE TITLE
Cannot read property 'prev' of undefined

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2740]
egg 版本 2.9.1   

启动报错

2018-06-27 19:12:33,127 ERROR 20484 nodejs.TypeError: Cannot read property 'prev' of undefined
    at Compiler.<anonymous> (/Users/linxuanwei/cis-gfs-test/node_modules/nanomatch/lib/compilers.js:213:25)
    at Compiler.visit (/Users/linxuanwei/cis-gfs-test/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/Users/linxuanwei/cis-gfs-test/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/Users/linxuanwei/cis-gfs-test/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/Users/linxuanwei/cis-gfs-test/node_modules/snapdragon/index.js:156:32)
    at /Users/linxuanwei/cis-gfs-test/node_modules/micromatch/index.js:786:23
    at memoize (/Users/linxuanwei/cis-gfs-test/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/Users/linxuanwei/cis-gfs-test/node_modules/micromatch/index.js:783:10)
    at create (/Users/linxuanwei/cis-gfs-test/node_modules/micromatch/index.js:686:25)
    at /Users/linxuanwei/cis-gfs-test/node_modules/micromatch/index.js:695:16

**Comment by linxuanwei** [comment]
请紧急修复

**Comment by linxuanwei** [comment]
![image](https://user-images.githubusercontent.com/10094722/41970962-4f366a62-7a3f-11e8-87c5-08499688114c.png)

**Comment by linxuanwei** [comment]
"nanomatch": "1.2.9"

egg 依赖的这个库报错的   升级到1.2.9 就好了

**Comment by popomore** [comment]
remove node_modules and reinstall
