### ISSUE TITLE
关于错误堆栈的一个疑惑

### ISSUE THREAD

**Issue by lee1hang** [eggjs/egg#2741]
直接使用官方example的[hackernews](https://github.com/eggjs/examples/tree/master/hackernews)。

对`app/service/HackerNews.js`进行操作，增加个主动抛异常
```javascript
 async getItem(id) {
    await this.request(`item/${id}.json`);
    throw new Error()
  }
```
原先期望能够在错误堆栈上清楚的看到调用链，然而却这样了
``` bash
2018-06-27 19:34:34,168 ERROR 86115 [-/127.0.0.1/-/940ms GET /news] nodejs.Error:
    at HackerNews.getItem (/Users/liyihang/Desktop/examples-master/hackernews/app/service/HackerNews.js:59:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

干掉`await`那一行后
``` javascript
 async getItem(id) {
    throw new Error()
  }
```
log如期望正常
``` bash
[2018-06-27 19:39:35.298] [cfork:master:86106] worker:86126 exit (code: 0, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2018-06-27 19:39:45,208 ERROR 86206 [-/127.0.0.1/-/761ms GET /news] nodejs.Error:
    at HackerNews.getItem (/Users/liyihang/Desktop/examples-master/hackernews/app/service/HackerNews.js:59:11)
    at Promise.all.idList.map.id (/Users/liyihang/Desktop/examples-master/hackernews/app/controller/news.js:14:80)
    at Array.map (<anonymous>)
    at NewsController.list (/Users/liyihang/Desktop/examples-master/hackernews/app/controller/news.js:14:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

求解为何会这样？？ QAQ

**Comment by popomore** [comment]
因为 httpclient 是异步的，可以去 node 问下

**Comment by popomore** [comment]
https://github.com/nodejs/node/issues/11865

**Comment by lee1hang** [comment]
感谢 @popomore 。

逛了一圈社区都没有找到较好的解决方法，要么是用第三方库重写部分代码，要么是babel把`async`转`generator`，目前是先在[这个解决方案](https://gist.github.com/lll000111/3d6a53da4d53beb909189793c7631ba6)的基础上解决堆栈不全的问题。

**Comment by popomore** [comment]
很多解法有性能问题，慎用
