### ISSUE TITLE
docker下面npm stop失败

### ISSUE THREAD

**Issue by leegang2017** [eggjs/egg#2781]
* **Node Version**:
v8.11.3
* **Egg Version**:
    "egg": "^2.2.1",
    "egg-scripts": "^2.6.0"

* **docker**:

 ```sh
FROM node:8-alpine

RUN echo http://mirrors.aliyun.com/alpine/v3.6/main > /etc/apk/repositories; \
echo http://mirrors.aliyun.com/alpine/v3.6/community >> /etc/apk/repositories

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      libc6-compat \
      krb5 \
      cyrus-sasl-gssapi \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

# Create app directory
RUN mkdir -p /data/g7-work/docker/node-rdkafka/app

# Move to the app directory
WORKDIR /data/g7-work/docker/node-rdkafka/app
 ```
在里面创建一个最简单的egg程序,npm start,然后再npm stop
```sh
egg-init egg-example --type=simple
....
npm stop
 ```
会报下面的错
```sh
> eggctl stop --title=egg-server-example

  common-bin [EggScripts] origin argument `stop --title=egg-server-example` +0ms
  common-bin [EggScripts] add command `start` from `/data/g7-work/docker/node-rdkafka/app/egg-example/node_modules/egg-scripts/lib/cmd/start.js` +6ms
  common-bin [EggScripts] add command `stop` from `/data/g7-work/docker/node-rdkafka/app/egg-example/node_modules/egg-scripts/lib/cmd/stop.js` +0ms
  common-bin [EggScripts] loaded command `start,stop` from directory `/data/g7-work/docker/node-rdkafka/app/egg-example/node_modules/egg-scripts/lib/cmd` +0ms
  common-bin [EggScripts] dispatch to subcommand `stop` -> `StopCommand` with ["--title=egg-server-example"] +20ms
  common-bin [StopCommand] origin argument `--title=egg-server-example` +0ms
  common-bin [StopCommand] exec run command +2ms
[egg-scripts] stopping egg application with --title=egg-server-example
⚠️  Error: Run "sh -c ps -eo "pid,command"" error, exit code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
  common-bin args --title=egg-server-example +11ms
  common-bin Error: Run "sh -c ps -eo "pid,command"" error, exit code 1
  common-bin     at ChildProcess.proc.on.code (/data/g7-work/docker/node-rdkafka/app/egg-example/node_modules/runscript/index.js:74:21)
  common-bin     at emitTwo (events.js:126:13)
  common-bin     at ChildProcess.emit (events.js:214:7)
  common-bin     at maybeClose (internal/child_process.js:925:16)
  common-bin     at Socket.stream.socket.on (internal/child_process.js:346:11)
  common-bin     at emitOne (events.js:116:13)
  common-bin     at Socket.emit (events.js:211:7)
  common-bin     at Pipe._handle.close [as _onclose] (net.js:557:12) +0ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 stop: `eggctl stop --title=egg-server-example`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example@1.0.0 stop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-09T06_35_35_819Z-debug.log

 ```

**Comment by atian25** [comment]
node:8-alpine 里面执行 `sh -c ps -eo "pid,command"` 挂了，操作系统问题。

话说，docker 的话没必要 stop 吧，切流量后直接杀掉容器了。

**Comment by leegang2017** [comment]
在docker容器里面可以直接执行 sh -c ps -eo "pid,command" 的,
好吧,希望以后可以用npm stop

**Comment by atian25** [comment]
`Common-bin Error: Run "sh -c ps -eo "pid,command"" error, exit code 1`

这个就要你去查下了，我们一般都是 centos 这些的，有可能是你的镜像比较精简，或者是权限问题，导致执行失败。

**Comment by leegang2017** [comment]
可以提供个阿里(或者eggjs)用的Dockerfile吗? 用node:8-alpine的原因是支持node-rdkafka,不过node:8-alpine用uws也有问题,谢谢喽

**Comment by atian25** [comment]
egg 对环境没什么特殊的要求，我们用的都是内部的镜像。

你这个调用系统 ps 命令执行出错，具体原因要分析下。

**Comment by leegang2017** [comment]
哟喂,还是建议eggjs出一个官方的Dockerfile, 免得很多环境上的问题哈

**Comment by popomore** [comment]
先开坑 https://github.com/eggjs/docker

**Comment by atian25** [comment]
@thonatos 接锅

**Comment by kennylbj** [comment]
我发现用Docker运行egg以后，在宿主机调用``egg-script stop``也能把docker里的egg给停掉，这个情况正常吗？

**Comment by atian25** [comment]
你 ps 看下docker 的进程名字是不是命中了

**Comment by popomore** [comment]
宿主机应该能看到所有进程的

**Comment by kennylbj** [comment]
是的，我理解错了，不好意思。
参照[连接](https://stackoverflow.com/questions/38487598/why-can-i-see-the-docker-container-process-when-i-do-a-ps-aux-on-the-host)
