### ISSUE TITLE
 Error: connect EMFILE 

### ISSUE THREAD

**Issue by yangchongduo** [eggjs/egg#2782]
日志

```
body: 
      { Error: connect EMFILE xx.xx.xx.xx:80 - Local (undefined:undefined)
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at internalConnect (net.js:976:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1122:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
        code: 'EMFILE',
        errno: 'EMFILE',
        syscall: 'connect',
```
监控 ：服务tcp  close_wait 数突然由0增加到 4k

给点方向 这是什么引起的？
谢谢

**Comment by popomore** [comment]
http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

**Comment by popomore** [comment]
@egg-bot Are you alive?
