### ISSUE TITLE
无法运行单元测试用例: egg启动总是超时

### ISSUE THREAD

**Issue by xingyuzhe** [eggjs/egg#2790]
* **Node Version**: 9.11.1
* **Egg Version**: 2.9.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows 7
* **Mini Showcase Repository**:

使用 egg-bin dev, egg-scripts start 命令均可正常启动项目, 但是使用egg-bin test命令时总是出现如下错误:  

忽略设置的15s超时，默认60s也是一样的
不引入app就能正常运行单元测试, 其实就是因为app启动超时导致的
感觉是用egg-mock启动时加载模块有问题吧，有人遇到这个问题么? 

```
$ cross-env DEBUG=egg-mock* egg-bin test test/app/flow/flow-condition.test.ts --ts --t 15000 --full-trace
  egg-mock once(error,() => {}), cache it because app has not init +0ms


  egg-mock get clusterPort 52772 +12s
  egg-mock agent instantiate +7s
  egg-mock agent ready +597ms
  egg-mock app instantiate +1m
  egg-mock this[APP_INIT] = true +1ms
  egg-mock once(error,() => {}), use cache and pass to app +2ms
2018-07-12 10:04:58,360 WARN 11272 [egg:core:ready_timeout] 10 seconds later D:\projects\wk-egg\node_modules\egg-watcher\app.js:15:7 was still unable
to finish.
2018-07-12 10:04:58,361 WARN 11272 [egg:core:ready_timeout] 10 seconds later D:\projects\wk-egg\node_modules\egg-sequelize\lib\loader.js:44:7 was still unable to finish.
2018-07-12 10:04:58,362 WARN 11272 [egg:core:ready_timeout] 10 seconds later D:\projects\wk-egg\node_modules\egg-redis\lib\redis.js:48:7 was still unable to finish.
2018-07-12 10:04:58,362 WARN 11272 [egg:core:ready_timeout] 10 seconds later D:\projects\wk-egg\node_modules\egg-mysql\lib\mysql.js:20:7 was still unable to finish.
2018-07-12 10:04:58,363 WARN 11272 [egg:core:ready_timeout] 10 seconds later D:\projects\wk-egg\app.ts:7:9 was still unable to finish.
  1) "before all" hook

  0 passing (1m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Hook.Runnable._timeoutError (D:\projects\wk-egg\node_modules\mocha\lib\runnable.js:440:10)
      at Timeout.<anonymous> (D:\projects\wk-egg\node_modules\mocha\lib\runnable.js:251:24)
      at ontimeout (timers.js:466:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:267:5)



⚠️  Error: D:\projects\wk-egg\node_modules\mocha\bin\_mocha --timeout=15000,--full-trace,--require=D:\projects\wk-egg\node_modules\co-mocha\lib\co-m
ocha.js,--require=D:\projects\wk-egg\node_modules\intelli-espower-loader\intelli-espower-loader.js,--require=D:\projects\wk-egg\node_modules\espower-typescript\guess.js,--exit,test/app/flow/flow-condition.test.ts exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
```

flow-condition.test.ts
```
import { app, assert } from 'egg-mock/bootstrap'

describe('test/app/flow/flow-condition.test.ts', () => {
  it('should isSystemJudgePassed return true', () => {
    assert(true === true)
  })
})

```

**Comment by xingyuzhe** [comment]
超时的是 egg-watcher egg-redis egg-mysql egg-sequelize, 其实不是超时, beforeStart里的异步函数等多久都不会结束。  奇怪的是 直接启动 一点问题也没有, 只有跑单元测试才这样

**Comment by atian25** [comment]
就是说我的那个原因，在单元测试下，你需要连接数据库的这几个插件都挂了。

检查下单元测试情况下的配置文件是否有问题吧。

如果还有问题，用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by xingyuzhe** [comment]
好的  我正在排查

**Comment by xingyuzhe** [comment]
找到解决办法了， 但我觉得这是一个BUG,  应该是2个BUG.
暂时的解决办法: EGG_READY_TIMEOUT_ENV 设置成100s . timeout 源码里改成120s.
如果我的service和controller里的文件继续增加, 则这个配置也要随之增加。并且大约是10倍的数量级增加。

为什么我说是2个BUG:
1 egg-bin test 里的 timeout参数 设置超过60s秒后就不再生效。
2 我开发环境启动大约是10s, 生产环境大约是几秒。但是单元测试启动就会变成100s. 我项目源码的增加数量与单元测试的增加数量大约是1：10的关系。  

我说怎么之前都可以跑测试, 突然就不行了。
单元测试的配置和开发环境的配置一样， 不存在连接速度不一致的问题。代码也无问题。
之前就觉得跑单元测试慢的很, 严重消耗了写单元测试的积极性。

其实主要是mock的时候启动app慢。 纯粹跑mocha就没有这个问题。

**Comment by atian25** [comment]
> 我开发环境启动大约是7s, 生产环境更少。但是单元测试启动就会变成100s

这个数据不正常。

你看下 run 目录下，有 timing 数据的。

**Comment by popomore** [comment]
EGG_READY_TIMEOUT_ENV 这个不会影响启动的

**Comment by 2015-lizaiyang** [comment]
不会啊！您在测试时检查一下您的数据库是否有连接成功。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by joey-lucky** [comment]
我也遇到过这种情况，是因为数据库连接数限制的问题，于是手动断开数据库连接就解决了。
`
    app.beforeClose(()=>{
        connection.close();
    })
`
