### ISSUE TITLE
egg服务崩溃

### ISSUE THREAD

**Issue by lampofaladdin** [eggjs/egg#2791]
* **Node Version**:8.9.3
* **Egg Version**:^2.2.1
* **Plugin Name**:egg-alinode
* **Plugin Version**:2.0.1
* **Platform**: centos7
* **Mini Showcase Repository**: 

报错信息：

**common-error.log**  日志的上面全是报 New client connected 错误
2018-07-11 03:54:14,513 ERROR 23775 nodejs.AlinodeAgentxSignatureError: New client connected.
    at Agent.onMessage (/home/tuosai/node/lunasol-6-7/node_modules/_agentx@1.9.3@agentx/lib/agent.js:173:15)
    at Connection.<anonymous> (/home/tuosai/node/lunasol-6-7/node_modules/_agentx@1.9.3@agentx/lib/agent.js:71:10)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at WebSocket.<anonymous> (/home/tuosai/node/lunasol-6-7/node_modules/_agentx@1.9.3@agentx/lib/connection.js:40:10)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (/home/tuosai/node/lunasol-6-7/node_modules/_ws@1.1.5@ws/lib/WebSocket.js:841:10)
    at /home/tuosai/node/lunasol-6-7/node_modules/_ws@1.1.5@ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/tuosai/node/lunasol-6-7/node_modules/_ws@1.1.5@ws/lib/Receiver.js:371:5)
name: 'AlinodeAgentxSignatureError'
pid: 23775
hostname: izj6ceftauv7x5rrtllrxiz

2018-07-11 04:05:33,128 ERROR 945 nodejs.ServerNoResponseError: server 127.0.0.1:34025 no response in 99207ms, maybe the socket is end on the other side. (address: 127.0.0.1:34025)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/tuosai/node/lunasol-6-29/node_modules/_tcp-base@3.1.0@tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ServerNoResponseError'
pid: 945
hostname: izj6ceftauv7x5rrtllrxiz

2018-07-11 04:09:42,232 ERROR 945 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:34025
    at Function.waitFor (/home/tuosai/node/lunasol-6-29/node_modules/_cluster-client@2.1.1@cluster-client/lib/server.js:238:15)
    at <anonymous>

pid: 945
hostname: izj6ceftauv7x5rrtllrxiz

**egg-web.log** 这个日志大概有十万行的报错。。。
2018-07-11 05:15:09,354 WARN 1530 nodejs.Error: register to channel: Watcher failed, will retry after 3s, [TCPBase] The socket was closed. (address: 127.0.0.1:37838)
    at Follower.send (/home/tuosai/node/lunasol-6-7/node_modules/_tcp-base@3.1.0@tcp-base/lib/base.js:184:19)
    at Follower.send (/home/tuosai/node/lunasol-6-7/node_modules/_cluster-client@2.1.0@cluster-client/lib/follower.js:103:18)
    at Follower._registerChannel (/home/tuosai/node/lunasol-6-7/node_modules/_cluster-client@2.1.0@cluster-client/lib/follower.js:212:10)
    at Timeout.setTimeout [as _onTimeout] (/home/tuosai/node/lunasol-6-7/node_modules/_cluster-client@2.1.0@cluster-client/lib/follower.js:221:31)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
id: 702458
data: 'AQAAAAAAAAAACrf6AADqYAAAADMAAAAAeyJ0eXBlIjoicmVnaXN0ZXJfY2hhbm5lbCIsImNoYW5uZWxOYW1lIjoiV2F0Y2hlciJ9'
pid: 1530
hostname: izj6ceftauv7x5rrtllrxiz

一共两个使用egg进行开发的项目，都是根据egg的文档进行配置，但是另外一个没有出现这种问题。
请教一下出现这个问题的原因。。
第一次提交issues，有不到之处请见谅。
谢谢你们！

**Comment by gxcsoccer** [comment]
@lampofaladdin 本地能够复现吗？另外方便提供代码吗？

**Comment by gxcsoccer** [comment]
@lampofaladdin 或者看先把 watcher 插件关闭，是否还会崩溃

**Comment by atian25** [comment]
目前应该只有 development 在开发期会依赖 watcher 来做热重启吧？ cc @popomore 
这样试试，在正式环境下关闭 watcher 看看。

```js
// plugin.prod.js
exports.watcher = false;
```

**Comment by popomore** [comment]
两个 egg 在一台服务器？

**Comment by atian25** [comment]
`nodejs.AlinodeAgentxSignatureError: New client connected`

这个 @JacksonTian 看看？

**Comment by lampofaladdin** [comment]
@gxcsoccer 没法复现，崩溃重启后，目前也没有报错。。就是担心下次还会出现这种问题，想找到报错的原因，谢谢你。

**Comment by lampofaladdin** [comment]
@atian25 一会我去插件里面配置一下，谢谢大佬。

**Comment by lampofaladdin** [comment]
@gxcsoccer  啊。。。不好意思。。还是报错的。。。我去整理一下报错信息。。。

**Comment by lampofaladdin** [comment]
common-error的报错日志。。。
`
2018-07-12 00:54:07,106 ERROR 11712 nodejs.ServerNoResponseError: server 127.0.0.1:46276 no response in 21140ms, maybe the socket is end on the other side. (address: 127.0.0.1:46276)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/tuosai/node/lunasol/node_modules/_tcp-base@3.1.0@tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ServerNoResponseError"
pid: 11712
hostname: izj6ceftauv7x5rrtllrxiz

2018-07-12 02:06:57,747 ERROR 11712 nodejs.Error: [TCPBase] The socket was closed. (address: 127.0.0.1:46276)
    at Follower.send (/home/tuosai/node/lunasol/node_modules/_tcp-base@3.1.0@tcp-base/lib/base.js:184:19)
    at Follower.send (/home/tuosai/node/lunasol/node_modules/_cluster-client@2.1.1@cluster-client/lib/follower.js:103:18)
    at Follower._registerChannel (/home/tuosai/node/lunasol/node_modules/_cluster-client@2.1.1@cluster-client/lib/follower.js:212:10)
    at Timeout.setTimeout [as _onTimeout] (/home/tuosai/node/lunasol/node_modules/_cluster-client@2.1.1@cluster-client/lib/follower.js:223:33)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
id: 1600
data: "AQAAAAAAAAAAAAZAAADqYAAAADMAAAAAeyJ0eXBlIjoicmVnaXN0ZXJfY2hhbm5lbCIsImNoYW5uZWxOYW1lIjoiV2F0Y2hlciJ9"
pid: 11712
hostname: izj6ceftauv7x5rrtllrxiz

2018-07-12 15:39:03,695 ERROR 19635 nodejs.ENOENTError: ENOENT: no such file or directory, access '/home/tuosai/node/lunasol/node_modules/_commandx@1.5.1@commandx/get_processes_count'
Error: ENOENT: no such file or directory, access '/home/tuosai/node/lunasol/node_modules/_commandx@1.5.1@commandx/get_processes_count'
errno: -2
code: "ENOENT"
syscall: "access"
path: "/home/tuosai/node/lunasol/node_modules/_commandx@1.5.1@commandx/get_processes_count"
name: "ENOENTError"
pid: 19635
hostname: izj6ceftauv7x5rrtllrxiz


2018-07-12 15:44:32,870 ERROR 19635 nodejs.AlinodeAgentxSignatureError: New client connected.
    at Agent.onMessage (/home/tuosai/node/lunasol/node_modules/_agentx@1.9.5@agentx/lib/agent.js:173:15)
    at Connection.<anonymous> (/home/tuosai/node/lunasol/node_modules/_agentx@1.9.5@agentx/lib/agent.js:71:10)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at WebSocket.<anonymous> (/home/tuosai/node/lunasol/node_modules/_agentx@1.9.5@agentx/lib/connection.js:40:10)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (/home/tuosai/node/lunasol/node_modules/_ws@1.1.5@ws/lib/WebSocket.js:841:10)
    at /home/tuosai/node/lunasol/node_modules/_ws@1.1.5@ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/tuosai/node/lunasol/node_modules/_ws@1.1.5@ws/lib/Receiver.js:371:5)
name: "AlinodeAgentxSignatureError"
pid: 19635
hostname: izj6ceftauv7x5rrtllrxiz
`

发现有个包没安装，是这个包的问题吗？
现在那个commandx的包已经安装好了。

**Comment by lampofaladdin** [comment]
@gxcsoccer @atian25 @popomore  
几位大佬。。
项目代码：https://github.com/lampofaladdin/egg-error-demo.git
涉及到页面的部分删除了。。。
麻烦你们了。。感谢大佬！

**Comment by JacksonTian** [comment]
AlinodeAgentxSignatureError 这个错误，跟 alinode 的配置有问题，确保 server, appid, secret 一定是正确的。

**Comment by lampofaladdin** [comment]
@JacksonTian  谢谢大佬，我去试一下。

**Comment by tong3jie** [comment]
存在同样的问题，而且appid和secret都没问题。

**Comment by atian25** [comment]
@tong3jie 这样一句干巴巴的反馈是没法跟踪的，请提供可复现方式和对应的日志。
