### ISSUE TITLE
实现rpc功能报错？

### ISSUE THREAD

**Issue by zurmokeeper** [eggjs/egg#2802]
请问在egg里使用sofa-rpc模块实现rpc功能，是不是一定要zookeeper？个人在写官方提供的sofa-rpc代码是时候，启动rpc服务的时候报错了，不知道为什么？是因为没有zookeeper服务的原因？例子链接

> https://github.com/eggjs/examples/blob/master/sofa-rpc/README.zh-CN.md

**npm start** 的时候报错如下：
```
13 verbose stack Error: example@1.0.0 start: `egg-scripts start --daemon --title=egg-server-sofa-rpc`
13 verbose stack Exit status 1
```

**Comment by dead-horse** [comment]
把前面的报错信息也贴出来

**Comment by zurmokeeper** [comment]
控制台报错如下：

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 rpcstart: `egg-scripts start --daemon --title=egg-server-sofa-rpc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@1.0.0 rpcstart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bruce\AppData\Roaming\npm-cache\_logs\2018-07-13T08_59_08_364Z-debug.log
```
2018-07-13T08_59_08_364Z-debug.log  里面的详细信息如下：

```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\install\\nodejs-8.11.2\\node.exe',
1 verbose cli   'E:\\install\\nodejs-8.11.2\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'rpcstart' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prerpcstart', 'rpcstart', 'postrpcstart' ]
5 info lifecycle example@1.0.0~prerpcstart: example@1.0.0
6 info lifecycle example@1.0.0~rpcstart: example@1.0.0
7 verbose lifecycle example@1.0.0~rpcstart: unsafe-perm in lifecycle true
8 verbose lifecycle example@1.0.0~rpcstart: PATH: E:\install\nodejs-8.11.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\学习\node.js\练习\Egg\egg-example\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;E:\install\xampp\mysql\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\install\xampp\php;C:\ProgramData\ComposerSetup\bin;E:\install\wkhtmltopdf\bin;E:\install\anzhuo\android-sdk_r24.4.1-windows\android-sdk-windows\tools;E:\install\anzhuo\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools;C:\Users\bruce\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;E:\install\httpd-2.4.25-x86-vc14-r1\Apache24\php\ext;E:\install\Git\Git\bin;E:\install\Ruby24-x64\bin;C:\WINDOWS\System32\OpenSSH\;E:\install\nodejs-8.11.2\;E:\install\python2.7.14;;E:\install\Microsoft VS Code\bin;E:\install\Ruby24-x64\bin;C:\Users\bruce\AppData\Local\Microsoft\WindowsApps;C:\Users\bruce\AppData\Roaming\Composer\vendor\bin;E:\install\Microsoft VS Code\bin;E:\install\V8\depot_tools;E:\install\NASM;C:\Users\bruce\AppData\Roaming\npm
9 verbose lifecycle example@1.0.0~rpcstart: CWD: D:\学习\node.js\练习\Egg\egg-example
10 silly lifecycle example@1.0.0~rpcstart: Args: [ '/d /s /c',
10 silly lifecycle   'egg-scripts start --daemon --title=egg-server-sofa-rpc' ]
11 silly lifecycle example@1.0.0~rpcstart: Returned: code: 1  signal: null
12 info lifecycle example@1.0.0~rpcstart: Failed to exec rpcstart script
13 verbose stack Error: example@1.0.0 rpcstart: `egg-scripts start --daemon --title=egg-server-sofa-rpc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\install\nodejs-8.11.2\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (E:\install\nodejs-8.11.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid example@1.0.0
15 verbose cwd D:\学习\node.js\练习\Egg\egg-example
16 verbose Windows_NT 10.0.17134
17 verbose argv "E:\\install\\nodejs-8.11.2\\node.exe" "E:\\install\\nodejs-8.11.2\\node_modules\\npm\\bin\\npm-cli.js" "run" "rpcstart"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error example@1.0.0 rpcstart: `egg-scripts start --daemon --title=egg-server-sofa-rpc`
22 error Exit status 1
23 error Failed at the example@1.0.0 rpcstart script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by BaffinLee** [comment]
把 egg 的 log 贴出来看看，npm 的 log 看不出什么问题

**Comment by zurmokeeper** [comment]
`egg` 的 `log` 是指哪一个文件 , 我看到 `egg-agent `, `egg-web` , `egg-schedule`这几个log文件里面都没有`err`的信息？

**Comment by dead-horse** [comment]
请提供更多信息后再开启
