### ISSUE TITLE
Command Error, enable `DEBUG=common-bin` for detail

### ISSUE THREAD

**Issue by maicss** [eggjs/egg#2808]
* **Node Version**: 10.4.0
* **Egg Version**: 2.9.1
* **Plugin Name**:  egg-bin
* **Plugin Version**: 4.7.1
* **Platform**: Mac

> 这个不影响项目的运行，但是我搜了一下，这个报错好像都是egg的，这个报错是内部的什么机制导致的？故意设计的还是怎么回事？

## 项目结构：
![image](https://user-images.githubusercontent.com/9784767/42733585-13bcb290-8866-11e8-8e72-cb6bff829161.png)

## package.json:
```
{
  "name": "egg-backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "egg-bin dev",
    "test": "egg-bin test",
  },
  "author": "Maicss",
  "license": "ISC",
  "dependencies": {
    "egg": "^2.9.1",
    "egg-bin": "^4.7.1",
    "egg-view-nunjucks": "^2.2.0"
  }
}
```

## test.js:
```
const assert = require('assert')

describe('test/home.test.js', () => {
  const arr = [1,2,3]
  it('power-assert', () => {
    assert(arr[1] === 10)
  })
  it('power-assert1111', () => {
    assert(arr[1] === 2)
  })
})
```

##没有加`DEBUG=common-bin`时候的运行结果:
```
➜  egg-backend npm run test

> egg-backend@1.0.0 test /Users/maicss/Development/javascript/egg-backend
> egg-bin test



  test/home.test.js
    1) power-assert
    ✓ power-assert1111


  1 passing (46ms)
  1 failing

  1) test/home.test.js
       power-assert:

      AssertionError [ERR_ASSERTION]:   # test/controller/home.test.js:6
  
  assert(arr[1] === 10)
         |  |   |      
         |  2   false  
         [1,2,3]       
  
  [number] 10
  => 10
  [number] arr[1]
  => 2
  
      + expected - actual

      -false
      +true
      
      at Context.it (test/controller/home.test.js:6:5)
      [use `--full-trace` to display the full stack trace]



⚠️  Error: /Users/maicss/Development/javascript/egg-backend/node_modules/mocha/bin/_mocha --require=/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/comocha/lib/co-mocha.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=60000,--exit,test/controller/home.test.js exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-backend@1.0.0 test: `egg-bin test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-backend@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maicss/.npm/_logs/2018-07-15T11_28_44_042Z-debug.log
```
## 加了之后的结果：
```
➜  egg-backend npm run test

> egg-backend@1.0.0 test /Users/maicss/Development/javascript/egg-backend
> DEBUG=common-bin egg-bin test

  common-bin [EggBin] origin argument `test` +0ms
  common-bin [EggBin] add command `autod` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/autod.js` +29ms
  common-bin [EggBin] add command `cov` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/cov.js` +2ms
  common-bin [EggBin] add command `debug` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/debug.js` +2ms
  common-bin [EggBin] add command `dev` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/dev.js` +1ms
  common-bin [EggBin] add command `pkgfiles` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/pkgfiles.js` +0ms
  common-bin [EggBin] add command `test` from `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd/test.js` +1ms
  common-bin [EggBin] loaded command `autod,cov,debug,dev,pkgfiles,test` from directory `/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/cmd` +0ms
  common-bin [EggBin] dispatch to subcommand `test` -> `TestCommand` with [] +66ms
  common-bin [TestCommand] origin argument `` +1ms
  common-bin [TestCommand] exec run command +10ms
  common-bin Run fork `/usr/local/Cellar/node/10.4.0/bin/node /Users/maicss/Development/javascript/egg-backend/node_modules/mocha/bin/_mocha --require=/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/mocha-clean.js --require=/Users/maicss/Development/javascript/egg-backend/node_modules/co-mocha/lib/co-mocha.js --require=/Users/maicss/Development/javascript/egg-backend/node_modules/intelli-espower-loader/intelli-espower-loader.js --timeout=60000 --exit test/controller/home.test.js` +0ms


  test/home.test.js
    1) power-assert
    ✓ power-assert1111


  1 passing (42ms)
  1 failing

  1) test/home.test.js
       power-assert:

      AssertionError [ERR_ASSERTION]:   # test/controller/home.test.js:6
  
  assert(arr[1] === 10)
         |  |   |      
         |  2   false  
         [1,2,3]       
  
  [number] 10
  => 10
  [number] arr[1]
  => 2
  
      + expected - actual

      -false
      +true
      
      at Context.it (test/controller/home.test.js:6:5)
      [use `--full-trace` to display the full stack trace]



⚠️  Error: /Users/maicss/Development/javascript/egg-backend/node_modules/mocha/bin/_mocha --require=/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/comocha/lib/co-mocha.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=60000,--exit,test/controller/home.test.js exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
  common-bin args  +492ms
  common-bin Error: /Users/maicss/Development/javascript/egg-backend/node_modules/mocha/bin/_mocha --require=/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/co-mocha/lib/co-mocha.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=60000,--exit,test/controller/home.test.js exit with code 1
  common-bin     at ChildProcess.proc.once.code (/Users/maicss/Development/javascript/egg-backend/node_modules/common-bin/lib/helper.js:56:21)
  common-bin     at Object.onceWrapper (events.js:273:13)
  common-bin     at ChildProcess.emit (events.js:182:13)
  common-bin     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12) +0ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-backend@1.0.0 test: `DEBUG=common-bin egg-bin test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-backend@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maicss/.npm/_logs/2018-07-15T11_18_16_867Z-debug.log
```

**Comment by popomore** [comment]
你测试挂了啊

**Comment by maicss** [comment]
一般输出不是这些就够了吗？
```
  test/home.test.js
    1) power-assert
    ✓ power-assert1111


  1 passing (42ms)
  1 failing

  1) test/home.test.js
       power-assert:

      AssertionError [ERR_ASSERTION]:   # test/controller/home.test.js:6
  
  assert(arr[1] === 10)
         |  |   |      
         |  2   false  
         [1,2,3]       
  
  [number] 10
  => 10
  [number] arr[1]
  => 2
  
      + expected - actual

      -false
      +true
      
      at Context.it (test/controller/home.test.js:6:5)
      [use `--full-trace` to display the full stack trace]
```
我用的框架少，就用过俩，都是类似的啊，难道还有这种风格的？

**Comment by popomore** [comment]
因为你运行的 egg-bin，不是 mocha

**Comment by maicss** [comment]
那为什么你们推荐这种方式运行test，那为什么这种方式会报这些错误呢？

**Comment by maicss** [comment]
该不会你们内部都是这样用的吧

**Comment by atian25** [comment]
没看懂，你的问题是啥？

**Comment by atian25** [comment]
额外的信息指的是哪一段？

**Comment by maicss** [comment]
```
 test/home.test.js
    1) power-assert
    ✓ power-assert1111


  1 passing (42ms)
  1 failing

  1) test/home.test.js
       power-assert:

      AssertionError [ERR_ASSERTION]:   # test/controller/home.test.js:6
  
  assert(arr[1] === 10)
         |  |   |      
         |  2   false  
         [1,2,3]       
  
  [number] 10
  => 10
  [number] arr[1]
  => 2
  
      + expected - actual

      -false
      +true
      
      at Context.it (test/controller/home.test.js:6:5)
      [use `--full-trace` to display the full stack trace]
```
对比其他框架的测试信息来说（我用过的两款），除了这部分，其他信息都是多余的，没必要的。

**Comment by atian25** [comment]
为什么你要加 `DEBUG=common-bin` 呢？ 那个是我们自己调试用的 debug 日志。
至于前面那段路径，不就是一个提示信息么？有什么问题么？

**Comment by maicss** [comment]
我也不想加啊，但是不加会报这些多余的信息:
```
⚠️  Error: /Users/maicss/Development/javascript/egg-backend/node_modules/mocha/bin/_mocha --require=/Users/maicss/Development/javascript/egg-backend/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/comocha/lib/co-mocha.js,--require=/Users/maicss/Development/javascript/egg-backend/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=60000,--exit,test/controller/home.test.js exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-backend@1.0.0 test: `egg-bin test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-backend@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maicss/.npm/_logs/2018-07-15T11_28_44_042Z-debug.log
```

**Comment by atian25** [comment]
这是 NPM 自己的报错啊。。。 不想看就用 `npm test -s`

再说，绝大部分情况下你如果看到这个，说明你的单元测试没过，这时候应该聚焦于去修复，修复完自然看不到了。

**Comment by maicss** [comment]
我去。。。我验证一下，如果是真的，我给你个红包，我知乎上关注你了，耽误你那么长时间。。。。

谢谢
