### ISSUE TITLE
agent_worker 内存泄露

### ISSUE THREAD

**Issue by shiny** [eggjs/egg#2837]
* **Node Version**: registry.cn-hangzhou.aliyuncs.com/aliyun-node/alinode:3-alpine
* **Egg Version**: 2.2.1

* **Plugin Name**:
* **Plugin Version**:
    "egg-alinode": "^2.0.1",
    "egg-kue": "^0.1.2",
    "egg-mysql": "^3.0.0",
    "egg-redis": "^2.0.0",
    "egg-scripts": "^2.5.0",
    "egg-sentry": "^1.0.0",
    "json-bigint": "^0.2.3"
* **Platform**: Docker on Linux
* **Mini Showcase Repository**:

如果觉得此 issues 无价值，请关闭，抱歉打扰。

1. 几个月来生产环境上出现无规律的偶然内存满，然后出现 core.* 的 core dump 文件
2. 今天下午复现，agent_worker 占用完机器剩余全部内存，而平时都平稳在一个 G 内。
3. 业务代码不复杂，仅仅是定时每小时更新微信 Token, 并且抓取微信粉丝资料、定时用 kue 群发消息。
4. 出现问题时候不是业务高峰期，最高仅仅每秒两三个请求，不处于群发时，而且测试到微信接口访问正常
5. 错误日志如下：
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[48:0x55fe4389b000]   523841 ms: Mark-sweep 1846.2 (2025.3) -> 1846.1 (1991.8) MB, 2643.5 / 3.1 ms  last resort GC in old space requested
[48:0x55fe4389b000]   526310 ms: Mark-sweep 1846.1 (1991.8) -> 1846.1 (1991.3) MB, 2468.5 / 2.9 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1e0cfa7257c1 <JSObject>
1: createSocket [_http_agent.js:~196] [pc=0x1ac786aae72f](this=0x2c551a29e771 <Agent map = 0x2eda31f60a29>,req=0x1b275cba4179 <ClientRequest map = 0x1d48289382e1>,options=0x1b275cba45a9 <Object map = 0x13ebf1024331>,cb=0x1b275cba46b9 <JSFunction handleSocketCreation_Inner (sfi = 0x280a0255d2f9)>)
2: addRequest [_http_agent.js:185] [bytecode=0x280a0255bb99 offset=441](this=0x2c551a29e771 ...

2018-07-24 18:19:54,641 ERROR 38 nodejs.AgentWorkerDiedError: [master] agent_worker#1:48 died (code: null, signal: SIGABRT)
at Master.onAgentExit (/usr/src/app/node_modules/egg-cluster/lib/master.js:317:17)
 at emitOne (events.js:116:13)
 at Master.emit (events.js:211:7)
  at Messenger.sendToMaster (/usr/src/app/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
 at Messenger.send (/usr/src/app/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
at ChildProcess.agentWorker.once (/usr/src/app/node_modules/egg-cluster/lib/master.js:216:22)
at Object.onceWrapper (events.js:317:30)
  at emitTwo (events.js:126:13)
  at ChildProcess.emit (events.js:214:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
name: 'AgentWorkerDiedError'
 hostname: 3cf5bbc0c321
```
7. alinode 后台没有追踪到内存暴涨的情况
![image](https://user-images.githubusercontent.com/117487/43147038-aedac980-8f94-11e8-8fb0-af3e306071c0.png)

8. 停用 egg-alinode 插件后恢复正常
9. 尝试分析 core 文件

请指教如何应对这种情况，因为 alinode 上每次出现这种情况数据都是空白的。

**Comment by BaffinLee** [comment]
提供一下能复现问题的最小代码仓库？

**Comment by shiny** [comment]
@BaffinLee  上次出现这个问题差不多是一个月前，复现比较难。
同一套代码，我的开发环境部署在京东云，也出现了 core dump，频率低点。（零访问量）
我想想如何提供复现的最小代码仓库。

**Comment by atian25** [comment]
第二点是昨天的一个 alinode 线上故障，已经修复了。

第一点的把 coredump 给朴老师看看吧

**Comment by hyj1991** [comment]
可以加下钉钉群 11794270，把 coredump 和 node 可执行文件发下，确认下问题

**Comment by hyj1991** [comment]
@shiny I'll close this issue, if any more question, you can reopen it.

**Comment by shiny** [comment]
感谢 @hyj1991 的支持，基本确认 agentx 引发的问题，如果有人遇到同样的问题，请确保 egg-alinode 依赖的 agentx 版本 >= 1.9.9 ，可通过升级 egg-alinode 
```
npm i egg-alinode
```

**Comment by hyj1991** [comment]
@shiny ok
