### ISSUE TITLE
nodejs.Error: register to channel: Watcher failed, will retry after 3s, [TCPBase] The socket was closed.

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#2838]
* **Node Version**:  v8.11.0
* **Egg Version**: v2.6.0
* **Plugin Name**: alinode
* **Plugin Version**: v3.11.0
* **Platform**:
* **Mini Showcase Repository**:

在egg-web.log 文件中出现大量类似日志：

`
2018-07-25_ 16:06:47,148 WARN 11843 nodejs.Error: register to channel: Watcher failed, will retry after 3s, [TCPBase] The socket was closed. (address: 127.0.0.1:43205)
    at Follower.send (/home/pay/node_modules/tcp-base/lib/base.js:184:19)
    at Follower.send (/home/pay/node_modules/cluster-client/lib/follower.js:106:18)
    at Follower._registerChannel (/home/pay/node_modules/cluster-client/lib/follower.js:216:10)
    at Timeout.setTimeout [as _onTimeout] (/home/pay/node_modules/cluster-client/lib/follower.js:225:31)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
id: 329993
data: 'AQAAAAAAAAAABQkJAADqYAAAADMAAAAAeyJ0eXBlIjoicmVnaXN0ZXJfY2hhbm5lbCIsImNoYW5uZWxOYW1lIjoiV2F0Y2hlciJ9'
pid: 11843
hostname: iz8vb4vmi6s951ztsbrfisz
`

common-error.log 中存在以下两种报错：

`
2018-07-25 10:11:12,507 ERROR 7430 nodejs.Error: Command failed: cat /proc/20517/environ
cat: /proc/20517/environ: No such file or directory
cat: /proc/20517/environ: No such file or directory
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
killed: false
code: 1
signal: null
cmd: 'cat /proc/20517/environ'
pid: 7430
hostname: iz8vb4vmi6s951ztsbrfisz
`

`
2018-07-25 11:39:39,891 ERROR 11832 nodejs.ServerNoResponseError: server 127.0.0.1:43205 no response in 25313ms, maybe the socket is end on the other side. (address: 127.0.0.1:43205)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/pay/node_modules/tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ServerNoResponseError'
pid: 11832
hostname: iz8vb4vmi6s951ztsbrfisz
`

是在一次降配重启后出现的这种情况，不确定是什么原因。停掉alinode后，两个文件中的报错都没有再出现，正在继续观察。
请问是什么原因造成的？该如何解决？谢谢~

**Comment by Cheese-Yu** [comment]
重新安装了所有依赖，目前agentx版本是v1.9.2，暂时没出现上面的情况了。十分感谢！

**Comment by hyj1991** [comment]
@Cheese-Yu 要把 agentx 升级到 v1.9.9 哦，这个版本才是最新没有问题的版本
