### ISSUE TITLE
按官网打包成tgz,本地正常访问远程数据库，部署后死活跑不起来

### ISSUE THREAD

**Issue by yaoxiaofdou** [eggjs/egg#2880]
> egg-bin dev

2018-08-07 22:54:56,482 INFO 12474 [master] node version v8.11.3
2018-08-07 22:54:56,484 INFO 12474 [master] egg version 2.9.1
2018-08-07 22:54:59,312 INFO 12474 [master] agent_worker#1:12480 started (2826ms)
egg deprecated [egg-security] `app.config.security.csrf.ignoreJSON` is not safe now, please disable it. node_modules/egg-core/lib/loader/egg_loader.js:299:29
[2018-08-07 22:55:01.636] [cfork:master:12474] worker:12490 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-08-07 22:55:01.637] [cfork:master:12474] don't fork, because worker:12490 will be kill soon
2018-08-07 22:55:01,637 INFO 12474 [master] app_worker#1:12490 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-08-07 22:55:02.032] [cfork:master:12474] worker:12490 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-08-07 22:55:02,034 ERROR 12474 nodejs.AppWorkerDiedError: [master] app_worker#1:12490 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:391:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 12474
hostname: nodetest

2018-08-07 22:55:02,035 ERROR 12474 [master] app_worker#1:12490 start fail, exiting with code:1
2018-08-07 22:55:02,035 ERROR 12474 [master] exit with code:1
2018-08-07 22:55:02,045 ERROR 12480 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
⚠️  Error: /www/wwwroot/showgirltime/node_modules/egg-bin/lib/start-cluster {"baseDir":"/www/wwwroot/showgirltime","framework":"/www/wwwroot/showgirltime/node_modules/egg","workers":1} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
2018-08-07 22:55:02,138 ERROR 12480 [agent_worker] exit with code:110
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! showgirltime@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the showgirltime@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-07T14_55_02_256Z-debug.log

------------------------------------------------------------------------------------------
线上的这个报错，按官网打包成tgz,本地正常访问远程数据库，部署后死活跑不起来～～～在线等

**Comment by popomore** [comment]
生产用 egg-script 部署

**Comment by yaoxiaofdou** [comment]
@popomore 有的，不过有问题没解决

Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...

**Comment by yaoxiaofdou** [comment]
@popomore 我去掉了--daemon ，启动后的报错是
[2018-08-08 08:57:15.900] [cfork:master:14445] worker:14461 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-08-08 08:57:15,901 ERROR 14445 nodejs.AppWorkerDiedError: [master] app_worker#1:14461 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:391:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 14445
hostname: nodetest

2018-08-08 08:57:15,904 ERROR 14445 [master] app_worker#1:14461 start fail, exiting with code:1
2018-08-08 08:57:15,904 ERROR 14445 [master] exit with code:1
(node:14435) UnhandledPromiseRejectionWarning: Error: spawn node /www/server/nvm/versions/node/v8.11.3/lib/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-showgirltime","framework":"/www/wwwroot/showgirltime/node_modules/egg","baseDir":"/www/wwwroot/showgirltime"} --title=egg-server-showgirltime fail, exit code: 1
    at ChildProcess.proc.once.code (/www/server/nvm/versions/node/v8.11.3/lib/node_modules/egg-scripts/node_modules/common-bin/lib/helper.js:90:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:14435) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-08-08 08:57:15,918 ERROR 14451 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-08-08 08:57:16,105 INFO 14451 [agent_worker] beforeExit success
2018-08-08 08:57:16,105 ERROR 14451 [agent_worker] exit with code:110

**Comment by atian25** [comment]
> UnhandledPromiseRejectionWarning: Error: spawn node 

看起来是 spawn node 就挂了，nvm 安装的 node 有问题？

**Comment by atian25** [comment]
先加上 `--daemon` 然后看下 **日志文件**，地址在控制台的前面有打印的， home 那边

非 `--daemon` 的我加个 catch https://github.com/eggjs/egg-scripts/pull/24/files

**Comment by yaoxiaofdou** [comment]
@atian25 你好😊，这次我执行了 egg-scripts start --daemon --title=egg-server-showgirltime --ignore-stderr

第一次看这个日志是提示我mongo连接需要加useNewUrlParser:true

修改之后日志内容是：
2018-08-08 10:39:00,007 ERROR 15690 nodejs.AppWorkerDiedError: [master] app_worker#1:15706 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:391:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/www/wwwroot/showgirltime/node_modules/egg-cluster/lib/master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 15690
hostname: nodetest

2018-08-08 10:39:00,008 ERROR 15690 [master] app_worker#1:15706 start fail, exiting with code:1
2018-08-08 10:39:00,008 ERROR 15690 [master] exit with code:1
2018-08-08 10:39:00,016 ERROR 15696 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-08-08 10:39:00,092 ERROR 15696 [agent_worker] exit with code:110

**Comment by atian25** [comment]
这日志看起来不全

**Comment by yaoxiaofdou** [comment]
我打开的是 master-stderr.log ,这次启动提示了

**Comment by yaoxiaofdou** [comment]
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,useNewUrlParser]

**Comment by atian25** [comment]
提交个可复现方式，还有 logs 都上传下吧。 这样的交流效率不高。

**Comment by yaoxiaofdou** [comment]
@atian25 👋刚刚创建了一个，我觉得可能是我的ecs的问题
这个是我提交的[地址](https://github.com/yaoxiaofdou/eggtest123.git)

**Comment by atian25** [comment]
没看出什么特殊之处，你本地 egg-scripts 能启动么

**Comment by yaoxiaofdou** [comment]
不能呢～～～一样的

[egg-scripts] Save log file to /Users/apple/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...

**Comment by yaoxiaofdou** [comment]
👌，谢谢你,我查到一片跟我类似的，我去尝试看看
[https://segmentfault.com/a/1190000013654491](https://segmentfault.com/a/1190000013654491)

**Comment by chinadbo** [comment]
npm start起不来
![image](https://user-images.githubusercontent.com/4602050/43829391-5cb7e9f0-9b31-11e8-98c1-b566407257b5.png)

**Comment by yaoxiaofdou** [comment]
@atian25 谢谢你🙏啊，现在可以了，～～～不过现在放外面运行太麻烦，我打算把它放进docker里去

**Comment by yaoxiaofdou** [comment]
是打包的时候egg-scripts没有进去，重新弄后nginx指向过去就可以访问了...
