### ISSUE TITLE
npm run debug 后无法实时 reload

### ISSUE THREAD

**Issue by scottming** [eggjs/egg#2895]
### 环境：

* 系统: macOS
* node: v10.0.0
* npm: 6.3.0
* egg 相关包：

```
├─ autod-egg@1.1.0
├─ egg-bin@4.6.3
├─ egg-bizerror@2.1.2
├─ egg-ci@1.8.0
├─ egg-cluster@1.16.0
├─ egg-cookies@2.2.2
├─ egg-core@4.6.0
├─ egg-cors@2.0.0
├─ egg-development@2.2.0
├─ egg-i18n@2.0.0
├─ egg-jsonp@2.0.0
├─ egg-logger@1.6.2
├─ egg-logrotator@3.0.3
├─ egg-mock@3.17.0
├─ egg-multipart@2.0.0
├─ egg-onerror@2.0.0
├─ egg-passport-local@1.2.1
├─ egg-passport@2.0.1
├─ egg-path-matching@1.0.1
├─ egg-schedule@3.3.0
├─ egg-scripts@2.6.0
├─ egg-security@2.2.2
├─ egg-sequelize@3.1.3
├─ egg-session@3.1.0
├─ egg-static@2.1.0
├─ egg-utils@2.4.0
├─ egg-view@2.1.0
├─ egg-watcher@3.0.0
├─ egg@2.6.1
├─ eslint-config-egg@6.0.0
```
### 具体问题：

```npm run debug``` 之后，修改里面的 controller 或 service 等文件，终端不会重新加载，让调试变得非常麻烦。这个问题是这两天才出现的，之前没有。

### 报错信息：

```
> Seahorse@1.0.0 debug /Users/Scott/Documents/WorkRepo/seahorse-service
> egg-bin debug

Debugger listening on ws://127.0.0.1:9229/f3a390b6-659c-4b40-8de3-196bd177425e
For help, see: https://nodejs.org/en/docs/inspector
2018-08-13 16:15:34,942 INFO 1987 [master] node version v10.0.0
2018-08-13 16:15:34,944 INFO 1987 [master] egg version 2.10.0
2018-08-13 16:15:34,944 INFO 1987 [master] start with options:
{
  "framework": "/Users/Scott/Documents/WorkRepo/seahorse-service/node_modules/egg",
  "baseDir": "/Users/Scott/Documents/WorkRepo/seahorse-service",
  "workers": 1,
  "plugins": null,
  "https": false,
  "isDebug": true
}
Debugger listening on ws://127.0.0.1:5800/719f3162-2fdb-4bd3-b5af-6896f31bbf7f
For help, see: https://nodejs.org/en/docs/inspector
2018-08-13 16:15:35,453 INFO 1988 [egg:logger] init all loggers with options: {"dir":"/Users/Scott/logs/Seahorse","encoding":"utf8","env":"pre","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"Seahorse-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"agent"}
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
2018-08-13 16:15:36,193 INFO 1988 [egg:core] dump config after load, 8ms
2018-08-13 16:15:36,228 INFO 1988 [egg-watcher:agent] watcher start success
2018-08-13 16:15:36,250 WARN 1988 [egg-watcher] defaultEventSource watcher will NOT take effect
2018-08-13 16:15:36,558 INFO 1988 [model] SHOW SERVER_VERSION (17ms)
2018-08-13 16:15:36,637 INFO 1988 [model] SELECT 1+1 AS result (8ms)
2018-08-13 16:15:36,641 INFO 1987 [master] agent_worker#1:1988 started (1694ms)
Debugger listening on ws://127.0.0.1:9230/61798a3f-5d6c-4632-a535-d30c2a6dc804
For help, see: https://nodejs.org/en/docs/inspector
2018-08-13 16:15:37,328 INFO 1989 [egg:logger] init all loggers with options: {"dir":"/Users/Scott/logs/Seahorse","encoding":"utf8","env":"pre","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"Seahorse-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"application"}
2018-08-13 16:15:37,378 INFO 1989 [egg-schedule]: register schedule /Users/Scott/Documents/WorkRepo/seahorse-service/node_modules/_egg-logrotator@3.0.3@egg-logrotator/app/schedule/clean_log.js
2018-08-13 16:15:37,378 INFO 1989 [egg-schedule]: register schedule /Users/Scott/Documents/WorkRepo/seahorse-service/node_modules/_egg-logrotator@3.0.3@egg-logrotator/app/schedule/rotate_by_file.js
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
2018-08-13 16:15:39,951 INFO 1989 [egg-static] starting static serve /public/ -> /Users/Scott/Documents/WorkRepo/seahorse-service/app/public
2018-08-13 16:15:39,955 INFO 1989 [egg-security] use methodnoallow middleware
2018-08-13 16:15:39,957 INFO 1989 [egg-security] use noopen middleware
2018-08-13 16:15:39,959 INFO 1989 [egg-security] use nosniff middleware
2018-08-13 16:15:39,961 INFO 1989 [egg-security] use xssProtection middleware
2018-08-13 16:15:39,963 INFO 1989 [egg-security] use xframe middleware
2018-08-13 16:15:39,964 INFO 1989 [egg-security] use dta middleware
2018-08-13 16:15:39,964 INFO 1989 [egg-security] compose 6 middlewares into one security middleware
2018-08-13 16:15:40,931 INFO 1989 [egg:core] dump config after load, 7ms
2018-08-13 16:15:40,997 INFO 1989 [egg-watcher:app] watcher start success
2018-08-13 16:15:41,173 INFO 1989 [model] SHOW SERVER_VERSION (55ms)
2018-08-13 16:15:41,525 INFO 1989 [model] SELECT 1+1 AS result (34ms)
2018-08-13 16:15:41,534 INFO 1987 [master] egg started on http://127.0.0.1:7001 (6590ms)
```

**Comment by scottming** [comment]
找到问题了，问题是我的 `.env` 把 EGG_SERVER_ENV 写死了。
