### ISSUE TITLE
根据eggjs官方文档到npx sequelize db:migrate 报错

### ISSUE THREAD

**Issue by cuteCloud** [eggjs/egg#2952]
npx sequelize db:migrate 向数据库升级表字段
npx: 1 安装成功，用时 3.618 秒
Path must be a string. Received undefined
C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_sequelize-cli@4.1.1@sequelize-cli\lib\sequelize

Sequelize CLI [Node: 8.11.2, CLI: 4.1.1, ORM: 4.38.0]

Loaded configuration file "database\config.json".
Using environment "development".
Fri, 31 Aug 2018 05:02:12 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\_sequelize@4.38.0@sequelize\lib\sequelize.js:242:13
crypto.js:99
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at sha1 (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\auth_41.js:29:8)
    at Object.token [as calculateToken] (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\auth_41.js:63:16)
    at new HandshakeResponse (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\packets\handshake_response.js:26:24)
    at ClientHandshake.sendCredentials (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\commands\client_handshake.js:51:27)
    at ClientHandshake.handshakeInit (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\commands\client_handshake.js:142:10)
    at ClientHandshake.Command.execute (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\commands\command.js:40:20)
    at Connection.handlePacket (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\connection.js:513:28)
    at PacketParser.onPacket (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\packet_parser.js:76:14)
    at Socket.<anonymous> (C:\webFrontend\oth\API.ONLY1314.CN\blog\node_modules\_mysql2@1.6.1@mysql2\lib\connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by dead-horse** [comment]
看起来是 auth 报错了，密码什么的没填错吧

**Comment by cuteCloud** [comment]
-----------------------------config.json开始---------------------------
{
  "development": {
    "username": "root",
    "password": 111111,
    "database": "egg-sequelize-doc-default",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "test": {
    "username": "root",
    "password": null,
    "database": "database_test",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "production": {
    "username": "root",
    "password": null,
    "database": "database_production",
    "host": "127.0.0.1",
    "dialect": "mysql"
  }
}
-----------------------------config.json结束---------------------------

-----------------------------config.deafult.js开始---------------------------
 config.sequelize = {
        dialect: 'mysql',
        host: 'localhost',
        port: 3306,
        database: 'egg-sequelize-doc-default',
    };
-----------------------------config.deafult.js结束---------------------------

**Comment by cuteCloud** [comment]
@dead-horse 密码应该是没错 根据提示网上找了一个上午了 都没有解决这个问题 步骤完全是按照官方的https://eggjs.org/zh-cn/tutorials/sequelize.html去走的

**Comment by dead-horse** [comment]
password: '111111' 试试呢

**Comment by cuteCloud** [comment]
@dead-horse 不行，加引号后报语法错误ERROR: Error reading "database\config.json". Error: SyntaxError: C:\webFrontend\oth\API.ONLY1314.CN\blog\database\config.json: Unexpected token ' in JSON at position 61

**Comment by dead-horse** [comment]
大哥，“111111”

**Comment by cuteCloud** [comment]
@dead-horse  感谢老哥，解决了 还真是这个密码的问题，之前我猜测可能是密码 我就换了一个错误密码 但是他直接报access denied ，我就以为不是密码的问题 谢谢  单引号尽然也不行 看来是严格的json字符串哇
