### ISSUE TITLE
egg-redis 集群连接问题以及配置优化建议

### ISSUE THREAD

**Issue by seekcx** [eggjs/egg#2983]
* **Node Version**: 8.11.2
* **Egg Version**: 2.10.0
* **Plugin Name**: egg-redis
* **Plugin Version**: 2.0.0
* **Platform**: macos

https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L19-L20
第一个问题，这个验证过于绝对，集群链接时，密码是通过 redisOptions 配置的。现在不配置密码参数插件直接报错了。

```js
exports.redis = {
   client: {
     cluster: true,
     nodes: [{
       host: '127.0.0.1',
       port: '6379',
     }],
     redisOptions: {
        password: 'secret',
     }
   },
};
```

https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L24
第二个问题，这里直接使用整个 client 的配置作为第二个参数传递给了 Redis.Cluster，抛出了 

Failed to refresh slots cache. 错误
```bash
[ioredis] Unhandled error event: Error: Failed to refresh slots cache.
    at tryNode (/Users/abel/Desktop/work/smart-investment/node_modules/ioredis/lib/cluster/index.js:375:19)
    at /Users/abel/Desktop/work/smart-investment/node_modules/ioredis/lib/cluster/index.js:387:9
    at /Users/abel/Desktop/work/smart-investment/node_modules/ioredis/lib/cluster/index.js:591:14
    at run (/Users/abel/Desktop/work/smart-investment/node_modules/ioredis/lib/utils/index.js:153:16)
    at tryCatcher (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/abel/Desktop/work/smart-investment/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

修改源码固定传递 
```js
redisOptions: {
    password: 'secret',
}
```
之后没有此问题。

猜测是否是参数名发生了冲突？
建议增加一个单独的参数来配置。

**Comment by seekcx** [comment]
密码写错了。。打扰了。
