### ISSUE TITLE
DNSCacheHttpClient 抛出异常 `nodejs.TypeError: this.app.runInBackground is not a function`

### ISSUE THREAD

**Issue by ImHype** [eggjs/egg#3001]
* **Node Version**:
* **Egg Version**:
v2.11.0

* **Plugin Name**:
egg

* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
开启 `httpclient.enableDNSCache` ， agent 抛出如下异常。看了下 agent 对象确实没有 `runInBackground` 方法。

```
2018-09-13 15:24:03,623 - xxxx - xxxx - ERROR [88985] nodejs.TypeError: this.app.runInBackground is not a function
    at DNSCacheHttpClient.[DNSCacheHttpClient#dnslookup] (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/egg/lib/core/dnscache_httpclient.js:92:18)
    at /home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/egg/lib/core/dnscache_httpclient.js:42:43
    at DNSCacheHttpClient.request (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/egg/lib/core/dnscache_httpclient.js:44:7)
    at DNSCacheHttpClient.curl (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/egg/lib/core/dnscache_httpclient.js:48:17)
    at Client.request (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/@kapp/disconf/lib/core/client.js:31:32)
    at Promise.all.groups.map (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/@kapp/disconf/lib/core/index.js:105:52)
    at Array.map (<anonymous>)
    at Disconf.getConfig (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/@kapp/disconf/lib/core/index.js:103:20)
    at onChange (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/@kapp/disconf/agent.js:24:40)
    at Timeout.setInterval [as _onTimeout] (/home/appops/kapp-playground/kapp-playground-performance/default/approot/node_modules/@kapp/disconf/agent.js:37:27)

pid: 88985
hostname: kaola-perfjd-0260
```

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```
