### ISSUE TITLE
woker异常错误，一直在channel closed，无法正常请求

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#3008]
* **Node Version**:v8.11.3
* **Egg Version**:2.6.0
* **Plugin Name**:egg-socket
* **Plugin Version**:4.0.7
* **Platform**:
* **Mini Showcase Repository**:

```
// 这是我自己代码的错误
[Sat Sep 15 2018 09:20:55 GMT+0800 (CST)] [graceful:worker:15105:uncaughtException] throw error 1 times
ReferenceError: user is not defined (uncaughtException throw 1 times on pid:15104)
    at /home/payTest/app/io/controller/listen.js:865:32
    at transporter.send.args (/home/payTest/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at SMTPConnection.connection.once.err (/home/payTest/node_modules/nodemailer/lib/smtp-transport/index.js:174:24)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at SMTPConnection.emit (events.js:211:7)
    at SMTPConnection._onError (/home/payTest/node_modules/nodemailer/lib/smtp-connection/index.js:596:14)
    at TLSSocket._socket.on.err (/home/payTest/node_modules/nodemailer/lib/smtp-connection/index.js:265:18)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
master-stderr.log 
```
[Sat Sep 15 2018 09:20:55 GMT+0800 (CST)] [graceful:worker:15105] will exit after 30000ms
[Sat Sep 15 2018 09:20:55 GMT+0800 (CST)] [graceful:worker:15105] close server#0, _connections: 0
[Sat Sep 15 2018 09:20:55 GMT+0800 (CST)] [graceful:worker:15105] close 1 servers!
[Sat Sep 15 2018 09:20:55 GMT+0800 (CST)] [graceful:worker:15105] worker disconnect!
[2018-09-15 09:20:55.710] [cfork:master:15073] worker:15105 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-09-15 09:20:55.715] [cfork:master:15073] new worker:10885 fork (state: none)
[2018-09-15 09:21:01.195] [cfork:master:15073] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Worker.send (internal/cluster/worker.js:54:28)
    at Server.require.createServer.connection (/home/payTest/node_modules/egg-cluster/lib/master.js:161:16)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1565:8)
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Worker.send (internal/cluster/worker.js:54:28)
    at Server.require.createServer.connection (/home/payTest/node_modules/egg-cluster/lib/master.js:161:16)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1565:8)
(total 2 disconnect, 0 unexpected exit)
```
日志里一直在循环channel closed。npm stop 也没有完全杀死进程，无法重新启动项目

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

试下上面的方式重新安装下依赖，然后看能否提供下最小可复现的仓库

**Comment by Cheese-Yu** [comment]
重启服务器后，再启动是正常的。
出错的代码是邮件发送异常的处理里面的报错
```
mailTransport.sendMail(options, function (error, response) {
     if (error) {
         ctx.logger.error(user + '发送邮件失败:' + error)  // user is not defined
     }
});
```
出错了两次，第一次Worker 进程关闭正常， 第二次就一直在关闭，请求进不来

**Comment by Cheese-Yu** [comment]
第一次错误是2018 08:27:34 看alinode数据，第一次错误开始libuv从12涨到400多就一直没有下去。感觉第一次错误进程也没处理好。

**Comment by popomore** [comment]
callback 的方式最好错误处理，你这个是触发了未捕获异常，然后进程重启了。
