### ISSUE TITLE
egg服务偶尔出现卡死，过一段时间又自己恢复正常

### ISSUE THREAD

**Issue by bobo717** [eggjs/egg#3015]
Node Version: v8.11.1
Egg Version:v2.11
Plugin Name:egg-mysql、egg-alinode
Plugin Version:
Platform:

错误日志如下：

2018-09-18 13:12:15,943 ERROR 28260 nodejs.ServerNoResponseError: server 127.0.0.1:39433 no response in 38304ms, maybe the socket is end on the other side. (address: 127.0.0.1:39433)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ServerNoResponseError'
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:12:15,943 ERROR 10915 nodejs.ServerNoResponseError: server 127.0.0.1:39433 no response in 43411ms, maybe the socket is end on the other side. (address: 127.0.0.1:39433)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ServerNoResponseError'
pid: 10915
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:12:18,945 ERROR 10896 nodejs.ClusterClientNoResponseError: client no response in 84750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 10896
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:12:16,035 ERROR 10924 nodejs.ServerNoResponseError: server 127.0.0.1:39433 no response in 24596ms, maybe the socket is end on the other side. (address: 127.0.0.1:39433)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/tcp-base/lib/base.js:427:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ServerNoResponseError'
pid: 10924
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:13:57,037 ERROR 28260 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:39433
    at Function.waitFor (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/server.js:238:15)
    at <anonymous>

pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:13:57,037 ERROR 10915 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:39433
    at Function.waitFor (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/server.js:238:15)
    at <anonymous>

pid: 10915
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:13:57,037 ERROR 10924 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:39433
    at Function.waitFor (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/server.js:238:15)
    at <anonymous>

pid: 10924
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:06,940 ERROR 10896 nodejs.ClusterClientNoResponseError: client no response in 109589ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 10896
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:09,627 ERROR 10896 nodejs.ClusterClientNoResponseError: client no response in 95897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 10896
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:13,930 ERROR 10896 nodejs.ClusterClientNoResponseError: client no response in 95585ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/home/node/XXXXXXXX-web/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ClusterClientNoResponseError'
pid: 10896
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:27,526 ERROR 10924 [-/undefined/-/203487ms GET /question/203471471941652480/answer/203525174954430464] nodejs.ResponseTimeoutError: Response timeout for 10000ms, POST https://www.XXXXXXXX.com/res/no040 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2453,"createSocketErrorCount":0,"closeSocketCount":2453,"errorSocketCount":0,"timeoutSocketCount":2409,"requestCount":5024,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/home/node/XXXXXXXX-web/node_modules/urllib/lib/urllib.js:791:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ResponseTimeoutError'
requestId: 5070
data: undefined
path: '/res/no040'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 180086, keepAliveSocket: false, data: undefined, requestUrls: [ 'https://www.XXXXXXXX.com/res/no040' ], timing: null, remoteAddress: 'XXX.XXX.XXX.XXX', remotePort: 443 }
headerSent: true
pid: 10924
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:45,634 ERROR 10915 [-/undefined/-/173305ms GET /] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/user/no004?token=6d3d1153c63bpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2516,"createSocketErrorCount":0,"closeSocketCount":2516,"errorSocketCount":0,"timeoutSocketCount":2476,"requestCount":5009,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
headerSent: true
pid: 10915
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:14:45,649 ERROR 28260 [-/undefined/-/175401ms GET /] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/user/no004?token=6d3d11a3f53c63bpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1181,"createSocketErrorCount":0,"closeSocketCount":1181,"errorSocketCount":0,"timeoutSocketCount":1180,"requestCount":1954,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
headerSent: true
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:15:14,636 ERROR 28260 [-/113.116.77.37/-/47105ms GET /] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/user/no004?token=49d5462687b1bc7dcpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1182,"createSocketErrorCount":0,"closeSocketCount":1182,"errorSocketCount":0,"timeoutSocketCount":1180,"requestCount":1954,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>

pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:15:14,636 ERROR 10915 [-/113.116.77.37/-/28991ms GET /] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/user/no004?token=6d3d1138263bpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2517,"createSocketErrorCount":0,"closeSocketCount":2517,"errorSocketCount":0,"timeoutSocketCount":2476,"requestCount":5009,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>

pid: 10915
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:20:44,228 ERROR 10924 [-/undefined/-/414011ms GET /user/profile/181776014702153728] nodejs.ResponseTimeoutError: Response timeout for 10000ms, POST https://www.XXXXXXXX.com/res/no031 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2456,"createSocketErrorCount":0,"closeSocketCount":2454,"errorSocketCount":0,"timeoutSocketCount":2409,"requestCount":5024,"freeSockets":{},"sockets":{"www.XXXXXXXX.com:443:::::::::":2},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/home/node/XXXXXXXX-web/node_modules/urllib/lib/urllib.js:791:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ResponseTimeoutError'
requestId: 5071
data: undefined
path: '/res/no031'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 325185, keepAliveSocket: false, data: undefined, requestUrls: [ 'https://www.XXXXXXXX.com/res/no031' ], timing: null, remoteAddress: 'XXX.XXX.XXX.XXX', remotePort: 443 }
headerSent: true
pid: 10924
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:21:06,336 ERROR 28260 [-/undefined/-/245298ms GET /user/profile/189032006410178560] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/system/no087 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1185,"createSocketErrorCount":0,"closeSocketCount":1183,"errorSocketCount":0,"timeoutSocketCount":1183,"requestCount":1954,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
headerSent: true
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:21:54,443 ERROR 10915 [-/undefined/-/265909ms GET /question/203879534297223168] nodejs.ResponseTimeoutError: Response timeout for 10000ms, POST https://www.XXXXXXXX.com/res/no035 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2518,"createSocketErrorCount":0,"closeSocketCount":2518,"errorSocketCount":0,"timeoutSocketCount":2476,"requestCount":5009,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/home/node/XXXXXXXX-web/node_modules/urllib/lib/urllib.js:791:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ResponseTimeoutError'
requestId: 5051
data: undefined
path: '/res/no035'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 170799, keepAliveSocket: false, data: undefined, requestUrls: [ 'https://www.XXXXXXXX.com/res/no035' ], timing: null, remoteAddress: 'XXX.XXX.XXX.XXX', remotePort: 443 }
headerSent: true
pid: 10915
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:23:43,039 ERROR 28260 [-/undefined/-/56002ms HEAD /search/www.daixiefabiao.net] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/system/no087 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1189,"createSocketErrorCount":0,"closeSocketCount":1186,"errorSocketCount":0,"timeoutSocketCount":1183,"requestCount":1954,"freeSockets":{},"sockets":{"www.XXXXXXXX.com:443:::::::::":3},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
headerSent: true
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:24:28,435 ERROR 28260 [-/undefined/-/100615ms GET /] nodejs.Error: ResponseTimeoutError: Response timeout for 10000ms, GET https://www.XXXXXXXX.com/user/no004?token=49d5422c66a1bc7dcpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1189,"createSocketErrorCount":0,"closeSocketCount":1188,"errorSocketCount":0,"timeoutSocketCount":1183,"requestCount":1954,"freeSockets":{},"sockets":{"www.XXXXXXXX.com:443:::::::::":1},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
headerSent: true
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:29:06,730 ERROR 28260 [-/undefined/-/255398ms GET /] nodejs.Error: ResponseError: socket hang up (req "error"), GET https://www.XXXXXXXX.com/user/no004?token=49d542bc7dcpc -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1190,"createSocketErrorCount":0,"closeSocketCount":1189,"errorSocketCount":0,"timeoutSocketCount":1183,"requestCount":1954,"freeSockets":{},"sockets":{"www.XXXXXXXX.com:443:::::::::":1},"requests":{}})
headers: {}
headers: {}
    at ctx.curl.then.catch.err (/home/node/XXXXXXXX-web/app/service/utils.js:77:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headerSent: true
pid: 28260
hostname: XXXXXXXXXXXXXXX

2018-09-18 13:29:06,726 ERROR 10924 [-/undefined/-/483984ms GET /question/221237763431862272/answer/221308330746974208] nodejs.ResponseTimeoutError: Response timeout for 10000ms, POST https://www.XXXXXXXX.com/res/no040 -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2463,"createSocketErrorCount":0,"closeSocketCount":2457,"errorSocketCount":0,"timeoutSocketCount":2410,"requestCount":5024,"freeSockets":{},"sockets":{"www.XXXXXXXX.com:443:::::::::":6},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/home/node/XXXXXXXX-web/node_modules/urllib/lib/urllib.js:791:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: 'ResponseTimeoutError'
requestId: 5074
data: undefined
path: '/res/no040'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 442489, keepAliveSocket: false, data: undefined, requestUrls: [ 'https://www.XXXXXXXX.com/res/no040' ], timing: null, remoteAddress: 'XXX.XXX.XXX.XXX', remotePort: 443 }
headerSent: true
pid: 10924
hostname: XXXXXXXXXXXXXXX

**Comment by atian25** [comment]
接入 alinode 看看是不是有做了什么 CPU 占用很高的操作，如用了 readFileSync 之类的 API

**Comment by bobo717** [comment]
用jmeter等压测发起高并发也会令egg服务出现类似的卡死

**Comment by atian25** [comment]
所以你要用 alinode 查啊，看看你业务哪些代码写的有问题

**Comment by okoala** [comment]
这个不就是响应超时吗

**Comment by bobo717** [comment]
占用CPU最高的进程为『无命令信息』，请问如何进一步跟踪？谢谢

**Comment by atian25** [comment]
alinode

**Comment by dead-horse** [comment]
看起来是后端响应超时
