### ISSUE TITLE
访问微信登录接口必定报错：nodejs.ClusterClientNoResponseError

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#3028]
* **Node Version**: 8.11.3
* **Egg Version**: 2.10.0
* **Plugin Name**: -
* **Plugin Version**: -
* **Platform**: macOS 10.13.6
* **Mini Showcase Repository**:

```bash
2018-09-20 22:36:17,878 INFO 11795 [-/127.0.0.1/-/0ms GET /passport/weixin?code=061wnHAu1ipVyb0OoYxu1SlzAu1wnHAl&state=http%3A%2F%2Fdushejitang.baishew.com%3A7701%2Fe07931e47c8acdc8e4b5541ec85cafef%3Fts%3D1537454159209] userAuth get sessionToken:  undefined
// 开始请求微信登录接口
wx https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxx&secret=xxx&code=xxx&grant_type=authorization_code
// 超时。此时页面一直在 pendding
2018-09-20 22:37:19,208 ERROR 11221 nodejs.ClusterClientNoResponseError: client no response in 63349ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liangjianzhong/workspace/projects/dushejitang/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 11221
hostname: LiangJianzhongdeMacBook-Pro.local
// 这里应该有打印其他 debug 信息的。
// 这里是黄色的提示，无端端又弹出来的日志信息。 此时页面自动重定向。
2018-09-20 22:37:47,875 WARN 11795 [TCPBase] socket is closed by other side while there were still unhandled data in the socket buffer
2018-09-20 22:37:47,876 WARN 11795 [ClusterClient:Watcher] follower closed, and try to init it again
2018-09-20 22:37:47,891 INFO 11795 [-/127.0.0.1/-/1ms GET /e07931e47c8acdc8e4b5541ec85cafef?ts=1537454159209] userAuth get sessionToken:  ttt
2018-09-20 22:37:50,439 INFO 11795 [-/127.0.0.1/-/1ms GET /e07931e47c8acdc8e4b5541ec85cafef/passport/isLogin] userAuth get sessionToken:  ttt
2018-09-20 22:37:52,926 INFO 11795 [-/127.0.0.1/-/0ms GET /e07931e47c8acdc8e4b5541ec85cafef/overview] userAuth get sessionToken:  ttt
```

![image](https://user-images.githubusercontent.com/7995232/45826438-11836c80-bd27-11e8-8b60-45c35703cc1d.png)

第一个 console 对应 红色报错前的打印信息。

然后实际执行了后面的却没有打印出信息，但是微信登录时成功的。
![image](https://user-images.githubusercontent.com/7995232/45826578-53acae00-bd27-11e8-9d7c-2a3faa1eaf65.png)

**Comment by thonatos** [comment]
- https://issue.eggjs.app/

**Comment by JZLeung** [comment]
无法复现。
