### ISSUE TITLE
cluster-client 的一些问题

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#304]
- 模块还是用事件吧，我搜了下只有两处在使用
    egg 也需要改
https://github.com/eggjs/egg/blob/0e0bef541b8c7f37893afd297e81455a13854249/lib/egg.js#L323
- app.cluster 可以统一处理错误
- 单测没有关闭连接

**Comment by popomore** [comment]
cc @gxcsoccer

**Comment by popomore** [comment]
还有 app.cluster 可以统一处理错误

**Comment by shaoshuai0102** [comment]
> 还有 app.cluster 可以统一处理错误

如果还有其他的自定义事件，cluster-client 做不来，而且职责不清了。

**Comment by popomore** [comment]
就处理错误吧，错误是肯定要打 logger 的

**Comment by popomore** [comment]
cluster-client 未 close 会有这样的错

```
Error: /Users/popomore/code/github.com/eggjs/egg-mock/test/fixtures/agent/logs/demo/egg-agent.log log stream had been closed
    at FileTransport.log (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.5.0@egg-logger/lib/transports/file.js:57:19)
    at EggLogger.log (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.5.0@egg-logger/lib/logger.js:73:19)
    at EggLogger.Logger.(anonymous function) [as info] (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.5.0@egg-logger/lib/logger.js:141:10)
    at Leader._handleRequest (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.0.2@cluster-client/lib/leader.js:268:21)
    at Connection.conn.on (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.0.2@cluster-client/lib/leader.js:215:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at process.nextTick (/Users/popomore/code/github.com/eggjs/egg-mock/node_modules/.1.0.2@cluster-client/lib/connection.js:148:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by popomore** [comment]
cc @gxcsoccer

**Comment by popomore** [comment]
要关闭 server https://github.com/node-modules/cluster-client/blob/master/lib/server.js

和每个 client

**Comment by shaoshuai0102** [comment]
clustclient close https://github.com/node-modules/cluster-client/pull/7 @popomore

**Comment by popomore** [comment]
其他两个问题再讨论下？

**Comment by gxcsoccer** [comment]
@popomore  下面两个？

> - 模块还是用事件吧，我搜了下只有两处在使用
egg 也需要改
https://github.com/eggjs/egg/blob/0e0bef541b8c7f37893afd297e81455a13854249/lib/egg.js#L323
> - app.cluster 可以统一处理错误

**Comment by popomore** [comment]
对的
zōng yǔ <notifications@github.com>于2017年2月8日 周三01:30写道：

**Comment by popomore** [comment]
这个关了
