### ISSUE TITLE
npm run test-local error

### ISSUE THREAD

**Issue by smallos** [eggjs/egg#3044]
* **Node Version**: v8.9.0
* **Egg Version**: egg@2.11.2   egg-core@4.10.2

现象：编写单元测试，后来发现项目中就无法一致提示这个错误，然后把用demo中的项目复制过去也是同样的错误。看了下是koa-proxy的错误。不过项目中与demo对比时，发现demo没有依赖这个项目。但是目前egg／egg-core版本都是相同的，原来项目中为egg 1.xx.xx

`  1) "before all" hook

  0 passing (859ms)
  1 failing

  1) "before all" hook:
     Error: miss options
      at module.exports (node_modules/koa-proxy/index.js:12:11)
      at proxyConfs.forEach.config (node_modules/egg-proxy/app.js:12:13)
      at Array.forEach (<anonymous>)
      at module.exports.app (node_modules/egg-proxy/app.js:11:14)
      at Hook.configDidLoad (node_modules/egg-core/lib/lifecycle.js:91:9)
      at Lifecycle.triggerConfigDidLoad (node_modules/egg-core/lib/lifecycle.js:133:14)
      at AppWorkerLoader.loadCustomApp (node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
      at AppWorkerLoader.load (node_modules/egg/lib/loader/app_worker_loader.js:34:10)
      at new Application (node_modules/egg/lib/application.js:65:19)
      at new MessengerApplication (node_modules/egg-mock/lib/app.js:241:7)
      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:69:29)
      at EventEmitter.next (<anonymous>)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
      [use `--full-trace` to display the full stack trace]

`

**Comment by atian25** [comment]
egg-proxy 肯定是你自己引入的，检查自己代码

**Comment by smallos** [comment]
原因找到了，因为项目中有不同环境的配置，当本地测试时候没有指定环境配置，config.default.js，上面配置不全。
启动脚本增加环境变量后配置可以获取了。
 "test-local": "EGG_SERVER_ENV=test egg-bin test ",

**Comment by atian25** [comment]
`EGG_SERVER_ENV=test` 这个不应该配置，单元测试其实是 `EGG_SERVER_ENV=unittest`

在 egg-bin 里面已经配置了，对应的配置文件是 config.unittest.js

**Comment by smallos** [comment]
get，谢谢天哥～～
