### ISSUE TITLE
希望提供类似 pm2 ls、pm2 logs 命令一样用于查看应用列表和运行状况的命令工具

### ISSUE THREAD

**Issue by charleslo1** [eggjs/egg#3047]
pm2 可通过ls、logs 命令能直观的列出应用列表以及监控应用实时运行状况，而 egg 里面的 egg-scripts 只能 start、stop，希望官方能提供一个类似 egg-scripts list、egg-scripts logs 的命令以方便开发者更直观的应用调试和维护

``` sh
root@localhost:/var/www/default# pm2 ls
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ koa      │ 0  │ fork │ 4789 │ online │ 6       │ 0s     │ 0%  │ 33.5 MB   │ root │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
root@localhost:/var/www/default# pm2 logs 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/add-out-0.log last 15 lines:
0|koa      |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|koa      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|koa      |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|koa      |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|koa      |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
0|koa      |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
0|koa      |   code: 'ER_BAD_FIELD_ERROR',
0|koa      |   errno: 1054,
0|koa      |   sqlMessage: 'Unknown column \'uuid\' in \'field list\'',
0|koa      |   sqlState: '42S22',
0|koa      |   index: 0,
```

**Comment by atian25** [comment]
- log 直接文件就有了，自己 tail
- list 的分析没啥意义，直接 alinode 就好了。
- 欢迎继承扩展 egg-scripts 贡献给社区

**Comment by buzai** [comment]
准备写一个哈

**Comment by buzai** [comment]
@atian25 写了不过直接写在那个 egg-scripts 里了。。改了改pm2的code

**Comment by tkvern** [comment]
In fact, You can also watch this within Alicloud console.
