### ISSUE TITLE
egg-mysql模块出错

### ISSUE THREAD

**Issue by love-ya** [eggjs/egg#308]
* **Node Version**: 6.9
* **Egg Version**: 0.9.0
* **Plugin Name**: egg-mysql
* **Plugin Version**: 1.0.1
* **Platform**: win7

按照步骤配置完egg-mysql后启动项目出现这样的问题，不太明白具体原因
```
2017-02-02 00:03:59,782 ERROR 7164 nodejs.TypeError: app.instrument is not a fun
ction
    at RDSClient.query (C:\Users\Administrator\Desktop\equipment\node_modules\eg
g-mysql\lib\mysql.js:25:21)
    at next (native)
    at onFulfilled (C:\Users\Administrator\Desktop\equipment\node_modules\co\ind
ex.js:65:19)
    at C:\Users\Administrator\Desktop\equipment\node_modules\co\index.js:54:5
    at co (C:\Users\Administrator\Desktop\equipment\node_modules\co\index.js:50:
10)
    at toPromise (C:\Users\Administrator\Desktop\equipment\node_modules\co\index
.js:118:63)
    at next (C:\Users\Administrator\Desktop\equipment\node_modules\co\index.js:9
9:29)
    at onFulfilled (C:\Users\Administrator\Desktop\equipment\node_modules\co\ind
ex.js:69:7)
    at C:\Users\Administrator\Desktop\equipment\node_modules\co\index.js:54:5
    at co (C:\Users\Administrator\Desktop\equipment\node_modules\co\index.js:50:
10)
```

**Comment by atian25** [comment]
最近的一个 break  change 移除了这个函数，看来有遗漏，@popomore

**Comment by popomore** [comment]
MySQL 要删了
TZ | 天猪 <notifications@github.com>于2017年2月2日 周四00:41写道：

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mysql/pull/4

**Comment by jtyjty99999** [comment]
+1

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mysql/pull/5

这个发版本没?

**Comment by popomore** [comment]
没，你发一个？
TZ | 天猪 <notifications@github.com>于2017年2月4日 周六10:11写道：

**Comment by atian25** [comment]
我没权限

**Comment by jtyjty99999** [comment]
@love-ya 再试试

**Comment by atian25** [comment]
1.1.0

**Comment by love-ya** [comment]
可以了@jtyjty99999，不过@popomore说 MySQL 要删了是指egg-mysql这个插件要关掉了吗？

**Comment by atian25** [comment]
他的意思是 egg-mysql 里面要删掉 `app.instrument`

**Comment by jtyjty99999** [comment]
@love-ya 对你透明，跟以前一样使用即可

**Comment by yekexuan** [comment]
https://eggjs.org/zh-cn/tutorials/mysql.html 文档中的示例配置要改一下。。还是装的老版本

```
// package.json
{
  "dependencies": {
    "egg-mysql": "^1.0.1"
  }
}
```

**Comment by popomore** [comment]
`^` 会装新的

**Comment by yekexuan** [comment]
新的版本是2.0了。。 我刚刚按照文档装的还是老的  ^1 不会装2.0的

**Comment by popomore** [comment]
@yekexuan 可以提个 PR

**Comment by atian25** [comment]
所以这里还是用 npm install --save 好点，而不是 pkg
