### ISSUE TITLE
eggjs启动报错，求大神帮看看！

### ISSUE THREAD

**Issue by Tencent-Luis** [eggjs/egg#3131]
master-stderr.log报错信息如下：
`
2018-10-29 16:00:27,507 ERROR 29375 nodejs.AppWorkerDiedError: [master] app_worker#2:29398 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: ["1","3","4"]
    at Master.onAppExit (/data/home/user00/playcrab/web/production/flow/node_modules/egg-cluster/lib/master.js:388:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/data/home/user00/playcrab/web/production/flow/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/data/home/user00/playcrab/web/production/flow/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/data/home/user00/playcrab/web/production/flow/node_modules/egg-cluster/lib/master.js:265:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:186:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 29375
hostname: iZ23v35ytd4Z

2018-10-29 16:00:27,509 ERROR 29375 [master] app_worker#2:29398 start fail, exiting with code:1
2018-10-29 16:00:27,511 ERROR 29375 [master] exit with code:1
2018-10-29 16:00:27,521 ERROR 29383 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2018-10-29 16:00:27,530 ERROR 29383 [agent_worker] exit with code:110
2018-10-29 16:00:27,791 ERROR 29393 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
2018-10-29 16:00:27,796 ERROR 29409 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
2018-10-29 16:00:27,796 ERROR 29400 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
`

**Comment by Tencent-Luis** [comment]
有人回答否？

**Comment by popomore** [comment]
错误在上面

**Comment by atian25** [comment]
错误信息不全，看下 common-error

**Comment by Tencent-Luis** [comment]
已自行解决，感谢！

**Comment by mragon1997** [comment]
> 已自行解决，感谢！

怎么解决的？
