### ISSUE TITLE
egg-static 视频播放报错

### ISSUE THREAD

**Issue by lampofaladdin** [eggjs/egg#3143]
* **Node Version**:8.7.0
* **Egg Version**:2.2.1
* **Plugin Name**:egg-static
* **Plugin Version**:内置版本
* **Platform**:windows
* **Mini Showcase Repository**:无

在使用egg内置的egg-static插件做静态资源服务的时候，客户端请求mp4视频文件，egg框架会报错，但浏览器没有报错，视频还是正常播放。

主要报错日志如下：
`2018-10-31 18:19:47,265 ERROR 3560 [-/undefined/-/80ms GET /public/videos/kol_miaopai_2.mp4] nodejs.ECONNABORTEDError: write ECONNABORTED
    at _errnoException (util.js:1021:11)
    at Socket._writeGeneric (net.js:760:25)
    at Socket._write (net.js:779:8)
    at doWrite (_stream_writable.js:387:12)
    at clearBuffer (_stream_writable.js:514:7)
    at Socket.Writable.uncork (_stream_writable.js:313:7)
    at connectionCorkNT (_http_outgoing.js:680:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: "ECONNABORTED"
errno: "ECONNABORTED"
syscall: "write"
headerSent: true
name: "ECONNABORTEDError"
pid: 3560
hostname: aladdin

2018-10-31 18:20:21,626 ERROR 3560 [-/undefined/-/39ms GET /public/videos/kol_miaopai_1.mp4] nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at TCP.onread (net.js:608:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
headerSent: true
name: "ECONNRESETError"
pid: 3560
hostname: aladdin`

查找问题的时候看到有人说可以做异常捕获，在官方文档里面没有找到这类异常捕获的方式，请问这种报错应该如何处理？

多方查找资源没有找到解决方式，希望各位大佬可以指点迷津。
感谢！

**Comment by atian25** [comment]
> ECONNABORTED
> 该错误被描述为 “software caused connection abort”，即“软件引起的连接中止”。原因在于当服务和客户进程在完成用于 TCP 连接的“三次握手”后，客户 TCP 却发送了一个 RST （复位）分节，在服务进程看来，就在该连接已由 TCP 排队，等着服务进程调用 accept 的时候 RST 却到达了。POSIX 规定此时的 errno 值必须 ECONNABORTED。源自 Berkeley 的实现完全在内核中处理中止的连接，服务进程将永远不知道该中止的发生。服务器进程一般可以忽略该错误，直接再次调用 accept 。

视频资源最好不要放在 public 里面，应该丢 CDN。

**Comment by lampofaladdin** [comment]
> > ECONNABORTED
> > 该错误被描述为 “software caused connection abort”，即“软件引起的连接中止”。原因在于当服务和客户进程在完成用于 TCP 连接的“三次握手”后，客户 TCP 却发送了一个 RST （复位）分节，在服务进程看来，就在该连接已由 TCP 排队，等着服务进程调用 accept 的时候 RST 却到达了。POSIX 规定此时的 errno 值必须 ECONNABORTED。源自 Berkeley 的实现完全在内核中处理中止的连接，服务进程将永远不知道该中止的发生。服务器进程一般可以忽略该错误，直接再次调用 accept 。
> 
> 视频资源最好不要放在 public 里面，应该丢 CDN。

学习了，这就把视频放到CDN上，感谢大佬的回复。
