### ISSUE TITLE
hackernews-datahub breaks

### ISSUE THREAD

**Issue by johntom** [eggjs/egg#3158]
* **Node Version**:
9.11.2
* **Egg Version**:
2.12.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
win10
* **Mini Showcase Repository**:
hackernews-datahub

I'm just testing eggis for the first time following documnetaion and all was going good until

PS D:\KOA\Egg\examples\hackernews-datahub>
PS D:\KOA\Egg\examples\hackernews-datahub> npm run dev
> hackernews-datahub@1.0.0 dev D:\KOA\Egg\examples\hackernews-datahub
> egg-bin dev

2018-11-04 18:42:50,910 INFO 16004 [master] node version v9.11.2
2018-11-04 18:42:50,913 INFO 16004 [master] egg version 2.12.0
2018-11-04 18:42:52,569 INFO 16004 [master] agent_worker#1:6876 started (1595ms)
D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg\lib\application.js:69
      throw e;
      ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at module.exports.app (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-datahub\app.js:17:31)
    at Hook.configDidLoad (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-core\lib\lifecycle.js:93:9)
    at Lifecycle.triggerConfigDidLoad (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-core\lib\lifecycle.js:144:14)
    at Lifecycle.triggerConfigWillLoad (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-core\lib\lifecycle.js:138:10)
    at AppWorkerLoader.loadCustomApp (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-core\lib\loader\mixin\custom.js:37:20)
    at AppWorkerLoader.load (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg\lib\loader\app_worker_loader.js:33:10)
    at new Application (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg\lib\application.js:65:19)
    at Object.<anonymous> (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-cluster\lib\app_worker.js:19:13)
[2018-11-04 18:42:54.390] [cfork:master:16004] worker:18532 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-11-04 18:42:54.394] [cfork:master:16004] don't fork, because worker:18532 will be kill soon
2018-11-04 18:42:54,395 INFO 16004 [master] app_worker#1:18532 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-11-04 18:42:54.397] [cfork:master:16004] worker:18532 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-11-04 18:42:54,399 ERROR 16004 nodejs.AppWorkerDiedError: [master] app_worker#1:18532 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-cluster\lib\master.js:398:21)
    at Master.emit (events.js:180:13)
    at Messenger.sendToMaster (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-cluster\lib\utils\messenger.js:133:17)
    at Messenger.send (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-cluster\lib\utils\messenger.js:98:12)
    at EventEmitter.cluster.on (D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-cluster\lib\master.js:267:22)
    at EventEmitter.emit (events.js:185:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:194:13)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
name: "AppWorkerDiedError"
pid: 16004
hostname: Michaelsroom

2018-11-04 18:42:54,400 ERROR 16004 [master] app_worker#1:18532 start fail, exiting with code:1
2018-11-04 18:42:54,408 ERROR 16004 [master] exit with code:1
⚠️  Error: D:\KOA\Egg\examples\hackernews-datahub\node_modules\egg-bin\lib\start-cluster {"baseDir":"D:\\KOA\\Egg\\examples\\hackernews-datahub","workers":1,"framework":"D:\\KOA\\Egg\\examples\\hackernews-datahub\\node_modules\\egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hackernews-datahub@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackernews-datahub@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\john\AppData\Roaming\npm-cache\_logs\2018-11-04T23_42_54_448Z-debug.log
PS D:\KOA\Egg\examples\hackernews-datahub> node --version
v9.11.2
PS D:\KOA\Egg\examples\hackernews-datahub>

**Comment by popomore** [comment]
It seems that egg-datahub is not compatible with Windows.

@zhangyuheng
