### ISSUE TITLE
请问同时使用egg-oss的 RAM和STS切换该如何设置，无法进行切换

### ISSUE THREAD

**Issue by bulolo** [eggjs/egg#3184]
如题目：同时使用egg-oss的 RAM和STS改如何设置

比如我的需求是我既要给客户端使用sts,并且服务端不使用sts。
如果是ali-oss设置如下：

```
var oss = require('ali-oss');
var store = oss({
  accessKeyId: 'your access key',
  accessKeySecret: 'your access secret',
  bucket: 'your bucket name',
  region: 'oss-cn-hangzhou'
});
```
如上，我就能使用RAM

```
let OSS = require('ali-oss');
let STS = OSS.STS;
let sts = new STS({
  accessKeyId: '<子账号的AccessKeyId>',
  accessKeySecret: '<子账号的AccessKeySecret>'
});
```
如上，我就能使用STS模式

但是到了egg-oss,我设置了
```
 client: {
    sts: true,
    accessKeyId: '',
    accessKeySecret: '',
 }
```
我就没办法在切换非sts了。
如设置了非sts,app.oss.STS也拿不到。我需要能切换使用。请问这个是能做到的吗，在egg-oss中

**Comment by popomore** [comment]
用 clients 可以配多个

**Comment by bulolo** [comment]
我对clients进行配置，并保证我有 bucket: 'junyao-files',

```
exports.oss = {
  clients: {
    bucket1: {
      sts: true,
      bucket: 'junyao-files',
    },
    bucket2: {
      bucket: 'junyao-files',
    },
  },
  default: {
    endpoint: 'oss-cn-shenzhen.aliyuncs.com',
    accessKeyId: '',
    accessKeySecret: '',
  },
}
```

而实际使用中：
1.使用bucket2
```
    const bucket2 = await app.oss.get('bucket2')
    const list = await bucket2.list();
```
能正常使用,说明bucket2正常。
2.使用bucket1
```
      const bucket1 = app.oss.get('bucket1')
      // console.log('bucket1', bucket1) 
      try {
        const token = await bucket1.assumeRole(roleArn, policy, tokenExpireTime, 'appointment')
        console.log('token', token)
      } catch (error) {
        console.log('error', error)
      }
```
正常输出bucket1为STS
但当使用 
const token = await bucket1.assumeRole(roleArn, policy, tokenExpireTime, 'appointment')
时候
却报
```
error { Error: UnknownError: <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist.</Message>
  <RequestId>5BE66F2E271EEE359CBEE88F</RequestId>
  <HostId>oss-cn-shenzhen.aliyuncs.com</HostId>
  <BucketName></BucketName>
</Error>

    at STS._requestError (/Users/hongjunyao/Desktop/崛起-校庆/egg_jueqi/node_modules/ali-oss/lib/sts.js:118:15)
    at STS.assumeRole (/Users/hongjunyao/Desktop/崛起-校庆/egg_jueqi/node_modules/ali-oss/lib/sts.js:105:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  status: 404,
  message: 'UnknownError: <?xml version="1.0" encoding="UTF-8"?>\n<Error>\n  <Code>NoSuchBucket</Code>\n  <Message>The specified bucket does not exist.</Message>\n  <RequestId>5BE66F2E271EEE359CBEE88F</RequestId>\n  <HostId>oss-cn-shenzhen.aliyuncs.com</HostId>\n <BucketName></BucketName>\n</Error>\n',
  params:
   { agent: undefined,
     timeout: 60000,
     method: 'POST',
     content: 'Action=AssumeRole&RoleArn=&RoleSessionName=appointment&DurationSeconds=3600&Format=JSON&Version=2015-04-01&AccessKeyId=LTAIIDrH9q1SFAv4&SignatureMethod=HMAC-SHA1&SignatureVersion=1.0&SignatureNonce=0.2567116118580257&Timestamp=2018-11-10T05%3A39%3A58.607Z&Signature=%2BITTZLAAsB8H%2BnjzsBNptyonYuI%3D',
     headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
     ctx: undefined,
     tracer: undefined } }
```

**Comment by bulolo** [comment]
附上我完整代码

```

exports.oss = {
  clients: {
    bucket1: {
      sts: true,
      bucket: 'junyao-files',
    },
    bucket2: {
      bucket: 'junyao-files',
    },
  },
  default: {
    endpoint: 'oss-cn-shenzhen.aliyuncs.com',
    accessKeyId: 'XXX',
    accessKeySecret: 'XXX',
  },
  policyFile: 'config/policy/all_policy.txt',
  roleArn: 'XXX',
  tokenExpireTime: '3600',
}
```


list()方法正常执行
assume_role() 无法正常执行
```
'use strict';
const path = require('path');
const fs = require('fs');
const MpUploadOssHelper = require('mp-upload-oss-helper');

const Controller = require('egg').Controller;

class OssController extends Controller {
  async assume_role() {
    const {
      ctx,
      service,
      app
    } = this;
    const {
      roleArn,
      policyFile,
      tokenExpireTime
    } = app.config.oss
    let policy
    if (policyFile) {
      policy = fs.readFileSync(path.resolve(policyFile)).toString('utf-8');
    }
    try {
      //1、生成sts临时访问权限参数
      const token = await app.oss.get('bucket1').assumeRole(roleArn, policy, tokenExpireTime, 'appointment')

      //2、生成签名参数
      const mpHelper = new MpUploadOssHelper({
        accessKeyId: token.credentials.AccessKeyId,
        accessKeySecret: token.credentials.AccessKeySecret,
        timeout: 1, // 限制参数的有效时间(单位: 小时)
        maxSize: 10 // 限制上传文件大小(单位: Mb)
      });

      // 生成的参数
      const sign = mpHelper.createUploadParams();

      console.log('签名sign', sign)

      const result = {
        region: app.config.oss.region,
        bucket: app.config.oss.bucket,
        accessKeyId: token.credentials.AccessKeyId,
        accessKeySecret: token.credentials.AccessKeySecret,
        stsToken: token.credentials.SecurityToken,
        expiration: token.credentials.Expiration,
        signature: sign.signature,
        policy: sign.policy,
        key: sign.key
      }
      ctx.helper.success({
        ctx,
        res: result
      })
    } catch (error) {
      ctx.helper.fail({
        ctx,
        res: error,
      })
    }
  }

  async list() {

    await this.listDir('jueqi/')

  }
  async listDir(dir) {
    const {
      ctx,
      service,
      app
    } = this;
    const list = await app.oss.get('bucket2').list({
      prefix: dir,
      delimiter: '/'
    });

    ctx.helper.success({
      ctx,
      res: list
    })
  }
}

module.exports = OssController;
```

**Comment by bulolo** [comment]
@popomore

**Comment by popomore** [comment]
egg-oss 只保证了使用了 STS 客户端，具体逻辑还得问 ali-oss，分开两个 bucket 试试，一个单独授权 sts。

**Comment by bulolo** [comment]
单独的都可以。只要这种配置的都不行，可见不是ali-oss的问题
```
exports.oss = {
  clients: {
    bucket1: {
      sts: true,
      bucket: 'junyao-files',
    },
    bucket2: {
      bucket: 'junyao-files',
    },
  },
  default: {
    endpoint: 'oss-cn-shenzhen.aliyuncs.com',
    accessKeyId: 'XXX',
    accessKeySecret: 'XXX',
  },
  // 以下配置权限参数，非OSS配置项，自定义用途
  policyFile: 'config/policy/all_policy.txt',
  roleArn: 'XXX',
  tokenExpireTime: '3600',
}
```

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/48563916-5810d400-e930-11e8-90b8-198cf83d1dc8.png)

**Comment by bulolo** [comment]
确实已经定位出来 
clients 方式的 sts是用不了的。
单独的都可以

**Comment by popomore** [comment]
给 egg-oss 提个 test 吧

**Comment by popomore** [comment]
我加了测试时可以的 https://github.com/eggjs/egg-oss/pull/8

**Comment by bulolo** [comment]
单个配置clients确实是可以阿
我的意思是配了clients 一个用sts 一个不用，这时候sts就用不了

**Comment by bulolo** [comment]
@popomore 我看了你的测试，clients下只配置了一个 sts

需要

```
  clients: {
    bucket1: {
      sts: true,
      bucket: 'junyao-files',
    },
    bucket2: {
      bucket: 'junyao-files',
    },
  },
```
clients 两个情况下，一个是sts，这个sts的就用不了。
其他任意使用一个都是可以的。

**Comment by bulolo** [comment]
汇总情况是：
1.clients 下单独配一个，无论是不是sts，都是可以用的
2.clients 下,配置一个sts，一个不是sts， 非sts可以使用，sts的无法使用。 我说的是这种情况无法使用。

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/48664614-4ff59780-eadc-11e8-9c38-d71a1db77ad0.png)
测试不是我说的这种情况

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/48675471-213af800-eb94-11e8-92a8-63403a62313a.png)
这边发现了endpoint和我这边不一样的问题，最终也发现了是这个endpoint导致的

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/48675508-a8886b80-eb94-11e8-845e-ec2a67b74fdd.png)
如果用我自己的oss所在的endpoint就报错
![image](https://user-images.githubusercontent.com/10026498/48675516-bc33d200-eb94-11e8-95aa-9a8f733d80ba.png)

**Comment by bulolo** [comment]
```
exports.oss = {
  clients: {
    bucket1: {
      sts: true,
    },
    bucket2: {},
  },
  default: {
    accessKeyId: 'XXXXX',
    accessKeySecret: 'XXXX',
    region: 'oss-cn-shenzhen',
    bucket: 'biaojingli-test',
    endpoint: 'http://oss-cn-shenzhen.aliyuncs.com',  
    //当这里配置了endpoint,合并default和bucket1时候，sts使用了：http://oss-cn-shenzhen.aliyuncs.com，而这个对sts无效
  //而对bucket2，非sts有效
    timeout: '60s',
  }
}
```

但是 非clients的配置情况下，单独的client 使用的endpoint用http://oss-cn-shenzhen.aliyuncs.com 却对sts有效

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/48675699-1cc40e80-eb97-11e8-8168-fb0ee4bfa159.png)

**Comment by KevinHades** [comment]
解决方法：
config中配置：
`
exports.bucket1_sts = {
  sts: true,
  accessKeyId: '',
  accessKeySecret: '',
}
exports.bucket1 = {
  endpoint: 'https://oss-cn-hangzhou.aliyuncs.com',
  accessKeyId: '',
  accessKeySecret: '',
  bucket: '',
}
`
在需要oss操作的地方：
`const` bucket1_sts = `this.oss.createInstance(this.app.config.bucket1_sts)`
