### ISSUE TITLE
升级到最新版 仍然无法解决日志切割的问题。

### ISSUE THREAD

**Issue by luoxiaoji** [eggjs/egg#3209]
同 #2405  ，只不过看到有说延后了1秒，但是仍然会报错。

> ERROR 119596 nodejs.Error: [egg-logrotator] rename xxx\common-error.log, found exception: targetFile xxx\common-error.log.2018-11-16 exists!!!

**Comment by luoxiaoji** [comment]
补充： 并不是每一天都发生，大概2，3天会报一次。

**Comment by RoseFang** [comment]
切割问题会导致程序挂掉吗

**Comment by luoxiaoji** [comment]
> 切割问题会导致程序挂掉吗？

不会挂掉，只会把日志写入前一天，导致漏了一天的。

**Comment by RoseFang** [comment]
请问egg的同学能给个答案吗？
看了源码，源码是做了重命名，不太明白为什么会偶现这个问题：
`
//这里是处理核心代码，catch中打印出了报错问题
try {
        debug('rename from %s to %s', file.srcPath, file.targetPath);
        await renameOrDelete(file.srcPath, file.targetPath);
        rotatedFile.push(`${file.srcPath} -> ${file.targetPath}`);
      } catch (err) {
        err.message = `[egg-logrotator] rename ${file.srcPath}, found exception: ` + err.message;
        this.logger.error(err);
      }

//这里是分隔的核心文件，报错也是从改这里来的
// rename from srcPath to targetPath, for example foo.log.1 > foo.log.2
async function renameOrDelete(srcPath, targetPath) {
  if (srcPath === targetPath) {
    return;
  }
  const srcExists = await fs.exists(srcPath);
  if (!srcExists) {
    return;
  }
  const targetExists = await fs.exists(targetPath);
  // if target file exists, then throw
  // because the target file always be renamed first.
  if (targetExists) {
    const err = new Error(`targetFile ${targetPath} exists!!!`);
    throw err;
  }
  await fs.rename(srcPath, targetPath);
}`

**Comment by atian25** [comment]
js 的 setTimeout 精度有问题

**Comment by atian25** [comment]
@luoxiaoji @RoseFang 

> common-error.log.2018-11-16 exists

这个有点诡异，这条日志的输出时间是啥时？

**Comment by atian25** [comment]
@popomore 这里的逻辑感觉可以兼容优化下，即使文件存在了，也可以继续写入的。作为 warning 就好了。

https://github.com/eggjs/egg-logrotator/blob/master/app/lib/rotator.js

不过文件为啥存在，这个很奇怪。

**Comment by popomore** [comment]
存在了不应该覆盖吧，就是因为出现了这个异常情况

**Comment by atian25** [comment]
是覆盖而不是追加写入？ 覆盖的话确实不应该。

**Comment by luoxiaoji** [comment]
我上面说错了，是会追加写入 在前一天的，比如今天的日志报错了，今天就没有日志，日志都追加写入在昨天的了。 我是想看看是不是优化下，比如异常了 是否可以在比对一次尝试多创建一次。来回几次。

**Comment by fengmk2** [comment]
错误日志日期能否都反馈上来？得看看切割时间当时是当天，还是前一天。。。

**Comment by luoxiaoji** [comment]
```
2018-12-01 23:59:58,436 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxx\logs\admin-server-egg\common-error.log, found exception: targetFile E:\xxx\logs\admin-server-egg\common-error.log.2018-11-30 exists!!!
    at renameOrDelete (E:\xxx\node_modules\egg-logrotator\app\lib\rotator.js:63:17)

pid: 125988
hostname: xxx

2018-12-01 23:59:58,439 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxx\logs\admin-server-egg\admin-server-egg-web.log, found exception: targetFile E:\xx\logs\admin-server-egg\admin-server-egg-web.log.2018-11-30 exists!!!
    at renameOrDelete (E:\xxx\node_modules\egg-logrotator\app\lib\rotator.js:63:17)

pid: 125988
hostname: xxx

2018-12-01 23:59:58,440 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxx\logs\admin-server-egg\egg-web.log, found exception: targetFile E:\xxx\logs\admin-server-egg\egg-web.log.2018-11-30 exists!!!
    at renameOrDelete (E:\xxx\node_modules\egg-logrotator\app\lib\rotator.js:63:17)

pid: 125988
hostname: xxxx

2018-12-01 23:59:58,441 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxx\logs\admin-server-egg\egg-schedule.log, found exception: targetFile E:\xxxx\logs\admin-server-egg\egg-schedule.log.2018-11-30 exists!!!
    at renameOrDelete (E:\xx\xxx\node_modules\egg-logrotator\app\lib\rotator.js:63:17)

pid: 125988
hostname: xxxx

2018-12-01 23:59:58,442 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxxx\logs\admin-server-egg\egg-agent.log, found exception: targetFile E:\xxx\logs\admin-server-egg\egg-agent.log.2018-11-30 exists!!!
    at renameOrDelete (E:\xx\xx\node_modules\egg-logrotator\app\lib\rotator.js:63:17)

pid: 125988
hostname: xxxx

```


路径做了处理之外，这是1号完整的

**Comment by fengmk2** [comment]
> 2018-12-01 23:59:58,436 ERROR 125988 nodejs.Error: [egg-logrotator] rename E:\xxx\logs\admin-server-egg\common-error.log, found exception: targetFile E:\xxx\logs\admin-server-egg\common-error.log.2018-11-30 exists!!!

其实已经可以发现问题所在了。

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-logrotator/blob/master/app/schedule/rotate_by_file.js#L13

```js
schedule: {
      type: 'worker', // only one worker run this task
      cron: '1 0 0 * * *', // run every day at 00:00
    },
```

会有误差，提前触发了，需要修正一下。
