### ISSUE TITLE
最近无法创建项目 egg-init cnode-api --type=simple

### ISSUE THREAD

**Issue by ioscit** [eggjs/egg#3227]
TypeError: You must specify a "protocol" for the proxy type (http, https, socks, socks4, socks4a, socks5, socks5h, pac+data, pac+file, pac+ftp, pac+http, pac+https)
    at mapOptsToProxy (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_proxy-agent@2.3.1@proxy-agent\index.js:100:11)
    at new ProxyAgent (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_proxy-agent@2.3.1@proxy-agent\index.js:150:17)
    at Command.run (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\lib\init_command.js:51:26)
    at run.next (<anonymous>)
    at onFulfilled (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_co@4.6.0@co\index.js:50:10)
    at toPromise (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_co@4.6.0@co\index.js:118:63)
    at next (C:\Users\root\AppData\Roaming\npm\node_modules\egg-init\node_modules\_co@4.6.0@co\index.js:99:29)

**Comment by atian25** [comment]
你翻墙了吧，环境变量不对

**Comment by zm592565** [comment]
我也是 无法创建啊

**Comment by zm592565** [comment]
![image](https://user-images.githubusercontent.com/23302142/48927416-a87bc900-ef10-11e8-9405-d89008339673.png)
然后就没有然后了··

**Comment by ioscit** [comment]
> 你翻墙了吧，环境变量不对
没翻墙 还是家用网络 怎么搞定 如果环境变量不对 我现在该怎么办

**Comment by 4meet** [comment]
一样，也是在 home.test.js这一行卡住

**Comment by yangshuhappy1** [comment]
是这样的，这个Bug这么明显，到现在还没有解决
用win10基本上就会出现这个问题，CTRL+c结束就好了
用ubuntu-16.04没有这个问题

**Comment by atian25** [comment]
感谢 @yangshuhappy1 的反馈。我们几个人手头都没 win 没法跟进。

之前的打算是 egg-init 会完全重构，所以暂时 hold。

**Comment by 750973092** [comment]
> ![image](https://user-images.githubusercontent.com/23302142/48927416-a87bc900-ef10-11e8-9405-d89008339673.png)
> 然后就没有然后了··

请问解决了吗

**Comment by hyj1991** [comment]
@yangshuhappy1 我在 win10 1809 上用 cmd 或者 powershell 都可以正常使用 egg-init 创建，你的系统是 win10 的哪一个版本呢？

**Comment by blackteay** [comment]
![image](https://user-images.githubusercontent.com/1991257/52847726-eec77980-3147-11e9-9ae9-c52189fc1d18.png)
相同的问题

**Comment by blackteay** [comment]
![image](https://user-images.githubusercontent.com/1991257/52847762-07379400-3148-11e9-8a96-3801f04f6aec.png)
 相同的问题

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-init/pull/48

**Comment by whxaxes** [comment]
修复版本已经发布，更新 egg-init 到 1.15.1 再试一下

**Comment by jjzjx118** [comment]
mac 版本 egg-init@1.16.1 依然卡住....
