### ISSUE TITLE
egg-cors 报错 'headers' of null 

### ISSUE THREAD

**Issue by whyour** [eggjs/egg#3237]
* **Node Version**:  8.12.0
* **Egg Version**: 2.14.0
* **Plugin Name**: egg-cors
* **Plugin Version**:  2.1.1
* **Platform**: macos
* **Mini Showcase Repository**:

```
{ TypeError: Cannot read property 'headers' of null
    at next.catch.err (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/@koa/cors/index.js:92:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) status: 500 }
2018-11-27 10:19:04,382 ERROR 16823 [-/::1/-/231ms GET /api/me?t=1543285143981] nodejs.TypeError: Cannot read property 'headers' of null
    at next.catch.err (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/@koa/cors/index.js:92:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 16823

```
![image](https://user-images.githubusercontent.com/22700758/49054321-d1f96500-f22e-11e8-84e0-0effa67e65aa.png)

打印出来 `err`是` null`.

情况是redis  中的token没找到。

**Comment by whyour** [comment]
。。这原因有点。。就是redis里的token没有了，然后cookie还没过期，

**Comment by atian25** [comment]
没看明白 cors 和 redis 有啥关系？

**Comment by whyour** [comment]
我只是猜测，描述的是实际情况，具体cors为什么catch到error，却没有值就不太明白了。

**Comment by atian25** [comment]
上面不是提了，需要提供最小可复现仓库么，否则没法跟进
