### ISSUE TITLE
线上部署 npm start 启动失败，Cannot find module 'common-bin' 

### ISSUE THREAD

**Issue by Rudy24** [eggjs/egg#3299]
* **Node Version**: v10.14.1
* **Egg Version**:^2.2.1
* **Plugin Name**:
   "egg-sequelize": "^4.2.0",
    "egg-validate": "^2.0.2",
* **Plugin Version**:
* **Platform**: linux
* **Mini Showcase Repository**:

[按照应用部署文档操作（通过淘宝镜像 cnpm）](https://eggjs.org/zh-cn/core/deployment.html#mobileAside)
构建完成之后，通过ftp上传阿里云服务器上面，然后tar -zxvf /release.tgz -C /server 压缩指定的目录，启动npm start 时 出现报错  

```javascript
[root@iz8vbguxboxddpbfikq718z server]# npm start

> egg-mysql-vue-server@1.0.0 start /home/ftprudy/htdoc/server
> egg-scripts start --daemon --title=egg-server-egg-mysql-vue-server

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'common-bin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ftprudy/htdoc/server/node_modules/_egg-scripts@2.10.0@egg-scripts/lib/command.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-mysql-vue-server@1.0.0 start: `egg-scripts start --daemon --title=egg-server-egg-mysql-vue-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-mysql-vue-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-13T03_05_55_730Z-debug.log

```    
发现egg-scripts/node_modules目录下许多文件夹都是空的，打不开，可能是打包时候出现的问题

请问有没有遇到类似的问题？有没有对应的解决方案？

**Comment by atian25** [comment]
先自行检查下你的 tar 打出来的包对不对吧

**Comment by Rudy24** [comment]
@atian25 刚咨询了下同事，有可能是因为我的操作系统是windows，所以在node_modules里面很多都是软连接

**Comment by atian25** [comment]
软连接是 cnpm 的安装方式，这个没问题的。应该是你的打包指令问题，导致没把软链打进去。

**Comment by Rudy24** [comment]
@atian25 但都是按照 文档上面 tar -zcvf ../release.tgz . 打包构建的

**Comment by atian25** [comment]
win 没 tar 吧。自行检查下压缩包相关指令吧。先确保你打包出的代码是对的。

linux 指令不在答疑范畴。
