### ISSUE TITLE
同时在egg

### ISSUE THREAD

**Issue by spursy** [eggjs/egg#3319]
版本： 我使用的是 egg 2.2.1版本，
Issue： 我在我的项目中同时使用egg-mysqls 和 egg-sequelize 两个插件，当我使用egg-bin dev 测试的时候没有问题，当我将项目移到生产环境通过 **NODE_ENV=prod egg-scripts start --title=egg-server-test-sequelize** 就会报出下面错：

```
2018-12-17 13:29:39,136 ERROR 45064 nodejs.SequelizeConnectionError: Too many connections
    at Utils.Promise.tap.then.catch.err (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_sequelize@4.42.0@sequelize/lib/dialects/mysql/connection-manager.js:149:19)
    at tryCatcher (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/async.js:138:12)
    at _drainQueue (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Volumes/BOOTCAMP/dev/egg/test-sequelize/node_modules/_bluebird@3.5.3@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
name: "SequelizeConnectionError"
parent: {"code":"ER_CON_COUNT_ERROR","errno":1040,"sqlState":"","sqlMessage":"Too many connections"}
original: {"code":"ER_CON_COUNT_ERROR","errno":1040,"sqlState":"","sqlMessage":"Too many connections"}
pid: 45064

```

当我只使用 egg-mysqls 或egg-sequelize其中一个插件就不会出现问题？

求如何同时使用这两个插件？

**Comment by atian25** [comment]
写的很清楚了吧，`nodejs.SequelizeConnectionError: Too many connections`

egg-bin 的时候，只启动了一个进程，所以没问题。而 egg-scripts 的时候，是多进程的。
