### ISSUE TITLE
worker 模式 schedule 被调用了两次

### ISSUE THREAD

**Issue by whyour** [eggjs/egg#3386]
```
2019-01-09 17:40:58,599 INFO 30201 [Timer] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts next time will execute after 5000ms at 2019-01-09 17:41:03.599
2019-01-09 17:41:03,604 INFO 30245 [Job#154702686360339147978208628497] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:03,604 INFO 30245 [Job#154702686360339147978208628497] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 0ms
2019-01-09 17:41:03,604 INFO 30245 [Job#154702686360339147978208628497] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:03,605 INFO 30245 [Job#154702686360339147978208628497] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 1ms
2019-01-09 17:41:03,603 INFO 30201 [Timer] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts next time will execute after 5000ms at 2019-01-09 17:41:08.603
2019-01-09 17:41:08,605 INFO 30245 [Job#154702686860439148478320751798] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:08,606 INFO 30245 [Job#154702686860439148478320751798] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 1ms
2019-01-09 17:41:08,606 INFO 30245 [Job#154702686860439148478320751798] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:08,606 INFO 30245 [Job#154702686860439148478320751798] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 0ms
2019-01-09 17:41:08,605 INFO 30201 [Timer] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts next time will execute after 5000ms at 2019-01-09 17:41:13.605
2019-01-09 17:41:13,609 INFO 30245 [Job#154702687360839148978647829399] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:13,611 INFO 30245 [Job#154702687360839148978647829399] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 2ms
2019-01-09 17:41:13,609 INFO 30245 [Job#154702687360839148978647829399] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:13,611 INFO 30245 [Job#154702687360839148978647829399] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 2ms
2019-01-09 17:41:13,608 INFO 30201 [Timer] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts next time will execute after 5000ms at 2019-01-09 17:41:18.608
2019-01-09 17:41:18,612 INFO 30245 [Job#1547026878611391494789973577100] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:18,613 INFO 30245 [Job#1547026878611391494789973577100] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 1ms
2019-01-09 17:41:18,613 INFO 30245 [Job#1547026878611391494789973577100] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts executing by app
2019-01-09 17:41:18,613 INFO 30245 [Job#1547026878611391494789973577100] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts execute succeed, used 0ms
2019-01-09 17:41:18,612 INFO 30201 [Timer] /Users/wangpeng/resp/wt-hulk/back-end/app/schedule/xiaoTeMessageJob.ts next time will execute after 5000ms at 2019-01-09 17:41:23.612
```

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**: egg-schedule
- **Plugin Version**:
- **Platform**:

**Comment by whxaxes** [comment]
能把你的 schedule 代码贴出来看看么

**Comment by whyour** [comment]
@whxaxes  写错了，我用的是 `worker`

**Comment by whxaxes** [comment]
我本机无法复现，麻烦提供一下能稳定复现的 repo

**Comment by whyour** [comment]
@whxaxes 我建个私有仓库，加下你，你帮忙看下，还有dev启动也会一直有错误，也帮忙看下，谢谢，里面有大量信息，请勿泄露，谢谢。

**Comment by whxaxes** [comment]
@whyour  你这代码量也太多了 ... 你看一下弄个最简能复现的吧

**Comment by whyour** [comment]
@whxaxes schedule的很少，只有一个文件，我初始化一个新的，就复现不了，不知道是不是当初初始化的时候有些问题没处理好。

**Comment by whxaxes** [comment]
@whyour  我把你除 schedule 之外的代码都删掉之后就正常了，怀疑你的业务代码有做运行 schedule 的操作

**Comment by whyour** [comment]
@whxaxes 我也怀疑业务代码有问题，但是 schedule 在其他地方没用过。。还有什么方法可能可以调用，dev还报这个错。希望大神能给把把脉。
```
2019-01-09 23:45:11,418 WARN 35761 [egg:core:ready_timeout] 10 seconds later /Users/wangpeng/resp/release/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
1547048757
1547048757
2019-01-09 23:46:02,166 ERROR 35761 [-/127.0.0.1/-/0ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined
    at Function.waitFor (/Users/wangpeng/resp/release/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 35761
```

**Comment by whxaxes** [comment]
@whyour  你在 `app/core/redis.ts` 里又重新实例化了一个 `Application` .... 这种骚操作是哪里学来的 ，所以导致又重新跑了一遍 app worker 的 loader 逻辑，schedule 也就注册了两次了 ...

**Comment by whxaxes** [comment]
@whyour  已删
