### ISSUE TITLE
isredis的初始化在configWillLoad之前进行了

### ISSUE THREAD

**Issue by Vcgoyo** [eggjs/egg#3401]
## What happens?

业务需要在configWillLoad中动态的修改一些中间件的连接配置，我们将configWillLoad写在了一个独立的插件中，然后在应用组件引用该插件，同时应用层组件也引用了egg-redis，在应用层组件启动的时候发现，ioredis的初始化在configWillLoad之前 ，导致redis密码还未在configWillLoad中修改为正确的时候，redis就初始化了就报密码错误了

```
2019-01-14 10:53:41,438 INFO 7032 [master] node version v10.13.0
2019-01-14 10:53:41,441 INFO 7032 [master] egg version 2.14.2
2019-01-14 10:53:43,470 ERROR 6228 [egg-redis] client error: ReplyError: ERR invalid password
2019-01-14 10:53:43,472 ERROR 6228 nodejs.ReplyError: ERR invalid password
    at JavascriptRedisParser.returnError (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Command.initPromise (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\command.js:63:18)
    at new Command (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\command.js:51:8)
    at Redis.auth (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\commander.js:131:29)
    at Socket.<anonymous> (F:\InfoSightIoT\node\egg-hik-framework\hen-hik-web\node_modules\ioredis\lib\redis\event_handler.js:17:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:10)
name: "ReplyError"
message: "ERR invalid password"
command: {"name":"auth","args":["nkdSpjou"]}
pid: 6228
```

在另一个插件中的app.js，而且只有redis的顺序出现了问题，还有其他中间件比如consul则配置正常初始化后才初始化consul插件
```
class AppBootHook  {
    constructor(app) {
        console.info("init___________________________________________")
        this.app = app;
        this.configLogObj={};
        this._configProp;
        this._serviceDirAddr;
    }
    configWillLoad() {
        console.info("configWillLoad_________________________________________________")
        try {
            this._configInit();
        }catch (e) {
            this.app.logger.error(e);
        }
    }

    _configInit(){
       ...
    }
}
module.exports = AppBootHook;
```

## 相关环境信息
- **操作系统**：windows7

**Comment by Vcgoyo** [comment]
@

**Comment by mickeyinfoshan** [comment]
@Vcgoyo 后来怎么解决的？
