### ISSUE TITLE
线上egg服务总是不定时报 ERR_IPC_CHANNEL_CLOSED 错误

### ISSUE THREAD

**Issue by houxiaofei123** [eggjs/egg#3405]
## What happens?
线上用docker部署了两个egg服务，其中一台正常，另外一台会报错 具体日志如下 (并没有发现业务上的错误)
```
2019-01-04 10:15:42,150 INFO 35 [master] app_worker#2:56 started at 3737, remain 1 (1546ms)
2019-01-04 10:15:42,161 INFO 35 [master] app_worker#1:51 started at 3737, remain 0 (1557ms)
2019-01-04 10:15:42,163 INFO 35 [master] egg started on http://127.0.0.1:7001 (2022ms) with STICKY MODE!
(node:57) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:56) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
2018-12-27T16:00:00.000Z
2018-12-27T16:00:00.000Z
(node:51) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:63) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
[Mon Jan 07 2019 10:24:45 GMT+0800 (CST)] [graceful:worker:63:uncaughtException] throw error 1 times
{ ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:63)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  name: 'ECONNRESETError' }
ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:63)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
[Mon Jan 07 2019 10:24:45 GMT+0800 (CST)] [graceful:worker:63] will exit after 30000ms
[Mon Jan 07 2019 10:24:45 GMT+0800 (CST)] [graceful:worker:63] close server#0, _connections: 0
[Mon Jan 07 2019 10:24:45 GMT+0800 (CST)] [graceful:worker:63] close 1 servers!
[Mon Jan 07 2019 10:24:45 GMT+0800 (CST)] [graceful:worker:63] worker disconnect!
[2019-01-07 10:24:45.887] [cfork:master:35] worker:63 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2019-01-07 10:24:45.889] [cfork:master:35] new worker:125 fork (state: none)
2019-01-07 10:24:45,889 INFO 35 [master] app_worker#4:63 disconnect, suicide: true, state: disconnected, current workers: ["1","2","3","4","5"]
2019-01-07 10:24:45,890 INFO 35 [master] app_worker#5:125 start, state: none, current workers: ["1","2","3","4","5"]
2019-01-07 10:24:46,231 INFO 125 Plugin development is disabled by env unmatched, require env(local) but got env is prod
2019-01-07 10:24:46,247 INFO 125 [egg:core] App root: /home/project
2019-01-07 10:24:46,248 INFO 125 [egg:core] All *.log files save on "/root/logs/"
```
然后
```
2019-01-07 10:24:47,226 INFO 125 [egg-mongoose] instance[0] start successfully
2019-01-07 10:24:47,239 INFO 125 [egg:core:ready_stat] end ready task /home/project/node_modules/egg-mongoose/lib/mongoose.js:77:7, remain ["/home/project/node_modules/egg-watcher/lib/init.js:15:14"]
2019-01-07 10:24:47,244 INFO 125 [egg-watcher:application] watcher start success
2019-01-07 10:24:47,244 INFO 125 [egg:core:ready_stat] end ready task /home/project/node_modules/egg-watcher/lib/init.js:15:14, remain []
2019-01-07 10:24:47,267 INFO 35 [master] app_worker#5:125 started at 3737, remain 0 (259746663ms)
[2019-01-07 10:24:56.386] [cfork:master:35] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Worker.send (internal/cluster/worker.js:54:28)
    at Server.require.createServer.connection (/home/project/node_modules/egg-cluster/lib/master.js:164:16)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1561:8)
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Worker.send (internal/cluster/worker.js:54:28)
    at Server.require.createServer.connection (/home/project/node_modules/egg-cluster/lib/master.js:164:16)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1561:8)
(total 1 disconnect, 0 unexpected exit)
[Mon Jan 07 2019 10:25:15 GMT+0800 (CST)] [graceful:worker:63] kill timeout, exit now.
2019-01-07 10:25:15,897 ERROR 63 [app_worker] exit with code:1
[2019-01-07 10:25:15.905] [cfork:master:35] worker:63 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2019-01-07 10:25:15,906 ERROR 35 nodejs.AppWorkerDiedError: [master] app_worker#4:63 died (code: 1, signal: null, suicide: true, state: dead), current workers: ["1","2","3","5"]
    at Master.onAppExit (/home/project/node_modules/egg-cluster/lib/master.js:398:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/home/project/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/home/project/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/home/project/node_modules/egg-cluster/lib/master.js:267:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 35
```

## 复现步骤，错误日志以及相关配置
找不到复现条件 在测试环境 一台机器没有出问题 
到了线上 就一台机器出问题

## 相关环境信息
- **操作系统**：
- **Node 版本**：v8.9.4
- **Egg 版本**：^2.2.1

**Comment by popomore** [comment]
上面出现了一个未捕获异常，进程重启了。

**Comment by houxiaofei123** [comment]
首先非常感谢大神的回复

这个 我意识到有未捕获的异常 也在错误中间间里加了日志 最后一行
```
 // 生产环境时 500 错误的详细错误内容不返回给客户端，因为可能包含敏感信息
      const error_msg = status === 500 && app.config.env === 'prod'
        ? 'Internal Server Error'
        : err.message;
      // 从 error 对象上读出各个属性，设置到响应中
      ctx.logger.error('status [%d]  message [%s]', status, error_msg);
```
打开/root/logs/common-error.log.2019-01-14  文件
查看错误日志 看到了这个报错  可是没明白具体什么意思 代码中也没有业务逻辑错误 (没有异常业务代码)
还请大神指点 如何定位
```
2019-01-14 16:50:31,426 ERROR 56 nodejs.ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "ECONNRESETError"
pid: 56
```
或者是否 需要手动 process.on('uncaughtException',function() {
//
})

另外这个进程重启 应该不会影响这个服务吧 目前来看  这个服务会挂掉 然后 报500

**Comment by houxiaofei123** [comment]
> 上面出现了一个未捕获异常，进程重启了。

首先非常感谢大神的回复

这个 我意识到有未捕获的异常 也在错误中间间里加了日志 最后一行

 // 生产环境时 500 错误的详细错误内容不返回给客户端，因为可能包含敏感信息
      const error_msg = status === 500 && app.config.env === 'prod'
        ? 'Internal Server Error'
        : err.message;
      // 从 error 对象上读出各个属性，设置到响应中
      ctx.logger.error('status [%d]  message [%s]', status, error_msg);
打开/root/logs/common-error.log.2019-01-14 文件
查看错误日志 看到了这个报错 可是没明白具体什么意思 代码中也没有业务逻辑错误 (没有异常业务代码)
还请大神指点 如何定位

2019-01-14 16:50:31,426 ERROR 56 nodejs.ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "ECONNRESETError"
pid: 56
或者是否 需要手动 process.on('uncaughtException',function() {
//
})

另外这个进程重启 应该不会影响这个服务吧 目前来看 这个服务会挂掉 然后 报500

**Comment by guoshencheng** [comment]
egg-clsuster 会管理集群，在某个worker抛出未捕获的异常的时候，会注销当前的worker并重启一个新的worker，一般不会影响服务

**Comment by guoshencheng** [comment]
看你好像是开启了sticky mode，这个模式我还没有用过，略看了一下源码这个模式似乎只能启用单worker

```javascript
 if (this.options.sticky) {
      this.startMasterSocketServer(err => {
        if (err) return this.ready(err);
        this.ready(true);
      });
    } else {
      this.ready(true);
    }
```
而startMasterSocketServer()的实现
```javascript
  startMasterSocketServer(cb) {
    // Create the outside facing server listening on our port.
    require('net').createServer({ pauseOnConnect: true }, connection => {
      // We received a connection and need to pass it to the appropriate
      // worker. Get the worker for this connection's source IP and pass
      // it the connection.

      /* istanbul ignore next */
      if (!connection.remoteAddress) {
        connection.close();
      } else {
        const worker = this.stickyWorker(connection.remoteAddress);
        worker.send('sticky-session:connection', connection);
      }
    }).listen(this[REALPORT], cb);
  }
```

在worker启动的时候也会判断sticky

```javascript
 if (options.sticky) {
    server.listen(0, '127.0.0.1');
    // Listen to messages sent from the master. Ignore everything else.
    process.on('message', (message, connection) => {
      if (message !== 'sticky-session:connection') {
        return;
      }

      // Emulate a connection event on the server by emitting the
      // event with the connection the master sent us.
      server.emit('connection', connection);
      connection.resume();
    });
  } else {
    // prepare server and listen
  }
```

最后只有一个worker能够处理从master中传入的connection

**Comment by houxiaofei123** [comment]
> 看你好像是开启了sticky mode，这个模式我还没有用过，略看了一下源码这个模式似乎只能启用单worker
> 
> ```js
>  if (this.options.sticky) {
>       this.startMasterSocketServer(err => {
>         if (err) return this.ready(err);
>         this.ready(true);
>       });
>     } else {
>       this.ready(true);
>     }
> ```
> 
> 而startMasterSocketServer()的实现
> 
> ```js
>   startMasterSocketServer(cb) {
>     // Create the outside facing server listening on our port.
>     require('net').createServer({ pauseOnConnect: true }, connection => {
>       // We received a connection and need to pass it to the appropriate
>       // worker. Get the worker for this connection's source IP and pass
>       // it the connection.
> 
>       /* istanbul ignore next */
>       if (!connection.remoteAddress) {
>         connection.close();
>       } else {
>         const worker = this.stickyWorker(connection.remoteAddress);
>         worker.send('sticky-session:connection', connection);
>       }
>     }).listen(this[REALPORT], cb);
>   }
> ```
> 
> 在worker启动的时候也会判断sticky
> 
> ```js
>  if (options.sticky) {
>     server.listen(0, '127.0.0.1');
>     // Listen to messages sent from the master. Ignore everything else.
>     process.on('message', (message, connection) => {
>       if (message !== 'sticky-session:connection') {
>         return;
>       }
> 
>       // Emulate a connection event on the server by emitting the
>       // event with the connection the master sent us.
>       server.emit('connection', connection);
>       connection.resume();
>     });
>   } else {
>     // prepare server and listen
>   }
> ```
> 
> 最后只有一个worker能够处理从master中传入的connection

多谢回答
我看了一下 确实是以sticky mode模式启动的  这是当时使用socket.io的时候加的  等之后 去掉试试 
现在主要是这个异常 我不知道如何引起的  而且 另外一台服务 从来没有出过这种问题

**Comment by houxiaofei123** [comment]
> 上面出现了一个未捕获异常，进程重启了。
```
2019-01-04 10:16:04,445 INFO 35 [master] egg started on http://127.0.0.1:7001 (2023ms) with STICKY MODE!
(node:56) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:58) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:63) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
[Fri Jan 11 2019 16:07:25 GMT+0800 (CST)] [graceful:worker:56:uncaughtException] throw error 1 times
{ ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  name: 'ECONNRESETError' }
ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
```
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead. 
//这个告警会引起异常吗？？

**Comment by houxiaofei123** [comment]
> egg-clsuster 会管理集群，在某个worker抛出未捕获的异常的时候，会注销当前的worker并重启一个新的worker，一般不会影响服务

兄弟 多谢你的回复啊  我这样 是否就能知道 未捕获的异常是什么了？
 process.on('uncaughtException',function() {
//
})

**Comment by guoshencheng** [comment]
额。同为egg的使用者不敢多指教 egg使用的`graceful`也是使用的
```
process.on('uncaughtException',function() {
//
})
```
来兜底异常处理的。
未捕获的异常也给你打出来了，应该就是

```
ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  name: 'ECONNRESETError'
```
这个信息。

如果要给个找问题的建议的话，我觉得，一台能启一台不能，应该是环境(包括运行容器、配置等等)导致的，可以查看一下环境的问题。或者可以暴露debug端口，直接debug这个egg服务

**Comment by houxiaofei123** [comment]
> 额。同为egg的使用者不敢多指教 egg使用的`graceful`也是使用的
> 
> ```
> process.on('uncaughtException',function() {
> //
> })
> ```
> 来兜底异常处理的。
> 未捕获的异常也给你打出来了，应该就是
> 
> ```
> ECONNRESETError: read ECONNRESET (uncaughtException throw 1 times on pid:56)
>     at _errnoException (util.js:1022:11)
>     at TCP.onread (net.js:615:25)
>   code: 'ECONNRESET',
>   errno: 'ECONNRESET',
>   syscall: 'read',
>   name: 'ECONNRESETError'
> ```
> 这个信息。
> 
> 如果要给个找问题的建议的话，我觉得，一台能启一台不能，应该是环境(包括运行容器、配置等等)导致的，可以查看一下环境的问题。或者可以暴露debug端口，直接debug这个egg服务

嗯!如果说 错误打印出来了 尴尬地是我看不懂这个错误  最尴尬的是 今天到线上看了日志 另外一台也出现了同样的问题 
由于是线上的 我不能随时操作 所以准备 先去掉sticky模式 然后 查一下 容器网络相关的问题
给你发了一封邮件 查收一下
