### ISSUE TITLE
npm run dev 每隔一到两天就会奔溃一次？怎么解决

### ISSUE THREAD

**Issue by raodaqi** [eggjs/egg#3513]
[2019-03-04 11:21:45.715] [cfork:master:12180] worker:12208 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2019-03-04 11:21:45.715] [cfork:master:12180] don't fork new work (refork: false)
2019-03-04 11:21:45,716 INFO 12180 [master] app_worker#1:12208 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2019-03-04 11:21:45.716] [cfork:master:12180] worker:12208 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2019-03-04 11:21:45,718 ERROR 12180 nodejs.AppWorkerDiedError: [master] app_worker#1:12208 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/home/wwwroot/xiaoying.sharevar.com/xiaoying/server/node_modules/egg-cluster/lib/master.js:398:21)
    at Master.emit (events.js:159:13)
    at Messenger.sendToMaster (/home/wwwroot/xiaoying.sharevar.com/xiaoying/server/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/home/wwwroot/xiaoying.sharevar.com/xiaoying/server/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/home/wwwroot/xiaoying.sharevar.com/xiaoying/server/node_modules/egg-cluster/lib/master.js:267:22)
    at EventEmitter.emit (events.js:164:20)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
name: "AppWorkerDiedError"
pid: 12180
hostname: iZ2ze7o97laq66l386sgw3Z

**Comment by atian25** [comment]
提供可复现方式和详细报错，从给出的日志看不出什么来。

另外， `npm run dev` 是本地开发用的，不要在线上使用。

**Comment by raodaqi** [comment]
> 提供可复现方式和详细报错，从给出的日志看不出什么来。
> 
> 另外， `npm run dev` 是本地开发用的，不要在线上使用。

就是无法复现，是在服务器上使用的，但是也觉得很奇怪，上线没有问题，使用也没有问题，就是过一两天就得重启。

**Comment by atian25** [comment]
服务器上不应该使用 `npm run dev`

**Comment by unclexiao** [comment]
你这个情况并不是服务自己挂掉的，而是被系统Kill了进程，你应该用守护进程来启动。或者参考文档（[应用部署](https://eggjs.org/zh-cn/core/deployment.html)），只需要：
```shell
npm run start
```
