### ISSUE TITLE
SOFA Node 不支持Sofa Rest服务？

### ISSUE THREAD

**Issue by lzuwen** [eggjs/egg#3529]
Node Version:v11.30
sofa-node version 1.0.1
Plugin Name:
Plugin Version:
Platform:Win 7
异常信息如下：
![image](https://user-images.githubusercontent.com/44759266/54107737-f57aa100-4414-11e9-860e-1975dfca4034.png)
2019-03-11 15:43:43,418 ERROR 8268 [-/127.0.0.1/c0a87560155229022337310008268/46ms POST /console/sysconfig/user/query] nodejs.RpcSocketCloseError: The socket was closed. (address: address => rest://192.168.117.96:8341?version=1.0&accepts=100000&appName=gov-hoox-console-run&weight=100&language=java&pid=9608&interface=com.linewell.gov.hoox.console.facade.config.user.ConsoleUserFacede&timeout=300000&serialization=hessian2&protocol=rest&delay=-1&dynamic=true&startTime=1552290088583&id=rpc-cfg-6&uniqueId=&rpcVer=50501)
    at RpcConnection._cleanRequest (F:\JAVA\fwzt_workspace\egg-ant-design-pro\node_modules\sofa-rpc-node\lib\client\connection\rpc.js:240:13)
    at RpcConnection._handleClose (F:\JAVA\fwzt_workspace\egg-ant-design-pro\node_modules\sofa-rpc-node\lib\client\connection\rpc.js:260:10)
    at Socket._socket.once (F:\JAVA\fwzt_workspace\egg-ant-design-pro\node_modules\sofa-rpc-node\lib\client\connection\rpc.js:86:45)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:616:12)
name: "RpcSocketCloseError"
resultCode: "02"
pid: 8268
hostname: LISECTGROUP

**Comment by popomore** [comment]
是对应的 sofa rpc，sofa rest 是 http 协议的，可以用 httpclient 直接调用。

**Comment by lzuwen** [comment]
Sofa rpc同时存在bolt、rest服务，SOFA Node调用服务就随机存在失败，即SOFA Node调用Rest服务失败，有什么好的方法解决吗？

**Comment by popomore** [comment]
现在是不支持 rest 的

**Comment by lzuwen** [comment]
后期会支持吗？

**Comment by popomore** [comment]
暂时还没计划，你可以试试 rpc
