### ISSUE TITLE
egg-socket.io example运行报错

### ISSUE THREAD

**Issue by r6c** [eggjs/egg#3536]
## What happens?
egg-socket.io example运行报错

## How To Reproduce

**Steps to reproduce the behavior:**
yarn install 后 yarn start, node client.js.报错
![image](https://user-images.githubusercontent.com/45527749/54180124-cbd57e80-44d5-11e9-913f-b4266d5a61bd.png)

**Expected behavior**
正常运行

## Context
- **Node Version**:10.15.2
- **Egg Version**:2.20.0
- **Plugin Name**:egg-socket.io
- **Plugin Version**:4.1.5
- **Platform**:mac mojave

**Comment by r6c** [comment]
**具体报错日志如下**
```
2019-03-12 14:41:53,524 ERROR 41253 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:41253)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 41253
hostname: JIMUs-Mac-mini.local

[Tue Mar 12 2019 14:41:53 GMT+0800 (China Standard Time)] [graceful:worker:41253:uncaughtException] throw error 1 times
TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:41253)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:41253)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Tue Mar 12 2019 14:41:53 GMT+0800 (China Standard Time)] [graceful:worker:41253] will exit after 30000ms
[Tue Mar 12 2019 14:41:53 GMT+0800 (China Standard Time)] [graceful:worker:41253] close server#0, _connections: 0
[Tue Mar 12 2019 14:41:53 GMT+0800 (China Standard Time)] [graceful:worker:41253] close 1 servers!
[Tue Mar 12 2019 14:41:53 GMT+0800 (China Standard Time)] [graceful:worker:41253] worker disconnect!
[2019-03-12 14:42:06.119] [cfork:master:41251] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 0 unexpected exit)
[2019-03-12 14:42:07.917] [cfork:master:41251] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 0 unexpected exit)
[2019-03-12 14:42:18.532] [cfork:master:41251] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 0 unexpected exit)
[Tue Mar 12 2019 14:42:23 GMT+0800 (China Standard Time)] [graceful:worker:41253] kill timeout, exit now.
[2019-03-12 14:42:23.536] [cfork:master:41251] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 0 unexpected exit)
2019-03-12 14:42:23,575 ERROR 41253 [app_worker] exit with code:1
[2019-03-12 14:42:23.582] [cfork:master:41251] worker:41253 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: false, worker.disableRefork: false)
[2019-03-12 14:42:23.582] [cfork:master:41251] don't fork new work (refork: false)
[2019-03-12 14:42:23.582] [cfork:master:41251] (total 0 disconnect, 1 unexpected exit) WorkerDiedUnexpectedError: worker:41253 died unexpected (code: 1, signal: null, exitedAfterDisconnect: true, state: dead)
    at EventEmitter.onUnexpected (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/cfork/index.js:223:15)
    at EventEmitter.emit (events.js:189:13)
    at EventEmitter.<anonymous> (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/cfork/index.js:143:13)
    at EventEmitter.emit (events.js:194:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:194:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-03-12 14:42:23,583 ERROR 41251 nodejs.AppWorkerDiedError: [master] app_worker#1:41253 died (code: 1, signal: null, suicide: true, state: dead), current workers: []
    at Master.onAppExit (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:408:21)
    at Master.emit (events.js:189:13)
    at Messenger.sendToMaster (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:277:22)
    at EventEmitter.emit (events.js:194:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:194:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 41251
hostname: JIMUs-Mac-mini.local

[2019-03-12 14:42:24.397] [cfork:master:41251] master uncaughtException: TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 1 unexpected exit)
[2019-03-12 14:42:28.076] [cfork:master:41251] master uncaughtException: TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 1 unexpected exit)
[2019-03-12 14:42:28.077] [cfork:master:41251] master uncaughtException: TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (/Users/r6c/Desktop/egg-socket.io-master/example/node_modules/egg-cluster/lib/master.js:174:16)
    at Server.emit (events.js:189:13)
    at TCP.onconnection (net.js:1517:8)
(total 0 disconnect, 1 unexpected exit)
```

**Comment by qingdengyue** [comment]
#3531

**Comment by ngot** [comment]
duplicated with https://github.com/eggjs/egg/issues/3531
