### ISSUE TITLE
egg-socket 启动报错 Cannot set property 'parsingHeadersStart' of undefined

### ISSUE THREAD

**Issue by kissyam** [eggjs/egg#3576]
## What happens?
egg项目安装egg-socket.io后报错。 直接clone官方的demo也是同样报错。

## Mini Showcase Repository(REQUIRED)
the error info
nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:3514)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**: v10.15.3
- **Egg Version**: 2.20.2
- **Plugin Name**: egg-scoket.io
- **Plugin Version**:  4.1.5
- **Platform**:MacOs majve

**Comment by xiongsongsong** [comment]
@kissyam 使用Node v10.15.1 即可，官方还没修复。

**Comment by hezhongfeng** [comment]
亲测升级到目前最新的v10.16.0解决

**Comment by rise0chen** [comment]
我用的alinode:4.7.2镜像也出现了这个问题。
nodejs版本也是10.15.3。
但是alinode镜像不更新，欲哭无泪。。。

**Comment by rise0chen** [comment]
亲测升级nodejs版本就好了。
2019-06-29 00:53:15,625 INFO 41 [master] node version v12.4.0
2019-06-29 00:53:15,625 INFO 41 [master] alinode version v5.4.0
2019-06-29 00:53:15,625 INFO 41 [master] egg version 2.22.2

**Comment by ggpp224** [comment]
sb项目

**Comment by fyzhu** [comment]
调了一下午，口吐芬芳

**Comment by QJune** [comment]
> 我用的alinode:4.7.2镜像也出现了这个问题。
> nodejs版本也是10.15.3。
> 但是alinode镜像不更新，欲哭无泪。。。

同10.15.3，好恨早上不来找你
