### ISSUE TITLE
npm run dev时报错:middleware is not a function

### ISSUE THREAD

**Issue by tozlam** [eggjs/egg#3594]
## 相关环境信息
- **操作系统**：Centos 7.3
- **Node 版本**：v10.15.0
- **Egg 版本**：2.15.1

````
//app.middleware.authLogin.js
'use strict';

module.exports = () => {

    /**
     * 校验是否登录
     */
    return async function (ctx, next) {
        const isLogin = ctx.session.token;
        const expireTime = ctx.session.expireTime;
        const nowTime = new Date().getTime();
        if (!isLogin) {
            ctx.status = 200;
            ctx.body = {
                data: {
                    erroeCode: 403,
                    errorMsg: '请登录'
                }
            };
            return;
        }else if(nowTime > expireTime){
            ctx.status = 200;
            ctx.body = {
                data: {
                    erroeCode: 403,
                    errorMsg: '登录超时，请重新登录'
                }
            };
            return;
        }
        await next();
    }

}
````

````
//app.router.order.js
'use strict';

/**
 * @param {Egg.RuleData} app - egg application
 */
module.exports = app => {
    const {
        router,
        controller,
        middleware
    } = app;

    const authLogin = middleware.authLogin();
    const {order} = controller;

    router.post('/api/order/myOrder',authLogin, order.myOrder);
    router.post('/api/order/orderDetail',authLogin,order.orderDetail);
    router.post('/api/order/newOrder',authLogin,order.newOrder);
    router.post('/api/order/settlement',authLogin,order.settlement);
    router.post('/api/order/buyNow',authLogin,order.buyNow);
};
````

npm run dev时报错：
````
TypeError: app.middleware.authLogin is not a function
    at module.exports.app (/usr/share/nginx/HALO_NODE_SERVER/app/router/order.js:13:38)
    at module.exports.app (/usr/share/nginx/HALO_NODE_SERVER/app/router.js:11:28)
    at AppWorkerLoader.loadFile (/usr/share/nginx/HALO_NODE_SERVER/node_modules/egg-core/lib/loader/egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (/usr/share/nginx/HALO_NODE_SERVER/node_modules/egg-core/lib/loader/mixin/router.js:17:10)
    at AppWorkerLoader.load (/usr/share/nginx/HALO_NODE_SERVER/node_modules/egg/lib/loader/app_worker_loader.js:41:10)
    at new Application (/usr/share/nginx/HALO_NODE_SERVER/node_modules/egg/lib/application.js:66:19)
    at Object.<anonymous> (/usr/share/nginx/HALO_NODE_SERVER/node_modules/egg-cluster/lib/app_worker.js:19:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
````

**Comment by atian25** [comment]
提供最小可复现仓库
