### ISSUE TITLE
[AgentWorkerDiedError]在eggjs中加入egg-sequelize后报错

### ISSUE THREAD

**Issue by praeteritis** [eggjs/egg#3599]
我在eggjs框架中加入egg-sequelize后，npm run dev报错

`2019-04-08 21:16:17,070 ERROR 2568 nodejs.AgentWorkerDiedError: [master] agent_worker#1:4180 died (code: 1, signal: null)
    at Master.onAgentExit (F:\MX\MX_0.2\node_modules\egg-cluster\lib\master.js:341:17)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (F:\MX\MX_0.2\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (F:\MX\MX_0.2\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at ChildProcess.agentWorker.once (F:\MX\MX_0.2\node_modules\egg-cluster\lib\master.js:232:22)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AgentWorkerDiedError"
pid: 2568
hostname: 

2019-04-08 21:16:17,074 ERROR 2568 [master] agent_worker#1:4180 start fail, exiting with code:1
2019-04-08 21:16:17,076 ERROR 2568 [master] exit with code:1
⚠️  Error: F:\MX\MX_0.2\node_modules\egg-bin\lib\start-cluster {"typescript":false,"declarations":true,"workers":1,"baseDir":
"F:\\MX\\MX_0.2","framework":"F:\\MX\\MX_0.2\\node_modules\\egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mxproject@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mxproject@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

请问这是什么问题？
尝试过很多次，也换过数据库，都报错

**Comment by atian25** [comment]
看 common-error 日志

**Comment by praeteritis** [comment]
> 看 common-error 日志

common-error是空的
https://github.com/praeteritis/mx
这是我的最小代码，麻烦了

**Comment by HenryYong** [comment]
> 已经解决了，感谢

请问是如何解决的呀？

**Comment by JayenLee** [comment]
我也出现这个问题 在common-error.log里面报
2019-09-06 09:02:01,748 ERROR 77 [-/127.0.0.1/-/0ms GET /] nodejs.EFAULTError: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at loadFile (/www/node_modules/koa-static-cache/index.js:196:19)
    at /www/node_modules/koa-static-cache/index.js:33:7
    at Array.forEach (<anonymous>)
    at staticCache (/www/node_modules/koa-static-cache/index.js:32:37)
    at basicRouterRegister (/www/node_modules/egg-doc/lib/router/index.js:23:13)
    at module.exports.swaggerInit.app (/www/node_modules/egg-doc/lib/index.js:18:5)
    at app.beforeStart (/www/node_modules/egg-doc/app.js:8:5)
    at Object.callFn (/www/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/www/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by fastCreator** [comment]
2019-10-02 15:43:52,403 ERROR 4172 nodejs.AgentWorkerDiedError: [master] agent_worker#1:4160 died (code: 1, signal: null)
    at Master.onAgentExit (E:\compass\server\node_modules\_egg-cluster@1.25.0@egg-cluster\lib\master.js:425:17)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (E:\compass\server\node_modules\_egg-cluster@1.25.0@egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\compass\server\node_modules\_egg-cluster@1.25.0@egg-cluster\lib\utils\messenger.js:102:12)
    at ChildProcess.agentWorker.once (E:\compass\server\node_modules\_egg-cluster@1.25.0@egg-cluster\lib\master.js:289:22)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
name: "AgentWorkerDiedError"

**Comment by shotforsky** [comment]
possibly a node/npm version issue, better try using another or higher node/npm version if there is no clue yet.

**Comment by dunizb** [comment]
> 已经解决了，感谢

卧槽，怎么解决的啊？公布一下啊，这个issues对别人没帮助啊

**Comment by dunizb** [comment]
@praeteritis @egg-bot 卧槽，怎么解决的啊？公布一下啊，这个issues对别人没帮助啊

**Comment by Fziqian** [comment]
@praeteritis 咋解决的啊，我也遇到了这个问题

**Comment by chenjiafeng1121** [comment]
我升级了node版本(12.x -> 14.x)并重新运行npm run dev解决了这个问题
