### ISSUE TITLE
npm install出错

### ISSUE THREAD

**Issue by lijinshanmx** [eggjs/egg#3625]
npm i
npm WARN deprecated @types/urllib@2.33.0: This is a stub types definition. urllib provides its own type definitions, so you do not need this installed.
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '...9ab1c36c3ee9f31f08e90'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lijinshan/.npm/_logs/2019-04-12T11_17_41_834Z-debug.log

**Comment by lijinshanmx** [comment]
npm ERR! Unexpected end of JSON input while parsing near '...9ab1c36c3ee9f31f08e90',应该是这里出问题了,我这边的环境是mac10.14,nodev10.15.3.

**Comment by lijinshanmx** [comment]
2304 silly saveTree   ├── egg-static@2.2.0
2304 silly saveTree   ├── egg-view@2.1.2
2304 silly saveTree   ├── egg-watcher@3.1.0
2304 silly saveTree   ├── extend2@1.0.0
2304 silly saveTree   ├── graceful@1.0.2
2304 silly saveTree   ├── humanize-ms@1.2.1
2304 silly saveTree   ├── is-type-of@1.2.1
2304 silly saveTree   ├── koa-bodyparser@4.2.1
2304 silly saveTree   ├── koa-is-json@1.0.0
2304 silly saveTree   ├── koa-override@3.0.0
2304 silly saveTree   ├── on-finished@2.3.0
2304 silly saveTree   ├── sendmessage@1.1.0
2304 silly saveTree   ├── urllib@2.33.3
2304 silly saveTree   ├── utility@1.16.1
2304 silly saveTree   └── ylru@1.2.1
2305 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...9ab1c36c3ee9f31f08e90'
2305 verbose stack     at JSON.parse (<anonymous>)
2305 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2305 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
2305 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
2306 verbose cwd /Users/lijinshan/Projects/poms_server
2307 verbose Darwin 18.5.0
2308 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2309 verbose node v10.15.3
2310 verbose npm  v6.4.1
2311 error Unexpected end of JSON input while parsing near '...9ab1c36c3ee9f31f08e90'
2312 verbose exit [ 1, true ]

**Comment by lijinshanmx** [comment]
解决了,来回的重试,clean cache,然后又一个一个的安装,最后就ok了.
