### ISSUE TITLE
[master] 1 agent and 0 worker(s) alive, exit to avoid unknown state 的意思是？

### ISSUE THREAD

**Issue by bymaxchen** [eggjs/egg#3641]
```
2019-04-19 16:38:10,671 ERROR 31528 nodejs.ClusterWorkerExceptionError: [master] 1 agent and 0 worker(s) alive, exit to avoid unknown state
    at Manager.Master.workerManager.on (/data/dev/we-chat/node_modules/egg-cluster/lib/master.js:134:19)
    at emitOne (events.js:116:13)
    at Manager.emit (events.js:211:7)
    at Timeout.timer.setInterval [as _onTimeout] (/data/dev/we-chat/node_modules/egg-cluster/lib/utils/manager.js:67:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterWorkerExceptionError"
count: {"agent":1,"worker":0}
pid: 31528
hostname: cvm-10_4_1_200
```

这个错误表达的意思是不是，当所有worker进程退出后，master也会退出？

**Comment by atian25** [comment]
嗯，因为正常情况下，worker 不应该全部退出的，挂了一个后 master 会立即重启一个。如果全部挂掉的话，就是僵死了。
