### ISSUE TITLE
egg-mongoose 3.1.2 url报错

### ISSUE THREAD

**Issue by salamander-mh** [eggjs/egg#3675]
## What happens?
对于这样的url  `mongodb://mongo:40031,mongo2:40031,mongo3:40031`
报错
```
TypeError [ERR_INVALID_URL]: Invalid URL: mongodb://spider:40031,mongo2:40031,mongo3:40031
admin_1_b02f67874576 |     at onParseError (internal/url.js:241:17)
admin_1_b02f67874576 |     at new URL (internal/url.js:319:5)
admin_1_b02f67874576 |     at filterURLPassword (/usr/src/app/node_modules/egg-mongoose/lib/filterURLPassword.js:20:15)
```
之前3.1.1还是正常的,今天线上打包启动发现报错了

## Context
- **Node Version**: 10.15
- **Egg Version**:  2.15
- **Plugin Name**:  egg-mongoose
- **Plugin Version**: 3.1.2
- **Platform**: Linux

**Comment by atian25** [comment]
再重新打下，刚才已经回滚了 dist-tag

```bash
$ npm dist-tags ls egg-mongoose
latest: 3.1.1
```
