### ISSUE TITLE
framework依赖的plugin在windows上必须在app里再定义一次才能加载，mac上没问题

### ISSUE THREAD

**Issue by guozefei** [eggjs/egg#3690]
## What happens?
我自己封装了一个framework egg-ydauthorization-framework，自己写了一个插件egg-passport-neteasecorp，egg-passport-neteasecorp插件依赖egg-passport插件，在egg-ydauthorization-framework中enable了egg-passport和egg-passport-neteasecorp插件，并且加了egg-passport-neteasecorp插件的相关配置，然后通过 npm init egg --type=simple 新建了一个应用使用egg-ydauthorization-framework，
app -> egg-ydauthorization-framework -> egg-passport-neteasecorp
在windows7上 发现 我还是必须在app中去enable egg-passport和egg-passport-neteasecorp插件并且还是必须在app的config.default.js中去配置egg-passport-neteasecorp的相关配置
在mac上可以正常运行

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
https://github.com/guozefei/egg-ydauthorization-framework-example

https://github.com/guozefei/egg-ydauthorization-framework-example

## How To Reproduce

**Steps to reproduce the behavior:**
1. cd node-pms-server
2. yarn
3. npm run debug

**Expected behavior**
正常运行

## Context
- **Node Version**:
8.11.2
- **Egg Version**:
2.3.0
- **Plugin Name**:
egg-passport egg-passport-neteasecorp
- **Plugin Version**:
- **Platform**:
windows7

**Comment by qingdengyue** [comment]
**macOS**
不用配置config/plugin.js 对应插件的enable，也可以使用插件

**Windows** 
必须配置config/plugin.js配置enable才能起作用。



是这个意思吧？在两个平台的配置部分，分别放上来吧。

**Comment by guozefei** [comment]
两个平台是同样的代码
https://github.com/guozefei/egg-ydauthorization-framework-example/blob/master/node-pms-server/config/plugin.js  这个是app里的Plugin，没有配置任何plugin
https://github.com/guozefei/egg-ydauthorization-framework-example/blob/master/egg-ydauthorization-framework/config/plugin.js 这个是framework中的plugin enable了egg-passport和egg-passport-neteasecorp插件
https://github.com/guozefei/egg-ydauthorization-framework-example/blob/master/egg-ydauthorization-framework/config/config.default.js 这个是framework的config.default.js 里面配置了egg-passport-neteasecorp的相关配置
mac和windows是一样的代码 但是mac可以正常run起来 windows7不行

**Comment by guozefei** [comment]
并且windows的 run/application_config.json里 plugins里已经有了passport和passportNeteasecorp
![捕获](https://user-images.githubusercontent.com/6120426/57504603-b048f180-7327-11e9-99e1-1248fb4415b8.PNG)

**Comment by guozefei** [comment]
windows上报错如下
![捕获](https://user-images.githubusercontent.com/6120426/57504647-dbcbdc00-7327-11e9-9289-673f9352f1c9.PNG)

**Comment by qingdengyue** [comment]
node-pms-server 这个工程有问题。你用 npm init egg --type=simple重新生成一下你这个工程。然后重新引入你写的framework。试一下。

**Comment by guozefei** [comment]
重新 npm init egg --type=simple 生成 node-pms-server之后还是会有同样的问题，在 https://github.com/guozefei/egg-ydauthorization-framework-example 中已经提交了

**Comment by guozefei** [comment]
windows里的node-pms-server下面的 /run/application_config.json里的plugins没有passport和passportNeteasecorp

**Comment by qingdengyue** [comment]
不对啊。
我这边生成的dependencies里是这样的：
![image](https://user-images.githubusercontent.com/3230673/57512267-cc578d80-733d-11e9-86d5-f453560f05af.png)
你的里面，怎么没有了 egg和egg-scripts 这两个依赖。
![image](https://user-images.githubusercontent.com/3230673/57512314-e2fde480-733d-11e9-8a71-57be434876fc.png)

**Comment by guozefei** [comment]
请问您那边直接用 https://github.com/guozefei/egg-ydauthorization-framework-example  在windows上是可以成功的 npm run debug run起来了吗？

**Comment by guozefei** [comment]
这个工程在mac上是可以成功run起来的 
我看 egg-examples里有 framework 和 progressive/step4
里面的 package.json是没有egg 和 egg-scripts的依赖的
![捕获](https://user-images.githubusercontent.com/6120426/57519210-55c28c00-734d-11e9-8729-ab19aa1ed1cd.PNG)
![捕获](https://user-images.githubusercontent.com/6120426/57519266-712d9700-734d-11e9-8403-b6133172bed8.PNG)

**Comment by qingdengyue** [comment]
不能啊，package.json缺egg的依赖，肯定起不来。你在其他环境试一下 npm init egg --type=simple 
egg,egg-script的依赖是必须存在的。

**Comment by qingdengyue** [comment]
现在的问题是:存在egg,egg-scripts是新建工程应该包含的，如果不存在，则工程本身就有问题。这个simple工程没有问题，如果还是启动不了，才能继续定位问题。

**Comment by guozefei** [comment]
![捕获](https://user-images.githubusercontent.com/6120426/57522336-054f2c80-7355-11e9-845a-080337b09771.PNG)
更新了node-pms-server的package.json 增加了egg和egg-scripts依赖，然后把node-pms-server下的node_modules目录删除后重新yarn 再次运行 npm run debug 还是会报错

**Comment by qingdengyue** [comment]
```

PS egg-ydauthorization-framework-example\node-pms-server> npm run debug

> node-pms-server@1.0.0 debugegg-ydauthorization-framework-example\node-pms-server
> egg-bin debug --port=8375

Debugger listening on ws://127.0.0.1:9229/d5a9730c-1c07-41ff-b7a0-320b2e58cc33
For help see https://nodejs.org/en/docs/inspector
[egg-ts-helper] create typings\app\controller\index.d.ts (12ms)
[egg-ts-helper] create typings\config\index.d.ts (12ms)
[egg-ts-helper] create typings\app\index.d.ts (3ms)
2019-05-10 19:20:47,831 INFO 229080 [master] node version v8.11.4
2019-05-10 19:20:47,832 INFO 229080 [master] egg-ydauthorization-framework version 1.0.0
Debugger listening on ws://127.0.0.1:5800/d567870a-659f-4370-a6d7-8e3e8744c5a4
For help see https://nodejs.org/en/docs/inspector
2019-05-10 19:20:49,528 INFO 229080 [master] agent_worker#1:29332 started (1693ms)
Debugger listening on ws://127.0.0.1:9230/4701db2f-ab21-4729-8bad-e5ec382a1864
For help see https://nodejs.org/en/docs/inspector
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
2019-05-10 19:20:51,962 INFO 229080 [master] egg-ydauthorization-framework started on http://127.0.0.1:8375 (4130ms)
```




我这边你用刚才更新的node-pms-server工程，使用 npm run debug  启动成功了。


8375端口可以正常访问。


我是 Windows 10 


你删除掉，node-pms-server 下的node_modules 目录，然后重新执行 npm install,然后运行 npm run debug ,并把打印的日志信息提供一下。

**Comment by guozefei** [comment]
好的，我下周一提供一下日志信息，因为现在不在那台电脑边了，多谢兄台，我回去在win10上也试试

**Comment by guozefei** [comment]
F:\git\egg-ydauthorization-framework-example2>cd node-pms-server

F:\git\egg-ydauthorization-framework-example2\node-pms-server>npm run debug

> node-pms-server@1.0.0 debug F:\git\egg-ydauthorization-framework-example2\node-pms-server
> egg-bin debug

Debugger listening on ws://127.0.0.1:9229/36b4402a-99a2-47fe-a5f2-52baacbbc708
For help see https://nodejs.org/en/docs/inspector
[egg-ts-helper] create typings\app\controller\index.d.ts (3ms)
[egg-ts-helper] create typings\config\index.d.ts (19ms)
[egg-ts-helper] create typings\config\plugin.d.ts (5ms)
[egg-ts-helper] create typings\app\index.d.ts (0ms)
2019-05-13 09:37:07,188 INFO 7244 [master] node version v8.11.2
2019-05-13 09:37:07,190 INFO 7244 [master] ydauthorization-framework version 1.0.0
Debugger listening on ws://127.0.0.1:5800/26227ab4-f262-43c4-84a8-753f3dfa9fea
For help see https://nodejs.org/en/docs/inspector
2019-05-13 09:37:08,762 INFO 7244 [master] agent_worker#1:4408 started (1568ms)
Debugger listening on ws://127.0.0.1:9230/a3b7e09e-fd44-462d-977f-23f1471fbfb1
For help see https://nodejs.org/en/docs/inspector
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg\lib\application.js:70
      throw e;
      ^

TypeError: Cannot read property 'authenticate' of undefined
    at module.exports.app (F:\git\egg-ydauthorization-framework-example2\node-pms-server\app\router.js:9:36)
    at AppWorkerLoader.loadFile (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\mixin\router.js:17:10)
    at AppWorkerLoader.load (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg\lib\loader\app_worker_loader.js:43:10)
    at new Application (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg\lib\application.js:66:19)
    at new Application (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-ydauthorization-framework\lib\framework.js:7:1)
    at Object.<anonymous> (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-cluster\lib\app_worker.js:19:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[2019-05-13 09:37:10.385] [cfork:master:7244] worker:5136 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-05-13 09:37:10.386] [cfork:master:7244] don't fork, because worker:5136 will be kill soon
2019-05-13 09:37:10,386 INFO 7244 [master] app_worker#1:5136 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2019-05-13 09:37:10.392] [cfork:master:7244] worker:5136 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-05-13 09:37:10,394 ERROR 7244 nodejs.AppWorkerDiedError: [master] app_worker#1:5136 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-cluster\lib\master.js:411:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.cluster.on (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-cluster\lib\master.js:280:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 7244
hostname: HIH-D-3021

2019-05-13 09:37:10,398 ERROR 7244 [master] app_worker#1:5136 start fail, exiting with code:1
2019-05-13 09:37:10,399 ERROR 7244 [master] exit with code:1

**Comment by guozefei** [comment]
之前是 1.删除 node_modules 2.yarn 3.npm run debug
我改为 1.删除 node_modules 2. npm install 3. npm run debug，日志变化：
F:\git\egg-ydauthorization-framework-example2\node-pms-server>npm run debug

> node-pms-server@1.0.0 debug F:\git\egg-ydauthorization-framework-example2\node-pms-server
> egg-bin debug

Debugger listening on ws://127.0.0.1:9229/52449b80-0026-481f-a32a-3cf147a36650
For help see https://nodejs.org/en/docs/inspector
cache-require-paths: Failed saving cache: Error: ENOENT: no such file or directory, open 'F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper\.tmp\requirePaths.json'
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application
    at EggLoader.getEggPaths (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\egg_loader.js:266:7)
    at new EggLoader (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
    at getLoader (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper\dist\scripts\eggInfo.js:71:12)
    at Object.<anonymous> (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper\dist\scripts\eggInfo.js:20:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
[egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
[egg-ts-helper] create typings\config\index.d.ts (21ms)
[egg-ts-helper] create typings\app\index.d.ts (0ms)
2019-05-13 09:54:52,821 INFO 6220 [master] node version v8.11.2
2019-05-13 09:54:52,822 INFO 6220 [master] egg-ydauthorization-framework version 1.0.0
Debugger listening on ws://127.0.0.1:5800/3656914c-f283-4643-a261-c39eede67de4
For help see https://nodejs.org/en/docs/inspector
2019-05-13 09:54:55,434 INFO 6220 [master] agent_worker#1:1028 started (2607ms)
Debugger listening on ws://127.0.0.1:9230/2daa7898-9de5-44ab-9330-be4a4f828e0d
For help see https://nodejs.org/en/docs/inspector
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
2019-05-13 09:54:58,659 INFO 6220 [master] egg-ydauthorization-framework started on http://127.0.0.1:7001 (5836ms)

**Comment by qingdengyue** [comment]
后面这个 就是已经启动成功了。7001 可以访问接口了。

```
2019-05-13 09:54:58,659 INFO 6220 [master] egg-ydauthorization-framework started on http://127.0.0.1:7001 (5836ms)
```

**Comment by atian25** [comment]
最近挺忙的，现在是啥情况了？

复现方式是一楼那个还是？

**Comment by guohuihot** [comment]
> 之前是 1.删除 node_modules 2.yarn 3.npm run debug
> 我改为 1.删除 node_modules 2. npm install 3. npm run debug，日志变化：
> F:\git\egg-ydauthorization-framework-example2\node-pms-server>npm run debug
> 
> > node-pms-server@1.0.0 debug F:\git\egg-ydauthorization-framework-example2\node-pms-server
> > egg-bin debug
> 
> Debugger listening on ws://127.0.0.1:9229/52449b80-0026-481f-a32a-3cf147a36650
> For help see https://nodejs.org/en/docs/inspector
> cache-require-paths: Failed saving cache: Error: ENOENT: no such file or directory, open 'F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper.tmp\requirePaths.json'
> assert.js:42
> throw new errors.AssertionError({
> ^
> 
> AssertionError [ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application
> at EggLoader.getEggPaths (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\egg_loader.js:266:7)
> at new EggLoader (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
> at getLoader (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper\dist\scripts\eggInfo.js:71:12)
> at Object. (F:\git\egg-ydauthorization-framework-example2\node-pms-server\node_modules\egg-bin\node_modules\egg-ts-helper\dist\scripts\eggInfo.js:20:16)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Function.Module.runMain (module.js:693:10)
> [egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
> [egg-ts-helper] create typings\config\index.d.ts (21ms)
> [egg-ts-helper] create typings\app\index.d.ts (0ms)
> 2019-05-13 09:54:52,821 INFO 6220 [master] node version v8.11.2
> 2019-05-13 09:54:52,822 INFO 6220 [master] egg-ydauthorization-framework version 1.0.0
> Debugger listening on ws://127.0.0.1:5800/3656914c-f283-4643-a261-c39eede67de4
> For help see https://nodejs.org/en/docs/inspector
> 2019-05-13 09:54:55,434 INFO 6220 [master] agent_worker#1:1028 started (2607ms)
> Debugger listening on ws://127.0.0.1:9230/2daa7898-9de5-44ab-9330-be4a4f828e0d
> For help see https://nodejs.org/en/docs/inspector
> 9230 opened
> Debug Proxy online, now you could attach to 9999 without worry about reload.
> DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/**ws_proxy**
> 2019-05-13 09:54:58,659 INFO 6220 [master] egg-ydauthorization-framework started on http://127.0.0.1:7001 (5836ms)

都没遇到吗？我也 是这样的问题，虽然跑起来了，但是会报错
Symbol.for('egg#eggPath') is required

**Comment by atian25** [comment]
参考下 https://zhuanlan.zhihu.com/p/154643011

有新的问题可以重新提 issue
