### ISSUE TITLE
webstorm启动进程kill不了

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3694]
直接启动和启动debug都会报错

```js

> xserver@1.0.1 debug /Users/xx/xserver
> egg-bin debug

Debugger listening on ws://127.0.0.1:9229/8dc555b6-702f-4237-afd8-9307808d2203
For help, see: https://nodejs.org/en/docs/inspector
2019-05-13 10:56:18,554 INFO 33652 [master] node version v10.12.0
2019-05-13 10:56:18,558 INFO 33652 [master] egg version 2.20.1
Starting inspector on 127.0.0.1:5800 failed: address already in use
2019-05-13 10:56:18,606 ERROR 33652 nodejs.AgentWorkerDiedError: [master] agent_worker#1:33653 died (code: 12, signal: null)
    at Master.onAgentExit (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/master.js:338:17)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at ChildProcess.agentWorker.once (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/master.js:229:22)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AgentWorkerDiedError"
pid: 33652
hostname: localhost

2019-05-13 10:56:18,606 ERROR 33652 [master] agent_worker#1:33653 start fail, exiting with code:1
2019-05-13 10:56:18,607 ERROR 33652 [master] exit with code:1

Process finished with exit code 0
```
已尝试方法
---
1. lsof -i:5800 并kill 没用
1. 重启webstorm 没用

**Comment by killagu** [comment]
try kill -9

**Comment by MJingv** [comment]
> try kill -9

重启电脑可以 
kill -9也不行

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
