### ISSUE TITLE
egg.js服务报错

### ISSUE THREAD

**Issue by fabin5** [eggjs/egg#3706]
[2019-05-15 14:01:41.200] [cfork:master:4420] master uncaughtException: TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (xxxxx\node_modules\egg-cluster\lib\master.js:174:16)
    at Server.emit (events.js:182:13)
    at TCP.onconnection (net.js:1519:8)
TypeError: Cannot read property 'send' of undefined
    at Server.require.createServer.connection (xxxxx\node_modules\egg-cluster\lib\master.js:174:16)
    at Server.emit (events.js:182:13)
    at TCP.onconnection (net.js:1519:8)
(total 1 disconnect, 0 unexpected exit)

**Comment by atian25** [comment]
看起来像是单进程 messenger 重构后的那个问题，你重新安装下依赖应该就 OK 了。

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by myouj** [comment]
I also had this problem, but it didn't happen after I changed the nodejs version to v8.12.0
