### ISSUE TITLE
:

### ISSUE THREAD

**Issue by kebichishaobing** [eggjs/egg#3714]
- **Node Version**: v8.11.1
- **Egg Version**: 2.22.2
- **Plugin Name**: egg-schedule
- **Plugin Version**: 3.6.2
- **Platform**: windows

Create a custom schedule type according official website:
https://eggjs.org/en/basics/schedule.html#extend-scheduled-task-type

//agent.js
module.exports = function(agent) {
    class CustomStrategy extends agent.ScheduleStrategy {
        start() {
            // such as mq / redis subscribe
            agent.mq.subscribe('doSomething', data => {
                this.sendOne(data);
            });
        }
    }
    agent.schedule.use('custom', CustomStrategy);
};

//schedule/doSomething.js
const Subscription = require('egg').Subscription;
class ClusterTask extends Subscription {
    static get schedule() {
        return {
            type: 'custom',
        };
    }
    async subscribe(data) {
        console.log('got custom data:', data);
    }
}
module.exports = ClusterTask;

error when run:
2019-05-17 20:45:45,625 ERROR 23672 nodejs.TypeError: Cannot read property 'subscribe' of undefined
    at CustomStrategy.start (E:\Project\test_agent_strategy\agent.js:7:22)
    at Schedule.start (E:\Project\test_agent_strategy\node_modules\egg-schedule\lib\schedule.js:71:16)
    at Messenger.agent.messenger.once (E:\Project\test_agent_strategy\node_modules\egg-schedule\agent.js:23:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Messenger.emit (events.js:211:7)
    at Messenger._onMessage (E:\Project\test_agent_strategy\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)

**Comment by atian25** [comment]
@kebichishaobing 如能提供一个最小可复现仓库后，可以 reopen 这个 issue
