### ISSUE TITLE
启动npm run dev，出现错了？？？

### ISSUE THREAD

**Issue by next2014** [eggjs/egg#373]
➜  showcase npm run dev

> showcase@1.0.0 dev /Users/next/showcase
> egg-bin dev

/Users/next/showcase/node_modules/sdk-base/index.js:35
      const newListener = (...args) => {
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/next/showcase/node_modules/egg/lib/core/agent_worker_client.js:5:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
[common-bin] run dev with ["--baseDir","/Users/next/showcase","--cluster","1","--eggPath=/Users/next/showcase/node_modules/egg"] at /Users/next/showcase error:
Error: /Users/next/showcase/node_modules/egg-bin/lib/start-cluster --baseDir,/Users/next/showcase,--cluster,1,--eggPath=/Users/next/showcase/node_modules/egg exit with code 1
    at ChildProcess.<anonymous> (/Users/next/showcase/node_modules/common-bin/lib/helper.js:31:21)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/next/.nvm/versions/node/v5.4.0/bin/node" "/Users/next/.nvm/versions/node/v5.4.0/bin/npm" "run" "dev"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! showcase@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the showcase@1.0.0 dev script 'egg-bin dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the showcase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     egg-bin dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls showcase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/next/showcase/npm-debug.log

**Comment by atian25** [comment]
> npm ERR! node v5.4.0

egg 最低支持的 node 版本是 6.x，而且 5.x 是不稳定版本，升级下你的 node 即可。
