### ISSUE TITLE
测试定时任务功能时报错：s.subscribe is not a function

### ISSUE THREAD

**Issue by kaindy7633** [eggjs/egg#3737]
## What happens?
今天想测试一下定时任务功能，我这里是使用的 `Typescript`，代码如下：

```ts
import { Subscription } from 'egg';

class TestSubscription extends Subscription {
  // ...
  static get schedule() {
    return {
      interval: '10s',
      type: 'worker',
      immediate: true,
    };
  }

  // ...
  async schedule() {
    console.log('我是每隔1分钟就会被执行一次的定时任务...');
  }
}

module.exports = TestSubscription;
```

很简单的一个测试定时任务的代码，但启动之后就报错：

```
2019-05-31 11:49:05,637 ERROR 36956 nodejs.TypeError: s.subscribe is not a function (uncaughtException throw 1 times on pid:36956)
    at Object.task (E:\myProject\xunboba-api-project\node_modules\egg-schedule\lib\load_schedule.js:37:22)
    at Messenger.app.messenger.on.info (E:\myProject\xunboba-api-project\node_modules\egg-schedule\app.js:46:21)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (E:\myProject\xunboba-api-project\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:194:15)
    at process.emit (E:\myProject\xunboba-api-project\node_modules\source-map-support\source-map-support.js:465:21)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 36956
hostname: DESKTOP-FK4MR79
```

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：10.15.3
- **Egg 版本**：2.22.2

**Comment by atian25** [comment]
`async schedule() {` 是什么鬼，文档是 `async subscribe() {`

**Comment by sunjianfengHub** [comment]
> ## 会发生什么？
> 想每天测试一下定时任务功能，我这里是使用的`Typescript`，代码如下：
> 
> ```ts
>  从'鸡蛋'导入{ 订阅 }  ； 
> 
> class  TestSubscription  extends  Subscription  { 
>   // ... 
>   static  get  schedule ( )  { 
>     return  { 
>       interval : '10s' , 
>       type : 'worker' , 
>       immediate : true , 
>     } ; 
>   }
> 
>   // ...
>   异步 调度( )  {
>     控制台. log ( '我是每一次被执行一次的定时任务...' ) ; 
>   } 
> }
> 
> 模块。出口 = 测试订阅；
> ```
> 
> 很简单的一个测试任务的代码，但是启动之后就报错：
> 
> ```
> 2019-05-31 11:49:05,637 ERROR 36956 nodejs.TypeError: s.subscribe is not a function (uncaughtException throw 1 times on pid:36956)
>     at Object.task (E:\myProject\xunboba-api-project\node_modules\egg-schedule\lib\load_schedule.js:37:22)
>     at Messenger.app.messenger.on.info (E:\myProject\xunboba-api-project\node_modules\egg-schedule\app.js:46:21)
>     at Messenger.emit (events.js:189:13)
>     at Messenger._onMessage (E:\myProject\xunboba-api-project\node_modules\egg\lib\core\messenger\ipc.js:116:12)
>     at process.emit (events.js:194:15)
>     at process.emit (E:\myProject\xunboba-api-project\node_modules\source-map-support\source-map-support.js:465:21)
>     at emit (internal/child_process.js:820:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> 
> pid: 36956
> hostname: DESKTOP-FK4MR79
> ```
> 
> ## 相关环境信息
> * **操作系统**：windows10
> * **节点版本**：10.15.3
> * **鸡蛋版本**：2.22.2
你好，请问您解决了吗？我猜测是ts与egg的直接的关系
