### ISSUE TITLE
egg-redis 连接长时间后无响应自动断开是否会自动重新连接

### ISSUE THREAD

**Issue by MonsterRHD** [eggjs/egg#3786]
长时间连接后自动断开后，请问egg-redis 是否会重新自动连接呢？

报错代码
`019-06-28 17:20:06,587 WARN 10960 [ClusterClient:Watcher] follower closed, and try to init it again
2019-06-28 17:20:06,593 ERROR 792 nodejs.ClusterClientNoResponseError: client no response in 3151986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\lenovo\Desktop\haowuadmin\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 792
hostname: DESKTOP-699PGPQ

    2019-06-28 17:20:16,569 ERROR 10960 [egg-redis] client error: Error: read ECONNRESET
    2019-06-28 17:20:16,576 ERROR 10960 nodejs.ECONNRESETError: read ECONNRESET
        at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
    errno: "ECONNRESET"
    code: "ECONNRESET"
    syscall: "read"
    name: "ECONNRESETError"
    pid: 10960
    hostname: DESKTOP-699PGPQ`

## 相关环境信息
- **操作系统**：
win
- **Node 版本**：
10.16.0
- **Egg 版本**：
2.22.2

**Comment by qingdengyue** [comment]
如果没有手动调用disconnect或者quit，则egg-redis 内部的ioredis会自动重连。
https://github.com/luin/ioredis#auto-reconnect

**Comment by MonsterRHD** [comment]
> 如果没有手动调用disconnect或者quit，则egg-redis内部的ioredis会自动重连
> [.https：//github.com/luin/ioredis#auto-reconnect](https://github.com/luin/ioredis#auto-reconnect)

那其实这个报错信息 不用管他就好啦 对吧

**Comment by qingdengyue** [comment]
> > 如果没有手动调用disconnect或者quit，则egg-redis内部的ioredis会自动重连
> > [.https：//github.com/luin/ioredis#auto-reconnect](https://github.com/luin/ioredis#auto-reconnect)
> 
> 那其实这个报错信息 不用管他就好啦 对吧

是的。
