### ISSUE TITLE
egg-router-plus namespace 为根 '/' 时，再在该 namespace 下定义其他路由时并不生效

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3789]
## What happens?

当定义了一个 '/' 名称的 namepsace 后，在其下定义的其他路由不会报错，但是实际上不生效，会是 404。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/Jeff-Tian/egg-router-plus-bug

## 复现步骤，错误日志以及相关配置

运行以下命令，即可重现 BUG
```
git clone https://github.com/Jeff-Tian/egg-router-plus-bug
npm i
npm run test-local 
```

```
➜ npm run test-local

> egg-router-plus-bug@1.0.0 test-local /Users/jefftian/egg-router-plus-bug
> egg-bin test



  test/app/controller/home.test.ts
    ✓ should GET /
    1) should redirect

  test/app/service/Test.test.js
    ✓ sayHi


  2 passing (535ms)
  1 failing

  1) test/app/controller/home.test.ts
       should redirect:
     Error: expected 302 "Found", got 404 "Not Found"
      at process._tickCallback (internal/process/next_tick.js:180:9)
      [use `--full-trace` to display the full stack trace]



{ Error: /Users/jefftian/egg-router-plus-bug/node_modules/egg-bin/node_modules/mocha/bin/_mocha --declarations,--timeout=60000,--exit,--require=/Users/jefftian/egg-router-plus-bug/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/jefftian/egg-router-plus-bug/node_modules/co-mocha/lib/co-mocha.js,--require=/Users/jefftian/egg-router-plus-bug/node_modules/intelli-espower-loader/intelli-espower-loader.js,--require=/Users/jefftian/egg-router-plus-bug/node_modules/espower-typescript/guess.js,test/app/controller/home.test.ts,test/app/service/Test.test.ts exit with code 1
    at ChildProcess.proc.once.code (/Users/jefftian/egg-router-plus-bug/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-router-plus-bug@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-router-plus-bug@1.0.0 test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jefftian/.npm/_logs/2019-07-01T03_55_10_282Z-debug.log
```

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：v8.11.3
- **Egg 版本**：latest

**Comment by atian25** [comment]
为什么你要定义了一个 '/' 名称的 namespace？

**Comment by Jeff-Tian** [comment]
老项目就是存在这个 namepsace。所以是用法不正确？那我改掉它。

**Comment by Jeff-Tian** [comment]
那 egg-router-plus 文档里是不是可以把这个单独说明一下，以防止掉坑里……

**Comment by atian25** [comment]
https://github.com/eggjs/egg-router-plus/blob/master/lib/router.js#L65

因为你相当于定义了 `router.get('//xxx')` 了。
