### ISSUE TITLE
[egg-sequelize]v4升级v5报错。

### ISSUE THREAD

**Issue by diangong** [eggjs/egg#3794]
新项目初始化后，配置egg-sequelize v4可以启动，升级到v5服务不能启动。

**Comment by whxaxes** [comment]
自行看 sequelize 4 到 5 之间的区别

**Comment by diangong** [comment]
配置需要改吗?我直接按照V5的说明配置，服务没法启动，改回V4可以启动，而且看了你们升级的COMMIT 没有看到文档中关于配置需要修改的内容。

**Comment by whxaxes** [comment]
配置不需要改，参考：https://github.com/eggjs/examples/tree/master/sequelize

**Comment by diangong** [comment]
直接clone 官方例子，我也没法运行。
2019-07-03 11:47:48,775 INFO 7044 [master] node version v12.0.0
2019-07-03 11:47:48,777 INFO 7044 [master] egg version 2.22.2


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000111875DD502019-07-03 11:47:50,492 ERROR 7044 nodejs.AgentWorkerDiedError: [master] agent_worker#1:13760 died (code: 3221225477, signal: null)
    at Master.onAgentExit (F:\examples\sequelize\node_modules\egg-cluster\lib\master.js:358:17)
    at Master.emit (events.js:196:13)
    at Messenger.sendToMaster (F:\examples\sequelize\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (F:\examples\sequelize\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at ChildProcess.<anonymous> (F:\examples\sequelize\node_modules\egg-cluster\lib\master.js:249:22)
    at Object.onceWrapper (events.js:284:20)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
name: "AgentWorkerDiedError"
pid: 7044
hostname: DESKTOP-2F8PU43

2019-07-03 11:47:50,496 ERROR 7044 [master] agent_worker#1:13760 start fail, exiting with code:1
2019-07-03 11:47:50,497 ERROR 7044 [master] exit with code:1
Error: F:\examples\sequelize\node_modules\egg-bin\lib\start-cluster {"workers":1,"baseDir":"F:\\examples\\sequelize","framework":"F:\\examples\\sequelize\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (F:\examples\sequelize\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:284:20)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sequelize-example@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sequelize-example@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by diangong** [comment]
MariaDB 10.3 例子的 migration 都没法运行

**Comment by whxaxes** [comment]
https://github.com/nodejs/node/issues/27379   nodejs 的 bug ，把 node 版本换成 10 就可以

**Comment by diangong** [comment]
OK了，感谢大佬的帮助
