### ISSUE TITLE
使用egg-sequelize后，定义model后在没有挂载到ctx上

### ISSUE THREAD

**Issue by sunweifei** [eggjs/egg#3845]
## What happens?
使用egg-sequelize后，定义model后在没有挂载到ctx上

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

https://github.com/sunweifei/eggDemo

## 复现步骤，错误日志以及相关配置
init项目后按照官网教程使用egg-sequelize在controller层使用model时报错
报错内容：
ERROR 2620 [-/::1/-/6ms GET /] nodejs.TypeError: Cannot read property 'User' of undefined
    at HomeController.index (F:\testProduction\egg-sql01\app\controller\home.js:10:34)
    at Object.callFn (F:\testProduction\egg-sql01\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\testProduction\egg-sql01\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\testProduction\egg-sql01\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\testProduction\egg-sql01\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\testProduction\egg-sql01\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at next (F:\testProduction\egg-sql01\node_modules\@eggjs\router\node_modules\koa-compose\index.js:45:18)
    at F:\testProduction\egg-sql01\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (F:\testProduction\egg-sql01\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at F:\testProduction\egg-sql01\node_modules\@eggjs\router\node_modules\koa-compose\index.js:36:12

pid: 2620

## 相关环境信息
- **win10 64**：
- **node 12.3.1**：
- **Egg 2.15.1**：

**Comment by sunweifei** [comment]
自己的疏忽，没有在plugin种配置egg-sequelize
