### ISSUE TITLE
egg-mongoose 可以在 connection closed 之后重试连接吗？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3848]
## What happens?

一个 egg 项目引用了 egg-mongoose 插件，发现某些实例挂了，看日志显示是因为 mongodb 连接被关闭。有没有办法在这种事件发生后自动重连呢？

```
2019-07-26 09:46:35,440 ERROR 47 [master] app_worker#1:75 start fail, exiting with code:1
2019-07-26 09:46:35,440 ERROR 47 [master] exit with code:1
2019-07-26 09:46:35,446 ERROR 76 [egg-mongoose] mongodb://****?replicaSet=mgset-4016449 disconnected
2019-07-26 09:46:35,448 ERROR 76 nodejs.MongoError: [egg-mongoose]connection 2 to dds-***.mongodb.rds.aliyuncs.com:3717 closed
    at Function.MongoError.create (/app/node_modules/egg-mongoose/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/app/node_modules/egg-mongoose/node_modules/mongodb-core/lib/connection/connection.js:214:22)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)
name: 'MongoError'
message: '[egg-mongoose]connection 2 to dds-***.mongodb.rds.aliyuncs.com:3717 closed'
pid: 76
hostname: ***-7fd45b64cf-cxqgk
```

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

抱歉，这个不是一定能重现的，同时启动多个实例，只有某些实例出现……

![image](https://user-images.githubusercontent.com/3367820/61920986-1db30880-af8e-11e9-8355-1349181eba7b.png)

## 复现步骤，错误日志以及相关配置

日志如上。配置如下：

```
  config.mongoose = {
    client: {
      url:
        'mongodb://***.rds.aliyuncs.com:3717/***',
      options: {
        useMongoClient: true,
        autoReconnect: true,
        keepAlive: 120,
        connectTimeoutMS: 30000,
        reconnectTries: 30,
        reconnectInterval: 5000,
      },
    },
  }
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by whxaxes** [comment]
mongoose 默认支持重连的，这个不需要 egg-mongoose 里做处理

![image](https://user-images.githubusercontent.com/5856440/62935446-bc968c00-bdf9-11e9-98c3-9c8a2b72c164.png)

只要你没设置这个 autoReconnect 为 false 就行

**Comment by Jeff-Tian** [comment]
并没有配置 `autoReconnect: false`，不清楚为啥 mongoose 没有自动重连。想在捕捉到这种连接错误信息后，强行自已写代码重连，不知道 `egg-mongoose` 支不支持这种事件监听？比如

```
config.mongoose = {
    client: {
      onerror(err) {
           // 这里可以自行写代码重新连接
      }, 
      url:
        'mongodb://***.rds.aliyuncs.com:3717/***',
      options: {
        useMongoClient: true,
        autoReconnect: true,
        keepAlive: 120,
        connectTimeoutMS: 30000,
        reconnectTries: 30,
        reconnectInterval: 5000,
      },
    },
  }
```

**Comment by whxaxes** [comment]
@Jeff-Tian 

支持的

```js
app.mongoose.on('disconnect', () => {
   // do something
})
```

**Comment by Jeff-Tian** [comment]
谢谢！

**Comment by unclexiao** [comment]
应该先定位为什么会连接不上，其次再找自动重连，比如，MongoDB服务端是否做了最大连接数量限制？

```shell
> db.serverStatus().connections
# { "current" : 1, "available" : 203, "totalCreated" : 103, "active" : 1 }
```

连接之前看看**available**是否充足？
