### ISSUE TITLE
webstorm debugger 5800kill不了

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3875]
lsof -i:5800
kill -9 pid
之后5800又会出现pid
这个问题出现了很多次了，希望大佬们能看看
---

/Users/xx/.nvm/versions/node/v10.12.0/bin/node /Users/xx/.nvm/versions/node/v10.12.0/lib/node_modules/npm/bin/npm-cli.js run debug --scripts-prepend-node-path=auto

To debug the "debug" script, make sure the $NODE_DEBUG_OPTION string is specified as the first argument for the node command you'd like to debug.
For example:
  "scripts": {
    "start": "node $NODE_DEBUG_OPTION server.js"
  }

> xserver@1.0.1 debug /Users/xx/pro/xserver
> egg-bin debug

Use $NODE_DEBUG_OPTION: --inspect-brk=61029
Debugger listening on ws://127.0.0.1:61029/714e72e8-5a8b-4417-9e90-be364d1d3b2b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2019-08-07 15:21:22,351 INFO 22171 [master] node version v10.12.0
2019-08-07 15:21:22,356 INFO 22171 [master] egg version 2.22.2
Starting inspector on 127.0.0.1:5800 failed: address already in use
2019-08-07 15:21:22,475 ERROR 22171 nodejs.AgentWorkerDiedError: [master] agent_worker#1:22184 died (code: 12, signal: null)
    at Master.onAgentExit (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/master.js:358:17)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at ChildProcess.agentWorker.once (/Users/xx/pro/xserver/node_modules/egg-cluster/lib/master.js:249:22)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AgentWorkerDiedError"
pid: 22171
hostname: localhost

2019-08-07 15:21:22,476 ERROR 22171 [master] agent_worker#1:22184 start fail, exiting with code:1
2019-08-07 15:21:22,477 ERROR 22171 [master] exit with code:1

**Comment by atian25** [comment]
请提供可复现方式。

另外， `NODE_DEBUG_OPTION` 是不需要的，看下 egg 文档开发章节。
