### ISSUE TITLE
You have used the alias xxx in two separate associations. Aliased associations must have unique aliases.

### ISSUE THREAD

**Issue by KevinHades** [eggjs/egg#3901]
## What happens?
Aliased associations must have unique aliases。

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.定义
//hot_opus.js
```
module.exports = app => {
  const DataTypes = app.Sequelize;
  const HotOpus = app.kankanModel.define('hotOpus', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      field: 'id'
    },
    userId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: '0',
      unique: true,
      field: 'user_id'
    },, {
    tableName: 'hot_opus'
  });
  HotOpus.associate = function() {

    app.kankanModel.HotOpus.belongsTo(app.kankanModel.Anchor, {foreignKey: 'userId', targetKey: 'userId'});
  }
  return HotOpus;
};
```

//anchor.js
```
module.exports = app => {
  const DataTypes = app.Sequelize;
  const Anchor = app.kankanModel.define('anchor', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      field: 'id'
    },
   userId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: '0',
      unique: true,
      field: 'user_id'
    },
  }, {
    tableName: 'anchor'
  });
  Anchor.associate = function() {
    app.kankanModel.Anchor.hasMany(app.kankanModel.HotOpus, {as: 'opus', foreignKey: 'userId', sourceKey: 'userId'});
  }
  return Anchor;
};
```

//controller
```
await ctx.kankanModel.Anchor.findAndCountAll({
    ...
    include:[
        {
            model: ctx.model.HotOpus,
            as: 'opus'
        }
    ]
});
```
2.npm run dev

**Expected behavior**
1.
```
SequelizeAssociationError: You have used the alias hopus in two separate associations. Aliased associations must have unique aliases.
    at new Association (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/associations/base.js:106:13)
    at new HasMany (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/associations/has-many.js:19:5)
    at Function.hasMany (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/associations/mixin.js:34:25)
    at Function.Anchor.associate (/Users/kevinwork/Node/kankanOpenAPI/app/model/kankan/anchor.js:177:28)
    at models.forEach.model (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-sequelize/lib/loader.js:118:54)
    at Array.forEach (<anonymous>)
    at loadDatabase (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-sequelize/lib/loader.js:117:12)
    at config.datasources.forEach.datasource (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-sequelize/lib/loader.js:35:22)
    at Array.forEach (<anonymous>)
    at module.exports.app (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-sequelize/lib/loader.js:34:24)
    at module.exports.app (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-sequelize/app.js:4:26)
    at Hook.configDidLoad (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/lifecycle.js:92:9)
    at Lifecycle.triggerConfigDidLoad (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/lifecycle.js:147:14)
    at Lifecycle.triggerConfigWillLoad (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/lifecycle.js:141:10)
    at AppWorkerLoader.loadCustomApp (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
    at AppWorkerLoader.load (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg/lib/loader/app_worker_loader.js:35:10)
    at new Application (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg/lib/application.js:66:19)
    at Object.<anonymous> (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-cluster/lib/app_worker.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```
把as去掉，调试发现anchor.js这个model被sequelize加载了三次
## Context
- **Node Version**: v10.16.2
- **Egg Version**: 2.15.1
- **Plugin Name**: egg-sequelize
- **Plugin Version**: 5.2.0
- **Platform**: macos

**Comment by atian25** [comment]
同一个进程 3 次？

**Comment by KevinHades** [comment]
> 同一个进程 3 次？

应该是的，在egg-sequelize中有hasAlias的方法检测别名，在那里做输出后发现加载三次的问题，第一次hasAlias为false，加载第二次时应该是因为缓存问题，hasAlias为true导致报这个错误，另外附上这个问题的一些补充信息：
1、sequelize用的是多数据源datasources(不知道是否为这个问题，但是数据源大于三个）
2、在我查看了eggjs/example下的例子后发现，官方定义了两个model，user与post，在user的model中定义associate的时使用了prototype
```js
User.prototype.associate = function() {
    ...
}
```
我在项目中也加上了prototype后不会再报以上文中的错误，但是出现了别名失效的错误：
```js
ror: hotOpus is not associated to anchor!
    at Function._getIncludedAssociation (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:715:13)
    at Function._validateIncludedElement (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:619:53)
    at options.include.options.include.map.include (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:516:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:511:39)
    at Function.aggregate (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:1953:12)
    at Promise.try.then (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:2042:19)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Function.count (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:2026:8)
    at Function.findAndCountAll (/Users/kevinwork/Node/kankanOpenAPI/node_modules/sequelize/lib/model.js:2094:12)
    at TestModel.getAnchorByRegionId (/Users/kevinwork/Node/kankanOpenAPI/app/service/v1_0_0/gifshow/testModel.js:68:61)
    at TestModel.getAnchorByRegionId (/Users/kevinwork/Node/kankanOpenAPI/app/controller/v1_0_0/gifshow/testModel.js:106:72)
    at Object.callFn (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/kevinwork/Node/kankanOpenAPI/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/kevinwork/Node/kankanOpenAPI/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/kevinwork/Node/kankanOpenAPI/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/kevinwork/Node/kankanOpenAPI/node_modules/koa-compose/index.js:44:32)
    at next (/Users/kevinwork/Node/kankanOpenAPI/node_modules/koa-compose/index.js:45:18)
    at /Users/kevinwork/Node/kankanOpenAPI/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/kevinwork/Node/kankanOpenAPI/node_modules/koa-compose/index.js:44:32)
    at /Users/kevinwork/Node/kankanOpenAPI/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/kevinwork/Node/kankanOpenAPI/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/kevinwork/Node/kankanOpenAPI/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/kevinwork/Node/kankanOpenAPI/app/middleware/auth.js:56:27)
name: "SequelizeEagerLoadingError"
pid: 67391
hostname: bihumarketdeAir
```
但是我在model与find查询中都已经声明了as参数。

**Comment by KevinHades** [comment]
```js 
 Anchor.associate = function() {
    console.log('this is anchor.associate')
    if(!app.kankanModel.Anchor.hasAlias('hopus')) {
      app.kankanModel.Anchor.hasOne(app.kankanModel.HotOpus, {as: 'hopus' , foreignKey: 'userId', sourceKey: 'userId'});
    }
  }
```
可规避错误

**Comment by KevinHades** [comment]
我很想知道是egg-sequelize的加载的问题，还是我这边的问题，如果我是这边的问题，我很想知道大概是哪方面的问题，我也以从什么地方入手去排除这个问题

**Comment by atian25** [comment]
可以调试下 egg-sequelize 的 loader 分析定位下问题

**Comment by KevinHades** [comment]
调了一遍加载过程，发现问题是多数据源设置中，一共设置了四个数据源，但是有两个数据源的的时候有两个数据源的baseDir参数，设置成了其他两个数据源的父级路径，而加载的时候是遍历所设置的baseDir，导致加载的时候两个正确的数据源的model都会加载三次。小问题，是我没检查好。附上错误对的配置与正确的配置对比：
```
datasources: [
        {
          dialect: 'mysql',
          delegate: 'aaModel',
          baseDir: 'model/aa',  //问题出在这里，错误的与其他数据源混淆
          database: 'aa',
          host: 'serverIp',
          port: 'serverPort',
          username: 'user',
          password: 'pass',
          freezeTableName: false,
          underscored: true

        },
        {
          dialect: 'mysql',
          delegate: 'bbModel',
          baseDir: 'model',       //这里的dir设置成了第一个数据源的父级目录，加载时深度遍历了目录，导致同一model加载多次的问题
          database: 'bb',
          host: 'serverIp',
          port: 'serverPort',
          username: 'user',
          password: 'pass',
          freezeTableName: false,
          underscored: true
        }]
```
