### ISSUE TITLE
egg-utils 这模块不维护?

### ISSUE THREAD

**Issue by sqlwwx** [eggjs/egg#3911]
build error好久啦

**Comment by whxaxes** [comment]
原因是 travis 配置有问题，欢迎 PR （ clone 下来装一下依赖，travis.yml 就会自动更新为正常版本的 ）

**Comment by sqlwwx** [comment]
本来拉下来测试也是一堆错误

**Comment by whxaxes** [comment]
那我晚点看一下

**Comment by sqlwwx** [comment]
```
AssertionError [ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application
    at EggLoader.getEggPaths (/home/wwx/project/weidian/egg-plugins/node_modules/egg-core/lib/loader/egg_loader.js:266:7)
    at new EggLoader (/home/wwx/project/weidian/egg-plugins/node_modules/egg-core/lib/loader/egg_loader.js:72:26)
    at getLoader (/home/wwx/project/weidian/egg-plugins/egg-utils/lib/plugin.js:48:10)
    at exports.getConfig.opt (/home/wwx/project/weidian/egg-plugins/egg-utils/lib/plugin.js:30:18)
    at Object.<anonymous> (/home/wwx/project/weidian/egg-plugins/egg-utils/test/fixtures/egg-app/get_config.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      8) should get configs using npminstall


  19 passing (3m)
  8 failing
```

**Comment by duncup** [comment]
@whxaxes 我这边看了一下，确实是配置问题。但是在加上node12后node12跑不通。

**Comment by thonatos** [comment]
@duncup 12 没发 LTS 先不加，CI 配置合并了
