### ISSUE TITLE
egg-router-plus namespace设置middleware后报错

### ISSUE THREAD

**Issue by ITHcc** [eggjs/egg#3950]
## What happens?
这里我想针对不同的路由组合来配置middleware，但是配置后报错. 

## How To Reproduce
[HPM] Proxy created: /  ->  http://localhost.brs.local:7001/
[HPM] Proxy rewrite rule created: "^/sso" ~> ""
2019-09-24 16:25:11,126 ERROR 16504 [-/127.0.0.1/-/32ms GET /gateway/userInfo] nodejs.TypeError: Cannot read property 'app' of undefined
    at new BaseContextClass (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\egg-core\lib\utils\base_context_class.js:25:20)
    at new BaseContextClass (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\egg\lib\core\base_context_class.js:13:1)
    at new LoginController (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\app\controller\gateway\login.js:4:1)
    at classControllerMiddleware (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\egg-core\lib\loader\mixin\controller.js:83:26)
    at dispatch (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\koa-compose\index.js:45:18)
    at C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\koa-compose\index.js:44:32)
    at C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\hcc\Desktop\brs-middleware\middleware-proxy\node_modules\@eggjs\router\lib\router.js:195:33)

pid: 16504
hostname: DESKTOP-785I615

**Comment by ITHcc** [comment]
已解决:
const testRouter = router.namespace('/test')
// 中间件需要传入app
testRouter .get('/a', middleware.permissions(app), controller.test.index);

**Comment by atian25** [comment]
这个跟 router 没关系，路由中间件是需要自己初始化的。

不过你这个初始化有问题，Koa 中间件都是 `(options, app)` 入参的，最好改改，前面加个 undefined 都好。
