### ISSUE TITLE
dotenv

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3958]
How can I use dotenv with eggjs?

I dont know where can I place `require('dotenv').config()`

**Comment by duncup** [comment]
You may need a app.js file, and create the file by your self.
https://eggjs.org/en/basics/structure.html
https://eggjs.org/en/basics/app-start.html

**Comment by atian25** [comment]
```js
// config/config.default.js
require('dotenv').config();

module.exports = () => {
  const config = {};

 config.xx = {
      host: process.env.DB_HOST,
      username: process.env.DB_USER,
      password: process.env.DB_PASS,
 };

  return config;
};
```

**Comment by sm2017** [comment]
@atian25 I placed it in plugin.js as it it imported sooner
Is it good place?

**Comment by atian25** [comment]
@sm2017 plugin.js is not a good place.

see the new Egg lifecyle docs

https://eggjs.org/en/advanced/loader.html#life-cycles

**Comment by sm2017** [comment]
@atian25 why? You told that `config/config.default.js` is good , why `plugin.js` is not?

![image](https://user-images.githubusercontent.com/19644997/65851900-5346ea00-e361-11e9-9498-4f5bef42fd6a.png)


I think that `plugin.js` is loaded before `config/config.default.js`

**Comment by atian25** [comment]
if you want to load it as far as possible, just add it to start script.

`egg-scripts start --require=xxx.js`

**Comment by atian25** [comment]
feel free to reopen this issue if anymore information.

**Comment by VincentSit** [comment]
> if you want to load it as far as possible, just add it to start script.
> 
> `egg-scripts start --require=xxx.js`
> 
> then it will be passthrough to egg-cluster, and exec in the first line of each process, see https://github.com/eggjs/egg-cluster/blob/master/lib/app_worker.js#L7

@atian25 Thank you for sharing the tip, it's very helpful.

I have a preload.js file located in baseDir.

I tested that `npm run dev` and `npm run debug` both can load normally, but the `npm run start` prompts that the module could not be found. Seems that the `egg-scripts` doesn't support relative paths. Is it a bug?

```JSON
{
    "start": "egg-scripts start --require=/absolute/path/to/preload.js --title=egg-server-my-server",
    "stop": "egg-scripts stop --title=egg-server-my-server",
    "dev": "egg-bin dev --require=./preload.js",
    "debug": "egg-bin debug --require=./preload.js"
}
```

```log
➜  my-project git:(develop) ✗ npm run start

> my-project@1.0.0 start /Users/myusername/Dropbox/Projects/customPath/my-project
> egg-scripts start --require=../preload.js --title=egg-server-my-project

[egg-scripts] Starting egg application at /Users/myusername/Dropbox/Projects/customPath/my-project
[egg-scripts] Run node /Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg-scripts/lib/start-cluster {"require":"../preload.js","title":"egg-server-my-project","baseDir":"/Users/myusername/Dropbox/Projects/customPath/my-project","framework":"/Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg"} --title=egg-server-my-project
2019-11-01 01:59:09,735 INFO 53065 [master] =================== egg start =====================
2019-11-01 01:59:09,735 INFO 53065 [master] node version v12.12.0
2019-11-01 01:59:09,735 INFO 53065 [master] egg version 2.24.0
2019-11-01 01:59:09,736 INFO 53065 [master] start with options:
{
  "framework": "/Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg",
  "baseDir": "/Users/myusername/Dropbox/Projects/customPath/my-project",
  "workers": 12,
  "plugins": null,
  "https": false,
  "require": [
    "../preload.js"
  ],
  "title": "egg-server-my-project"
}
2019-11-01 01:59:09,736 INFO 53065 [master] start with env: isProduction: true, EGG_SERVER_ENV: undefined, NODE_ENV: production
2019-11-01 01:59:09,740 INFO 53065 [master] agent_worker#1:53066 start with clusterPort:54283
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../preload.js'
Require stack:
- /Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg-cluster/lib/agent_worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg-cluster/lib/agent_worker.js:16:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg-cluster/lib/agent_worker.js:15:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/myusername/Dropbox/Projects/customPath/my-project/node_modules/egg-cluster/lib/agent_worker.js'
  ]
}
```

**Comment by kerryChen95** [comment]
@VincentSit  You can write bash scripts in npm scripts

```bash
// package.json
{
  "scripts": {
    "start": "egg-scripts start --require=$(pwd)/relative/path/to/your/preload.js --title=egg-server-my-server",
  }
}
```
