### ISSUE TITLE
egg-redis客户端每次不到10分钟，就报ERR server closed connection

### ISSUE THREAD

**Issue by huenchao** [eggjs/egg#3964]
## What happens?
我用egg-redis插件来作为redis客户端，每次超过10分钟左右，redis就会被断开，并且没有重链机制，并且报错。错误如下：
```
2019-10-07 15:54:05,764 ERROR 33651 [egg-redis] client error: Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
2019-10-07 15:54:05,774 ERROR 33651 nodejs.Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
    at DataHandler.shiftCommand (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:164:27)
    at DataHandler.returnError (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:33:27)
    at JavascriptRedisParser.returnError (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:15:22)
    at JavascriptRedisParser.execute (/Users/huenchao/common/egg-test/node_modules/redis-parser/lib/parser.js:542:14)
    at Socket.DataHandler.redis.stream.on.data (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

pid: 33651
hostname: huenchaodeMacBook-Pro.local
```

## Context
- **Node Version*10.13.1*:
- **Egg Version*2.6.1*:
- **Plugin Name*egg-redis*:
- **Plugin Version*2.4.0*:
- **Platform *macos*:

**Comment by huenchao** [comment]
这是bug，还是我使用方式不对？刚开始启动项目，redis是可以正常使用的～过十分钟左右，就报错不行了。

**Comment by huenchao** [comment]
redis: {
      client: {
        port: 6379,        
        host: 'xxxxx',
        password: 'xxxx',
        db: 8
      }
    }

**Comment by atian25** [comment]
> 2019-10-07 15:54:05,764 ERROR 33651 [egg-redis] client error: Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
2019-10-07 15:54:05,774 ERROR 33651 nodejs.Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
    at DataHandler.shiftCommand (/Users/huenchao/common/egg-test/node_modules/ioredis

看起来是服务端断了，可以 google 下 ioredis 和对应的错误信息 ERR server closed connection 看看。如 retryStrategy 等

**Comment by huenchao** [comment]
> > 2019-10-07 15:54:05,764 ERROR 33651 [egg-redis] client error: Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
> > 2019-10-07 15:54:05,774 ERROR 33651 nodejs.Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
> > at DataHandler.shiftCommand (/Users/huenchao/common/egg-test/node_modules/ioredis
> 
> 看起来是服务端断了，可以 google 下 ioredis 和对应的错误信息 ERR server closed connection 看看。如 retryStrategy 等

我在config.default.js里，加上retryStrategy回调，貌似也没执行过～
``` javascript
    redis: {
      client: {
        port: 6379,        
        host: '172.22.6.8',
        password: 'muiibafUZiej0re2',
        db: 8,
        retryStrategy: function(times) {
          console.log(`[times]`,times)
          return 10;
        }
      }
    }
```

**Comment by atian25** [comment]
可以先自己断点查查看，egg-redis 就是简单的包装了下 ioredis

**Comment by hyj1991** [comment]
这个问题可以反馈到 ioredis 这边，egg-redis 只是对 ioredis 的简单封装。
