### ISSUE TITLE
iisnode部署egg报错

### ISSUE THREAD

**Issue by adxyvax** [eggjs/egg#3990]
iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error

You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:
(node:4796) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2019-10-18 21:31:10,608 ERROR 4796 nodejs.AgentWorkerDiedError: [master] agent_worker#1:236 died (code: 1, signal: null)
    at Master.onAgentExit (C:\Program Files\iisnode\www\x\node_modules\egg-cluster\lib\master.js:358:17)
    at Master.emit (events.js:209:13)
    at Messenger.sendToMaster (C:\Program Files\iisnode\www\x\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (C:\Program Files\iisnode\www\x\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at ChildProcess.<anonymous> (C:\Program Files\iisnode\www\x\node_modules\egg-cluster\lib\master.js:249:22)
    at Object.onceWrapper (events.js:299:26)
    at ChildProcess.emit (events.js:209:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
name: "AgentWorkerDiedError"
pid: 4796
hostname: 172_17_0_11

2019-10-18 21:31:10,608 ERROR 4796 [master] agent_worker#1:236 start fail, exiting with code:1

2019-10-18 21:31:10,608 ERROR 4796 [master] exit with code:1

**Comment by hyj1991** [comment]
iisnode 提供 ssh 么？可以 ssh 进去手动启动下看看能不能启动

**Comment by adxyvax** [comment]
不是的，我用的是windows server 2012，通过iisnode部署node项目，通过外网访问时报以上错误，服务器上通过本机IP+端口号是可以访问的，为了排查，我另外部署了一个koa node项目，是可以通过外网访问的，推测可能是egg项目框架中有些限制导致
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"hyj1991"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年10月21日(星期一) 晚上8:08
 收件人:&nbsp;"eggjs/egg"<egg@noreply.github.com&gt;;
 抄送:&nbsp;"余欢欢"<535179266@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [eggjs/egg] iisnode部署egg报错 (#3990)

 

 
iisnode 提供 ssh 么？可以 ssh 进去手动启动下看看能不能启动

**Comment by atian25** [comment]
https://github.com/eggjs/egg-scripts

--ignore-stderr

**Comment by hyj1991** [comment]
如果没有其他问题先关闭了。
