### ISSUE TITLE
项目运行一段时间后会报错退出

### ISSUE THREAD

**Issue by coolucifer** [eggjs/egg#3998]
## What happens?
egg项目打包成docker镜像, 在服务器上运行一段时间后会报错退出

## Mini Showcase Repository(REQUIRED)
暂无

## How To Reproduce

**Steps to reproduce the behavior:**
1. 在服务器上拉取项目镜像, 运行: docker run -d --net=host --name egg docohub/egg
2. 启动后可以正常访问网站
3. 过段时间后发现网站访问502, 进入服务器发现进程报错退出

**Expected behavior**
1. 正常运行

## Context
- Dockerfile:
```
# https://www.jianshu.com/p/8cd7ba8bc3d5
# https://nodejs.org/zh-cn/docs/guides/nodejs-docker-webapp/
# step 1
FROM node:10.16.0 as build

ENV HOST 0.0.0.0
ENV NODE_ENV=production

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
RUN npm install --production

# if you are building your code for production
# RUN npm ci --only=production

# Boundle app source
COPY . .

# Build nuxt
# RUN npm run build

# step 2
# https://www.jianshu.com/p/147a5262e356
FROM node:10.16.0-alpine
COPY --from=build /app /app
WORKDIR /app

# Expose port
EXPOSE 7001

# Run
CMD npm start
```

- **Egg Version**: 2.22
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: centos7
- **报错信息**: 
```
[2019-10-22 02:35:38.042] [cfork:master:28] worker:46 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2019-10-22 02:35:38.062] [cfork:master:28] new worker:57 fork (state: none)
[2019-10-22 02:35:38.064] [cfork:master:28] worker:46 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2019-10-22 02:35:38,066 ERROR 28 nodejs.AppWorkerDiedError: [master] app_worker#1:46 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: ["2"]
    at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/app/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:203:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 28
hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
2019-10-22 02:35:38,063 INFO 28 [master] app_worker#1:46 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
2019-10-22 02:35:38,063 INFO 28 [master] app_worker#2:57 start, state: none, current workers: ["1","2"]
2019-10-22 02:36:18,564 INFO 28 [master] try to start a new agent_worker after 1s ...
[2019-10-22 02:36:19.078] [cfork:master:28] worker:57 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-10-22 02:36:19.078] [cfork:master:28] don't fork, because worker:57 will be kill soon
2019-10-22 02:36:19,078 INFO 28 [master] app_worker#2:57 disconnect, suicide: false, state: disconnected, current workers: ["2"]
[2019-10-22 02:36:19.078] [cfork:master:28] worker:57 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-10-22 02:36:18,450 ERROR 28 nodejs.AgentWorkerDiedError: [master] agent_worker#1:35 died (code: null, signal: SIGKILL)
    at Master.onAgentExit (/app/node_modules/egg-cluster/lib/master.js:425:17)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at ChildProcess.agentWorker.once (/app/node_modules/egg-cluster/lib/master.js:289:22)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AgentWorkerDiedError"
pid: 28
hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
2019-10-22 02:36:19,080 ERROR 28 nodejs.AppWorkerDiedError: [master] app_worker#2:57 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/app/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 28
hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
2019-10-22 02:36:19,806 INFO 28 [master] new agent_worker starting...
2019-10-22 02:36:19,819 INFO 28 [master] agent_worker#2:64 start with clusterPort:34855
2019-10-22 02:36:21,380 INFO 64 Plugin development is disabled by env unmatched, require env(local) but got env is prod
2019-10-22 02:36:21,418 INFO 64 [egg:core] App root: /app
2019-10-22 02:36:21,419 INFO 64 [egg:core] All *.log files save on "/root/logs/egg-server"
2019-10-22 02:36:21,419 INFO 64 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-session","version":"3.1.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-security","version":"2.6.1"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-onerror","version":"2.1.0"},{"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-i18n","version":"2.1.1"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-watcher","version":"3.1.0"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-schedule","version":"3.6.4"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":["schedule"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-multipart","version":"2.9.0"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-logrotator","version":"3.1.0"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-static","version":"2.2.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-view","version":"2.1.2"},{"enable":true,"package":"egg-view-nunjucks","name":"nunjucks","dependencies":["security","view"],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-view-nunjucks","version":"2.2.0"},{"enable":true,"package":"egg-mongoose","name":"mongoose","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-mongoose","version":"3.2.0"},{"enable":true,"package":"egg-socket.io","name":"io","dependencies":["session"],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-socket.io","version":"4.1.6"},{"enable":true,"package":"egg-cors","name":"cors","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-cors","version":"2.2.0"}]
2019-10-22 02:36:21,573 INFO 64 [egg:logger] init all loggers with options: {"dir":"/root/logs/egg-server","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"egg-server-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"agent"}
2019-10-22 02:36:21,590 INFO 64 [egg:core] dump config after load, 7ms
2019-10-22 02:36:21,639 INFO 64 [egg-watcher:agent] watcher start success
2019-10-22 02:36:21,641 INFO 64 [egg:core:ready_stat] end ready task /app/node_modules/egg-schedule/agent.js:12:9, remain ["/app/node_modules/egg-watcher/lib/init.js:15:14"]
2019-10-22 02:36:21,641 WARN 64 [egg-watcher] defaultEventSource watcher will NOT take effect
2019-10-22 02:36:21,641 INFO 64 [egg:core:ready_stat] end ready task /app/node_modules/egg-watcher/lib/init.js:15:14, remain []
2019-10-22 02:36:21,648 INFO 28 [master] agent_worker#2:64 started (1841ms)
2019-10-22 02:36:39,001 ERROR 28 nodejs.ClusterWorkerExceptionError: [master] 1 agent and 0 worker(s) alive, exit to avoid unknown state
    at Manager.Master.workerManager.on (/app/node_modules/egg-cluster/lib/master.js:161:19)
    at Manager.emit (events.js:198:13)
    at Timeout.timer.setInterval [as _onTimeout] (/app/node_modules/egg-cluster/lib/utils/manager.js:67:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterWorkerExceptionError"
count: {"agent":1,"worker":0}
pid: 28
hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
2019-10-22 02:36:39,002 ERROR 28 [master] exit with code:1
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn node /app/node_modules/egg-scripts/lib/start-cluster {"sticky":true,"baseDir":"/app","framework":"/app/node_modules/egg","title":"egg-server-egg-server"} --title=egg-server-egg-server fail, exit code: 1
    at ChildProcess.child.once.code (/app/node_modules/egg-scripts/lib/cmd/start.js:179:31)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at ChildProcess.child.once.code (/app/node_modules/egg-scripts/lib/cmd/start.js:179:17)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-10-22 02:36:39,018 ERROR 64 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-server@1.0.0 start: `egg-scripts start --sticky`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-22 02:36:39,034 ERROR 64 [agent_worker] exit with code:110
2019-10-22 02:36:39,034 INFO 64 [agent_worker] beforeExit success
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-22T02_36_39_029Z-debug.log
```

**Comment by coolucifer** [comment]
debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle egg-server@1.0.0~prestart: egg-server@1.0.0
6 info lifecycle egg-server@1.0.0~start: egg-server@1.0.0
7 verbose lifecycle egg-server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle egg-server@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle egg-server@1.0.0~start: CWD: /app
10 silly lifecycle egg-server@1.0.0~start: Args: [ '-c', 'egg-scripts start --sticky' ]
11 silly lifecycle egg-server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle egg-server@1.0.0~start: Failed to exec start script
13 verbose stack Error: egg-server@1.0.0 start: `egg-scripts start --sticky`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid egg-server@1.0.0
15 verbose cwd /app
16 verbose Linux 3.10.0-957.1.3.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error egg-server@1.0.0 start: `egg-scripts start --sticky`
22 error Exit status 1
23 error Failed at the egg-server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by atian25** [comment]
看下 stderr 和 common-error.log

**Comment by coolucifer** [comment]
> 看下 stderr 和 common-error.log

请问这两个的目录在哪里呢, 我看本地项目会有logs文件夹, 里面有common-error.log, 但是docker容器里没有logs文件夹

**Comment by coolucifer** [comment]
![image](https://user-images.githubusercontent.com/23123540/67270406-35495100-f4eb-11e9-9452-5352c0fd1de1.png)
common-error.log文件是空的

**Comment by atian25** [comment]
看下日志文档，线上模式是在 home 下

**Comment by coolucifer** [comment]
> 看下日志文档，线上模式是在 home 下

![image](https://user-images.githubusercontent.com/23123540/67271416-0a5ffc80-f4ed-11e9-9b94-1cd29974c338.png)
docker容器里是空文件夹
![image](https://user-images.githubusercontent.com/23123540/67271590-5f9c0e00-f4ed-11e9-905f-e03586c4bb42.png)
请问是这里 的log文件吗?

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/logger.html#%E6%96%87%E4%BB%B6%E6%97%A5%E5%BF%97

**Comment by atian25** [comment]
> 2019-10-22 02:36:19,806 INFO 28 [master] new agent_worker starting...

感觉是你的 agent 里面有未捕获的异常

**Comment by hyj1991** [comment]
确实是异常退出的话，开启下 `ulimit -c unlimited`，看看有无 core 文件生成。
有的话使用 Node.js 性能平台的 core 分析工具看看异常退出前的堆栈信息

**Comment by coolucifer** [comment]
> 确实是异常退出的话，开启下 `ulimit -c unlimited`，看看有无 core 文件生成。
> 有的话使用 Node.js 性能平台的 core 分析工具看看异常退出前的堆栈信息

请问使用docker的话要在哪里查看呢?

**Comment by hyj1991** [comment]
先关闭了，有后续 core 文件等可以 reopen

**Comment by ITHcc** [comment]
> ## What happens?
> egg项目打包成docker镜像, 在服务器上运行一段时间后会报错退出
> 
> ## Mini Showcase Repository(REQUIRED)
> 暂无
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:**
> 
> 1. 在服务器上拉取项目镜像, 运行: docker run -d --net=host --name egg docohub/egg
> 2. 启动后可以正常访问网站
> 3. 过段时间后发现网站访问502, 进入服务器发现进程报错退出
> 
> **Expected behavior**
> 
> 1. 正常运行
> 
> ## Context
> * Dockerfile:
> 
> ```
> # https://www.jianshu.com/p/8cd7ba8bc3d5
> # https://nodejs.org/zh-cn/docs/guides/nodejs-docker-webapp/
> # step 1
> FROM node:10.16.0 as build
> 
> ENV HOST 0.0.0.0
> ENV NODE_ENV=production
> 
> # Create app directory
> WORKDIR /app
> 
> # Install app dependencies
> # A wildcard is used to ensure both package.json AND package-lock.json are copied
> # where available (npm@5+)
> COPY package.json ./
> RUN npm install --production
> 
> # if you are building your code for production
> # RUN npm ci --only=production
> 
> # Boundle app source
> COPY . .
> 
> # Build nuxt
> # RUN npm run build
> 
> # step 2
> # https://www.jianshu.com/p/147a5262e356
> FROM node:10.16.0-alpine
> COPY --from=build /app /app
> WORKDIR /app
> 
> # Expose port
> EXPOSE 7001
> 
> # Run
> CMD npm start
> ```
> 
> * **Egg Version**: 2.22
> * **Plugin Name**:
> * **Plugin Version**:
> * **Platform**: centos7
> * **报错信息**:
> 
> ```
> [2019-10-22 02:35:38.042] [cfork:master:28] worker:46 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
> [2019-10-22 02:35:38.062] [cfork:master:28] new worker:57 fork (state: none)
> [2019-10-22 02:35:38.064] [cfork:master:28] worker:46 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
> 2019-10-22 02:35:38,066 ERROR 28 nodejs.AppWorkerDiedError: [master] app_worker#1:46 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: ["2"]
>     at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:510:21)
>     at Master.emit (events.js:198:13)
>     at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
>     at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
>     at EventEmitter.cluster.on (/app/node_modules/egg-cluster/lib/master.js:353:22)
>     at EventEmitter.emit (events.js:203:15)
>     at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:203:15)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> name: "AppWorkerDiedError"
> pid: 28
> hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
> 2019-10-22 02:35:38,063 INFO 28 [master] app_worker#1:46 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
> 2019-10-22 02:35:38,063 INFO 28 [master] app_worker#2:57 start, state: none, current workers: ["1","2"]
> 2019-10-22 02:36:18,564 INFO 28 [master] try to start a new agent_worker after 1s ...
> [2019-10-22 02:36:19.078] [cfork:master:28] worker:57 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
> [2019-10-22 02:36:19.078] [cfork:master:28] don't fork, because worker:57 will be kill soon
> 2019-10-22 02:36:19,078 INFO 28 [master] app_worker#2:57 disconnect, suicide: false, state: disconnected, current workers: ["2"]
> [2019-10-22 02:36:19.078] [cfork:master:28] worker:57 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
> 2019-10-22 02:36:18,450 ERROR 28 nodejs.AgentWorkerDiedError: [master] agent_worker#1:35 died (code: null, signal: SIGKILL)
>     at Master.onAgentExit (/app/node_modules/egg-cluster/lib/master.js:425:17)
>     at Master.emit (events.js:198:13)
>     at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
>     at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
>     at ChildProcess.agentWorker.once (/app/node_modules/egg-cluster/lib/master.js:289:22)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> name: "AgentWorkerDiedError"
> pid: 28
> hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
> 2019-10-22 02:36:19,080 ERROR 28 nodejs.AppWorkerDiedError: [master] app_worker#2:57 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
>     at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:510:21)
>     at Master.emit (events.js:198:13)
>     at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
>     at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
>     at EventEmitter.cluster.on (/app/node_modules/egg-cluster/lib/master.js:353:22)
>     at EventEmitter.emit (events.js:203:15)
>     at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> name: "AppWorkerDiedError"
> pid: 28
> hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
> 2019-10-22 02:36:19,806 INFO 28 [master] new agent_worker starting...
> 2019-10-22 02:36:19,819 INFO 28 [master] agent_worker#2:64 start with clusterPort:34855
> 2019-10-22 02:36:21,380 INFO 64 Plugin development is disabled by env unmatched, require env(local) but got env is prod
> 2019-10-22 02:36:21,418 INFO 64 [egg:core] App root: /app
> 2019-10-22 02:36:21,419 INFO 64 [egg:core] All *.log files save on "/root/logs/egg-server"
> 2019-10-22 02:36:21,419 INFO 64 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-session","version":"3.1.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-security","version":"2.6.1"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-onerror","version":"2.1.0"},{"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-i18n","version":"2.1.1"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-watcher","version":"3.1.0"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-schedule","version":"3.6.4"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":["schedule"],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-multipart","version":"2.9.0"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-logrotator","version":"3.1.0"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-static","version":"2.2.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/node_modules/egg/config/plugin.js","path":"/app/node_modules/egg-view","version":"2.1.2"},{"enable":true,"package":"egg-view-nunjucks","name":"nunjucks","dependencies":["security","view"],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-view-nunjucks","version":"2.2.0"},{"enable":true,"package":"egg-mongoose","name":"mongoose","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-mongoose","version":"3.2.0"},{"enable":true,"package":"egg-socket.io","name":"io","dependencies":["session"],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-socket.io","version":"4.1.6"},{"enable":true,"package":"egg-cors","name":"cors","dependencies":[],"optionalDependencies":[],"env":[],"from":"/app/config/plugin.js","path":"/app/node_modules/egg-cors","version":"2.2.0"}]
> 2019-10-22 02:36:21,573 INFO 64 [egg:logger] init all loggers with options: {"dir":"/root/logs/egg-server","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"egg-server-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"agent"}
> 2019-10-22 02:36:21,590 INFO 64 [egg:core] dump config after load, 7ms
> 2019-10-22 02:36:21,639 INFO 64 [egg-watcher:agent] watcher start success
> 2019-10-22 02:36:21,641 INFO 64 [egg:core:ready_stat] end ready task /app/node_modules/egg-schedule/agent.js:12:9, remain ["/app/node_modules/egg-watcher/lib/init.js:15:14"]
> 2019-10-22 02:36:21,641 WARN 64 [egg-watcher] defaultEventSource watcher will NOT take effect
> 2019-10-22 02:36:21,641 INFO 64 [egg:core:ready_stat] end ready task /app/node_modules/egg-watcher/lib/init.js:15:14, remain []
> 2019-10-22 02:36:21,648 INFO 28 [master] agent_worker#2:64 started (1841ms)
> 2019-10-22 02:36:39,001 ERROR 28 nodejs.ClusterWorkerExceptionError: [master] 1 agent and 0 worker(s) alive, exit to avoid unknown state
>     at Manager.Master.workerManager.on (/app/node_modules/egg-cluster/lib/master.js:161:19)
>     at Manager.emit (events.js:198:13)
>     at Timeout.timer.setInterval [as _onTimeout] (/app/node_modules/egg-cluster/lib/utils/manager.js:67:14)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)
> name: "ClusterWorkerExceptionError"
> count: {"agent":1,"worker":0}
> pid: 28
> hostname: ip-172-26-15-164.ap-northeast-1.compute.internal
> 2019-10-22 02:36:39,002 ERROR 28 [master] exit with code:1
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn node /app/node_modules/egg-scripts/lib/start-cluster {"sticky":true,"baseDir":"/app","framework":"/app/node_modules/egg","title":"egg-server-egg-server"} --title=egg-server-egg-server fail, exit code: 1
>     at ChildProcess.child.once.code (/app/node_modules/egg-scripts/lib/cmd/start.js:179:31)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> Emitted 'error' event at:
>     at ChildProcess.child.once.code (/app/node_modules/egg-scripts/lib/cmd/start.js:179:17)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> 2019-10-22 02:36:39,018 ERROR 64 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! egg-server@1.0.0 start: `egg-scripts start --sticky`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the egg-server@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2019-10-22 02:36:39,034 ERROR 64 [agent_worker] exit with code:110
> 2019-10-22 02:36:39,034 INFO 64 [agent_worker] beforeExit success
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-22T02_36_39_029Z-debug.log
> ```

解决了吗？
