### ISSUE TITLE
为什么会block掉心跳？

### ISSUE THREAD

**Issue by dythbj** [eggjs/egg#4021]
## What happens?
这段伪代码会block掉心跳吗？
for( i = 0; i < 10000000; i++){
  await this.ctx.model.Test.create({value: i}); 
}

*ORM是Mongoose
业务需求是将sqlite里一张表的所有记录导入到Mongodb,核心代码是：
db.serialize(() => {
            const stmt = db.prepare('select * from tiles');
            stmt.each(async (err, row) => {
                if (!err) {
                    Promise.all(
                        await this.ctx.model.Tiles.create({
                            name: 'road',
                            level: row.zoom_level,
                            column: row.tile_column,
                            row: row.tile_row,
                            data: row.tile_data
                        })
                    );
                }
 }, (err, rl) => { console.log('done with all!total:' + rl) });

**结果**
<--- Last few GCs --->

[28056:0x103001a00]   366252 ms: Mark-sweep 1594.7 (1686.9) -> 1594.7 (1649.9) MB, 1950.1 / 0.0 ms  last resort GC in old space requested
[28056:0x103001a00]   368031 ms: Mark-sweep 1594.7 (1649.9) -> 1594.7 (1649.9) MB, 1778.3 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x207f4aaa58b9 <JSObject>
    1: push(this=0x207f24c25531 <JSArray[114467]>)
    2: executeOperation(aka executeOperation) [/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/mongodb/lib/utils.js:~364] [pc=0x2e6d38098fc9](this=0x207fd12022d1 <undefined>,topology=0x207ff2399b21 <EventEmitter map = 0x207f7ba44939>,operation=0x207f90676ae9 <JSFunction insertOne (sfi = 0x207f7a7c93a1)>,args=0x207f9eedbd01 <JSArray[4]>...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::AddImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/usr/local/bin/node]
 8: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/usr/local/bin/node]
 9: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x2e6d37b842fd
11: 0x2e6d37bd6dde
[2019-10-31 20:56:08.514] [cfork:master:27732] worker:28056 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: false)
[2019-10-31 20:56:08.517] [cfork:master:27732] don't fork new work (refork: false)
[2019-10-31 20:56:08.518] [cfork:master:27732] (total 0 disconnect, 2 unexpected exit) WorkerDiedUnexpectedError: worker:28056 died unexpected (code: null, signal: SIGABRT, exitedAfterDisconnect: false, state: dead)
    at EventEmitter.onUnexpected (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/cfork/index.js:223:15)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at EventEmitter.<anonymous> (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/cfork/index.js:143:13)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:191:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
2019-10-31 20:56:08,524 ERROR 27732 nodejs.AppWorkerDiedError: [master] app_worker#2:28056 died (code: null, signal: SIGABRT, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/egg-cluster/lib/master.js:411:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/Users/gaojie/Library/Develop/egg/bj/GeoLiny/node_modules/egg-cluster/lib/master.js:280:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:191:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 27732

## Context
- **Node Version**:8.14.1
- **Egg Version**:2.15.1
- **Platform**:mac os

**Comment by atian25** [comment]
**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

**Comment by dythbj** [comment]
> **FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**
天猪大神，你好：
        目前日志反馈了2条主要信息：1）mongodb一直create内存爆了,2)egg心跳block，超时了。
        我想请教的是对于这种长事务的操作，在egg里面如何实现比较好？
        之前看另外一篇类似问题帖子里面您提到了https://github.com/sindresorhus/promise-fun，您方便结合我的具体需求给小白具体普及一下如何使用和实现吗？

**Comment by atian25** [comment]
> mongodb一直create内存爆了

检查你的代码逻辑，检查不出来的话就上 alinode 看。

> egg心跳block，超时了

egg 没做这事，可以看下 egg-moogoose 源码

**Comment by dythbj** [comment]
我的代码逻辑比较粗暴，其实核心还是想请教一下您，对于这种长事务的业务逻辑，在egg里如何处理比较好？

**Comment by supperchong** [comment]
并发太多了，可以用队列，先把数据全查出来(或者数据量太大了分页查)，然后每次处理m条数据

**Comment by dythbj** [comment]
> 并发太多了，可以用队列，先把数据全查出来(或者数据量太大了分页查)，然后每次处理m条数据

请教一下，如何使用队列呢？
