### ISSUE TITLE
用egg-sequelize管理sqlite数据库，dev环境下可以正常读写，生产环境下报错SequelizeDatabaseError: SQLITE_ERROR: no such table

### ISSUE THREAD

**Issue by wsdqr001** [eggjs/egg#4042]
求助各位大佬，我遇到一个问题，用egg-sequelize管理sqlite数据库，dev环境下sqlite读写正常，但是部署到生产环境后会报错：
2019-11-07 19:05:12,332 ERROR 64995 nodejs.SequelizeDatabaseError: SQLITE_ERROR: no such table: systemSetting
at Query.formatError (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:422:16)
at Query._handleQueryResponse (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
at afterExecute (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)
at replacement (/app/bff/node_modules/sqlite3/lib/trace.js:19:31)
at Statement.errBack (/app/bff/node_modules/sqlite3/lib/sqlite3.js:16:21)
name: "SequelizeDatabaseError"
parent: {"errno":1,"code":"SQLITE_ERROR","sql":"SELECT id, uuid, name, creator, alarmType, errorHandle, linkUserIds, smsUsers, mailUserIds, proxyAlarmValue, proxyAlarmFrequency, apiCheckAlarmValue, apiCheckAlarmFrequency, cpuAlarmValue, memAlarmValue, osAlarmFrequency, createdAt, updatedAt, timeStamp FROM systemSetting AS systemSetting;"}
original: {"errno":1,"code":"SQLITE_ERROR","sql":"SELECT id, uuid, name, creator, alarmType, errorHandle, linkUserIds, smsUsers, mailUserIds, proxyAlarmValue, proxyAlarmFrequency, apiCheckAlarmValue, apiCheckAlarmFrequency, cpuAlarmValue, memAlarmValue, osAlarmFrequency, createdAt, updatedAt, timeStamp FROM systemSetting AS systemSetting;"}
sql: "SELECT id, uuid, name, creator, alarmType, errorHandle, linkUserIds, smsUsers, mailUserIds, proxyAlarmValue, proxyAlarmFrequency, apiCheckAlarmValue, apiCheckAlarmFrequency, cpuAlarmValue, memAlarmValue, osAlarmFrequency, createdAt, updatedAt, timeStamp FROM systemSetting AS systemSetting;"
parameters: undefined
pid: 64995
hostname: OP002-web-4258

打开生产环境初始化的数据库，里面是有systemSetting这个表的。

@huacnlee @pmq20 @shiny

**Comment by wsdqr001** [comment]
midway baseDir 配置问题，已解决
