### ISSUE TITLE
egg-bin --require babel-register  has error with file .umirc.local.js

### ISSUE THREAD

**Issue by yanxlg** [eggjs/egg#4045]
## What happens?
when use egg-bin to run dev with option '--require babel-register'，the console show an error:
E:\workspace\create-umi\a1\app\web\\.umirc.local.js:3
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Module._compile (E:\workspace\create-umi\a1\node_modules\pirates\lib\index.js:97:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.newLoader [as .js] (E:\workspace\create-umi\a1\node_modules\pirates\lib\index.js:102:7)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireFile (E:\workspace\create-umi\a1\node_modules\umi-core\lib\getUserConfig.js:106:11)
    at getConfigByConfigFile (E:\workspace\create-umi\a1\node_modules\umi-core\lib\getUserConfig.js:127:148)
� Starting Umi UI using umi@2.11.3...

It seems that file '.umirc.local.js' did not compile with babel.so how to deal with it.

**Comment by atian25** [comment]
it seems the error is thrown by `umi-core`, maybe you should report the issue to them.

**Comment by yanxlg** [comment]
It's not umi-core's error,because if not use ssr，it is powerful，only use egg with ssr, it throw this error，it seems that egg-bin can not support babel perfectly.

**Comment by atian25** [comment]
egg doesn't provide an official umi egg plugin.

`egg-bin --require` is just add it to `execArgv`, if you fork umi without append the argv, it'll not pass to umi.
