### ISSUE TITLE
nodeinstall无法安装alinodeGET http://alinode.aliyun.com/dist/new-alinode/v3.15.1/alinode-v3.15.1-win-x64.tar.gz got 404

### ISSUE THREAD

**Issue by Ghohankawk** [eggjs/egg#4076]
命令：nodeinstall --install-alinode ^3
报错：
Error: GET http://alinode.aliyun.com/dist/new-alinode/v3.15.1/alinode-v3.15.1-win-x64.tar.gz got 404
    at downloadTgz (C:\Users\hankun\AppData\Roaming\nvm\v10.13.0\node_modules\nodeinstall\lib\installer\installer.js:125:17)
    at downloadTgz.next (<anonymous>)
    at onFulfilled (C:\Users\hankun\AppData\Roaming\nvm\v10.13.0\node_modules\nodeinstall\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
PS D:\work\fanyi\fanyi-api> nodeinstall --install-alinode 3
Error: GET http://alinode.aliyun.com/dist/new-alinode/v3.15.1/alinode-v3.15.1-win-x64.tar.gz got 404
    at downloadTgz (C:\Users\hankun\AppData\Roaming\nvm\v10.13.0\node_modules\nodeinstall\lib\installer\installer.js:125:17)
    at downloadTgz.next (<anonymous>)
    at onFulfilled (C:\Users\hankun\AppData\Roaming\nvm\v10.13.0\node_modules\nodeinstall\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

具体原因，初步分析是因为下面路径不存在，
http://alinode.aliyun.com/dist/new-alinode/v3.12.0/alinode-v3.12.0-win-x64.tar.gz
实际路径应该是下面
http://alinode.aliyun.com/dist/new-alinode/v3.12.0/alinode-v3.12.0-darwin-x64.tar.gz

那么问题，请问，为啥我执行的时候会是上面的路径呢？

**Comment by hyj1991** [comment]
alinode 目前不支持 windows

**Comment by Ghohankawk** [comment]
谢谢，解答，只能部署linux环境了
