### ISSUE TITLE
【egg-ons有偿】MQPushConsumer occurred an errorMQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error, No topic route info in name server for the topic

### ISSUE THREAD

**Issue by liuhuanhui** [eggjs/egg#4080]
`2019-12-04 19:50:06,821 ERROR 5642 nodejs.MQClientException: MQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error, No topic route info in name server for the topic: %RETRY%MQ_INST_1472914557190026_BbqLxNCE%GID_PaySystem
See http://rocketmq.apache.org/docs/faq/ for further details.
See http://rocketmq.apache.org/docs/faq/ for further details.
    at MQClient._defaultHandler (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/ali-ons/lib/mq_client_api.js:559:17)
    at MQClient.getTopicRouteInfoFromNameServer (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/ali-ons/lib/mq_client_api.js:197:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MQClient.updateTopicRouteInfoFromNameServer (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/ali-ons/lib/mq_client.js:247:30)
    at next (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/p-gather/index.js:30:22)
    at async Promise.all (index 0)
    at gather (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/p-gather/index.js:39:3)
    at MQClient.updateAllTopicRouterInfo (/Users/huanhuiliu/Project/xxx-App-Api/node_modules/ali-ons/lib/mq_client.js:217:17)
    at /Users/huanhuiliu/Project/xxx-App-Api/node_modules/ali-ons/lib/mq_client.js:105:11
name: "MQClientException"
code: 17
pid: 5642`

**Comment by liuhuanhui** [comment]
已经解决

**Comment by zhanghouji** [comment]
@liuhuanhui 你好，你可以接受到消息吗?
```
WARN 23055 [egg-ons] CANNOT find the subscription logic for topic=dev
```

**Comment by liuhuanhui** [comment]
可以，但是会经常会有异常
