### ISSUE TITLE
启动了测试npm test 出现问题了

### ISSUE THREAD

**Issue by next2014** [eggjs/egg#410]
➜  egg-example npm test

> egg-example@1.0.0 test /Users/next/egg-example
> egg-bin test

  test/app/middleware/robot.test.js
    1) "before all" hook

  0 passing (572ms)
  1 failing

  1) test/app/middleware/robot.test.js "before all" hook:
     ReferenceError: load file: /Users/next/egg-example/app/service/some.js, error: app is not defined
      at Object.<anonymous> (app/service/some.js:1:27)
      at Object.extensions..js (node_modules/espower-loader/index.js:48:13)
      at require (internal/module.js:20:19)
      at module.exports (node_modules/interop-require/index.js:2:13)
      at Object.loadFile (node_modules/egg-core/lib/utils/index.js:14:17)
      at getExports (node_modules/egg-core/lib/loader/file_loader.js:122:23)
      at ContextLoader.parse (node_modules/egg-core/lib/loader/file_loader.js:83:25)
      at ContextLoader.load (node_modules/egg-core/lib/loader/file_loader.js:33:24)
      at AppWorkerLoader.loadToContext (node_modules/egg-core/lib/loader/egg_loader.js:283:28)
      at AppWorkerLoader.loadService (node_modules/egg-core/lib/loader/mixin/service.js:24:10)
      at AppWorkerLoader.load (node_modules/egg/lib/loader/app_worker_loader.js:35:10)
      at Application (node_modules/egg/lib/application.js:37:17)
      at MeesengerApplication (node_modules/egg-mock/lib/app.js:216:7)
      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:67:29)
      at EventEmitter.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

[common-bin] run test with [] at /Users/next/egg-example error:
Error: /Users/next/egg-example/node_modules/egg-bin/node_modules/mocha/bin/_mocha --timeout,30000,--require,/Users/next/egg-example/node_modules/thunk-mocha/index.js,--require,/Users/next/egg-example/node_modules/intelli-espower-loader/intelli-espower-loader.js,/Users/next/egg-example/test/app/middleware/robot.test.js exit with code 1
    at ChildProcess.<anonymous> (/Users/next/egg-example/node_modules/common-bin/lib/helper.js:31:21)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Test failed.  See above for more details.

**Comment by dead-horse** [comment]
贴一下你的代码。

> /Users/next/egg-example/app/service/some.js, error: app is not defined

这个文件有语法错误

**Comment by atian25** [comment]
呃。。。是看了 quickstart 吧

```js
// app/service/some.js
class SomeService extends app.Service {
  * list() {
    const rule = this.app.config.robot.ua;
  }
}
```

改为
```js
module.exports = app => {
  class SomeService extends app.Service {
    * list() {
      const rule = this.app.config.robot.ua;
    }
  }
}
```

**Comment by next2014** [comment]
@atian25 按照你这样改了，成功了测试到了
![jietu20170219-225609](https://cloud.githubusercontent.com/assets/7641722/23103478/a6ad3b9a-f6f6-11e6-8df9-b2fe62688fae.jpg)
