### ISSUE TITLE
ctx.curl问题，谢谢解答

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#4101]
const result = await ctx.curl
我使用这个方法去爬取数据，出现了下面错误：
===============================================
2019-12-14 16:13:48,180 ERROR 19580 [-/127.0.0.1/-/92677ms POST /api/common/spider/getPostCode] nodejs.ResponseError: socket hang up, GET https://usa.youbianku.com/county-city-json/Nolan -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":35,"freeSockets":{},"sockets":{"usa.youbianku.com:443::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 5, socketHandledResponses: 4)
headers: {}
headers: {}
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.socketOnEnd (_http_client.js:440:23)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
code: "ECONNRESET"
name: "ResponseError"
data: undefined
path: "/county-city-json/Nolan"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":623,"keepAliveSocket":true,"requestUrls":["https://usa.youbianku.com/county-city-json/Nolan"],"timing":null,"remoteAddress":"47.88.10.57","remotePort":443,"socketHandledRequests":5,"socketHandledResponses":4}
pid: 19580
hostname: WJ-201911031519

2019-12-14 16:13:48,181 ERROR 19580 [-/127.0.0.1/-/92679ms POST /api/common/spider/getPostCode] nodejs.AssertionError: invalid status code: -1
    at Object.set status [as status] (E:\MES\node_modules\koa\lib\response.js:88:5)
    at Object.status (E:\MES\node_modules\delegates\index.js:92:31)
    at errorHandler (E:\MES\app\middleware\errorHandler.js:12:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
generatedMessage: false
code: "ERR_ASSERTION"
actual: false
expected: true
operator: "=="
pid: 19580
hostname: WJ-201911031519

**Comment by atian25** [comment]
对方服务问题

**Comment by xinnian1992** [comment]
谢谢
