### ISSUE TITLE
nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#4102]
应用在机器上启动运行没问题，在docker中使用会出现以下问题，docker的基础镜像是公司内部镜像不方便在外复现。请问出现以下错误大概是什么原因？
```
2019-12-16 12:20:48,043 INFO 52 [egg:core:ready_stat] end ready task /data/node_modules/egg-core/lib/egg.js:303:10, remain ["/data/node_modules/egg-watcher/lib/init.js:15:14"]
2019-12-16 12:20:48,043 INFO 51 [egg:core:ready_stat] end ready task /data/node_modules/egg-core/lib/egg.js:303:10, remain ["/data/node_modules/egg-watcher/lib/init.js:15:14"]
2019-12-16 12:20:57,972 WARN 51 [egg:core:ready_timeout] 10 seconds later /data/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2019-12-16 12:20:57,973 WARN 52 [egg:core:ready_timeout] 10 seconds later /data/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2019-12-16 12:21:48,049 ERROR 52 [-/127.0.0.1/-/1ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 52
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 52 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 52
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 51 [-/127.0.0.1/-/0ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 51
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 52 [app_worker] start error, exiting with code:1
2019-12-16 12:21:48,051 ERROR 51 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 51
hostname: e095a781a8d3
2019-12-16 12:21:48,051 ERROR 51 [app_worker] start error, exiting with code:1
2019-12-16 12:21:48,056 INFO 51 [app_worker] receive signal SIGTERM, exiting with code:0
2019-12-16 12:21:48,058 INFO 51 [app_worker] beforeExit success
2019-12-16 12:21:48,058 INFO 51 [app_worker] exit with code:0
2019-12-16 12:21:48,060 INFO 52 [app_worker] receive signal SIGTERM, exiting with code:0
2019-12-16 12:21:48,062 INFO 52 [app_worker] beforeExit success
2019-12-16 12:21:48,062 INFO 52 [app_worker] exit with code:0
[2019-12-16 12:21:48.067] [cfork:master:33] worker:51 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-12-16 12:21:48.067] [cfork:master:33] don't fork, because worker:51 will be kill soon
2019-12-16 12:21:48,067 INFO 33 [master] app_worker#1:51 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
[2019-12-16 12:21:48.068] [cfork:master:33] worker:52 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-12-16 12:21:48.068] [cfork:master:33] don't fork, because worker:52 will be kill soon
2019-12-16 12:21:48,068 INFO 33 [master] app_worker#2:52 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
[2019-12-16 12:21:48.068] [cfork:master:33] worker:51 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-12-16 12:21:48,069 ERROR 33 nodejs.AppWorkerDiedError: [master] app_worker#1:51 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["2"]
    at Master.onAppExit (/data/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/data/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/data/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/data/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 33
hostname: e095a781a8d3
2019-12-16 12:21:48,070 ERROR 33 [master] app_worker#1:51 start fail, exiting with code:1
2019-12-16 12:21:48,070 ERROR 33 [master] exit with code:1
2019-12-16 12:21:48,075 ERROR 40 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2019-12-16 12:21:48,077 INFO 40 [agent_worker] beforeExit success
2019-12-16 12:21:48,077 ERROR 40 [agent_worker] exit with code:110
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-pic@1.0.0 start4docker: `egg-scripts start --workers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-pic@1.0.0 start4docker script.2019-12-16 12:20:48,043 INFO 52 [egg:core:ready_stat] end ready task /data/node_modules/egg-core/lib/egg.js:303:10, remain ["/data/node_modules/egg-watcher/lib/init.js:15:14"]
2019-12-16 12:20:48,043 INFO 51 [egg:core:ready_stat] end ready task /data/node_modules/egg-core/lib/egg.js:303:10, remain ["/data/node_modules/egg-watcher/lib/init.js:15:14"]
2019-12-16 12:20:57,972 WARN 51 [egg:core:ready_timeout] 10 seconds later /data/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2019-12-16 12:20:57,973 WARN 52 [egg:core:ready_timeout] 10 seconds later /data/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2019-12-16 12:21:48,049 ERROR 52 [-/127.0.0.1/-/1ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 52
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 52 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 52
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 51 [-/127.0.0.1/-/0ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 51
hostname: e095a781a8d3
2019-12-16 12:21:48,050 ERROR 52 [app_worker] start error, exiting with code:1
2019-12-16 12:21:48,051 ERROR 51 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:35241
    at Function.waitFor (/data/node_modules/cluster-client/lib/server.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
pid: 51
hostname: e095a781a8d3
2019-12-16 12:21:48,051 ERROR 51 [app_worker] start error, exiting with code:1
2019-12-16 12:21:48,056 INFO 51 [app_worker] receive signal SIGTERM, exiting with code:0
2019-12-16 12:21:48,058 INFO 51 [app_worker] beforeExit success
2019-12-16 12:21:48,058 INFO 51 [app_worker] exit with code:0
2019-12-16 12:21:48,060 INFO 52 [app_worker] receive signal SIGTERM, exiting with code:0
2019-12-16 12:21:48,062 INFO 52 [app_worker] beforeExit success
2019-12-16 12:21:48,062 INFO 52 [app_worker] exit with code:0
[2019-12-16 12:21:48.067] [cfork:master:33] worker:51 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-12-16 12:21:48.067] [cfork:master:33] don't fork, because worker:51 will be kill soon
2019-12-16 12:21:48,067 INFO 33 [master] app_worker#1:51 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
[2019-12-16 12:21:48.068] [cfork:master:33] worker:52 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-12-16 12:21:48.068] [cfork:master:33] don't fork, because worker:52 will be kill soon
2019-12-16 12:21:48,068 INFO 33 [master] app_worker#2:52 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
[2019-12-16 12:21:48.068] [cfork:master:33] worker:51 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-12-16 12:21:48,069 ERROR 33 nodejs.AppWorkerDiedError: [master] app_worker#1:51 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["2"]
    at Master.onAppExit (/data/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/data/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/data/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/data/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 33
hostname: e095a781a8d3
2019-12-16 12:21:48,070 ERROR 33 [master] app_worker#1:51 start fail, exiting with code:1
2019-12-16 12:21:48,070 ERROR 33 [master] exit with code:1
2019-12-16 12:21:48,075 ERROR 40 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2019-12-16 12:21:48,077 INFO 40 [agent_worker] beforeExit success
2019-12-16 12:21:48,077 ERROR 40 [agent_worker] exit with code:110
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-pic@1.0.0 start4docker: `egg-scripts start --workers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-pic@1.0.0 start4docker script.
```
## 相关环境信息
- **操作系统**：linux
- **Node 版本**：10.16.3+
- **Egg 版本**：2.0+

**Comment by atian25** [comment]
启动时有耗时操作导致 CPU 60s 都没时间发一次心跳。

检查下 run 下的 timing 文件看看是哪里耗时

**Comment by logzh** [comment]
@atian25 没有run和logs目录，应该是权限问题吧

**Comment by scott-leung** [comment]
> @atian25 没有run和logs目录，应该是权限问题吧

在 `/data` 目录下，确实应该注意权限问题。

**Comment by fomenyesu** [comment]
备注：
如果耗时超过60s，可以在环境变量里增加以下参数解决：

EGG_APP_CLOSE_TIMEOUT: app worker boot timeout value
EGG_AGENT_CLOSE_TIMEOUT: agent worker boot timeout value

link: [https://github.com/eggjs/egg-cluster/blob/master/README.md](https://github.com/eggjs/egg-cluster/blob/master/README.md)
