### ISSUE TITLE
egg-script  cluster options.require seems not working

### ISSUE THREAD

**Issue by StevenYuysy** [eggjs/egg#4105]
### 背景：

需要将后端应用接入 APM，APM 要求在应用的首行注入 APM 模块。如官方文档提到的 [koa 用例](https://www.elastic.co/guide/en/apm/agent/nodejs/current/koa.html#koa-initialization)。

搜索了文档之后，发现如果要在 Egg.js 实现对应的功能，参考了

https://github.com/eggjs/egg/issues/2706

里提到的 `options.require` 方法。根据 [eggjs 部署文档](https://eggjs.org/zh-cn/core/deployment.html#%E5%90%AF%E5%8A%A8%E5%91%BD%E4%BB%A4) 我尝试了两种方式

1. 在 启动配置项 里启动配置

```
// config/config.default.js

exports.cluster = {
  listen: {
    port: 7001,
    hostname: '127.0.0.1', // 不建议设置 hostname 为 '0.0.0.0'，它将允许来自外部网络和来源的连接，请在知晓风险的情况下使用
    // path: '/var/run/egg.sock',
  },
  require: path.join(appInfo.baseDir, './firsline.js')
}
```

发现这个方式并没有生效。

2. 尝试使用 `--require` 进行透传

将 package.json 的 start 命令增加 require 参数，得到

```
"start": "egg-scripts start --daemon --title=egg-server-bug --require ./firstline.js",
```

运行 `yarn start`。

结果日志输出，使用 require 参数无法找到对应模块。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

https://github.com/StevenYuysy/bug

## 复现步骤，错误日志以及相关配置

1.  `npm init egg --type=simple bug`
1. ` cd ./bug && yarn`
1. 新增 firstline.js
  ```js
  console.log('should add first line')
  ```
1. 修改 package.json start 命令 `"start": "egg-scripts start --daemon --title=egg-server-bug --require ./firstline.js",`
1. 运行 `yarn start`

```bash
[egg-scripts] Got error when startup: 
[egg-scripts] internal/modules/cjs/loader.js:584
[egg-scripts]     throw err;
[egg-scripts]     ^
[egg-scripts] 
[egg-scripts] Error: Cannot find module './firstline.js'
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:637:17)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:22:18)
[egg-scripts]     at options.require.forEach.mod (/Volumes/Dev/github/bug/node_modules/egg-cluster/lib/agent_worker.js:16:5)
[egg-scripts]     at Array.forEach (<anonymous>)
[egg-scripts]     at Object.<anonymous> (/Volumes/Dev/github/bug/node_modules/egg-cluster/lib/agent_worker.js:15:19)
```

## 相关环境信息
- **操作系统**：MacOS 10.15.2
- **Node 版本**：v10.15.3
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
- exports.cluster 并没有文档说明支持 require
- egg-scripts start --require 我记得是支持的，你试下 npm

**Comment by StevenYuysy** [comment]
`npm start ` 也是一样的结果

```bash
$ npm start

> bug@1.0.0 start /Volumes/Dev/github/bug
> egg-scripts start --daemon --title=egg-server-bug --require ./firstline.js

[egg-scripts] Starting egg application at /Volumes/Dev/github/bug
[egg-scripts] Run node /Volumes/Dev/github/bug/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-bug","require":"./firstline.js","baseDir":"/Volumes/Dev/github/bug","framework":"/Volumes/Dev/github/bug/node_modules/egg"} --title=egg-server-bug
[egg-scripts] Save log file to /Users/steven.yu/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] tail -n 100 /Users/steven.yu/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] internal/modules/cjs/loader.js:584
[egg-scripts]     throw err;
[egg-scripts]     ^
[egg-scripts] 
[egg-scripts] Error: Cannot find module './firstline.js'
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:637:17)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:22:18)
[egg-scripts]     at options.require.forEach.mod (/Volumes/Dev/github/bug/node_modules/egg-cluster/lib/agent_worker.js:16:5)
```

**Comment by atian25** [comment]
要全路径

**Comment by StevenYuysy** [comment]
全路径有一个问题，我在本地环境的路径和生产环境的路径是不一样的，有没有办法支持动态配置呢？现在这个参数是写在 package.json 里的

**Comment by atian25** [comment]
一种方式是用 Node 自带的环境变量，有个 NODE_OPTIONS
一种是你直接写个启动脚本，继承下 egg-scripts
还有一种是你直接写个 bin/start.js 里面调用下 egg-scripts

**Comment by StevenYuysy** [comment]
另外全路径确实是可以了，还有一个问题是，我在 `firstline` 里面使用了 console，但是终端并没有打出来，请问有什么方式验证它真正执行了 firstline 里面的逻辑吗？

**Comment by StevenYuysy** [comment]
感谢建议，我试下

**Comment by atian25** [comment]
console 的应该在 master-stdout.log 里面吧，这个跟 egg 关系不大了，就是 Node 的多进程。

**Comment by StevenYuysy** [comment]
话说你们不考虑支持下 相对路径吗？

**Comment by StevenYuysy** [comment]
node 的 --require  参数是支持相对路径的

**Comment by atian25** [comment]
可以提个 PR 支持下：https://github.com/node-modules/common-bin/blob/master/lib/command.js#L341

**Comment by atian25** [comment]
https://github.com/node-modules/common-bin/pull/38

**Comment by atian25** [comment]
@StevenYuysy hey, landed, please retry after reinstall dependencies.
