### ISSUE TITLE
连续for循环执行自动事务，有一条不成功

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#4108]
连续for循环执行自动事务，有一条不成功

result = await app.mysql.beginTransactionScope(async conn => {
                //mini_order_status插入新状态
                let miniOrderStatusObj = {
                    status_code: data.code,
                    module: data.module,
                    module_type: data.moduleType,
                    mini_order_id: data.id,
                    admin_id: ctx.request.body.user_id,
                    create_time: data.nowTime
                }
                let miniOrderStatusInfo = await conn.insert("mini_order_status", miniOrderStatusObj);
                console.log("miniOrderStatusInfo",miniOrderStatusInfo)
                //更新mini_order状态
                let miniOrderObj = {
                    id: data.id,
                    update_time: data.nowTime,
                    status_id: miniOrderStatusInfo.insertId,
                };
                console.log("miniOrderObj",miniOrderObj)
                await conn.update("mini_order", miniOrderObj);
                return true;
            }, ctx);

=====================================================
2019-12-18 13:43:29,836 ERROR 17508 nodejs.unhandledRejectionError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.Sequence._packetToError (E:\MES\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\MES\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\MES\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\MES\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\MES\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\MES\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\MES\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (E:\MES\node_modules\mysql\lib\Connection.js:527:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    --------------------
    at Pool.query (E:\MES\node_modules\mysql\lib\Pool.js:199:23)
    at E:\MES\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (E:\MES\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\MES\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\MES\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\MES\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\MES\node_modules\co\index.js:65:19)
    at E:\MES\node_modules\co\index.js:54:5
    sql: UPDATE `mini_order` SET `abnormal_id` = 20 WHERE `id` = 1
code: "ER_LOCK_WAIT_TIMEOUT"
errno: 1205
sqlMessage: "Lock wait timeout exceeded; try restarting transaction"
sqlState: "HY000"
index: 0
sql: "UPDATE `mini_order` SET `abnormal_id` = 20 WHERE `id` = 1"
name: "unhandledRejectionError"
pid: 17508
hostname: WJ-201911031519

**Comment by atian25** [comment]
错误写的很清楚了：2019-12-18 13:43:29,836 ERROR 17508 nodejs.unhandledRejectionError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
