### ISSUE TITLE
egg服务启动后频繁挂掉

### ISSUE THREAD

**Issue by mixtan** [eggjs/egg#4213]
egg服务启动后频繁挂掉，几分钟后自动挂掉，并且报错，看了一下应该是egg的进程通信问题，但是具体解决思路暂无想到，请求官方协助，谢谢。
`2020-03-09 13:28:21,105 INFO 18944 [master] app_worker#2:16800 disconnect, suicide: true, state: disconnected, current workers: ["2"]
[Mon Mar 09 2020 13:28:51 GMT+0800 (GMT+08:00)] [graceful:worker:16800] kill timeout, exit now.
2020-03-09 13:28:51,317 ERROR 16800 [app_worker] exit with code:1
2020-03-09 13:28:51,323 WARN 13120 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2020-03-09 13:28:51.330] [cfork:master:18944] worker:16800 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2020-03-09 13:28:51,331 ERROR 18944 nodejs.AppWorkerDiedError: [master] app_worker#2:16800 died (code: 1, signal: null, suicide: true, state: dead), current workers: []
    at Master.onAppExit (E:\test\egg-autoops\node_modules\egg-cluster\lib\master.js:510:21)
    at Master.emit (events.js:189:13)
    at Messenger.sendToMaster (E:\test\egg-autoops\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\test\egg-autoops\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.cluster.on (E:\test\egg-autoops\node_modules\egg-cluster\lib\master.js:353:22)
    at EventEmitter.emit (events.js:194:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 18944
hostname: DESKTOP-6IK5K3L
`

**Comment by hyj1991** [comment]
服务器上抓个 core 看下哪里 crash 的

**Comment by atian25** [comment]
看 common-error.log

**Comment by zhengtulymGh** [comment]
我也遇到这个问题了，本地启动没问题，服务器上用docker启动就有这个问题

**Comment by vius** [comment]
> egg服务启动后频繁挂掉，几分钟后自动挂掉，并且报错，看了一下是cluster进程通信问题
> `2020-03-09 13:28:21,105 INFO 18944 [master] app_worker#2:16800 disconnect, suicide: true, state: disconnected, current workers: ["2"] [Mon Mar 09 2020 13:28:51 GMT+0800 (GMT+08:00)] [graceful:worker:16800] kill timeout, exit now. 2020-03-09 13:28:51,317 ERROR 16800 [app_worker] exit with code:1 2020-03-09 13:28:51,323 WARN 13120 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer [2020-03-09 13:28:51.330] [cfork:master:18944] worker:16800 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false) 2020-03-09 13:28:51,331 ERROR 18944 nodejs.AppWorkerDiedError: [master] app_worker#2:16800 died (code: 1, signal: null, suicide: true, state: dead), current workers: [] at Master.onAppExit (E:\test\egg-autoops\node_modules\egg-cluster\lib\master.js:510:21) at Master.emit (events.js:189:13) at Messenger.sendToMaster (E:\test\egg-autoops\node_modules\egg-cluster\lib\utils\messenger.js:137:17) at Messenger.send (E:\test\egg-autoops\node_modules\egg-cluster\lib\utils\messenger.js:102:12) at EventEmitter.cluster.on (E:\test\egg-autoops\node_modules\egg-cluster\lib\master.js:353:22) at EventEmitter.emit (events.js:194:15) at ChildProcess.worker.process.once (internal/cluster/master.js:193:13) at Object.onceWrapper (events.js:277:13) at ChildProcess.emit (events.js:189:13) at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) name: "AppWorkerDiedError" pid: 18944 hostname: DESKTOP-6IK5K3L `
请问下怎么解决的?

**Comment by vius** [comment]
> 我也遇到这个问题了，本地启动没问题，服务器上用docker启动就有这个问题

有解决方案了吗？

**Comment by lfpei** [comment]
core用什么看？
