### ISSUE TITLE
pm2 cluster模式不能启动egg项目，app workers exit error:  TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zdmission** [eggjs/egg#4301]
## 问题
pm2 cluster模式不能启动egg项目，报错app workers exit error:  TypeError: Cannot convert undefined or null to object，但是pm2 fork模式可以启动项目并且访问，报错如下
```
2020-05-13 19:28:33,213 ERROR 37933 [master] app workers exit error:  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:399:20
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:65:19)
    at /Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:50:10)
    at Master.killAppWorkers (/Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:398:12)
    at Master._doClose (/Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:686:18)
    at _doClose.next (<anonymous>)
```

pm2 配置文件
```js
'use strict';
//  读取packae.json
const packageJSON = require('./package.json');

module.exports = {
  name: packageJSON.name,
  script: './server.js',
  instances: 1, // 启动的核数
  exec_mode: 'cluster', // 启动模式
  // exec_mode: 'fork',
  instance_var: 'INSTANCE_ID',
  vizion: false,
  env_test: {
    NODE_ENV: 'test',
    EGG_SERVER_ENV: 'unittest',
  },
  env_pre: {
    NODE_ENV: 'pre',
    EGG_SERVER_ENV: 'pre',
  },
  env_production: {
    NODE_ENV: 'production',
    EGG_SERVER_ENV: 'prod',
  },
  max_restarts: 10,
  min_uptime: 20000,
};

```

## 使用npm init egg --type=simple bug创建的项目
github地址
> https://github.com/zdmission/egg-example.git

## 操作重现步骤
1.npm run start_test
2.pm2 list 查看启动的进程
![image](https://user-images.githubusercontent.com/28522048/81810460-9010cb80-9555-11ea-90ef-33420e9971b2.png)
进程运行正常
3.浏览器访问：http://127.0.0.1:11001/，显示无法访问此网站
4.pm2 log查看，得到错误信息
```
2020-05-13 19:28:33,213 ERROR 37933 [master] app workers exit error:  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:399:20
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:65:19)
    at /Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/Users/zdmission/Desktop/iview/egg-example/node_modules/co/index.js:50:10)
    at Master.killAppWorkers (/Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:398:12)
    at Master._doClose (/Users/zdmission/Desktop/iview/egg-example/node_modules/egg-cluster/lib/master.js:686:18)
    at _doClose.next (<anonymous>)
```

## 开发环境
- **Node Version**: 10.16.3
- **Egg Version**: 2.26.1
- **Plugin Name**:
- **Plugin Version**:
- **PM2 Version**: 3.4.0
- **Platform**: Mac OS X 10.15.4

**Comment by atian25** [comment]
不要用 PM2 来启动 Egg，没啥意义。
