### ISSUE TITLE
don't fork, because worker:9700 will be kill soon

### ISSUE THREAD

**Issue by wineforyou** [eggjs/egg#4305]
## What happens?
```
 D:\code\all\server\node_modules\egg-bin\lib\start-cluster {"typescript":false,"declarations":true,"workers":1,"baseDir":"D:\\code\\all\\server","framework":"D:\\code\\all\\server\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (D:\code\all\server\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1
```
# version ：2020/05/13 更新后

**Comment by atian25** [comment]
请提供可复现方式以及更详细的日志（common-error 和 master-stderr）

**Comment by wineforyou** [comment]
稍等。我自己把版本更新到最新的试下。不好意思

**Comment by wineforyou** [comment]
请忽略。报错找到了，sequelize 设置model时 unique 过多。
但是我之前都是正常的。我自己研究下。打扰了。感谢您的回答
