### ISSUE TITLE
xdError: Request failed with status code 404

### ISSUE THREAD

**Issue by LXxxx1** [eggjs/egg#4310]
xdError: Request failed with status code 404
    at createError (/www/wwwroot/blog/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/www/wwwroot/blog/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/www/wwwroot/blog/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {

**Comment by atian25** [comment]
it's an error of axios, not eggjs
