### ISSUE TITLE
egg-mysql+ts多数据源报错undefined

### ISSUE THREAD

**Issue by donghj93** [eggjs/egg#4329]
1、config配置

```js
exports.mysql = {
    clients: {
      db1: {
        host: process.env.MYSQL_HOST,
        port: process.env.MYSQL_PORT,
        user: process.env.MYSQL_USER,
        password: process.env.MYSQL_PASSWORD,
        database: 'XXX',
      },
      db2: {
        host: process.env.MYSQL_HOST,
        port: process.env.MYSQL_PORT,
        user: process.env.MYSQL_USER,
        password: process.env.MYSQL_PASSWORD,
        database: 'XXX',
      },
      default: {
        timezone: '+08:00',
        connectionLimit: 50,
      },
    },
    // load into app,default is open //加载到应用程序，默认为打开
    app: true,
    // load into agent,default is close //加载到代理中，默认值为“关闭”
    agent: false,
  };
```

2、index.d.ts中声明

```js
declare module 'egg' {
    interface Application {
        mysql: any;
    }
}
```

3、service.js中调用

```js
const db1 = await ctx.app.mysql.get('db1');
const data = await db1.query(querySql.sql, querySql.values);
```

报错：

```bash
err: TypeError: Cannot read property 'query' of undefined
    at Common.sqlQuery (XXXX.ts:46:24)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at XXX.XXX (XXX.ts:292:12)
    at XXX.XXX (XXXX:56:24)
```

求解答

**Comment by hyj1991** [comment]
奇怪，为什么配置多数据源看到两个 issue 没办法访问了，我本地一直这么配置都没问题：

```js
config.mysql = {
  clients: {
    db1: {
      host: 'xxxxxx',
      port: 3306,
      user: 'xxxxxx',
      password: 'xxxxxx',
      database:  'xxxxxxx'
    },
    db2: {
      host: 'xxxxxx',
      port: 3306,
      user: 'xxxxxx',
      password: 'xxxxxx',
      database:  'xxxxxxx'
    }
  }
}

const db1 = app.mysql.get('db1');
await db1.query('select * from xxxx');
```

能给个可以复现的例子么？

另外，建议代码用 markdown 编辑下，这样看起来太乱了

**Comment by hyj1991** [comment]
你是不是还有其他环境的配置覆盖了这里的配置？
