### ISSUE TITLE
sofa-node 客户端多服务请求设置报错

### ISSUE THREAD

**Issue by fuxiaowo** [eggjs/egg#4335]
## What happens?
我有三个服务 a ,b ,c 

a 是服务端
```
config.rpc = {
    server: {
        namespace: 'com.alipay.sofa.rpc.protobuf',
        port:12200
    },
};
```
b 既是服务端又是客户端
```
config.rpc = {
    client: {
        serverHost: '127.0.0.1:12200',
        responseTimeout: 3000,
    },
    server: {
        namespace: 'com.alipay.sofa.rpc.protobuf',
       port:12201
    },
};
```

c 既是服务端又是客户端
```
config.rpc = {
    client: {
        serverHost: '127.0.0.1:12200',   // 这个地方怎么设置访问多个服务？
        responseTimeout: 3000,
    },
    server: {
        namespace: 'com.alipay.sofa.rpc.protobuf',
        port:12202
    },
};
```

```
2020-06-01 00:04:40,997 ERROR 98728 nodejs.EADDRINUSEError: bind EADDRINUSE null:12202
    at listenOnMasterHandle (net.js:1346:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at process.emit (/Users/admin/Documents/Projects/moogrid-server-egg/book/node_modules/_source-map-support@0.5.19@source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
errno: "EADDRINUSE"
code: "EADDRINUSE"
syscall: "bind"
address: null
port: 12202
name: "EADDRINUSEError"
pid: 98728
```
本地运行，三个服务依次启动，c服务最终会失败并报错。
如果只启动c或者b与a服务，没有问题，并能正常获取数据。
c作为客户端，怎么既能访问a又能访问b呢？

用的是 sofa-node 1.0.1  + zookeeper

**Comment by naxiaoguang** [comment]
@gxcsoccer 是不是我的配置写的不对  ？ namespace: 'com.alipay.sofa.rpc.protobuf',  protobuf 应该是可以自定义，三个服务应该是 com.alipay.sofa.rpc.a; com.alipay.sofa.rpc.b;  com.alipay.sofa.rpc.c;
是吧

**Comment by naxiaoguang** [comment]
@gxcsoccer 能否加你微信请教rpc问题？

**Comment by gxcsoccer** [comment]
参考这里： https://github.com/eggjs/egg/issues/4340#event-3399910086
