### ISSUE TITLE
onerror 捕获不到具体的错误信息

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [eggjs/egg#4353]
## What happens?

controller、service 中不做 try...catch 处理，希望在 onerror 中统一处理错误

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

MiniRepo: <https://github.com/bug-repos/egg-onerror>

## How To Reproduce

**Steps to reproduce the behavior:**
1. controller、service 中不做 try...catch 处理
controller/test.js:
```js
'use strict';

const Controller = require('egg').Controller;

class TestController extends Controller {

  constructor(ctx) {
    super(ctx);
    this.service = this.ctx.service.test;
  }
  async echo(ctx) {
    const res = await this.service.echo();
    ctx.respondData(200, res);
  }
}

module.exports = TestController;
```

service/test.js:
```js
'use strict';

const Service = require('egg').Service;

class TestService extends Service {
  constructor(ctx) {
    super(ctx);
    this.request = this.ctx.service.remoteAPI.request;
  }
  async echo() {
    const res = await this.request('get', 'https://www.oschina.net/action/openapi/user');
    return res;
  }
}

module.exports = TestService;
```
2. 在 config.onerror 中处理：
```js
config.onerror = {
    all(err, ctx) {
      console.log(err); // 这里的 err 拿不到详细信息
      ctx.body = 'error';
      ctx.status = 500;
    },
  };
```

log 输出：

```log
{ Error: non-error thrown: [object Object]
    at Object.app.context.onerror (/Users/jiangzhiguo/Workspace/bug-repos/egg-onerror/node_modules/koa-onerror/index.js:39:24)
    at onerror (/Users/jiangzhiguo/Workspace/bug-repos/egg-onerror/node_modules/koa/lib/application.js:163:32)
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 400 }
```

**Expected behavior**
1.
2.

## Context
- **Node Version**: v10.15.3
- **Egg Version**: ^2.15.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: mac

**Comment by atian25** [comment]
复现路径是访问 test ？

**Comment by Mr-jiangzhiguo** [comment]
> 复现路径是访问 test ？

/api/test

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/84861385-807c2980-b0a3-11ea-882f-4fc93c9ff900.png)

因为你返回的不是 Error 对象啊

**Comment by atian25** [comment]
改成类似就好了，具体怎么组装这个 Error 可以参考下。

```js
 try {
      const response = await axios(configObj);
      return response.data;
    } catch (err) {
      if (err.response) {
        Object.assign(err, {
          status: err.response.status,
          statusText: err.response.statusText,
          data: { API_Error: err.response.data },
          config: err.response.config,
        });
      }
      throw err;
    }
```

从这段代码来看，感觉你可能需要补下 Promise 和 Async 这块的背景知识。
