### ISSUE TITLE
ERROR 7266 nodejs.AgentWorkerDiedError

### ISSUE THREAD

**Issue by lifengsbotlp** [eggjs/egg#4355]
## What happens?

2020-06-20 18:01:58,127 ERROR 2101 [-/127.0.0.1/-/0ms GET /] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/Connection.js:412:13)
    at Object.onceWrapper (events.js:427:28)
    at Socket.emit (events.js:321:20)
    at Socket._onTimeout (net.js:478:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
    --------------------
    at Protocol._enqueue (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/macintosh/Documents/demo/MyDemo/blog/blog_server_egg_ts/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 2101
hostname: sbotlp.local
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
1、确定数据库配置完全没问题，原因，一直正常开发，关闭项目重新跑 之后遇到此问题，多尝试几次又不会出现此问题

## 相关环境信息
- **操作系统**：macOS 10.14.5 
- **Node 版本**：v13.8.0
- **Egg 版本**：2.6.1

**Comment by atian25** [comment]
handleConnectTimeout -- mysql 连接超时
