### ISSUE TITLE
nodeinstall无法使用

### ISSUE THREAD

**Issue by ninsun** [eggjs/egg#4359]
**不带--china参数时, 无法获取https://nodejs.org/dist/index.json, 因为服务器上没有该文件**
PS D:\Git\TrainningInfomationServer> nodeinstall 12
ConnectionTimeoutError: Connect timeout for 5000ms, GET https://nodejs.org/dist/index.json -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (X:\Users\ninsun\AppData\Roaming\npm\node_modules\nodeinstall\node_modules\urllib\lib\urllib.js:946:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**带--china参数时, 文件名后缀是错误的无法下载, windows系统的文件名后缀是7z或zip,不是tar.gz**
PS D:\Git\TrainningInfomationServer> nodeinstall 12 --china
Error: GET https://npm.taobao.org/mirrors/node/v12.18.1/node-v12.18.1-win-x64.tar.gz got 404
    at downloadTgz (X:\Users\ninsun\AppData\Roaming\npm\node_modules\nodeinstall\lib\installer\installer.js:125:17)
    at downloadTgz.next (<anonymous>)
    at onFulfilled (X:\Users\ninsun\AppData\Roaming\npm\node_modules\nodeinstall\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by hyj1991** [comment]
`nodeinstall` 就没有说支持 windows 吧，这个问题干嘛不提到 nodeinstall 那边去

**Comment by ninsun** [comment]
不知道为啥nodeinstall那边的readme最后的汇报bug的连接是这里的...

**Comment by hyj1991** [comment]
> 不知道为啥nodeinstall那边的readme最后的汇报bug的连接是这里的...

https://github.com/cnpm/nodeinstall/issues
