### ISSUE TITLE
egg-scripts stop之后再以daemon方式启动会失败,需要再次启动一次才可以

### ISSUE THREAD

**Issue by xuliuzhu1834** [eggjs/egg#4390]
## What happens?

egg-scripts stop之后再以daemon方式启动会失败,需要再次启动一次才可以

COMMAND: 
  npm run start -- --title=example --daemon --ignore-stderr
  npm run stop -- --title=example

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
- 1. 执行 npm run start -- --env=local --title=example --daemon --ignore-stderr
- 2. 执行 npm run stop -- --title=example
- 3. 然后立马执行 npm run start -- --env=local --title=example --daemon --ignore-stderr

启动会失败

master-stderr.log:

````2020-07-21 17:35:40,783 ERROR 21873 [master] app_worker#2:21876 start fail, exiting with code:1
2020-07-21 17:35:40,783 ERROR 21873 [master] exit with code:1
2020-07-21 17:35:40,789 ERROR 21874 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2020-07-21 17:35:40,791 ERROR 21874 [agent_worker] exit with code:110
2020-07-21 17:35:40,829 ERROR 21875 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
2020-07-21 17:35:40,882 ERROR 21877 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2020-07-21 17:35:40,970 ERROR 21878 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2020-07-21 17:35:41,251 ERROR 21882 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2020-07-21 17:35:41,280 ERROR 21879 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2020-07-21 17:35:41,300 ERROR 21881 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2020-07-21 17:35:41,317 ERROR 21880 [app_worker] exit with code:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at Object.<anonymous> (/Users/xuliuzhu/WebstormProjects/translation/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
````

## 相关环境信息
- **操作系统**：
macOS
- **Node 版本**：
12.18.0
- **Egg 版本**：
"egg": "^2.20.0",
"egg-scripts": "^2.11.0",

**Comment by atian25** [comment]
为什么要指定 --env=local  ？ 这个是本地开发用的，线上不要用。

stop 后 PS 看看进程还在不在吧，从报错看不出来是啥

**Comment by xuliuzhu1834** [comment]
env参数可以忽略, 主要是为了本地复现此问题, 我正在搞复现仓库.

**Comment by xuliuzhu1834** [comment]
抱歉,是我自己的问题,由于某个插件没有在plugin.js中启用导致的

**Comment by John-Oldman-Wang** [comment]
什么插件没有在plugin.js中启用导致的啊？
