### ISSUE TITLE
nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout

### ISSUE THREAD

**Issue by kiziboy** [eggjs/egg#4499]
## 在使用 egg-mysql 的时候 nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
这种错误一般都应该是 数据库配置有问题 但是 我前一天才配置成功过 而且 还操作了数据 都没问题 隔天就挂了。。。
数据库是跑在vagrant 中

## Mini Showcase Repository(REQUIRED)
> // config/plugin.js 
> exportsmysql = {
> enable: true,
>  package: 'egg-mysql',
 >}

> // config.default.js
> config.mysql = {
>    client: {
>      host: '192.168.33.10',
>      port: '3306',
>      user: 'homestead',
>      password: 'secret',
>      database: 'egg_article',
>    },
    app: true,
    agent: false
  }

## 在 npm run dev 的时候就会报错 错误如下
2020-10-19 20:36:47,450 ERROR 1119 nodejs.AppWorkerDiedError: [master] app_worker#1:1123 died (code: 0, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/lijun/egg/egg-2/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/Users/lijun/egg/egg-2/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/lijun/egg/egg-2/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/Users/lijun/egg/egg-2/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 1119
hostname: lijundeMacBook-Pro-4.local

2020-10-19 20:36:47,451 ERROR 1119 [master] app_worker#1:1123 start fail, exiting with code:1
2020-10-19 20:36:47,452 ERROR 1119 [master] exit with code:1
2020-10-19 20:36:47,458 ERROR 1121 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2020-10-19 20:36:47,460 ERROR 1121 [agent_worker] exit with code:110
{ Error: /Users/lijun/egg/egg-2/node_modules/egg-bin/lib/start-cluster {"typescript":false,"declarations":true,"workers":1,"baseDir":"/Users/lijun/egg/egg-2","framework":"/Users/lijun/egg/egg-2/node_modules/egg"} exit with code 1
    at ChildProcess.proc.once.code (/Users/lijun/egg/egg-2/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 2@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lijun/.npm/_logs/2020-10-19T12_36_47_472Z-debug.log

## 以下是 项目中 common-error.log 的错误
2020-10-19 19:38:54,410 ERROR 1103 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:198:13)
    at Handshake._onTimeout (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/lijun/egg/egg-demo/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/lijun/egg/egg-demo/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/lijun/egg/egg-demo/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/lijun/egg/egg-demo/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/lijun/egg/egg-demo/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 1103
hostname: lijundeMacBook-Pro-4.local

**Comment by kiziboy** [comment]
问题解决了 node 版本低了 本地是 10的版本 升级成14了 就好了

**Comment by kiziboy** [comment]
有的时候可能是虚拟机有问题 比较慢 换成 本地的数据库 就可以跑了 电脑最近虚拟机特别慢 导致链接超时了 通过laravel 可以访问到虚拟机的数据库 但是特别慢 这边可以设置 egg-mysql 的超时时间吗？

**Comment by qingdengyue** [comment]
@kiziboy 与mysql配置相同
https://www.npmjs.com/package/mysql#connection-options

**Comment by jjeejj** [comment]
这个要学会怎么去看的
这个过程是这样的： 
1: 查看 `egg-mysql`  是怎么实现的，依赖的什么库，这里发现使用的是 `ali-rds`
2: 再确定 `ali-rds` 怎么实现的，发现使用的是 `mysql` 库

如果还有依赖就这样一级一级的找下去
