### ISSUE TITLE
Can't find viewEngine for /.../app/view/index.tpl

### ISSUE THREAD

**Issue by geekdada** [eggjs/egg#455]
* **Node Version**: 7.6.0
* **Egg Version**: 1.0.0-rc.1
* **Plugin Name**: egg-view-nunjucks
* **Plugin Version**: 2.0.0
* **Platform**: macOS 10.12.3

**My configs**

```js
// {app_root}/config/plugin.js
exports.nunjucks = {
  enable: true,
  package: 'egg-view-nunjucks',
};
```

```js
exports.view = {
  defaultViewEngine: 'nunjucks',
  mapping: {
    '.tpl': 'nunjucks',
  },
};
```

**Comment by atian25** [comment]
检查你的代码, 在哪里调用 `app.viewEngine` 了,  1.0.0 里面已经移除这个了, 改为 `app.nunjucks`

**Comment by geekdada** [comment]
我从头到尾都是照着开源的文档配置的，没用过这个…

**Comment by geekdada** [comment]
写错配置…

**Comment by atian25** [comment]
看下调用栈, 查下哪有有这个关键词, 是不是其他插件里面用到了

**Comment by johnnychen** [comment]
@geekdada 怎么解决的？我也遇到这个报错了

```
AssertionError: Can't find viewEngine for /Users/johnnychq/workbench/cxinscn_cathay_portal/private/app/view/home/index.nj
    at ContextView.[contextView#render] (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.1.0.0@egg-view/lib/context_view.js:69:5)
    at next (native)
    at onFulfilled (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by geekdada** [comment]
检查你的config目录是放在项目根目录的，不是app下。

李一航
Roy Li

**Comment by popomore** [comment]
看看应用目录的 run/config_application.json 的配置是否正确
Roy Li <notifications@github.com>于2017年2月28日 周二09:05写道：

**Comment by johnnychen** [comment]
检查了，

* config目录跟app是同级的
* run/config_application.json 是自动生成的，截图如下


![image](https://cloud.githubusercontent.com/assets/1297278/23389056/ae125f86-fda0-11e6-82a4-259a30fe4574.png)

**Comment by atian25** [comment]
@johnnychen 不是看这个 key, 这个是 `plugins.nunjucks`, 要看根节点的 view 和 nunjucks

**Comment by johnnychen** [comment]
@atian25 config/plugin.js 我是按照egg-view-nunjucks官方配置的

```
 exports.nunjucks = {
   enable: true,
   package: 'egg-view-nunjucks',
 };

 exports.view = {
   defaultViewEngine: 'nunjucks',
   mapping: {
     '.nj': 'nunjucks',
   },
 };
```

**Comment by popomore** [comment]
```
 exports.view = {
   defaultViewEngine: 'nunjucks',
   mapping: {
     '.nj': 'nunjucks',
   },
 };
```

这个是放在 config/config.default.js 里的

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view-nunjucks/pull/14 还是要说清楚 -.-

**Comment by johnnychen** [comment]
-_- 谢谢

**Comment by atian25** [comment]
@johnnychen 已经在 https://github.com/eggjs/egg-view-nunjucks/issues/13 补充了

**Comment by yangg** [comment]
这个很坑啊，因为egg-init的simple模板里有这下面这个
```js
module.exports = appInfo => {
  const config = {}

  // should change to your own
  config.keys = appInfo.name + '_1492679669188_8695'

  return config
}
```
这样你不管在下面加什么都得出错，只能加到中间，或者改掉这上面的

**Comment by atian25** [comment]
@yangg 这是 Node 的基础知识来着，我觉得不算坑。

**Comment by ngot** [comment]
@yangg 这是基础知识

**Comment by yangg** [comment]
这知识我知道，但是这个模版坑，按着文档来，结果出不来

**Comment by geeyu** [comment]
```
module.exports = appInfo => {
  const config = {};

  config.keys = appInfo.name + '_1493400288522_208';
  config.view = {
    defaultViewEngine: 'nunjucks',
    mapping: {
      '.tpl': 'nunjucks',
    },
  };

  return config;
};
```
这样写就好了
