### ISSUE TITLE
EggJs项目在执行npm run dev时报错退出

### ISSUE THREAD

**Issue by ImOxygen233** [eggjs/egg#4598]
## What happens?

根据官网描述的步骤，利用脚手架快速创建了一个EggJs项目，但是却在执行npm run dev时报错了

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

就是脚手架自动生成的代码。。。

## 复现步骤，错误日志以及相关配置

复现步骤、错误日志：
E:\ProjectName\主站后端\ProjectName>npm run dev

> ProjectName@1.0.0 dev E:\ProjectName\主站后端\ProjectName
> egg-bin dev

[egg-ts-helper] create typings\app\controller\index.d.ts (29ms)
[egg-ts-helper] create typings\config\index.d.ts (13ms)
[egg-ts-helper] create typings\config\plugin.d.ts (8ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2021-02-01 23:03:57,634 INFO 3592 [master] node version v12.18.3
2021-02-01 23:03:57,635 INFO 3592 [master] egg version 2.29.1
2021-02-01 23:04:00,844 INFO 3592 [master] agent_worker#1:22176 started (3203ms)
2021-02-01 23:04:13,158 WARN 15552 [egg:core:ready_timeout] 10 seconds later E:\ProjectName\主站后端\ProjectName\node_modules\egg-watcher\lib\init.js:15:14 was still unable to finish.
2021-02-01 23:05:04,789 WARN 15552 nodejs.ResponseTimeoutError: register to channel: Watcher failed, will retry after 3s, Server no response in 60000ms, address#127.0.0.1:6635
    at Timeout._onTimeout (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:225:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
socketMeta: {"id":2,"dataLength":75,"bufferSize1":0,"bufferSize2":0,"startTime":1612191844778,"endTime":1612191844779,"writeSuccess":true}
name: "ResponseTimeoutError"
pid: 15552
hostname: ComputerName

2021-02-01 23:05:08,892 WARN 15552 [ClusterClient:Watcher] follower closed, and try to init it again
2021-02-01 23:05:08,895 ERROR 15552 [-/127.0.0.1/-/1ms GET /] nodejs.SocketCloseError: The socket was closed. (address: 127.0.0.1:6635)
    at Follower._errorCallback (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:257:13)
    at Follower._cleanInvokes (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:268:12)
    at Follower._handleClose (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:359:10)
    at Socket.<anonymous> (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:393:39)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
name: "SocketCloseError"
pid: 15552
hostname: ComputerName

2021-02-01 23:05:08,902 ERROR 15552 nodejs.SocketCloseError: The socket was closed. (address: 127.0.0.1:6635)
    at Follower._errorCallback (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:257:13)
    at Follower._cleanInvokes (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:268:12)
    at Follower._handleClose (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:359:10)
    at Socket.<anonymous> (E:\ProjectName\主站后端\ProjectName\node_modules\tcp-base\lib\base.js:393:39)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
name: "SocketCloseError"
pid: 15552
hostname: ComputerName

2021-02-01 23:05:08,906 ERROR 15552 [app_worker] start error, exiting with code:1
[2021-02-01 23:05:08.912] [cfork:master:3592] worker:15552 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2021-02-01 23:05:08.916] [cfork:master:3592] don't fork, because worker:15552 will be kill soon
2021-02-01 23:05:08,918 INFO 3592 [master] app_worker#1:15552 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2021-02-01 23:05:08.920] [cfork:master:3592] worker:15552 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2021-02-01 23:05:08,924 ERROR 3592 nodejs.AppWorkerDiedError: [master] app_worker#1:15552 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (E:\ProjectName\主站后端\ProjectName\node_modules\egg-cluster\lib\master.js:510:21)
    at Master.emit (events.js:315:20)
    at Messenger.sendToMaster (E:\ProjectName\主站后端\ProjectName\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\ProjectName\主站后端\ProjectName\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (E:\ProjectName\主站后端\ProjectName\node_modules\egg-cluster\lib\master.js:353:22)
    at EventEmitter.emit (events.js:327:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:191:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AppWorkerDiedError"
pid: 3592
hostname: ComputerName

2021-02-01 23:05:08,929 ERROR 3592 [master] app_worker#1:15552 start fail, exiting with code:1
2021-02-01 23:05:08,932 ERROR 3592 [master] exit with code:1
Error: E:\ProjectName\主站后端\ProjectName\node_modules\egg-bin\lib\start-cluster {"typescript":false,"declarations":true,"workers":1,"baseDir":"E:\\ProjectName\\主站后端\\ProjectName","framework":"E:\\ProjectName\\主站后端\\ProjectName\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (E:\ProjectName\主站后端\ProjectName\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ProjectName@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ProjectName@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenp\AppData\Roaming\npm-cache\_logs\2021-02-01T15_05_08_993Z-debug.log
E:\ProjectName\主站后端\ProjectName>

## 相关环境信息
- **操作系统**：Win10 2004
- **Node 版本**：Node.Js v12.18.3
- **Egg 版本**：Egg.Js v2.29.1

**Comment by ImOxygen233** [comment]
问题已解决，原因：Proxifer与Egg-bin冲突
