### ISSUE TITLE
 return factory(app, sequelize);

### ISSUE THREAD

**Issue by wangweiqiangs** [eggjs/egg#4619]
2021-02-24 21:16:37,172 INFO 31995 [master] node version v12.13.1
2021-02-24 21:16:37,172 INFO 31995 [master] egg version 2.29.3
/Users/abc/Desktop/eggjs/node_modules/egg-sequelize/lib/loader.js:111
          return factory(app, sequelize);
                 ^

TypeError: Class constructor Router cannot be invoked without 'new'
    at initializer (/Users/abc/Desktop/eggjs/node_modules/egg-sequelize/lib/loader.js:111:18)
    at getExports (/Users/abc/Desktop/eggjs/node_modules/egg-core/lib/loader/file_loader.js:202:15)
    at FileLoader.parse (/Users/abc/Desktop/eggjs/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/Users/abc/Desktop/eggjs/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AgentWorkerLoader.loadToApp (/Users/abc/Desktop/eggjs/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadDatabase (/Users/abc/Desktop/eggjs/node_modules/egg-sequelize/lib/loader.js:101:16)
    at module.exports (/Users/abc/Desktop/eggjs/node_modules/egg-sequelize/lib/loader.js:32:20)
    at module.exports (/Users/abc/Desktop/eggjs/node_modules/egg-sequelize/agent.js:4:26)

**Comment by zhangxh1023** [comment]
你的 `app/model` 是返回了一个 class 吧，所以报这个错误。

**Comment by hyj1991** [comment]
这个问题还有后续不？
