### ISSUE TITLE
阿里云内部发布，连接内部mysql报错。本地开发环境开vpn连接mysql可以连上。一到阿里云内部连就废了

### ISSUE THREAD

**Issue by gongshaozhu** [eggjs/egg#4628]
[egg-scripts] hostname: prod-nginx-web-172-19-70-83-aliyun-hd2

[egg-scripts] 

[egg-scripts] 2021-03-03 19:00:43,001 ERROR 10313 [app_worker] start error, exiting with code:1

[egg-scripts] 2021-03-03 19:00:43,015 ERROR 10294 nodejs.AppWorkerDiedError: [master] app_worker#2:10314 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["1","3","4"]

[egg-scripts]     at Master.onAppExit (/home/releases/prod_bff_client/jenkins-prod_bff_client-24/prod_bff_client/node_modules/egg-cluster/lib/master.js:510:21)

[egg-scripts]     at Master.emit (events.js:314:20)

[egg-scripts]     at Messenger.sendToMaster (/home/releases/prod_bff_client/jenkins-prod_bff_client-24/prod_bff_client/node_modules/egg-cluster/lib/utils/messenger.js:137:17)

[egg-scripts]     at Messenger.send (/home/releases/prod_bff_client/jenkins-prod_bff_client-24/prod_bff_client/node_modules/egg-cluster/lib/utils/messenger.js:102:12)

[egg-scripts]     at EventEmitter.<anonymous> (/home/releases/prod_bff_client/jenkins-prod_bff_client-24/prod_bff_client/node_modules/egg-cluster/lib/master.js:353:22)

[egg-scripts]     at EventEmitter.emit (events.js:326:22)

[egg-scripts]     at ChildProcess.<anonymous> (internal/cluster/master.js:191:13)

[egg-scripts]     at Object.onceWrapper (events.js:421:26)

[egg-scripts]     at ChildProcess.emit (events.js:314:20)

[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

[egg-scripts] name: "AppWorkerDiedError"

[egg-scripts] pid: 10294

[egg-scripts] hostname: prod-nginx-web-172-19-70-83-aliyun-hd2

[egg-scripts] 

[egg-scripts] 2021-03-03 19:00:43,016 ERROR 10294 [master] app_worker#2:10314 start fail, exiting with code:1

[egg-scripts] 2021-03-03 19:00:43,016 ERROR 10294 [master] exit with code:1

[egg-scripts] 2021-03-03 19:00:43,022 ERROR 10326 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false

[egg-scripts] 2021-03-03 19:00:43,022 ERROR 10302 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110

[egg-scripts] 2021-03-03 19:00:43,024 ERROR 10302 [agent_worker] exit with code:110

[egg-scripts] 

[egg-scripts] Start got error, see /root/logs/master-stderr.log

[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.

**Comment by gongshaozhu** [comment]
使用的是egg-mysql

**Comment by gemwuu** [comment]
看上去只有一个 worker 挂了，还有 3 个 worker 是正常的。exit code 110 为 ETIMEOUT，重新部署下看看呢
