### ISSUE TITLE
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed     at ChildProcess.target.send (internal/child_process.js:679:16)

### ISSUE THREAD

**Issue by tomDogwow** [eggjs/egg#4663]
错误日志如下:`2021-04-23 00:20:41,829 INFO 24700 [master] app_worker#76:38800 disconnect, suicide: true, state: disconnected, current workers: ["77"] 2021-04-23 00:20:41,830 WARN 22996 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer [2021-04-23 00:20:41.832] [cfork:master:24700] master uncaughtException: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed     at ChildProcess.target.send (internal/child_process.js:679:16)     at Worker.send (internal/cluster/worker.js:45:28)     at Server.<anonymous> (D:\EGG\demo\node_modules\_egg-cluster@1.27.0@egg-cluster\lib\master.js:219:16)     at Server.emit (events.js:310:20)     at TCP.onconnection (net.js:1558:8) Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed     at ChildProcess.target.send (internal/child_process.js:679:16)     at Worker.send (internal/cluster/worker.js:45:28)     at Server.<anonymous> (D:\EGG\demo\node_modules\_egg-cluster@1.27.0@egg-cluster\lib\master.js:219:16)     at Server.emit (events.js:310:20)     at TCP.onconnection (net.js:1558:8) {   code: 'ERR_IPC_CHANNEL_CLOSED' } (total 76 disconnect, 0 unexpected exit)`

不是百分百触发的；试了二十来分钟就触发了二次；
场景是这样的：定义了两个路由 网址均为'/name'  一个是get（模板文件1）； 一个是post方法（模板文件2）
get请求'/name' 的是一个填写id的页面 在页面上通过post提交id到'/name' （也用了csrf）;
在post提交完处理的数据展示在模板文件2上  然后再模板文件2那个页面按f5刷新  就会有几率触发这个问题；（好像隔得时间越长在刷新时触发的几率就越大....）

**Comment by hyj1991** [comment]
需要提供复现的代码
