### ISSUE TITLE
egg-sequelize插件下使用MSSQL时，运行服务报错

### ISSUE THREAD

**Issue by BresterWang** [eggjs/egg#4680]
## What happens?
egg-sequelize插件下使用MSSQL时连接数据库报错,
MSSQL的 TCP/IP协议 已启用 

## 最小可复现仓库
https://github.com/BresterWang/egg-sequelize_mssql_bug.git

## 复现步骤，错误日志以及相关配置

config/config.default.js
```
  config.sequelize = {
    dialect: 'mssql',
    database: 'xxxx',
    host: 'localhost',
    port: '1433',
    username: 'sa',
    password: 'xxxx'
  }
```
config/plugin.js
```
module.exports = {
  // had enabled by egg
  // static: {
  //   enable: true,
  // }
  sequelize: {
    enable: true,
    package: 'egg-sequelize',
  }
};
```
日志:
```
PS E:\Nodejs\Simple_bug\source> npm run dev

> bug@1.0.0 dev E:\Nodejs\Simple_bug\source
> egg-bin dev

[egg-ts-helper] create typings\app\controller\index.d.ts (3ms)
[egg-ts-helper] create typings\config\index.d.ts (15ms)
[egg-ts-helper] create typings\config\plugin.d.ts (6ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2021-05-26 02:09:12,462 INFO 28360 [master] node version v12.18.2
2021-05-26 02:09:12,463 INFO 28360 [master] egg version 2.29.4
2021-05-26 02:09:14,429 WARN 14868 Sequelize Error: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed, sleep 1 seconds to retry...
2021-05-26 02:09:15,441 WARN 14868 Sequelize Error: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed, sleep 1 seconds to retry...
2021-05-26 02:09:16,457 WARN 14868 Sequelize Error: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed, sleep 1 seconds to retry...
2021-05-26 02:09:17,483 ERROR 14868 nodejs.SequelizeConnectionError: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed
    at ConnectionManager.connect (E:\Nodejs\Simple_bug\source\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:138:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeConnectionError"
parent: {"message":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed","code":"ESOCKET"}
original: {"message":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed","code":"ESOCKET"}
pid: 14868
hostname: LAPTOP-OEAMUFVA

2021-05-26 02:09:17,485 ERROR 14868 nodejs.SequelizeConnectionError: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed
    at ConnectionManager.connect (E:\Nodejs\Simple_bug\source\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:138:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeConnectionError"
parent: {"message":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed","code":"ESOCKET"}
original: {"message":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed","code":"ESOCKET"}
pid: 14868
hostname: LAPTOP-OEAMUFVA

2021-05-26 02:09:17,487 ERROR 14868 [agent_worker] start error, exiting with code:1
2021-05-26 02:09:17,504 ERROR 28360 nodejs.AgentWorkerDiedError: [master] agent_worker#1:14868 died (code: 1, signal: null)
    at Master.onAgentExit (E:\Nodejs\Simple_bug\source\node_modules\egg-cluster\lib\master.js:425:17)
    at Master.emit (events.js:315:20)
    at Messenger.sendToMaster (E:\Nodejs\Simple_bug\source\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\Nodejs\Simple_bug\source\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at ChildProcess.<anonymous> (E:\Nodejs\Simple_bug\source\node_modules\egg-cluster\lib\master.js:289:22)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AgentWorkerDiedError"
pid: 28360
hostname: LAPTOP-OEAMUFVA

2021-05-26 02:09:17,506 ERROR 28360 [master] agent_worker#1:14868 start fail, exiting with code:1
2021-05-26 02:09:17,507 ERROR 28360 [master] exit with code:1
Error: E:\Nodejs\Simple_bug\source\node_modules\egg-bin\lib\start-cluster {"declarations":true,"tscompiler":"ts-node/register","workers":1,"baseDir":"E:\\Nodejs\\Simple_bug\\source","framework":"E:\\Nodejs\\Simple_bug\\source\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (E:\Nodejs\Simple_bug\source\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1
}

```

## 相关环境信息
- **操作系统**：Windows 10
- **Node 版本**：v12.18.2
- **Egg 版本**：2.29.4
- **egg-sequelize版本** : 6.0.0
- **tedious版本** : 11.0.8

**Comment by BresterWang** [comment]
@atian25 大佬，求帮助

**Comment by BresterWang** [comment]
查到原因了，需要增加配置{encrypt: false}，
config/config.default.js
```
  config.sequelize = {
    dialect: 'mssql',
    database: 'database',
    host: 'localhost',
    port: '1433',
    username: 'username',
    password: 'password',
    dialectOptions: {
      options: {
        encrypt: false
      }
    }
  }
```
