### ISSUE TITLE
egg:core:ready_timeout怎么设置

### ISSUE THREAD

**Issue by nightmareT** [eggjs/egg#4694]
通过Jenkins跑ci的时候，使用egg_mock跑ut，很大概率出现如下报错
2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/egg-mongoose/lib/mongoose.js:91:7 was still unable to finish.
2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/app.ts:1:5366 was still unable to finish.
2021-06-15 11:25:18,974 ERROR 19291 [egg-mongoose] mongodb://127.0.0.1:27017/insightunittest disconnected
2021-06-15 11:25:18,979 ERROR 19291 nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connection timed out]
    at Pool.<anonymous> (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/pool.js:561:14)
    at connect (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.err (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "MongoNetworkError"
pid: 19291
hostname: build

直接在这台服务器上连mongo正常，需要大概10几秒钟，请问下怎么设置这个超时时间到60来避免这个问题

**Comment by jiesia** [comment]
你可以尝试修改 process.env.EGG_READY_TIMEOUT_ENV = 60000

**Comment by jiesia** [comment]
> 通过Jenkins跑ci的时候，使用egg_mock跑ut，很大概率出现如下报错
> 2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
> 2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/egg-mongoose/lib/mongoose.js:91:7 was still unable to finish.
> 2021-06-15 11:25:18,967 WARN 19291 [egg:core:ready_timeout] 10 seconds later /var/lib/jenkins/workspace/metis_pipeline/src/metis/server/app.ts:1:5366 was still unable to finish.
> 2021-06-15 11:25:18,974 ERROR 19291 [egg-mongoose] mongodb://127.0.0.1:27017/insightunittest disconnected
> 2021-06-15 11:25:18,979 ERROR 19291 nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connection timed out]
> at Pool. (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/topologies/server.js:438:11)
> at emitOne (events.js:116:13)
> at Pool.emit (events.js:211:7)
> at createConnection (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/pool.js:561:14)
> at connect (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/pool.js:994:11)
> at makeConnection (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:31:7)
> at callback (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:264:5)
> at Socket.err (/var/lib/jenkins/workspace/metis_pipeline/src/metis/server/node_modules/mongodb/lib/core/connection/connect.js:294:7)
> at Object.onceWrapper (events.js:313:30)
> at emitNone (events.js:106:13)
> at Socket.emit (events.js:208:7)
> at Socket._onTimeout (net.js:422:8)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5)
> name: "MongoNetworkError"
> pid: 19291
> hostname: build
> 
> 直接在这台服务器上连mongo正常，需要大概10几秒钟，请问下怎么设置这个超时时间到60来避免这个问题

你可以尝试修改 process.env.EGG_READY_TIMEOUT_ENV = 60000
