### ISSUE TITLE
ClusterClientNoResponseError

### ISSUE THREAD

**Issue by hqxluoyang** [eggjs/egg#4696]
程序运行中遇到下面的错误， 服务器会假死状态，

nodejs.ClusterClientNoResponseError: client no response in 99316ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/home/ubuntu/hqx/youtube_music_download/main/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 2751

**Comment by jiesia** [comment]
> 程序运行中遇到下面的错误， 服务器会假死状态，
> 
> nodejs.ClusterClientNoResponseError: client no response in 99316ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
> at Timeout._onTimeout (/home/ubuntu/hqx/youtube_music_download/main/node_modules/cluster-client/lib/leader.js:77:23)
> at listOnTimeout (internal/timers.js:554:17)
> at processTimers (internal/timers.js:497:7)
> name: "ClusterClientNoResponseError"
> pid: 2751

这个问题在 issues 中有的，你可以看看 https://github.com/eggjs/egg/issues/466

**Comment by wv1124** [comment]
at Timeout._onTimeout (/home/node/shop-bff/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    
    升级OS也出现这个问题
    
    # strace -p 2109
strace: Process 2109 attached
recvmsg(143, 
```

eggjs 两个进程被卡在recvmsg上，导致出现大量CLOSE_WAIT连接。

系统：
CentOS Linux release 7.9.2009 (Core)
Linux version 3.10.0-1160.53.1.el7.x86_64
alinode-v5.18.1
