### ISSUE TITLE
重启egg程序，突然报错 ERROR 16202 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined

### ISSUE THREAD

**Issue by anxuanyang** [eggjs/egg#4716]
更新程序，重启的时候日志显示 `ERROR 16202 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined`，没有添加新的依赖，仅仅是修改了文件中的一点逻辑。相同程序放到另外一个服务器启动正常。在出问题的服务器上使用`npm init egg --type=simple`创建了一个demo程序，`npm run dev`时也是同样的错误，在另外的服务器上使用`npm init egg --type=simple`创建，`npm run dev`启动正常。

完整启动日志：
```
npm run dev

> example@1.0.0 dev /home/egg/test/egg-example
> egg-bin dev

[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (16ms)
[egg-ts-helper] create typings/config/plugin.d.ts (1ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2021-07-16 19:51:46,185 INFO 16122 [master] node version v14.16.0
2021-07-16 19:51:46,186 INFO 16122 [master] egg version 2.29.4
2021-07-16 19:51:46,971 INFO 16122 [master] agent_worker#1:16187 started (776ms)
2021-07-16 19:51:57,688 WARN 16202 [egg:core:ready_timeout] 10 seconds later /home/egg/test/egg-example/node_modules/egg-watcher/lib/init.js:15:14 was still unable to finish.
2021-07-16 19:52:47,799 ERROR 16202 [-/127.0.0.1/-/1ms GET /] nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined
    at Function.waitFor (/home/egg/test/egg-example/node_modules/cluster-client/lib/server.js:238:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ClusterClient.[ClusterClient#createClient] (/home/egg/test/egg-example/node_modules/cluster-client/lib/wrapper/cluster.js:42:7)
    at async ClusterClient.[ClusterClient#init] (/home/egg/test/egg-example/node_modules/cluster-client/lib/wrapper/base.js:71:25)

pid: 16202
hostname: iZ2jdh86HGwqfiyp2f1Z

2021-07-16 19:52:47,800 ERROR 16202 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined
    at Function.waitFor (/home/egg/test/egg-example/node_modules/cluster-client/lib/server.js:238:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ClusterClient.[ClusterClient#createClient] (/home/egg/test/egg-example/node_modules/cluster-client/lib/wrapper/cluster.js:42:7)
    at async ClusterClient.[ClusterClient#init] (/home/egg/test/egg-example/node_modules/cluster-client/lib/wrapper/base.js:71:25)

pid: 16202
hostname: iZ2jdh86HGwqfiyp2f1Z

2021-07-16 19:52:47,800 ERROR 16202 [app_worker] start error, exiting with code:1
[2021-07-16 19:52:47.826] [cfork:master:16122] worker:16202 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2021-07-16 19:52:47.826] [cfork:master:16122] don't fork, because worker:16202 will be kill soon
2021-07-16 19:52:47,826 INFO 16122 [master] app_worker#1:16202 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2021-07-16 19:52:47.827] [cfork:master:16122] worker:16202 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2021-07-16 19:52:47,828 ERROR 16122 nodejs.AppWorkerDiedError: [master] app_worker#1:16202 died (code: 0, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/home/egg/test/egg-example/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:315:20)
    at Messenger.sendToMaster (/home/egg/test/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/home/egg/test/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/home/egg/test/egg-example/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:327:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:199:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
name: "AppWorkerDiedError"
pid: 16122
hostname: iZ2jdh86HGwqfiyp2f1Z

2021-07-16 19:52:47,829 ERROR 16122 [master] app_worker#1:16202 start fail, exiting with code:1
2021-07-16 19:52:47,829 ERROR 16122 [master] exit with code:1
2021-07-16 19:52:47,838 ERROR 16187 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2021-07-16 19:52:47,841 ERROR 16187 [agent_worker] exit with code:110
Error: /home/egg/test/egg-example/node_modules/egg-bin/lib/start-cluster {"declarations":true,"tscompiler":"ts-node/register","workers":1,"baseDir":"/home/egg/test/egg-example","framework":"/home/egg/test/egg-example/node_modules/egg"} exit with code 1
    at ChildProcess.<anonymous> (/home/egg/test/egg-example/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/egg/.npm/_logs/2021-07-16T11_52_47_855Z-debug.log
```

## 相关环境信息
- **操作系统**：Centos 7.5
- **Node 版本**：v14.16.0
- **Egg 版本**：2.15.1

**Comment by anxuanyang** [comment]
重启服务器后程序就可以正常启动了，暂时解决，原因未知。
