### ISSUE TITLE
Cannot read property 'appInfo' of undefined

### ISSUE THREAD

**Issue by askie** [eggjs/egg#472]
编写插件是出现的错误，不确定问题出在哪里了：
代码：
```javascript
function loadModel(app) {
    const dir = path.join(app.baseDir, 'app/model');
    console.log('[egg-camo] dir', dir);
    app.loader.loadToApp(dir, 'model', { 【这一行出错】
        inject: app.camo,
    });
}
```

```javascript
2017-02-27 18:00:10,561 INFO 31698 [master] =================== egg start =====================
2017-02-27 18:00:10,564 INFO 31698 [master] egg version 0.9.0
2017-02-27 18:00:10,566 INFO 31698 [master] start with options: {"customEgg":"/wwwroot/mvideor/egg/node_modules/egg","baseDir":"/wwwroot/mvideor/egg","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":""}
2017-02-27 18:00:10,566 INFO 31698 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development
2017-02-27 18:00:10,577 INFO 31698 [master] Agent Worker:31699 start with ["{\"customEgg\":\"/wwwroot/mvideor/egg/node_modules/egg\",\"baseDir\":\"/wwwroot/mvideor/egg\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"clusterPort\":55360}"]
agent.config.env = local
2017-02-27 18:00:11,274 INFO 31699 [egg:watcher:agent] watcher start success
2017-02-27 18:00:11,281 INFO 31698 [master] Agent Worker started (711ms)
2017-02-27 18:00:11,288 INFO 31698 [master] App Worker#1:31700 start, state: none, current workers: ["1"]
----------------[egg-camo] dir /wwwroot/mvideor/egg/app/model
/wwwroot/mvideor/egg/node_modules/egg-core/lib/utils/index.js:41
    const baseDir = app.loader.appInfo.baseDir;
                              ^

TypeError: Cannot read property 'appInfo' of undefined
    at Object.getPathName (/wwwroot/mvideor/egg/node_modules/egg-core/lib/utils/index.js:41:31)
    at FileLoader.parse (/wwwroot/mvideor/egg/node_modules/egg-core/lib/loader/file_loader.js:86:46)
    at FileLoader.load (/wwwroot/mvideor/egg/node_modules/egg-core/lib/loader/file_loader.js:33:24)
    at AppWorkerLoader.loadToApp (/wwwroot/mvideor/egg/node_modules/egg-core/lib/loader/egg_loader.js:274:25)
    at loadModel (/wwwroot/mvideor/egg/app/plugins/egg-camo/lib/camo.js:32:16)
    at module.exports.app (/wwwroot/mvideor/egg/app/plugins/egg-camo/lib/camo.js:22:5)
    at module.exports.app (/wwwroot/mvideor/egg/app/plugins/egg-camo/app.js:5:26)
    at AppWorkerLoader.loadFile (/wwwroot/mvideor/egg/node_modules/egg-core/lib/loader/egg_loader.js:215:34)
    at getLoadUnits.forEach.unit (/wwwroot/mvideor/egg/node_modules/egg-core/lib/loader/mixin/custom.js:25:29)
    at Array.forEach (native)
[Mon Feb 27 2017 18:00:13 GMT+0800 (CST)] [cfork:master:31698] worker:31700 disconnect (suicide: false, state: disconnected, isDead: false)
[Mon Feb 27 2017 18:00:13 GMT+0800 (CST)] [cfork:master:31698] don't fork new work (refork: false)
2017-02-27 18:00:13,506 INFO 31698 [master] App Worker#1:31700 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[Mon Feb 27 2017 18:00:13 GMT+0800 (CST)] [cfork:master:31698] worker:31700 exit (code: 1, suicide: false, state: dead, isDead: true, isExpected: true)
2017-02-27 18:00:13,511 ERROR 31698 nodejs.AppWorkerDiedError: [master] App Worker#1:31700 died (code: 1, signal: 1, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/wwwroot/mvideor/egg/node_modules/egg-cluster/lib/master.js:284:19)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:188:7)
    at Messenger.sendToMaster (/wwwroot/mvideor/egg/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/wwwroot/mvideor/egg/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/wwwroot/mvideor/egg/node_modules/egg-cluster/lib/master.js:194:22)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:379:15)
    at ChildProcess.g (events.js:291:16)
name: 'AppWorkerDiedError'
pid: 31698
```

**Comment by popomore** [comment]
可能是个 bug，inject 是非 app

**Comment by popomore** [comment]
inject 可以先传 app，这样应该可以跑过
