### ISSUE TITLE
TypeError: bootstrap_1.app.mockContext is not a function

### ISSUE THREAD

**Issue by JarvisQJ** [eggjs/egg#4749]
许久没有跑单元测试，最近发现无法运行起来了。

运行单元测试报错：
test/app/service/jsError.test.ts
    1) should exist the right sid
    2) "after each" hook for "should exist the right sid"

  0 passing (6s)
  2 failing

  1) test/app/service/jsError.test.ts
       should exist the right sid:
     TypeError: bootstrap_1.app.mockContext is not a function
      at Context.<anonymous> (test\app\service\jsError.test.ts:7:15)
      at processImmediate (internal/timers.js:456:21)
      [use `--full-trace` to display the full stack trace]

  2) "after each" hook for "should exist the right sid":
     TypeError: app.backgroundTasksFinished is not a function
      at Context.<anonymous> (node_modules\egg-mock\bootstrap.js:23:21)
      at processImmediate (internal/timers.js:456:21)
      [use `--full-trace` to display the full stack trace]

Error: D:\works\TinyMonitorServer\node_modules\egg-bin\node_modules\mocha\bin\_mocha --declarations,--timeout=60000,--exit,--require=D:\works\TinyMonitorServer\node_modules\egg-bin\lib\mocha-clean.js,--require=D:\works\TinyMonitorServer\node_modules\co-mocha\lib\co-mocha.js,--require=D:\works\TinyMonitorServer\node_modules\intelli-espower-loader\intelli-espower-loader.js,--require=D:\works\TinyMonitorServer\node_modules\espower-typescript\guess.js,test/app/controller/warning.test.ts,test/app/service/espaceMessage.test.ts,test/app/service/jsError.test.ts,test/app/service/warning.test.ts exit with
code 2
    at ChildProcess.<anonymous> (D:\works\TinyMonitorServer\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 2
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-monitor-server@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-monitor-server@1.0.0 test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qwx971593\AppData\Roaming\npm-cache\_logs\2021-09-06T08_30_45_288Z-debug.log
npm ERR! Test failed.  See above for more details.

npm i 装包无异常。

**Comment by JarvisQJ** [comment]
只有我遇到了吗，搜不到匹配的。这种情况感觉只能去啃源码了，无助。。。。。

**Comment by JarvisQJ** [comment]
原因没有找到。
后来通过删除package-lock.json，然后重新装包解决的。刚开始没想起来删除package-lock.json，一直重新装依赖都不行。
