### ISSUE TITLE
egg-mongoose配置连接失败

### ISSUE THREAD

**Issue by oneQiu** [eggjs/egg#4757]
![image](https://user-images.githubusercontent.com/50658231/133357054-faed28a5-a542-4d12-800a-fa86eee0cf73.png)

[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/app/middleware/index.d.ts (1ms)
[egg-ts-helper] create typings/app/model/index.d.ts (1ms)
[egg-ts-helper] create typings/config/index.d.ts (17ms)
[egg-ts-helper] create typings/config/plugin.d.ts (2ms)
[egg-ts-helper] create typings/app/service/index.d.ts (1ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2021-09-15 09:44:56,542 INFO 35266 [master] node version v14.17.6
2021-09-15 09:44:56,543 INFO 35266 [master] egg version 2.30.0
2021-09-15 09:44:58,943 ERROR 35271 nodejs.TSError: [egg-core] load file: /Users/qiuqiu/code/egg-demo-ts/config/config.default.ts, error: ⨯ Unable to compile TypeScript:
config/config.default.ts(16,7): error TS2739: Type '{ user: string; useUnifiedTopology: true; pass: string; }' is missing the following properties from type 'ConnectOptions': family, hints, localAddress, localPort, lookup

config/config.default.ts(16,7): error TS2739: Type '{ user: string; useUnifiedTopology: true; pass: string; }' is missing the following properties from type 'ConnectOptions': family, hints, localAddress, localPort, lookup

    at createTSError (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:261:12)
    at getOutput (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:367:40)
    at Object.compile (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
diagnosticText: "config/config.default.ts(16,7): error TS2739: Type '{ user: string; useUnifiedTopology: true; pass: string; }' is missing the following properties from type 'ConnectOptions': family, hints, localAddress, localPort, lookup\n"
diagnosticCodes: [2739]
pid: 35271
hostname: B-C3WKML85-1838.local
下载以后按照egg-mongoose的文档配置，显示缺失这几个属性值，但是按照error去配置，又是另外的报错
这几个字段到底是需要还是不需要呢？需要的话为什么提示不支持这几个字段呢，具体应该怎么配置才正确呢，第一次使用，感谢解答。
![image](https://user-images.githubusercontent.com/50658231/133357440-4d9930b1-2c6b-48da-b296-013253c7ed24.png)

[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/app/middleware/index.d.ts (1ms)
[egg-ts-helper] create typings/app/model/index.d.ts (1ms)
[egg-ts-helper] create typings/config/index.d.ts (21ms)
[egg-ts-helper] create typings/config/plugin.d.ts (2ms)
[egg-ts-helper] create typings/app/service/index.d.ts (1ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2021-09-15 09:51:14,370 INFO 35338 [master] node version v14.17.6
2021-09-15 09:51:14,371 INFO 35338 [master] egg version 2.30.0
2021-09-15 09:51:16,654 INFO 35338 [master] agent_worker#1:35343 started (2280ms)
(node:35347) [MONGODB DRIVER] Warning: the options [localAddress] is not supported
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35347) [MONGODB DRIVER] Warning: the options [localPort] is not supported
(node:35347) [MONGODB DRIVER] Warning: the options [hints] is not supported
(node:35347) [MONGODB DRIVER] Warning: the options [lookup] is not supported
2021-09-15 09:51:19,578 ERROR 35347 [-/127.0.0.1/-/0ms GET /] nodejs.TSError: [egg-core] load file: /Users/qiuqiu/code/egg-demo-ts/app/model/user.ts, error: ⨯ Unable to compile TypeScript:
app/model/user.ts(2,28): error TS2306: File '/Users/qiuqiu/code/egg-demo-ts/node_modules/Mongoose/index.d.ts' is not a module.

app/model/user.ts(2,28): error TS2306: File '/Users/qiuqiu/code/egg-demo-ts/node_modules/Mongoose/index.d.ts' is not a module.

    at createTSError (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:261:12)
    at getOutput (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:367:40)
    at Object.compile (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/qiuqiu/code/egg-demo-ts/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.loadFile (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:27:19)
    at getExports (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-core@4.20.0@egg-core/lib/loader/file_loader.js:199:23)
    at FileLoader.parse (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-core@4.20.0@egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-core@4.20.0@egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-core@4.20.0@egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/Users/qiuqiu/code/egg-demo-ts/node_modules/_egg-mongoose@3.3.1@egg-mongoose/lib/mongoose.js:124:14)
diagnosticText: "app/model/user.ts(2,28): error TS2306: File '/Users/qiuqiu/code/egg-demo-ts/node_modules/Mongoose/index.d.ts' is not a module.\n"
diagnosticCodes: [2306]
pid: 35347
hostname: B-C3WKML85-1838.local

直接使用 npm init egg --type=ts生成的项目

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v14.17.6
- **Egg 版本**：2.6.1

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/133358975-b44f0092-40c9-4fab-af10-31aa4bf6390f.png)
