### ISSUE TITLE
项目在dev环境下 会报 read ECONNRESET

### ISSUE THREAD

**Issue by lopo1983** [eggjs/egg#4777]
## What happens?
开发环境下 周期性出现
2021-10-13 11:10:06,436 ERROR 11484 [egg-redis] client error: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
2021-10-13 11:10:06,439 ERROR 11484 nodejs.ECONNRESETError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "ECONNRESETError"
pid: 11484
hostname: DESKTOP-J52QUAR

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：14.18.0
- **Egg 版本**：2.15.1

**Comment by lopo1983** [comment]
出现上述报错的同时 redis 相关的操作均会失败
