### ISSUE TITLE
2021-11-16 15:31:04,049 ERROR 15873 nodejs.unhandledExceptionError: ENOENT: no such file or directory, scandir '/Users/jsyang/work/exercise/egg-example/node_modules/egg-session/app/schedule'

### ISSUE THREAD

**Issue by jsyanyang** [eggjs/egg#4798]
## What happens?

用npm init egg --type=simple创建的仓库，安装依赖之后跑不起来
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
```bash
2021-11-16 15:31:04,407 ERROR 15872 nodejs.AppWorkerDiedError: [master] app_worker#1:15876 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/jsyang/work/exercise/egg-example/node_modules/egg-cluster/lib/master.js:511:21)
    at Master.emit (node:events:390:28)
    at Messenger.sendToMaster (/Users/jsyang/work/exercise/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/jsyang/work/exercise/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/Users/jsyang/work/exercise/egg-example/node_modules/egg-cluster/lib/master.js:354:22)
    at EventEmitter.emit (node:events:402:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:203:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
name: "AppWorkerDiedError"
pid: 15872
hostname: jsyangdeMacBook-Pro.local

2021-11-16 15:31:04,407 ERROR 15872 [master] app_worker#1:15876 start fail, exiting with code:1
2021-11-16 15:31:04,408 ERROR 15872 [master] exit with code:1
2021-11-16 15:31:04,411 ERROR 15873 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
```

## 相关环境信息
- **操作系统**：macos M1
- **Node 版本**：17.0.1
- **Egg 版本**：2.32.0

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/141942439-62ab8da2-563f-4da8-b25c-60d934d44443.png)

**Comment by atian25** [comment]
请提供最小可复现仓库。

另外，试下重新删除安装依赖

**Comment by DNA643** [comment]
降级 node 版本即可，我刚在 node v17.1.0 上也遇到了，降级到 v14.x.x 即可（eg: v14.16.0）

**Comment by hyj1991** [comment]
> 降级 node 版本即可，我刚在 node v17.1.0 上也遇到了，降级到 v14.x.x 即可（eg: v14.16.0）

因为 v17.x 开始 `readable._read` 里面的 error 异步抛出了，导致 egg 扫描目录的一个依赖模块跪了。

```js
const Readable = require('stream').Readable;

const stream = new Readable({ objectMode: true });;

stream._read = () => {
  throw 2;
}

const data = stream.read();
console.log(1, data);
```

这段代码在 v17.x 以前会直接 throw，但是在 v17.x 因为异步抛错会先输出 `1, null` 后抛错。
