### ISSUE TITLE
用pkg打包eggjs，node-dir第三方包报错：fs.readdirSync(buffer, { encoding: 'buffer' })返回string了

### ISSUE THREAD

**Issue by daoshenjay** [eggjs/egg#4801]
eggjs项目里，使用了require-context包，此包又依赖node-dir包，在win10上使用pkg打包后，运行exe报错：

```bash
[egg-core] load file: C:\snapshot\DemoEggPkg\app\router.js, error: The "list[2]" argument must be an instance of Buffer or
Uint8Array. Received type string ('home.js') at Function.concat (buffer.js:571:13) at onDirRead 
(C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:135:28) at onStat 
(C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:154:14) at Object.files 
(C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:162:12) at C:\snapshot\DemoEggPkg\node_modules\require-
context\index.js:17:6 at Object.<anonymous> (C:\snapshot\DemoEggPkg\app\router.js) at Module._compile 
(pkg/prelude/bootstrap.js:1794:22) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load 
(internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) code: 
"ERR_INVALID_ARG_TYPE" pid: 14636 hostname: DESKTOP-O20K12N
```

报错位置在

```js
// \node_modules\node-dir\lib\paths.js line 153：
`const list = fs.readdirSync(bufdir, { encoding: 'buffer' })`
```

这里list得到的是一个string数组，而不是buffer数组。

我也提了一个 [issue](https://github.com/vercel/pkg/issues/1399) 给pkg那边，结果得到的是需要eggjs这边支持，希望帮忙看下怎么解决，[这里](https://github.com/daoshenjay/DemoEggPkg) 有一个可以复现的demo project。
复现步骤：

```bash
step 1:
npm install

step 2:
npm run pkg-win // windows

step 3:
cd dist
DemoEgg.exe start --daemon
```

**Comment by daoshenjay** [comment]
别沉，有人有任何想法或者解决方式吗

**Comment by hyj1991** [comment]
不好意思，我来看下这个问题

**Comment by daoshenjay** [comment]
@hyj1991 感谢感谢！

**Comment by hyj1991** [comment]
这和 egg 无关，是你自己的代码导致的：

https://github.com/daoshenjay/DemoEggPkg/blob/master/app/router.js#L4

**Comment by hyj1991** [comment]
`node-dir` 这个库是 `require-context` 这个包引入的，这部分逻辑是你自己添加的，排查下 api 用法吧

**Comment by daoshenjay** [comment]
好的，谢谢，我再研究下
