### ISSUE TITLE
ctx.render方法不存在

### ISSUE THREAD

**Issue by bing1021** [eggjs/egg#481]
node 版本 v6.10.0
egg 版本 ^1.0.0-rc.1

使用 egg-view-nunjucks 渲染模板，报错。

错误为：ctx.render is not a function

render 方法不是挂载在context对象上的吗？

**Comment by atian25** [comment]
看下 egg-view-nunjucks 什么版本的

发自我的 iPhone

> 在 2017年2月28日，22:19，bing1021 <notifications@github.com> 写道：
> 
> egg-view-nunjucks

**Comment by popomore** [comment]
上传下配置看看 https://eggjs.org/zh-cn/faq.html#为什么我的配置不生效

**Comment by bing1021** [comment]
nunjucks 版本 0.5.0

// package.json
"dependencies": {
    "egg": "^1.0.0-rc.1",
    "egg-view": "^1.0.1",
    "egg-view-nunjucks": "0.5.0"
  },
  "devDependencies": {
    "egg-bin": "^2.2.3"
  }

**Comment by atian25** [comment]
升级到最新版。

发自我的 iPhone

**Comment by bing1021** [comment]
egg-view-nunjucks 换到2.0.0版本后， npm run dev 出错

**Comment by atian25** [comment]
那要给出报错信息啊。。。

**Comment by bing1021** [comment]
017-02-28 22:38:20,470 INFO 3685 [master] =================== egg start =====================
2017-02-28 22:38:20,474 INFO 3685 [master] egg version 1.0.0-rc.1
2017-02-28 22:38:20,475 INFO 3685 [master] start with options: {"customEgg":"/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg","baseDir":"/Users/zhangbing/my_code/demos/egg_demo","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":""}
2017-02-28 22:38:20,475 INFO 3685 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development
2017-02-28 22:38:20,483 INFO 3685 [master] Agent Worker:3686 start with ["{\"customEgg\":\"/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg\",\"baseDir\":\"/Users/zhangbing/my_code/demos/egg_demo\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"clusterPort\":56622}"]
2017-02-28 22:38:20,871 WARN 3686 [egg:loader] pluginName(view) is different from pluginConfigName(nunjucks)
/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-core/lib/loader/mixin/plugin.js:274
      throw err;
      ^

PluginSequencifyError: sequencify plugins has problem, missing: [], recursive: [view,view]
    at AgentWorkerLoader.getOrderPlugins (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-core/lib/loader/mixin/plugin.js:261:19)
    at AgentWorkerLoader.loadPlugin (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-core/lib/loader/mixin/plugin.js:127:30)
    at AgentWorkerLoader.loadConfig (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg/lib/loader/agent_worker_loader.js:19:11)
    at EggApplication (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg/lib/egg.js:35:17)
    at Agent (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg/lib/agent.js:21:5)
    at Object.<anonymous> (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-cluster/lib/agent_worker.js:15:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
2017-02-28 22:38:20,882 ERROR 3685 nodejs.AgentWorkerDiedError: [master] Agent Worker 3686 died (code: 1, signal: null)
    at Master.onAgentExit (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-cluster/lib/master.js:235:17)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:188:7)
    at Messenger.sendToMaster (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at ChildProcess.agentWorker.once (/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-cluster/lib/master.js:151:22)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
name: 'AgentWorkerDiedError'
pid: 3685
hostname: zhangbingdeAir

2017-02-28 22:38:20,883 ERROR 3685 [master] agent start fail, exit now
2017-02-28 22:38:20,883 INFO 3685 [master] exit with code: 1
[common-bin] run dev with ["--baseDir","/Users/zhangbing/my_code/demos/egg_demo","--cluster","1","--eggPath=/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg"] at /Users/zhangbing/my_code/demos/egg_demo error:
Error: /Users/zhangbing/my_code/demos/egg_demo/node_modules/egg-bin/lib/start-cluster --baseDir,/Users/zhangbing/my_code/demos/egg_demo,--cluster,1,--eggPath=/Users/zhangbing/my_code/demos/egg_demo/node_modules/egg exit with code 1
    at ChildProcess.<anonymous> (/Users/zhangbing/my_code/demos/egg_demo/node_modules/common-bin/lib/helper.js:31:21)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! egg_demo@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg_demo@1.0.0 dev script 'egg-bin dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the egg_demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     egg-bin dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs egg_demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls egg_demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhangbing/my_code/demos/egg_demo/npm-debug.log

**Comment by bing1021** [comment]
不能截图，就粘贴了

**Comment by popomore** [comment]
看一下 egg-view-nunjucks 的模块，plugin.js 配错了
bing1021 <notifications@github.com>于2017年2月28日 周二22:40写道：

**Comment by atian25** [comment]
你之前的版本太旧了，这里配置变更了，看下 egg-view-nunjucks 的 README，plugin.js 里面的 exports.view 要改为 exports.nunjucks

**Comment by bing1021** [comment]
我是按照 官方文档 快速入门 里面设置的

// config/plugin.js
exports.view = {
  enable: true,
  package: 'egg-view-nunjucks'
};

**Comment by atian25** [comment]
这里应该是改漏了，最近 view 这块做了重构，支持多引擎，所以有 break change。 文档明天我改下。

**Comment by bing1021** [comment]
谢谢啦

**Comment by bing1021** [comment]
谢谢了，你们好辛苦

**Comment by atian25** [comment]
@bing1021 已在 #482 修复了，文档已更新。

**Comment by yekexuan** [comment]
@atian25 egg升级的话，更新package的依赖就好了嘛？

**Comment by atian25** [comment]
嗯，这个问题是特殊场景下导致的，因为 0.x 不是正式版本，所以在兼容性方面不会太严格，在 egg 1.x 发布后，就会严格遵循 semver 规则，不用担心兼容性问题。

也正是因为 semver，我们推荐用 `^1.0.0` ，而不是写死版本(`1.0.0` , `~1.0.0`) 的方式来引入我们的模块，放心升级。

另外，如果你注意看我们的项目，还有骨架， 会发现我们都有配置了 autod 这个库，它就是用来快速升级依赖的： `npm run autod`

**Comment by yekexuan** [comment]
@atian25  执行了`npm run autod` 之后启动失败。。
```
017-03-01 12:01:51,127 INFO 19446 [master] Agent Worker:19452 start with ["{\"framework\":\"/home/trey/wifi/ssp-service/node_modules/egg\",\"baseDir\":\"/home/trey/wifi/ssp-service\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"customEgg\":\"/home/trey/wifi/ssp-service/node_modules/egg\",\"clusterPort\":42011}"]
/home/trey/wifi/ssp-service/node_modules/.1.0.0@egg-watcher/agent.js:28
  agent.startAgent({
        ^

TypeError: agent.startAgent is not a function
    at module.exports (/home/trey/wifi/ssp-service/node_modules/.1.0.0@egg-watcher/agent.js:28:9)
    at AgentWorkerLoader.loadFile (/home/trey/wifi/ssp-service/node_modules/.2.1.2@egg-core/lib/loader/egg_loader.js:259:34)
    at getLoadUnits.forEach.unit (/home/trey/wifi/ssp-service/node_modules/.2.1.2@egg-core/lib/loader/mixin/custom.js:33:29)
    at Array.forEach (native)
    at AgentWorkerLoader.loadCustomAgent (/home/trey/wifi/ssp-service/node_modules/.2.1.2@egg-core/lib/loader/mixin/custom.js:33:8)
    at AgentWorkerLoader.load (/home/trey/wifi/ssp-service/node_modules/.1.0.0-rc.1@egg/lib/loader/agent_worker_loader.js:25:10)
    at new Agent (/home/trey/wifi/ssp-service/node_modules/.1.0.0-rc.1@egg/lib/agent.js:25:17)
    at Object.<anonymous> (/home/trey/wifi/ssp-service/node_modules/.1.6.0@egg-cluster/lib/agent_worker.js:15:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
2017-03-01 12:01:51,343 ERROR 19446 nodejs.AgentWorkerDiedError: [master] Agent Worker 19452 died (code: 1, signal: null)
    at Master.onAgentExit (/home/trey/wifi/ssp-service/node_modules/.1.6.0@egg-cluster/lib/master.js:235:17)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:189:7)
    at Messenger.sendToMaster (/home/trey/wifi/ssp-service/node_modules/.1.6.0@egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/home/trey/wifi/ssp-service/node_modules/.1.6.0@egg-cluster/lib/utils/messenger.js:87:12)
    at ChildProcess.agentWorker.once (/home/trey/wifi/ssp-service/node_modules/.1.6.0@egg-cluster/lib/master.js:151:22)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
name: 'AgentWorkerDiedError'
pid: 19446
hostname: ttttt

2017-03-01 12:01:51,343 ERROR 19446 [master] agent start fail, exit now
2017-03-01 12:01:51,343 INFO 19446 [master] exit with code: 1
[common-bin] run dev with ["--baseDir","/home/trey/wifi/ssp-service","--cluster","1","--eggPath=/home/trey/wifi/ssp-service/node_modules/egg"] at /home/trey/wifi/ssp-service error:
Error: /home/trey/wifi/ssp-service/node_modules/.2.2.3@egg-bin/lib/start-cluster --baseDir,/home/trey/wifi/ssp-service,--cluster,1,--eggPath=/home/trey/wifi/ssp-service/node_modules/egg exit with code 1
    at ChildProcess.<anonymous> (/home/trey/wifi/ssp-service/node_modules/.1.0.1@common-bin/lib/helper.js:31:21)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)


```

**Comment by popomore** [comment]
删除 node_modules 重新安装下

**Comment by yekexuan** [comment]
@popomore 搞定了。。 这个是什么原因啊？

**Comment by popomore** [comment]
模块已经在了不会重新安装

**Comment by yekexuan** [comment]
@popomore soga.... 最近刚开始用node tks..
