### ISSUE TITLE
codeclimate

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#483]
我尝试使用codeclimate审查我的基于egg的项目，提示如下
```
File `.autod.conf.js` ignored because of your .eslintignore file.
File `.eslintignore` ignored because of your .eslintignore file.
File `.eslintrc` ignored because of your .eslintignore file.
File `.gitignore` ignored because of your .eslintignore file.
File `.codeclimate.yml` ignored because of your .eslintignore file.
File `.github` ignored because of your .eslintignore file.
File `.github/ISSUE_TEMPLATE.md` ignored because of your .eslintignore file.
File `.github/PULL_REQUEST_TEMPLATE.md` ignored because of your .eslintignore file.
File `.travis.yml` ignored because of your .eslintignore file.
File `.csslintrc` ignored because of your .eslintignore file.
/usr/src/app/node_modules/eslint/lib/config/config-file.js:401
            throw e;
            ^

Error: Cannot find module 'eslint-config-egg'
Referenced from: /code/.eslintrc
    at ModuleResolver.resolve (/usr/src/app/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/src/app/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:495:26)
    at configExtends.reduceRight.e (/usr/src/app/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/src/app/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/usr/src/app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/src/app/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/src/app/node_modules/eslint/lib/config.js:259:26)
````
有什么好办法么？我试了egg项目本身也是这个提示。

**Comment by atian25** [comment]
试了下 egg:  https://codeclimate.com/github/eggjs/egg/builds/1

看了下感觉是 `codeclimate` 的识别有问题，没有分析出我们配置的 eslint 规则，

可能需要额外增加一个配置 `.codeclimate.yml`，然后配置下路径， 你可以试试

https://docs.codeclimate.com/docs/eslint

**Comment by duncup** [comment]
好的，我抽时间试一试，如果可以会反馈回来。

**Comment by atian25** [comment]
感谢，到时直接在这里反馈下，先 close 了。

**Comment by popomore** [comment]
egg 也可以加个

**Comment by atian25** [comment]
@duncup 试完后，可以给 egg，egg-boilerplate-simple 都提下 PR。

**Comment by duncup** [comment]
好的，搞定的话我会回来提交的。

**Comment by duncup** [comment]
@atian25 忘记反馈了，最终结果是没有搞定。codeclimate对使用的eslint插件有限制。当时发了邮件过去。

**Comment by atian25** [comment]
ok，暂时不急，后面有进展麻烦知会下， 3x

**Comment by duncup** [comment]
@atian25 
结果是收到邮件问题被关闭。

## 官网说法
> Supported Plugins
For security concerns related to executing code within a docker container, our ESLint engine currently ignores all but a select number of ESLint plugins. Please see the list below of plugins we currently support on all channels:

疑似只接受一定使用量以上的Plugins。
目测短时间内的解决方案只有一种，放上去的时候屏蔽掉ESLint检查。

**Comment by atian25** [comment]
[摊手]
