### ISSUE TITLE
[Feature Request] Egg-Scripts cannot run with TypeScript ES6+ standard

### ISSUE THREAD

**Issue by minhthinhls** [eggjs/egg#4843]
> egg-scripts cannot run with TypeScript, it does not compile TS with ES6 modules.
export * from './status';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Admin\WebstormProjects\V3s_VCash_Server\config\role.js:3:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by atian25** [comment]
it's not the duty of egg or egg-scripts, you need to compile your code at build-time with tsc.
In the meantime, if you write code with ts, why not compile it to CommonJS? 

and due to egg loader is sync mode now, so currently you can't use ESM to write controllers/services,  anyway, you could import thrid npm modules with `await import('some-package')`. we will support ESM at egg3.0 season 1 of this year.

**Comment by minhthinhls** [comment]
> it's not the duty of egg or egg-scripts, you need to compile your code at build-time with tsc. In the meantime, if you write code with ts, why not compile it to CommonJS?
> 
> and due to egg loader is sync mode now, so currently you can't use ESM to write controllers/services, anyway, you could import thrid npm modules with `await import('some-package')`. we will support ESM at egg3.0 season 1 of this year.

Thank you for your reply. I've already fixed the issues and figure it out how to integrate Typescript with Egg-Application. By doing compile TS to JS, letting the JS file lay nearby the TS files, the app can run correctly on Production mode. However, on Windows 10, I cannot run egg-scripts with --daemon flag. If daemon got omitted then it can execute correctly. What happened ?

**Comment by pxim** [comment]
> 

2022年了，能否发布一个3.0版本，现在写惯了ts，再写js没有类型，好难受

**Comment by pxim** [comment]
> 

2022年了，能否发布一个3.0版本，现在写惯了ts，再写js没有类型，好难受

**Comment by atian25** [comment]
在 2020 年的时候，你就已经可以用 TS 写 Egg 了，所以你的问题是？

**Comment by anming-john** [comment]
> https://zhuanlan.zhihu.com/p/35334932
> 
> 早在 2018 年的时候，你就已经可以用 TS 写 Egg 了，所以你的问题是？

我现在根据你们的typescript 模板，下载下来后， 根据readme 跑一遍
