### ISSUE TITLE
egg-mongo 连接不成功

### ISSUE THREAD

**Issue by linger1216** [eggjs/egg#485]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

```
    node 6.9.5
    "egg": "^1.0.0-rc.1",
    "egg-mongoose": "^1.0.0"
    local: mac server: ubuntu
```

使用插件egg-mongoose连接一个带auth的mongodb, 连接始终不成功, auth使用的是url方式, 不是option的方式, 试验option方式连接不成功, url如下:

```
mongodb://test:123456@xxx.xxx.xx.xxx:27017/hawkeye
```

错误信息如下:
```
2017-03-01 18:21:58,683 ERROR 51464 nodejs.MongoError: not authorized on hawkeye to execute command { serverStatus: 1 }
    at Function.MongoError.create (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/error.js:31:11)
    at /Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
name: 'MongoError'
message: 'not authorized on hawkeye to execute command { serverStatus: 1 }'
ok: 0
errmsg: 'not authorized on hawkeye to execute command { serverStatus: 1 }'
code: 13
codeName: 'Unauthorized'
```

提示没有权限, 但实际上user,pwd是对的. 已经单独用其他程序以及客户端连接测试过.
![image](https://cloud.githubusercontent.com/assets/1551488/23457851/96939d42-feb4-11e6-9220-fbbc21a84d00.png)

为了排除egg使用方法不对, 我本地建立了一个不带auth mongo db, 修改url连接成功.

返回如下:
```
2017-03-01 18:31:50,821 INFO 55396 [master] egg version 1.0.0-rc.1
2017-03-01 18:31:50,822 INFO 55396 [master] start with options: {"framework":"/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg/1.0.0-rc.1/egg","baseDir":"/Users/tuyou/Desktop/tuyou/vainglory/node_patch","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":"","customEgg":"/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg/1.0.0-rc.1/egg"}
2017-03-01 18:31:50,822 INFO 55396 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: undefined
2017-03-01 18:31:50,831 INFO 55396 [master] Agent Worker:55400 start with ["{\"framework\":\"/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg/1.0.0-rc.1/egg\",\"baseDir\":\"/Users/tuyou/Desktop/tuyou/vainglory/node_patch\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"customEgg\":\"/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg/1.0.0-rc.1/egg\",\"clusterPort\":52375}"]
(node:55400) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2017-03-01 18:31:52,310 INFO 55396 [master] Agent Worker started (1484ms)
2017-03-01 18:31:52,315 INFO 55396 [master] App Worker#1:55410 start, state: none, current workers: ["1"]
(node:55410) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2017-03-01 18:31:54,178 WARN 55396 [master] App Worker#1:55410 started at 7001, remain 0 (1868ms)
2017-03-01 18:31:54,179 INFO 55396 [master] egg started on http://127.0.0.1:7001 (3357ms)

```

请问, 何解?

**Comment by jtyjty99999** [comment]
http://mongoosejs.com/docs/connections.html  mongoose应该是支持auth和url连接，但我看了下egg-mongoose插件没实现 mongoose.createConnection(uri) 这种

**Comment by jtyjty99999** [comment]
@linger1216 我现在没有环境，你能否自己在本地 https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L12  这里，手动把uri传进去试试，看看是否能连接成功？

**Comment by linger1216** [comment]
我现在也没有环境, 一会到家, 如果在createConnection里面直接传url, 其实跟我的测试代码没什么区别, 肯定会成功, 但我观察了beforeStart里面还有一个db, 如果在之前创建了connection, open方法应该会失败, 应该要closeConnection.

还有根据mongoose的文档, 针对`Multiple connections` model 是需要define在connection上的, 而其他则可以define在mongoose, 在针对这两种情况, 是不是需要给用户暴露一些config,可以配置, 比如拿到多个db connection的obj 等等, 谢谢.

我马上测试一下.

**Comment by linger1216** [comment]
```
2017-03-01 21:41:44,361 ERROR 89904 nodejs.Error: [egg-mongoose]Trying to open unclosed connection.
    at NativeConnection.Connection.open (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongoose/4.8.5/mongoose/lib/connection.js:237:15)
    at /Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg-mongoose/1.0.0/egg-mongoose/lib/mongoose.js:38:14
    at next (native)
    at onFulfilled (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/co/4.6.0/co/index.js:65:19)
```

是可以连接成功的, 但后面有问题, 注释掉就ok

**Comment by jtyjty99999** [comment]
ok，明白了，这个问题我来修一下，谢谢 @linger1216

**Comment by linger1216** [comment]
yield db.db.command error.

**Comment by jtyjty99999** [comment]
@linger1216 错误日志具体发一下？

**Comment by linger1216** [comment]
我调试createconnectiton成功了

下面的db.db.command注释就OK

```
2017-03-02 19:58:15,230 ERROR 93560 nodejs.MongoError: not authorized on hawkeye to execute command { serverStatus: 1 }
    at Function.MongoError.create (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/error.js:31:11)
    at /Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/mongodb-core/2.1.8/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
name: 'MongoError'
message: 'not authorized on hawkeye to execute command { serverStatus: 1 }'
ok: 0
errmsg: 'not authorized on hawkeye to execute command { serverStatus: 1 }'
code: 13
codeName: 'Unauthorized'
pid: 93560
hostname: MacBook-Pro.local

2017-03-02 19:58:15,231 ERROR 93560 [agent_worker] Agent Worker start error, exiting now!
2017-03-02 19:58:15,252 ERROR 93556 nodejs.AgentWorkerDiedError: [master] Agent Worker 93560 died (code: 1, signal: null)
    at Master.onAgentExit (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg-cluster/1.6.0/egg-cluster/lib/master.js:235:17)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:188:7)
    at Messenger.sendToMaster (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg-cluster/1.6.0/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg-cluster/1.6.0/egg-cluster/lib/utils/messenger.js:87:12)
    at ChildProcess.agentWorker.once (/Users/tuyou/Desktop/tuyou/vainglory/node_patch/node_modules/.npminstall/egg-cluster/1.6.0/egg-cluster/lib/master.js:151:22)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
name: 'AgentWorkerDiedError'
pid: 93556
hostname: MacBook-Pro.local

2017-03-02 19:58:15,252 ERROR 93556 [master] agent start fail, exit now
2017-03-02 19:58:15,252 INFO 93556 [master] exit with code: 1
```

**Comment by jtyjty99999** [comment]
看来得换一个心跳检查方法。。

**Comment by linger1216** [comment]
你们慢慢修吧, 我找点别的玩玩...

**Comment by zhangming0305** [comment]
这个我也折腾了半天，和mongodb的数据库建立db的权限很有关系。admin db的权限和其他db的权限设置得小心。提供一个我配置的：
```
use testdb
 db.createUser({user:"user", pwd:"xxx",roles: [ "readWrite", "dbAdmin", { role: "readAnyDatabase", db: "admin" },{ role: "clusterMonitor", db:"admin" } ]})
```

这样
```
not authorized on hawkeye to execute command { serverStatus: 1 }
```
就不会有

**Comment by jtyjty99999** [comment]
@zhangming0305 谢谢提供，主要是我们代码里判断心跳的这个接口权限太高导致的，我正在找一个比较普遍的做法

**Comment by zhangming0305** [comment]
👍

**Comment by dead-horse** [comment]
试试最新的 egg-mongoose（1.1.1）
