### ISSUE TITLE
关于异常报告文件的处理

### ISSUE THREAD

**Issue by robert091** [eggjs/egg#4852]
内存溢出生成了`report.xxxxx.xxx.json`的报告文件，这类文件如何指定生成的目录？不想让其生成在根目录下

我尝试着在 `egg-scripts start` 添加node的一些选项，但只有第一次生成report文件的时候是在 `/tmp`目录，之后还是在根目录下生成
```
--node-options--experimental-report --node-options--report-on-fatalerror --node-options--report-directory=/tmp
```

请问有什么比较好的处理方式吗？

```

<--- Last few GCs --->

[74:0x3c6b0b0]    84120 ms: Mark-sweep 256.4 (257.7) -> 256.3 (258.0) MB, 3710.1 / 0.0 ms  (average mu = 0.083, current mu = 0.002) allocation failure scavenge might not succeed
[74:0x3c6b0b0]    87608 ms: Mark-sweep 256.7 (258.0) -> 256.6 (258.0) MB, 3483.3 / 0.0 ms  (average mu = 0.044, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1e5a8c5c08d1 <JSObject>
    0: builtin exit frame: toString(this=0x1385708b7419 <HeapNumber 0.254672>,36,0x1385708b7419 <HeapNumber 0.254672>)

    1: _onTimeout [0x49392160e89] [/home/node/app/app/controller/memory.js:~42] [pc=0xc211e9f4d33](this=0x049392160ec1 <Timeout map = 0x38bcdf13e699>)
    2: listOnTimeout(aka listOnTimeout) [0xef3f9a0f279] [internal/timers.js:549] [bytecode=0x6b2a4396c91 offset=373](this=0x387...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20220104.090038.74.0.001.json
Node.js report completed
 1: 0xa09830 node::Abort() [/usr/local/bin/node]
 2: 0xa09c55 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb7d71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb7da99 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xd2a1f5  [/usr/local/bin/node]
 6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0xd37105 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0xd37fb5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0xd3aa6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0xd0891c v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
11: 0xd089e1 v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const> const&, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0xc3189a v8::internal::Builtin_NumberPrototypeToString(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x13c5c79  [/usr/local/bin/node]
[2022-01-04 09:00:38.485] [cfork:master:55] worker:74 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
2022-01-04 09:00:38,497 INFO 55 [master] app_worker#2:74 disconnect, suicide: false, state: disconnected, current workers: ["1","2","3","4","5"]
[2022-01-04 09:00:38.496] [cfork:master:55] new worker:117 fork (state: none)
2022-01-04 09:00:38,498 INFO 55 [master] app_worker#5:117 start, state: none, current workers: ["1","2","3","4","5"]
[2022-01-04 09:00:38.499] [cfork:master:55] worker:74 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2022-01-04 09:00:38,503 ERROR 55 nodejs.AppWorkerDiedError: [master] app_worker#2:74 died (code: null, signal: SIGABRT, suicide: false, state: dead), current workers: ["1","3","4","5"]
    at Master.onAppExit (/home/node/app/node_modules/egg-cluster/lib/master.js:511:21)
    at Master.emit (events.js:310:20)
    at Messenger.sendToMaster (/home/node/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/home/node/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/home/node/app/node_modules/egg-cluster/lib/master.js:354:22)
    at EventEmitter.emit (events.js:322:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AppWorkerDiedError"
pid: 55
hostname: test_server-core

2022-01-04 09:00:40,004 INFO 117 Plugin development is disabled by env unmatched, require env([ 'local' ]) but got env is prod
2022-01-04 09:00:40,097 INFO 117 [egg:core] App root: /home/node/app
2022-01-04 09:00:40,098 INFO 117 [egg:core] All *.log files save on "/root/logs/example"
2022-01-04 09:00:40,098 INFO 117 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-session","version":"3.3.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-security","version":"2.9.0"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-onerror","version":"2.1.0"},{"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-i18n","version":"2.1.1"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-watcher","version":"3.1.1"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-schedule","version":"3.6.6"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":["schedule"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-multipart","version":"2.13.1"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-logrotator","version":"3.1.0"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-static","version":"2.2.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-view","version":"2.1.3"}]
2022-01-04 09:00:40,531 INFO 117 [egg:logger] init all loggers with options: {"dir":"/root/logs/example","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"example-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"enablePerformanceTimer":false,"type":"application"}
2022-01-04 09:00:40,638 INFO 117 [egg-multipart] stream mode enable
2022-01-04 09:00:40,902 INFO 117 Use coreMiddleware order: ["meta","siteFile","notfound","static","bodyParser","overrideMethod","session","securities","i18n"]
2022-01-04 09:00:40,902 INFO 117 Use appMiddleware order: []
2022-01-04 09:00:40,913 INFO 117 [egg:loader] Use middleware: meta
2022-01-04 09:00:40,914 INFO 117 [egg:loader] Use middleware: siteFile
2022-01-04 09:00:40,915 INFO 117 [egg:loader] Use middleware: notfound
2022-01-04 09:00:40,916 INFO 117 [egg-static] starting static serve /public/ -> /home/node/app/app/public
2022-01-04 09:00:40,919 INFO 117 [egg:loader] Use middleware: static
2022-01-04 09:00:40,920 INFO 117 [egg:loader] Use middleware: bodyParser
2022-01-04 09:00:40,920 INFO 117 [egg:loader] Use middleware: overrideMethod
2022-01-04 09:00:40,921 INFO 117 [egg:loader] Use middleware: session
2022-01-04 09:00:40,925 INFO 117 [egg-security] use methodnoallow middleware
2022-01-04 09:00:40,926 INFO 117 [egg-security] use noopen middleware
2022-01-04 09:00:40,927 INFO 117 [egg-security] use nosniff middleware
2022-01-04 09:00:40,927 INFO 117 [egg-security] use xssProtection middleware
2022-01-04 09:00:40,928 INFO 117 [egg-security] use xframe middleware
2022-01-04 09:00:40,981 INFO 117 [egg-security] use dta middleware
2022-01-04 09:00:40,981 INFO 117 [egg-security] compose 6 middlewares into one security middleware
2022-01-04 09:00:40,982 INFO 117 [egg:loader] Use middleware: securities
2022-01-04 09:00:40,982 INFO 117 [egg:loader] Use middleware: i18n
2022-01-04 09:00:40,982 INFO 117 [egg:loader] Loaded middleware from ["/home/node/app/node_modules/egg-session/app/middleware","/home/node/app/node_modules/egg-security/app/middleware","/home/node/app/node_modules/egg-jsonp/app/middleware","/home/node/app/node_modules/egg-onerror/app/middleware","/home/node/app/node_modules/egg-i18n/app/middleware","/home/node/app/node_modules/egg-watcher/app/middleware","/home/node/app/node_modules/egg-schedule/app/middleware","/home/node/app/node_modules/egg-multipart/app/middleware","/home/node/app/node_modules/egg-logrotator/app/middleware","/home/node/app/node_modules/egg-static/app/middleware","/home/node/app/node_modules/egg-view/app/middleware","/home/node/app/node_modules/egg/app/middleware","/home/node/app/app/middleware"]
2022-01-04 09:00:40,988 INFO 117 [egg:loader] Controller loaded: /home/node/app/app/controller
2022-01-04 09:00:41,005 INFO 117 [egg:core] dump config after load, 10ms
2022-01-04 09:00:41,012 INFO 117 [egg:core:ready_stat] end ready task /home/node/app/node_modules/egg-core/lib/egg.js:303:10, remain ["/home/node/app/node_modules/egg-watcher/lib/init.js:15:14"]
2022-01-04 09:00:41,017 INFO 117 [egg-watcher:application] watcher start success
2022-01-04 09:00:41,017 INFO 117 [egg:core:ready_stat] end ready task /home/node/app/node_modules/egg-watcher/lib/init.js:15:14, remain []
2022-01-04 09:00:41,096 INFO 55 [master] app_worker#5:117 started at 7001, remain 0 (94584ms)
indexindexindexindexindexindex
(node:80) ExperimentalWarning: report is an experimental feature. This feature could change at any time

<--- Last few GCs --->

[80:0x38270b0]   323640 ms: Mark-sweep 256.4 (257.7) -> 256.2 (258.0) MB, 3416.6 / 0.0 ms  (average mu = 0.083, current mu = 0.002) allocation failure scavenge might not succeed
[80:0x38270b0]   327121 ms: Mark-sweep 256.8 (258.0) -> 256.7 (258.0) MB, 3472.7 / 0.0 ms  (average mu = 0.044, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13c5b79]
Security context: 0x3def00c408d1 <JSObject>
    1: random [0x3def00c43ca9](this=0x3def00c43209 <Object map = 0x5c596880899>)
    2: /* anonymous */ [0x4b0546ccd1] [/home/node/app/app/controller/memory.js:~42] [pc=0x23e261d53fd5](this=0x044f21788899 <Timeout map = 0x12a97777e5f9>)
    3: listOnTimeout(aka listOnTimeout) [0x5728c2b8651] [internal/timers.js:549] [bytecode=0x82d958faec9 offset=373](this=0x3467...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20220104.090437.80.0.001.json
Node.js report completed
 1: 0xa09830 node::Abort() [/usr/local/bin/node]
 2: 0xa09c55 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb7d71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb7da99 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xd2a1f5  [/usr/local/bin/node]
 6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0xd37105 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0xd37fb5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0xd3aa6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0xd0163b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
11: 0x104300e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x13c5b79  [/usr/local/bin/node]
[2022-01-04 09:04:37.896] [cfork:master:55] worker:80 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
[2022-01-04 09:04:37.902] [cfork:master:55] new worker:128 fork (state: none)
[2022-01-04 09:04:37.904] [cfork:master:55] worker:80 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
2022-01-04 09:04:37,905 ERROR 55 nodejs.AppWorkerDiedError: [master] app_worker#3:80 died (code: null, signal: SIGABRT, suicide: false, state: dead), current workers: ["1","4","5","6"]
    at Master.onAppExit (/home/node/app/node_modules/egg-cluster/lib/master.js:511:21)
    at Master.emit (events.js:310:20)
    at Messenger.sendToMaster (/home/node/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/home/node/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/home/node/app/node_modules/egg-cluster/lib/master.js:354:22)
    at EventEmitter.emit (events.js:322:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AppWorkerDiedError"
pid: 55
hostname: test_server-core

2022-01-04 09:04:37,903 INFO 55 [master] app_worker#3:80 disconnect, suicide: false, state: disconnected, current workers: ["1","3","4","5","6"]
2022-01-04 09:04:37,903 INFO 55 [master] app_worker#6:128 start, state: none, current workers: ["1","3","4","5","6"]
2022-01-04 09:04:39,489 INFO 128 Plugin development is disabled by env unmatched, require env([ 'local' ]) but got env is prod
2022-01-04 09:04:39,596 INFO 128 [egg:core] App root: /home/node/app
2022-01-04 09:04:39,596 INFO 128 [egg:core] All *.log files save on "/root/logs/example"
2022-01-04 09:04:39,597 INFO 128 [egg:core] Loaded enabled plugin [{"enable":true,"package":"egg-session","name":"session","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-session","version":"3.3.0"},{"enable":true,"package":"egg-security","name":"security","dependencies":[],"optionalDependencies":["session"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-security","version":"2.9.0"},{"enable":true,"package":"egg-jsonp","name":"jsonp","dependencies":[],"optionalDependencies":["security"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-jsonp","version":"2.0.0"},{"enable":true,"package":"egg-onerror","name":"onerror","dependencies":[],"optionalDependencies":["jsonp"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-onerror","version":"2.1.0"},{"enable":true,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-i18n","version":"2.1.1"},{"enable":true,"package":"egg-watcher","name":"watcher","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-watcher","version":"3.1.1"},{"enable":true,"package":"egg-schedule","name":"schedule","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-schedule","version":"3.6.6"},{"enable":true,"package":"egg-multipart","name":"multipart","dependencies":[],"optionalDependencies":["schedule"],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-multipart","version":"2.13.1"},{"enable":true,"package":"egg-logrotator","name":"logrotator","dependencies":["schedule"],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-logrotator","version":"3.1.0"},{"enable":true,"package":"egg-static","name":"static","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-static","version":"2.2.0"},{"enable":true,"package":"egg-view","name":"view","dependencies":[],"optionalDependencies":[],"env":[],"from":"/home/node/app/node_modules/egg/config/plugin.js","path":"/home/node/app/node_modules/egg-view","version":"2.1.3"}]
2022-01-04 09:04:39,997 INFO 128 [egg:logger] init all loggers with options: {"dir":"/root/logs/example","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"example-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"enablePerformanceTimer":false,"type":"application"}
2022-01-04 09:04:40,108 INFO 128 [egg-multipart] stream mode enable
2022-01-04 09:04:40,297 INFO 128 Use coreMiddleware order: ["meta","siteFile","notfound","static","bodyParser","overrideMethod","session","securities","i18n"]
2022-01-04 09:04:40,297 INFO 128 Use appMiddleware order: []
2022-01-04 09:04:40,385 INFO 128 [egg:loader] Use middleware: meta
2022-01-04 09:04:40,385 INFO 128 [egg:loader] Use middleware: siteFile
2022-01-04 09:04:40,386 INFO 128 [egg:loader] Use middleware: notfound
2022-01-04 09:04:40,392 INFO 128 [egg-static] starting static serve /public/ -> /home/node/app/app/public
2022-01-04 09:04:40,395 INFO 128 [egg:loader] Use middleware: static
2022-01-04 09:04:40,396 INFO 128 [egg:loader] Use middleware: bodyParser
2022-01-04 09:04:40,397 INFO 128 [egg:loader] Use middleware: overrideMethod
2022-01-04 09:04:40,398 INFO 128 [egg:loader] Use middleware: session
2022-01-04 09:04:40,403 INFO 128 [egg-security] use methodnoallow middleware
2022-01-04 09:04:40,404 INFO 128 [egg-security] use noopen middleware
2022-01-04 09:04:40,405 INFO 128 [egg-security] use nosniff middleware
2022-01-04 09:04:40,405 INFO 128 [egg-security] use xssProtection middleware
2022-01-04 09:04:40,407 INFO 128 [egg-security] use xframe middleware
2022-01-04 09:04:40,409 INFO 128 [egg-security] use dta middleware
2022-01-04 09:04:40,409 INFO 128 [egg-security] compose 6 middlewares into one security middleware
2022-01-04 09:04:40,409 INFO 128 [egg:loader] Use middleware: securities
2022-01-04 09:04:40,409 INFO 128 [egg:loader] Use middleware: i18n
2022-01-04 09:04:40,409 INFO 128 [egg:loader] Loaded middleware from ["/home/node/app/node_modules/egg-session/app/middleware","/home/node/app/node_modules/egg-security/app/middleware","/home/node/app/node_modules/egg-jsonp/app/middleware","/home/node/app/node_modules/egg-onerror/app/middleware","/home/node/app/node_modules/egg-i18n/app/middleware","/home/node/app/node_modules/egg-watcher/app/middleware","/home/node/app/node_modules/egg-schedule/app/middleware","/home/node/app/node_modules/egg-multipart/app/middleware","/home/node/app/node_modules/egg-logrotator/app/middleware","/home/node/app/node_modules/egg-static/app/middleware","/home/node/app/node_modules/egg-view/app/middleware","/home/node/app/node_modules/egg/app/middleware","/home/node/app/app/middleware"]
2022-01-04 09:04:40,414 INFO 128 [egg:loader] Controller loaded: /home/node/app/app/controller
2022-01-04 09:04:40,490 INFO 128 [egg:core] dump config after load, 6ms
2022-01-04 09:04:40,504 INFO 128 [egg:core:ready_stat] end ready task /home/node/app/node_modules/egg-core/lib/egg.js:303:10, remain ["/home/node/app/node_modules/egg-watcher/lib/init.js:15:14"]
2022-01-04 09:04:40,515 INFO 128 [egg-watcher:application] watcher start success
2022-01-04 09:04:40,515 INFO 128 [egg:core:ready_stat] end ready task /home/node/app/node_modules/egg-watcher/lib/init.js:15:14, remain []
2022-01-04 09:04:40,619 INFO 55 [master] app_worker#6:128 started at 7001, remain 0 (334107ms)
```
运行在 `docker` 下，镜像`node:12.16.3`

**Comment by atian25** [comment]
这个不是 egg 生成的，是系统或 Node 本身的行为，如何更改目录可以看下对应的文档。

内存泄露的话，用 alinode 或 easy-monitor 分析下吧
