### ISSUE TITLE
我在打包egg时遇到个问题

### ISSUE THREAD

**Issue by xkkkA** [eggjs/egg#4878]
Run node --no-deprecation C:\snapshot\src\node_modules\egg-scripts\lib\start-cluster {"port":7007,"title":"pkg-egg","baseDir":"C:\\Users\\Administrator\\Desktop\\pkg-egg-example-master\\src","framework":"C:\\Users\\Administrator\\Desktop\\pkg-egg-example-master\\src\\node_modules\\egg"} --title=pkg-egg
internal/modules/cjs/loader.js:977
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\pkg-egg-example-master\src\--no-deprecation'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:974:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:857:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by atian25** [comment]
应该是你 pkg 的用法问题。

**Comment by superlbr** [comment]
egg-scripts版本用2.13.0，或者注释掉lib/cmd/start.js下的`execArgvObj.deprecation = false`
