### ISSUE TITLE
生产环境AppWorkerDiedError

### ISSUE THREAD

**Issue by Qxiaobei** [eggjs/egg#4898]
## AppWorkerDiedError

在docker生产环境，执行某一个段代码去执行某个任务，具体就是处理某个图片，然后当图片较小的时候没问题，图片较大时间较长处理的时候就直接报错然后重启了，看了下root下日志没有任何出错的日志，而且奇怪的是在开发环境没有任何问题，请帮助。

具体日志如下：

2022-02-28T18:45:43.430362793Z APP 2022-02-28 10:45:43,430 ERROR 36 nodejs.AppWorkerDiedError: [master] app_worker#17:257 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: ["2","3","6","9","10","11","12","15","16","18","20","21","22","23","24","25"]
2022-02-28T18:45:43.430383593Z APP     at Messenger.sendToMaster (/opt/deployments/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
2022-02-28T18:45:43.430386093Z APP     at Messenger.send (/opt/deployments/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
2022-02-28T18:45:43.430393494Z APP     at ChildProcess.<anonymous> (internal/cluster/master.js:191:13)
2022-02-28T18:45:43.430395894Z APP     at Object.onceWrapper (events.js:422:26)
2022-02-28T18:45:43.430398094Z APP     at ChildProcess.emit (events.js:315:20)
2022-02-28T18:45:43.430400294Z APP     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2022-02-28T18:45:43.430402694Z APP name: "AppWorkerDiedError"
2022-02-28T18:45:43.430405094Z APP pid: 36
2022-02-28T18:45:43.430407294Z APP hostname: staticmanageweb-55cbff756b-69vcc
2022-02-28T18:45:43.430409694Z APP 
2022-02-28T18:45:43.812032448Z RTR  {"type":"RTR","log_format":"http","nodename":"htqhb01inf","timestamp":"202

后面的日志就是重启内容。root下的日志没有什么异常内容

**Comment by hyj1991** [comment]
打开 `ulimit -c unlimited` 的配置，估计是 OOM 了

**Comment by Qxiaobei** [comment]
> 

我也在怀疑是内存问题，提高下内存看看

**Comment by Qxiaobei** [comment]
> 打开 `ulimit -c unlimited` 的配置，估计是 OOM 了

我也在怀疑是内存问题，没任何报错日志，我提高下内存看看

**Comment by atian25** [comment]
SKILL 是主动被杀了，要么 OOM 要么进程卡太久被容器干掉了？

重 CPU 的操作不要在 Web 服务器做，要用 fc 函数计算。

**Comment by hyj1991** [comment]
> 我也在怀疑是内存问题，没任何报错日志，我提高下内存看看

在目标容器用 `dmesg` 看下系统操作日志，docker 内确实可能存在进程使用资源超过 `cgroup` 限制被内核干掉的场景

**Comment by Qxiaobei** [comment]
> > 我也在怀疑是内存问题，没任何报错日志，我提高下内存看看
> 
> 在目标容器用 `dmesg` 看下系统操作日志，docker 内确实可能存在进程使用资源超过 `cgroup` 限制被内核干掉的场景

确实是这个问题，之前有个内存限制比较少，memory瞬间超过限制了被Kill了，扩容之后没发现这个问题，我暂时关闭了
