### ISSUE TITLE
k8s pod里报middleware/body_parser.js split of undefined

### ISSUE THREAD

**Issue by dryqiao** [eggjs/egg#4925]
## What happens?

本地可以正常启动，阿里云线上也正常，
但是推到另一个k8s上容器就报错，一直重启，也无法进入容器查看日志

## 复现步骤，错误日志以及相关配置
- 在pod里执行`npx egg-scripts start --port=4015 --workers=2`
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/17639218/162877382-852f8d38-9126-4415-8e21-2ef3cc57b49b.png">

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：8.6.0
- **Egg 版本**：2.30.0

**Comment by xiongchen2012** [comment]
遇到相同的问题了：
2022-06-08 14:57:19,071 ERROR 47 nodejs.TypeError: [egg-core] load file: /usr/src/app/node_modules/egg/app/middleware/body_parser.js, error: Cannot read property 'split' of undefined
    at toIdentifier (/usr/src/app/node_modules/toidentifier/index.js:24:6)
    at forEachCode (/usr/src/app/node_modules/raw-body/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/src/app/node_modules/raw-body/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/src/app/node_modules/raw-body/node_modules/http-errors/index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by atian25** [comment]
提供可复现的最小仓库

**Comment by xugx29** [comment]
所以这个是什么原因导致的.. 我也遇到这个问题了..

**Comment by xugx29** [comment]
@atian25 @dryqiao 所以这个是什么原因导致的.. 我也遇到这个问题了..

**Comment by atian25** [comment]
不提供最小可复现仓库怎么查？
