### ISSUE TITLE
egg服务出现 EIO 报错，导致服务停止运行

### ISSUE THREAD

**Issue by Rock-Legend** [eggjs/egg#4967]
`
ERROR 29171 nodejs.unhandledExceptionError: write EIO
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at WriteStream.Socket._writeGeneric (net.js:785:11)
    at WriteStream.Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at WriteStream.Writable.write (internal/streams/writable.js:303:10)
    at ConsoleTransport.log (/opt/app/bas-app-node-server/node_modules/egg-logger/lib/transports/console.js:46:22)
    at Map.log (/opt/app/bas-app-node-server/node_modules/egg-logger/lib/logger.js:79:19)
    at Map.Logger.<computed> [as info] (/opt/app/bas-app-node-server/node_modules/egg-logger/lib/logger.js:169:10)
    at process.<anonymous> (/opt/app/bas-app-node-server/node_modules/graceful-process/index.js:39:35)
    at Object.onceWrapper (events.js:422:26)
    at process.emit (events.js:315:20)
errno: -5
code: "EIO"
syscall: "write"
name: "unhandledExceptionError"
pid: 29171
`
egg运行了一段时间后，突然服务停止运行，查找opt/logs下的日志，在 common-error.log 中输出了以上内容，其他日志中没有找到异常日志的输出；

**Comment by Rock-Legend** [comment]
@fengmk2  这个通常是什么情况下才报的呢，因为没有查到其他日志文件同时间的内容，没有定位出来。

**Comment by fengmk2** [comment]
磁盘异常了，可能需要做一下容错处理。

**Comment by Rock-Legend** [comment]
@fengmk2 好的，谢谢提醒

**Comment by shilucus** [comment]
> @fengmk2 好的，谢谢提醒

请问你这边有定位到具体原因吗？
