### ISSUE TITLE
egg body 解析bug

### ISSUE THREAD

**Issue by 1119302165** [eggjs/egg#4981]
问题机器egg环境：
```javascript
"egg": {
    "declarations": true
  },
  "dependencies": {
    "autocannon": "^7.9.0",
    "egg": "^2",
    "egg-redis": "^2.4.0",
    "egg-scripts": "^2",
    "tsc": "^2.0.4",
    "undici": "^5.7.0"
  },
  "devDependencies": {
    "autod": "^3",
    "autod-egg": "^1",
    "egg-bin": "^4",
    "egg-ci": "^2",
    "egg-mock": "^4",
    "eslint": "^8",
    "eslint-config-egg": "^12"
  },
  "engines": {
    "node": ">=16.0.0"
  },

```
问题复现：
post body 的字符串内容为json ` {"path":"\n"}`
传输过去的内容为` "{\"path\":\"\n\"}"`
在解析这个内容出现json解析错误，在springboot环境可解析正常，问题应该出现在egg http body 解析这块逻辑，报错如下。

```java
`2022-07-19 16:20:19,344 WARN 39558 [-/127.0.0.1/-/0ms POST /new] nodejs.SyntaxError: Unexpected token 
 in JSON at position 9, check bodyParser config
 in JSON at position 9, check bodyParser config
    at JSON.parse (<anonymous>)
    at parse (src/nodejs/release/node_modules/_co-body@6.1.0@co-body/lib/json.js:57:17)
    at AsyncFunction.module.exports [as json] (src/nodejs/release/node_modules/_co-body@6.1.0@co-body/lib/json.js:41:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async parseBody (src/nodejs/release/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:100:14)
    at async bodyParser (src/nodejs/release/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:85:19)
    at async src/nodejs/release/node_modules/_koa-static-cache@5.1.4@koa-static-cache/index.js:39:63
    at async notfound (src/nodejs/release/node_modules/_egg@2.36.0@egg/app/middleware/notfound.js:5:5)
    at async meta (src/nodejs/release/node_modules/_egg@2.36.0@egg/app/middleware/meta.js:18:5)
status: 400
body: "{\"path\":\"\n\"}"
pid: 39558`

```

**Comment by atian25** [comment]
header 不对吧。堆栈信息都有了，自己 debug 看看啥原因呗。

从报错只看得出是解析失败，除非你给出可复现的仓库，不然我们也没法查

**Comment by phypor** [comment]
代码比较简单，egg起了7001的，路由增加了new路径。

client.js 完整代码如下：
-----------------------------------------------------------
const undici = require('undici');
const httpClientPool = new undici.Pool('http://127.0.0.1:7001', {
    connections: 50
});

function post(path, params) {
    return httpClientPool.request({
        path,
        headers: { "content-type": "application/json" },
        method: 'POST',
        body: params
    });
}

async function test() {
    let path = "\n";
    await post("/new", `{"path":"${path}"}`)
}

test();

-----------------------------------------------------------

server controller 代码如下：
-----------------------------------------------------------
"use strict";

const Controller = require("egg").Controller;

class HomeController extends Controller {

  async new() {
    const { ctx } = this;
    const {
      request: { body },
    } = this.ctx;
    var path = body.path;
    ctx.body = {
      result: true,
    };
  }
}

module.exports = HomeController;

**Comment by phypor** [comment]
看起来是koa-bodyparser 和fastjson解析逻辑不一样的问题。。。
