### ISSUE TITLE
chunjun启动报错：Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by Flamelay** [eggjs/egg#4982]
（chunjun新手，按照教程自己磨了好几天，目前启动报错如下）

```
2022-07-20 15:41:10.546 [main] INFO  com.dtstack.chunjun.Main  - ------------program params-------------------------
2022-07-20 15:41:10.685 [main] INFO  com.dtstack.chunjun.Main  - -p
2022-07-20 15:41:10.688 [main] INFO  com.dtstack.chunjun.Main  - luginRoot
2022-07-20 15:41:10.689 [main] INFO  com.dtstack.chunjun.Main  - -job
2022-07-20 15:41:10.690 [main] INFO  com.dtstack.chunjun.Main  - %7B%0D%0A++%22job%22%3A+%7B%0D%0A++++%22content%22%3A+%5B%0D%0A++++++%7B%0D%0A++++++++%22reader%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22mysqlreader%22%2C%0D%0A++++++++++%22parameter%22%3A+%7B%0D%0A++++++++++++%22column%22%3A+%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22id%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22int%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22name%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22string%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22phone%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22string%22%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%2C%0D%0A++++++++++++%22customSql%22%3A+%22%22%2C%0D%0A++++++++++++%22where%22%3A+%22id+%3C+1000%22%2C%0D%0A++++++++++++%22splitPk%22%3A+%22id%22%2C%0D%0A++++++++++++%22increColumn%22%3A+%22id%22%2C%0D%0A++++++++++++%22startLocation%22%3A+%222%22%2C%0D%0A++++++++++++%22polling%22%3A+true%2C%0D%0A++++++++++++%22pollingInterval%22%3A+3000%2C%0D%0A++++++++++++%22queryTimeOut%22%3A+1000%2C%0D%0A++++++++++++%22username%22%3A+%22root%22%2C%0D%0A++++++++++++%22password%22%3A+%22root%22%2C%0D%0A++++++++++++%22connection%22%3A+%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22jdbcUrl%22%3A+%5B%0D%0A++++++++++++++++++%22jdbc%3Amysql%3A%2F%2F192.168.0.77%3A3306%2Fsource%3FuseSSL%3Dfalse%22%0D%0A++++++++++++++++%5D%2C%0D%0A++++++++++++++++%22table%22%3A+%5B%0D%0A++++++++++++++++++%22td_user%22%0D%0A++++++++++++++++%5D%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%0D%0A++++++++++%7D%0D%0A++++++++%7D%2C%0D%0A++++++++%22writer%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22mysqlwriter%22%2C%0D%0A++++++++++%22parameter%22%3A+%7B%0D%0A++++++++++++%22username%22%3A+%22root%22%2C%0D%0A++++++++++++%22password%22%3A+%22root%22%2C%0D%0A++++++++++++%22connection%22%3A+%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22jdbcUrl%22%3A+%22jdbc%3Amysql%3A%2F%2F192.168.0.77%3A3306%2Ftarget%3FuseSSL%3Dfalse%22%2C%0D%0A++++++++++++++++%22table%22%3A+%5B%0D%0A++++++++++++++++++%22tb_user%22%0D%0A++++++++++++++++%5D%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%2C%0D%0A++++++++++++%22writeMode%22%3A+%22insert%22%2C%0D%0A++++++++++++%22flushIntervalMills%22%3A%223000%22%2C%0D%0A++++++++++++%22column%22%3A+%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22id%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22int%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22name%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22string%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22phone%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22string%22%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%0D%0A++++++++++%7D%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%5D%2C%0D%0A++++%22setting%22%3A+%7B%0D%0A++++++%22restore%22%3A+%7B%0D%0A++++++++%22restoreColumnName%22%3A+%22id%22%0D%0A++++++%7D%2C%0D%0A++++++%22speed%22%3A+%7B%0D%0A++++++++%22channel%22%3A+1%2C%0D%0A++++++++%22bytes%22%3A+0%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D%0D%0A
2022-07-20 15:41:10.691 [main] INFO  com.dtstack.chunjun.Main  - -jobName
2022-07-20 15:41:10.693 [main] INFO  com.dtstack.chunjun.Main  - Flink_Job
2022-07-20 15:41:10.693 [main] INFO  com.dtstack.chunjun.Main  - -chunjunDistDir
2022-07-20 15:41:10.697 [main] INFO  com.dtstack.chunjun.Main  - G:\Software\chunjun-master\chunjun-dist
2022-07-20 15:41:10.697 [main] INFO  com.dtstack.chunjun.Main  - -confProp
2022-07-20 15:41:10.703 [main] INFO  com.dtstack.chunjun.Main  - {}
2022-07-20 15:41:10.705 [main] INFO  com.dtstack.chunjun.Main  - -pluginLoadMode
2022-07-20 15:41:10.706 [main] INFO  com.dtstack.chunjun.Main  - shipfile
2022-07-20 15:41:10.706 [main] INFO  com.dtstack.chunjun.Main  - -mode
2022-07-20 15:41:10.707 [main] INFO  com.dtstack.chunjun.Main  - local
2022-07-20 15:41:10.708 [main] INFO  com.dtstack.chunjun.Main  - -------------------------------------------
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.dtstack.chunjun.util.JobUtil.CommandTransform(JobUtil.java:60)
	at com.dtstack.chunjun.util.JobUtil.replaceJobParameter(JobUtil.java:37)
	at com.dtstack.chunjun.Main.main(Main.java:109)
	at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)

Process finished with exit code 1
```
编译部署步骤：

1、下载并解压chunjun项目压缩包

 2、执行官方依赖包安装脚本
      双击执行 chunjun-master/bin 目录下的install_jars.bat文件

3、使用Maven命令编译
      在 chunjun-master 目录下使用命令行输入：
     ` mvn clean install -DskipTests -Drat.skip=true`
      运行报错（文件存在格式冲突）
      根据提示执行 “`mvn spotless:apply`”
      编译成功

4、配置环境变量
      
5、IDEA相关配置
     idea运行参数
     `-job C:/Users/Administrator/Desktop/mysql_mysql_polling.json -pluginRoot G:/Software/chunjun-master/chunjun-connectors`
     运行报错：JAR包冲突   +    CHUNJUN_HOME is not configured      +        Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

    5.1  JAR包冲突：
      'SLF4J: Class path contains multiple SLF4J bindings.
      SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
      SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
      SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
      SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]'
      删除其中一个即可

   5.2   CHUNJUN_HOME is not configured ：
      在environment variables里边指定了一下CHUNJUN_HOME，就不报错了，再次取消指定环境变量，也不报错了……

  5.3  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1：
      目前卡在这了，求解！

**Comment by atian25** [comment]
你这是 Java，跟 Egg 有啥关系。。。

**Comment by Flamelay** [comment]
对8起，第一次提issue我人傻了，丢人丢到这了，属实是不好意思
