### ISSUE TITLE
mysql8.04以上连接失败

### ISSUE THREAD

**Issue by z2360326111** [eggjs/egg#5009]
##  Client does not support authentication protocol requested by server; consider upgrading MySQL client
我也是看过了已有的issue，上述的解决方案和网上的一样，都是修改mysql的配置，不过这条对我不适用；再加上那一条距离现在有些时间了，我不知道现在的版本是否支持连接8.04以上的mysql版本，我看了egg-mysql的这个库，用的是‘ali-rds’，而不是上一个issue里面说的mysql1，所以蜗居比较迷惑了，特来询问下，希望大佬们帮我解惑

## 错误日志以及相关配置

2022-09-02 15:03:55,787 ERROR 10960 [-/127.0.0.1/-/0ms GET /] nodejs.ER_NOT_SUPPORTED_AUTH_MODEError: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:116:18)
    at Pool.getConnection (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:48:16)
    at D:\project\GY\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\project\GY\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\project\GY\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at Pool.query (D:\project\GY\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:202:8)
    at D:\project\GY\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    sql: select now() as currentTime;
code: "ER_NOT_SUPPORTED_AUTH_MODE"
errno: 1251
sqlMessage: "Client does not support authentication protocol requested by server; consider upgrading MySQL client"
sqlState: "08004"
fatal: true
name: "ER_NOT_SUPPORTED_AUTH_MODEError"
pid: 10960
hostname: TONY-DELL7050

## 相关环境信息
- **操作系统**：
- **Node 版本**：v14.7
- **Egg 版本**：v2.15.1

**Comment by huihuicn** [comment]
应该要mysql设置一下密码验证的方式，修改为兼容模式
https://blog.csdn.net/weixin_35516624/article/details/113206657

**Comment by z2360326111** [comment]
> 应该要mysql设置一下密码验证的方式，修改为兼容模式 https://blog.csdn.net/weixin_35516624/article/details/113206657

我没这么大权限，连的别人的数据库，虽然现在我用mysql2解决了，但是egg-mysql确是找不到解决方案
