### ISSUE TITLE
在egg中使用软链接出现问题

### ISSUE THREAD

**Issue by johnsmithsren** [eggjs/egg#5121]
### Your detail info about the Bug:

1. 我在egg的ts版本中,开发模式下，通过引入另外编译好的js库，出现module not found的问题，因为应用源的js库那边没有对应的node_module包，而我希望运行引用的js时候直接能够使用本egg项目下的node_mudule中的相关依赖。不知道有什么配置可以实现.
2. 报错信息  Error [MODULE_NOT_FOUNDError]: [egg-core] load file: C:\xx\s-ops\sBack\app.ts, error: Cannot find module 'protobufjs/minimal'
Require stack:
- C:\xx\s-common\design\dist_china\js\msg_pb_generator.js
- C:\xx\s-common\design\dist_china\js\init.js
- C:\xx\s-ops\sBack\app.ts
- C:\xx\s-ops\sBack\node_modules\egg-core\lib\utils\index.js
- C:\xx\s-ops\sBack\node_modules\egg-core\lib\egg.js
- C:\xx\s-ops\sBack\node_modules\egg-core\index.js
- C:\xx\s-ops\sBack\node_modules\egg\lib\application.js
- C:\xx\s-ops\sBack\node_modules\egg\index.js
- C:\xx\s-ops\sBack\node_modules\egg-cluster\lib\app_worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (C:\xx\s-ops\sBack\node_modules\egg-core\node_modules\tsconfig-paths\src\register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\xx\s-common\design\dist_china\js\msg_pb_generator.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._compile (C:\xx\s-ops\sBack\node_modules\esbuild-register\dist\node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader (C:\xx\s-ops\sBack\node_modules\esbuild-register\dist\node.js:2262:9) {
  code: 'MODULE_NOT_FOUND',

### Reproduction Repo

null

### Node Version

16.14.1

### Eggjs Version

3.12.0

### Plugin Name and its version

null

### Platform and its version

win11

**Comment by fengmk2** [comment]
请提供一个最小复现代码库。

**Comment by johnsmithsren** [comment]
我直接拷贝过来了，不使用软链接了

**Comment by johnsmithsren** [comment]
不过我遇到另外一个问题，就是egg ts 项目 默认使用commonjs编译，当我指定 package.json 中 type:"module" 来避免一个报错 SyntaxError: Cannot use import statement outside a module ，发现设置后，egg-core 反而会报错。请问有什么建议吗？

**Comment by johnsmithsren** [comment]
https://github.com/johnsmithsren/symlink.git  复现库
