### ISSUE TITLE
agent worker 错误：Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by defghy** [eggjs/egg#5130]
### Your detail info about the Bug:

线上服务几率性502，一天几次；发现agent进程内存异常高；
观察了内存升高的时间节点，找到如下错误

`2023-01-17 04:56:01,271 ERROR 88 nodejs.unhandledExceptionError: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.utf8Slice (<anonymous>)
    at Buffer.toString (buffer.js:778:17)
    at JSON.parse (<anonymous>)
    at Function.decode (/home/web_server/nodejs/project/node_modules/cluster-client/lib/protocol/packet.js:86:26)
    at Socket.onReadable (/home/web_server/nodejs/project/node_modules/cluster-client/lib/server.js:138:29)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (internal/streams/readable.js:569:12)
    at onEofChunk (internal/streams/readable.js:547:5)
    at readableAddChunk (internal/streams/readable.js:264:5)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
code: "ERR_STRING_TOO_LONG"
name: "unhandledExceptionError"
pid: 88`

这里pid为88，是agent进程
 
![image](https://user-images.githubusercontent.com/5386958/213103153-ab34cd63-1e8a-44b3-a72d-eacd84497068.png)

分析为agent接收了大量数据，导致JSON.parse超出处理范围(512M)。

请求参数这里我们限制为30M
`        bodyParser: {
            jsonLimit: '30mb',
        },`

日志的数据缺失超过了500M，但是感觉日志文件大一些应该也没什么问题

我们的服务代码比较简单，只使用了比较基础的功能
不知道agent监听了哪些数据可能导致这个问题？

### Reproduction Repo

暂无

### Node Version

14

### Eggjs Version

2.36.0

### Plugin Name and its version

"egg-multipart": "2.4.0", "egg-scripts": "^2.11.0", "egg-socket.io": "^4.1.5", "egg-static": "^2.2.0", "egg-validate": "^2.0.2",

### Platform and its version

linux

**Comment by defghy** [comment]
在报错节点上添加了log
<img width="829" alt="image" src="https://user-images.githubusercontent.com/5386958/214390736-ec8b17f8-3e1a-4534-a46f-d08fe9a466b8.png">

报错信息如下
```
huyu.server 1213486160 
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.0; de; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
Host: 127.0.0.1:41941
Accept: */*

^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
...
```

分析报错日志
- connLength为1213486160，太大为直接报错原因。
- 这里^@搜了下，代表空字符，说明实际内容没有这么大
- connBuf应该是一个JSON字符串，类似于这样
<img width="507" alt="image" src="https://user-images.githubusercontent.com/5386958/214392339-03761ec9-8e4c-4853-b64a-f15499ed18f9.png">
但是报错这里，其内容看起来是个request header之类的东西
- 这里的41491表示clusterPort

**Comment by defghy** [comment]
添加日志后发现，tcp接收到的http请求，请求url为 /app/kibana

请求方ip为：127.0.0.1，端口号每次都会发生变化；
由于使用的是docer容器，因此怀疑还是项目自身发出的请求，而不是第三方比如安全组扫描之类的原因

搜索了项目下所有代码没有kibana相关字符串，请求来源待查
