### ISSUE TITLE
eggjs能把所有的日志都关掉吗，包括系统日志，也就是禁用egg-logger

### ISSUE THREAD

**Issue by nanhupatar** [eggjs/egg#5176]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

severless部署报错
```
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Error: EMFILE: too many open files, open '/var/user/package.json'\n    at Object.openSync (fs.js:438:3)\n    at Object.readFileSync (fs.js:343:35)\n    at Object.exports.readJSONSync (/var/user/node_modules/utility/lib/json.js:19:24)\n    at new EggLoader (/var/user/node_modules/egg-core/lib/loader/egg_loader.js:44:24)\n    at new AppWorkerLoader (/var/user/node_modules/egg/lib/loader/app_worker_loader.js:9:1)\n    at new EggCore (/var/user/node_modules/egg-core/lib/egg.js:121:19)\n    at new EggApplication (/var/user/node_modules/egg/lib/egg.js:47:5)\n    at new Application (/var/user/node_modules/egg/lib/application.js:60:5)\n    at Object.exports.tcbGetApp (/var/user/app.js:36:10)\n    at Runtime.module.exports.main [as handler] (/var/user/tcbindex.js:21:23)","statusCode":430}
```

怀疑是默认日志打印，读写引起的

### 可复现问题的仓库地址（Reproduction Repo）

https://github.com/eggjs/egg

### Node 版本号：

v12.0

### Eggjs 版本号：

^2.15.1

### 相关插件名称与版本号（PlugIn and Name）：

mysql2  egg-sequelize

### 操作平台与版本号（Platform and Version）：

mac

**Comment by nanhupatar** [comment]
@fengmk2

**Comment by atian25** [comment]
> EMFILE: too many open files, open '/var/user/package.json

解决问题，不是逃避问题，关闭日志只是把眼睛闭上。我看你在 https://github.com/eggjs/egg/issues/5165 有提了
