### ISSUE TITLE
egg v3 启动时报错

### ISSUE THREAD

**Issue by zyzy68** [eggjs/egg#5179]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

npm run dev时会报错，但程序功能正常，也不是每次启动都报错！
[egg-ts-helper] create typings\app\extend\helper.d.ts (3ms)
[egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (3ms)
[egg-ts-helper] create typings\app\model\index.d.ts (4ms)
[egg-ts-helper] create typings\config\index.d.ts (43ms)
[egg-ts-helper] create typings\config\plugin.d.ts (3ms)
[egg-ts-helper] create typings\app\service\index.d.ts (11ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2023-04-29 19:04:23,808 INFO 11888 [master] node version v16.20.0
2023-04-29 19:04:23,810 INFO 11888 [master] egg version 3.15.0
[egg-ts-helper] create typings\app\extend\helper.d.ts (6ms)
[egg-ts-helper] create typings\app\controller\index.d.ts (10ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (4ms)
[egg-ts-helper] create typings\app\model\index.d.ts (6ms)
[egg-ts-helper] create typings\config\index.d.ts (58ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (7ms)
[egg-ts-helper] create typings\app\index.d.ts (2ms)
(node:9632) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
Executed (default): SELECT 1+1 AS result Elapsed time: 5ms
2023-04-29 19:04:30,212 INFO 11888 [master] agent_worker#1:9632 started (6392ms)
2023-04-29 19:04:33,577 WARN 9632 [agent:development] reload worker because E:\cx\Workspace\tcenrollment\app\extend\helper.js change
2023-04-29 19:04:33,905 WARN 9632 [agent:development] reload worker because E:\cx\Workspace\tcenrollment\app.js change
(node:8612) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
Executed (default): SELECT 1+1 AS result Elapsed time: 4ms
2023-04-29 19:04:35,631 INFO 11888 [master] egg started on http://127.0.0.1:7001 (11820ms)
2023-04-29 19:04:35,671 WARN 9632 [agent:development] reload worker because E:\cx\Workspace\tcenrollment\app\controller\user\sysuser.js change
(node:19300) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
Executed (default): SELECT 1+1 AS result Elapsed time: 2ms
[2023-04-29 19:04:38.248] [cfork:master:11888] master uncaughtException: Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:874:20)
    at ChildProcess.target.send (node:internal/child_process:747:19)
    at Worker.send (node:internal/cluster/worker:48:10)
    at send (E:\cx\Workspace\tcenrollment\node_modules\sendmessage\index.js:39:18)
    at AppWorker.send (E:\cx\Workspace\tcenrollment\node_modules\egg-cluster\lib\utils\mode\impl\process\app.js:33:5)
    at Messenger.sendToAppWorker (E:\cx\Workspace\tcenrollment\node_modules\egg-cluster\lib\utils\messenger.js:166:14)
    at Messenger.send (E:\cx\Workspace\tcenrollment\node_modules\egg-cluster\lib\utils\messenger.js:119:12)
    at Master.onAppStart (E:\cx\Workspace\tcenrollment\node_modules\egg-cluster\lib\master.js:469:22)
    at Master.emit (node:events:513:28)
    at Messenger.sendToMaster (E:\cx\Workspace\tcenrollment\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:874:20)
    at ChildProcess.target.send (node:internal/child_process:747:19)
    at Worker.send (node:internal/cluster/worker:48:10)
    at send (E:\cx\Workspace\tcenrollment\node_modules\sendmessage\index.js:39:18)
2023-04-29 19:04:38,267 INFO 11888 [master] app_worker#1:8612 disconnect, suicide: true, state: disconnected, current workers: ["2","3"]
2023-04-29 19:04:38,272 WARN 9632 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2023-04-29 19:04:38.303] [cfork:master:11888] worker:8612 exit (code: null, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
(node:1056) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
Executed (default): SELECT 1+1 AS result Elapsed time: 3ms
[2023-04-29 19:04:42.982] [cfork:master:11888] worker:19300 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2023-04-29 19:04:42.983] [cfork:master:11888] don't fork new work (refork: false)
2023-04-29 19:04:42,983 INFO 11888 [master] app_worker#2:19300 disconnect, suicide: true, state: disconnected, current workers: ["3"]
2023-04-29 19:04:42,989 WARN 9632 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2023-04-29 19:04:43.022] [cfork:master:11888] worker:19300 exit (code: null, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

16.20.0

### Eggjs 版本号：

v3

### 相关插件名称与版本号（PlugIn and Name）：

 "egg-passport": "^2.1.1",     "egg-passport-local": "^1.2.1",    "egg-sequelize": "^6.0.0",    "egg-view-nunjucks": "^2.3.0",

### 操作平台与版本号（Platform and Version）：

Windows 11 专业版（22H2）

**Comment by davidchen27** [comment]
我也遇到了一样的问题, 虽然服务照常可用, 可是就是偶尔会发送这样的报错

**Comment by 2140509722** [comment]
![1111](https://github.com/eggjs/egg/assets/99722844/35306ca5-68a8-40f7-8f4e-22fbc75aac69)
