### ISSUE TITLE
logger.error support err.cause

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#5181]
### 请详细告知你的新点子（Nice Ideas）：

Can show the full stack 

```
2023-05-07 00:21:53,803 ERROR 62800 nodejs.Error: Save request files failed
    at Object.saveRequestFiles (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/egg-multipart@3.3.0/node_modules/egg-multipart/app/extend/context.js:177:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async multipart (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/egg-multipart@3.3.0/node_modules/egg-multipart/app/middleware/multipart.js:13:5)
    at async bodyParser (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/koa-bodyparser@4.4.0/node_modules/koa-bodyparser/index.js:91:5)
    at async /Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/koa-static-cache@5.1.4/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/egg@3.15.0/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/egg@3.15.0/node_modules/egg/app/middleware/meta.js:12:5)
    at async /Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/koa@2.14.2/node_modules/koa/lib/application.js:160:16

cause: Error: Unexpected end of form
    at Multipart._final (/Users/fengmk2/git/github.com/eggjs/examples/multipart-file-mode/node_modules/.store/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:588:17)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at Writable.end (node:internal/streams/writable:634:5)
    at IncomingMessage.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

pid: 62800
hostname: fengmk2deMacBook-Pro.local
```

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-logger/pull/91
