### ISSUE TITLE
install 之后，无法启动server

### ISSUE THREAD

**Issue by 778477** [eggjs/egg#523]
[package.json](https://raw.githubusercontent.com/TheraPackages/dumplings/master/package.json)

```
2017-03-06 19:06:01,174 INFO 60329 [master] =================== egg start =====================
2017-03-06 19:06:01,176 INFO 60329 [master] egg version 1.0.0-rc.2
2017-03-06 19:06:01,177 INFO 60329 [master] start with options: {"framework":"/Users/guomiaoyou/github/dumplings/node_modules/egg","baseDir":"/Users/guomiaoyou/github/dumplings","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":"","customEgg":"/Users/guomiaoyou/github/dumplings/node_modules/egg"}
2017-03-06 19:06:01,177 INFO 60329 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: undefined
2017-03-06 19:06:01,184 INFO 60329 [master] Agent Worker:60331 start with ["{\"framework\":\"/Users/guomiaoyou/github/dumplings/node_modules/egg\",\"baseDir\":\"/Users/guomiaoyou/github/dumplings\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"customEgg\":\"/Users/guomiaoyou/github/dumplings/node_modules/egg\",\"clusterPort\":54675}"]
2017-03-06 19:06:01,685 INFO 60329 [master] Agent Worker started (504ms)
2017-03-06 19:06:01,690 INFO 60329 [master] App Worker#1:60332 start, state: none, current workers: ["1"]
2017-03-06 19:06:02,695 ERROR 60332 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:60332)
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at cb (net.js:1317:16)
    at rr (cluster.js:626:14)
    at Worker.<anonymous> (cluster.js:595:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 60332
hostname: guomiaoyoudeMacBook-Pro.local
```

**Comment by fengmk2** [comment]
看来没有自动找到 free 的 端口，应该有问题。

**Comment by fengmk2** [comment]
@778477 你是使用 egg-bin 启动的吧？

**Comment by 778477** [comment]
我是直接 node index.js 启动的

**Comment by fengmk2** [comment]
@778477 你运行 `$ npm run dev` 看看，因为你的 7001 端口已经被占用了。

**Comment by 778477** [comment]
npm install 报错了

```
npm WARN enoent ENOENT: no such file or directory, open '/Users/guomiaoyou/github/dumplings/node_modules/JSONStream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/guomiaoyou/github/dumplings/node_modules/a-sync-waterfall/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/guomiaoyou/github/dumplings/node_modules/abbrev/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/guomiaoyou/github/dumplings/node_modules/accepts/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/guomiaoyou/github/dumplings/node_modules/acorn/package.json'

```

无法验证是否端口占用

**Comment by 778477** [comment]
新增 依赖 

```
    "egg-bin": "^2.2.3",
```

**Comment by atian25** [comment]
@778477 你不是用 egg-init 生成的项目?

**Comment by 778477** [comment]
是使用 `egg-init` 生成的啊。按文档Getting Started来的

**Comment by atian25** [comment]
你指的是用 `egg-init --type=simple` ? 遇到的问题是生成的项目的 `"egg-bin": "^2.2.3"` 的版本不对?
