### ISSUE TITLE
Can't find ViewEngine "nunjucks"

### ISSUE THREAD

**Issue by 778477** [eggjs/egg#525]
```
2017-03-06 21:48:50,902 INFO 86405 [master] egg started on http://127.0.0.1:7001 (1243ms)
2017-03-06 21:48:55,588 ERROR 86418 [-/::1/-/8ms GET /] nodejs.AssertionError: Can't find ViewEngine "nunjucks"
    at ContextView.[contextView#getViewEngine] (/Users/guomiaoyou/github/dumplings/node_modules/egg-view/lib/context_view.js:91:5)
    at ContextView.[contextView#render] (/Users/guomiaoyou/github/dumplings/node_modules/egg-view/lib/context_view.js:72:39)
    at next (native)
    at onFulfilled (/Users/guomiaoyou/github/dumplings/node_modules/co/index.js:65:19)
name: 'AssertionError'
actual: undefined
expected: true
operator: '=='
message: 'Can\'t find ViewEngine "nunjucks"'
generatedMessage: false
pid: 86418
hostname: guomiaoyoudeMacBook-Pro.local

```

`config/config.default.js ` 配置如下
```
'use strict';
const path = require('path')
module.exports = appInfo => {
  const config = {
	view:{
	  root: path.join(appInfo.baseDir, 'app/view'),
	  defaultExtension: '.html',
	  defaultViewEngine: 'nunjucks',
	  mapping: {'.nj':'nunjucks'},
	},
	security: {
		csrf: {
		  enable:false,
		},
	},
  };
  config.keys = appInfo.name + '778477';
  return config;
};

```

home.js 
```
module.exports = function*() {
  const result = {
    title: 'dumplings',
  };
  yield this.render('index.html', result);
};
```

**Comment by atian25** [comment]
plugin.js 呢？挂载 nunjucks 插件没

**Comment by 778477** [comment]
```
➜  config git:(master) cat plugin.js 
'use strict';

// had enabled by egg
// exports.static = true;

exports.nunjucks = {
	enable: true,
	package: 'egg-view-nunjucks'
};


```

**Comment by 778477** [comment]
不好意思，是我 覆盖配置了。。。我的锅

**Comment by zeroven** [comment]
@778477 帮忙同步下文档呗，http://eggjs.org/zh-cn/intro/quickstart.html#模板渲染 这里会掉坑的

**Comment by atian25** [comment]
什么坑？

**Comment by susanzhang66** [comment]
楼主怎么解决的？？
