### ISSUE TITLE
egg_amqplib 连接中断后导致程序异常退出

### ISSUE THREAD

**Issue by liuxieri** [eggjs/egg#5265]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

 worker:9284 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2023-10-27 16:06:52,633 ERROR 17708 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
cause: {"errno":-4078,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5672}
isOperational: true
errno: -4078
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 5672
pid: 17708
hostname: DESKTOP-D11N0NM
ERROR 14624 nodejs.AppWorkerDiedError: [master] app_worker#13:9284 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1","2","3","4","5","6","7","8","9","10","11","12","14","15"]
    at Master.onAppExit (E:\Project\kdb_api\node_modules\egg-cluster\lib\master.js:511:21)
    at Master.emit (node:events:526:28)
    at Messenger.sendToMaster (E:\Project\kdb_api\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\Project\kdb_api\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (E:\Project\kdb_api\node_modules\egg-cluster\lib\master.js:354:22)
    at EventEmitter.emit (node:events:538:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:203:13)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
name: "AppWorkerDiedError"
pid: 14624
hostname: DESKTOP-D11N0NM

2023-10-27 16:06:52,634 ERROR 17708 [app_worker] start error, exiting with code:1

### 可复现问题的仓库地址（Reproduction Repo）

没有

### Node 版本号：

v16.14.2

### Eggjs 版本号：

2.23.0，

### 相关插件名称与版本号（PlugIn and Name）：

egg_amqplib^2.0.5

### 操作平台与版本号（Platform and Version）：

Windows 11 专业版

**Comment by meguoe** [comment]
https://github.com/meguoe/egg-amqplib-tf 增强版，支持自动重连
