### ISSUE TITLE
初始化项目跑不起来

### ISSUE THREAD

**Issue by pkjy** [eggjs/egg#5345]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

按照官网教程  npm init egg --type=ts 
选择 ts 
结果报错

```
[egg-init] use registry: https://registry.npmjs.org
[egg-init] target dir is /Users/mac/work/shot-api-nodejs
[egg-init] fetching npm info of egg-init-config
[egg-init] use fallback from egg-init-config
? Please select a boilerplate type ts - Simple egg && typescript app boilerplate
[egg-init] use boilerplate: ts(egg-boilerplate-ts)
[egg-init] fetching npm info of egg-boilerplate-ts
HttpClientConnectTimeoutError: Connect Timeout Error
    at HttpClient.#requestInternal (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/urllib/dist/commonjs/HttpClient.js:620:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpClient.request (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/urllib/dist/commonjs/HttpClient.js:145:16)
    at async Object.request (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/urllib/dist/commonjs/index.js:45:12)
    at async Command.curl (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/egg-init/lib/init_command.js:506:12)
    at async Command.getPackageInfo (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/egg-init/lib/init_command.js:519:22)
    at async Command.downloadBoilerplate (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/egg-init/lib/init_command.js:484:20)
    at async Command.run (/Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/egg-init/lib/init_command.js:69:21)
    at async /Users/mac/.npm/_npx/ec707b6574c6079a/node_modules/egg-init/bin/egg-init.js:6:3
npm ERR! code 1
npm ERR! path /Users/mac/work/shot-api-nodejs
npm ERR! command failed
npm ERR! command sh -c -- create-egg

```

### 可复现问题的仓库地址（Reproduction Repo）

https://www.eggjs.org/zh-CN/tutorials/typescript

### Node 版本号：

v16.20.2

### Eggjs 版本号：

x

### 相关插件名称与版本号（PlugIn and Name）：

egg-boilerplate-ts

### 操作平台与版本号（Platform and Version）：

macOS 13.0 (22A380)

**Comment by pkjy** [comment]
参考 https://github.com/eggjs/egg-boilerplate-ts 里面的方法就正常了。
npx egg-init --type=ts


建议官网更新一下快速入门那的示例。
