### ISSUE TITLE
mysql动态创建实例失败，文档问题？

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#539]
文档地址：https://eggjs.org/zh-cn/advanced/plugin.html#动态创建实例

```
// app.js
module.exports = app => {
  app.beforeStart(function* () {
    // 从配置中心获取 MySQL 的配置
    const mysqlConfig = yield app.configCenter.fetch('mysql');
    // 动态创建 MySQL 实例
    app.database = app.mysql.createInstance(mysqlConfig);
  });
};
```

上述代码在我自己的app.js中直接报错，因为app.configCenter对象不存在，我试了两个Egg版本都报这个错误，分别是：

* 1.0.0-rc.1
* 0.5.0

最后mysqlConfig我直接写死了，如下：

```
// app.js
module.exports = app => {
    app.beforeStart(function* () {

	    if(app.config.env == 'local'){
	    	// app.mysql = app.mysql
	    	app.database = app.mysql.createInstance({
			    // 单数据库信息配置
			    client: {
			        // host
			        host: '10.164.50.22',
			        // 端口号
			        port: '3300',
			        // 用户名
			        user: 'johnny',
			        // 密码
			        password: 'johnny',
			        // 数据库名
			        database: 'cathay_portal',
			    },
			    // 是否加载到 app 上，默认开启
			    app: true,
			    // 是否加载到 agent 上，默认关闭
			    agent: false,
			});
	    }
 
    });
};
```

但app.mysql.createInstance()时，仍然报错

报错信息

```
> egg-bin dev --port=7003

2017-03-09 19:17:36,100 INFO 77804 [master] =================== egg start =====================
2017-03-09 19:17:36,101 INFO 77804 [master] egg version 1.0.0-rc.1
2017-03-09 19:17:36,102 INFO 77804 [master] start with options: {"customEgg":"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg","baseDir":"/Users/johnnychq/workbench/cxinscn_cathay_portal/private","port":7003,"workers":1,"plugins":null,"https":false,"key":"","cert":""}
2017-03-09 19:17:36,102 INFO 77804 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development
2017-03-09 19:17:36,122 INFO 77804 [master] Agent Worker:77805 start with ["{\"customEgg\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg\",\"baseDir\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/private\",\"port\":7003,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"clusterPort\":54345}"]
2017-03-09 19:17:36,608 INFO 77804 [master] Agent Worker started (490ms)
2017-03-09 19:17:36,614 INFO 77804 [master] App Worker#1:77806 start, state: none, current workers: ["1"]
2017-03-09 19:17:37,407 ERROR 77806 [-/127.0.0.1/-/0ms GET /] nodejs.AssertionError: [egg-mysql] 'host: undefined', 'port: undefined', 'user: undefined', 'database: null' are required on config
    at Singleton.createOneClient [as create] (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.0.0@egg-mysql/lib/mysql.js:13:3)
    at Singleton.createInstance (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.1.0.0-rc.1@egg/lib/core/singleton.js:53:17)
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/private/app.js:7:32
    at next (native)
    at onFulfilled (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:65:19)
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:54:5
    at co (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:118:63)
    at next (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:69:7)
name: 'AssertionError'
actual: undefined
expected: true
operator: '=='
message: '[egg-mysql] \'host: undefined\', \'port: undefined\', \'user: undefined\', \'database: null\' are required on config'
generatedMessage: false
pid: 77806
hostname: localhost
```

**Comment by johnnychen** [comment]
相关问题：生产环境mysql账号密码如何存储保密问题https://github.com/eggjs/egg/issues/493

**Comment by atian25** [comment]
应该是:

```js
app.mysql.createInstance({
  host: '127.0.0.1',
  port: 3306,
  user: 'root',
  password: '',
  database: 'test'
});
```

**Comment by atian25** [comment]
文档看了下，这里并不能看出 config 是什么，我注明下吧。

```js
const mysqlConfig = yield app.configCenter.fetch('mysql');
app.database = app.mysql.createInstance(mysqlConfig);
```

**Comment by jtyjty99999** [comment]
https://github.com/eggjs/egg-mysql/tree/master/test/fixtures/apps/mysqlapp-dynamic  用例里有一个动态创建的例子，可参考。 configCenter 只是一个事例

**Comment by johnnychen** [comment]
动态创建实例已经OK，但引起了其他方面的报错，报错信息如下：

```
> egg-bin dev

2017-03-10 17:23:45,381 INFO 88108 [master] =================== egg start =====================
2017-03-10 17:23:45,383 INFO 88108 [master] egg version 0.5.0
2017-03-10 17:23:45,384 INFO 88108 [master] start with options: {"framework":"/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/egg","baseDir":"/Users/johnnychq/workbench/cxinscn_cathay_portal/public","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":"","customEgg":"/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/egg"}
2017-03-10 17:23:45,384 INFO 88108 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development
2017-03-10 17:23:45,404 INFO 88108 [master] Agent Worker:88109 start with ["{\"framework\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/egg\",\"baseDir\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/public\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"customEgg\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/egg\",\"clusterPort\":56747}"]
2017-03-10 17:23:45,836 INFO 88109 [egg:watcher:agent] watcher start success
2017-03-10 17:23:45,841 INFO 88108 [master] Agent Worker started (441ms)
2017-03-10 17:23:45,851 INFO 88108 [master] App Worker#1:88110 start, state: none, current workers: ["1"]
2017-03-10 17:23:46,793 WARN 88108 [master] App Worker#1:88110 started at 7001, remain 0 (952ms)
2017-03-10 17:23:46,793 INFO 88108 [master] egg started on http://127.0.0.1:7001 (1409ms)
2017-03-10 17:23:46,810 ERROR 88110 nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'DBSA1'@'10.167.11.82' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.6.1@ali-rds/lib/client.js:28:10
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:136:8
    at thunkToPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:135:10)
    at toPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:99:29)
    sql: select now() as currentTime;
code: 'ER_ACCESS_DENIED_ERROR'
errno: 1045
sqlState: '28000'
fatal: true
name: 'ER_ACCESS_DENIED_ERRORError'
pid: 88110
hostname: johnnychq-MacBook-Pro.local

2017-03-10 17:23:46,840 ERROR 88110 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'DBSA1'@'10.167.11.82' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.2.6.1@ali-rds/lib/client.js:28:10
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:136:8
    at thunkToPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:135:10)
    at toPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/johnnychq/workbench/cxinscn_cathay_portal/public/node_modules/.4.6.0@co/index.js:99:29)
    sql: select now() as currentTime;
code: 'ER_ACCESS_DENIED_ERROR'
errno: 1045
sqlState: '28000'
fatal: true
name: 'ER_ACCESS_DENIED_ERRORError'
pid: 88110
hostname: johnnychq-MacBook-Pro.local

2017-03-10 17:23:46,852 INFO 88110 [egg-mysql] select now() as currentTime; 68ms
```

-----------------

报错信息比较简单，说连接mysql错误。

动态创建mysql的app.js的代码为：

```
// app.js
module.exports = app => {
    app.beforeStart(function* () {

      let mysqlConfig = app.config.mysql.client;
     
      if(app.config.env == 'prod'){
        mysqlConfig.password = decipher(mysqlConfig.password)
      }
      // app.mysql = app.mysql
      app.database = app.mysql.createInstance(mysqlConfig);
 
    });
};
```

生产环境config.prod.js的配置为

```
exports.mysql = {
    // 单数据库信息配置
    client: {
        // host
        host: 'rm-1te9836zx6059tmfx.mysql.rds.aliyuncs.com',
        // 端口号
        port: '3306',
        // 用户名
        user: 'rds',
        // 密码
        password: '118ba7981879cb098ff26ac419',
        // 数据库名
        database: 'cathay_portal',
    },
    // 是否加载到 app 上，默认开启
    app: true,
    // 是否加载到 agent 上，默认关闭
    agent: false,
};
```

上述config中的`password`已经进行加密，在app.js中根据`env=prod`判断，会进行动态解密密码，然后手动创建app.database的mysql实例。

上述过程代码以及逻辑我觉的没什么问题，但为什么会报错呢？

我怀疑是，即使通过app.js动态创建mysql实例，egg框架仍然会创建一个默认的mysql实例，并且该实例会以config中的账号、密码进行连接，由于config中的密码被加密，所以连接失败。即创建了两个mysql实例，自己动态创建的没问题，但egg内部默认创建的报错。

**Comment by atian25** [comment]
> egg version 0.5.0

- 先把你的 egg 升级到最新 RC 版再说，太旧了， 0.x 版本我们不保证兼容性的。
- 如果是用骨架生成的，执行一次 `npm run auto` 把依赖的版本也都升级了。
- 删除 node_modules 目录，重新 install 再看看

**Comment by johnnychen** [comment]
如果我猜测没错误的话，只要提供一个开关，关闭egg默认创建mysql示例即可？

**Comment by johnnychen** [comment]
没问题，你们不知道解密算法-_-

**Comment by atian25** [comment]
不想 egg 默认创建，就不要配置 `exports.mysql.client`

**Comment by atian25** [comment]
你这里不涉及到动态加载配置吧? 为何不把 `decipher` 放到 config 里面呢?

**Comment by johnnychen** [comment]
我换了另一个应用, 版本为 v1.0.0-rc-1，但问题是一样的

```
> cathay-portal-private@0.0.1 dev /Users/johnnychq/workbench/cxinscn_cathay_portal/private
> egg-bin dev --port=7003

2017-03-10 17:44:48,839 INFO 88324 [master] =================== egg start =====================
2017-03-10 17:44:48,841 INFO 88324 [master] egg version 1.0.0-rc.1
2017-03-10 17:44:48,841 INFO 88324 [master] start with options: {"framework":"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg","baseDir":"/Users/johnnychq/workbench/cxinscn_cathay_portal/private","port":7003,"workers":1,"plugins":null,"https":false,"key":"","cert":"","customEgg":"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg"}
2017-03-10 17:44:48,841 INFO 88324 [master] start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development
2017-03-10 17:44:48,867 INFO 88324 [master] Agent Worker:88325 start with ["{\"framework\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg\",\"baseDir\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/private\",\"port\":7003,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"customEgg\":\"/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/egg\",\"clusterPort\":52165}"]
2017-03-10 17:44:49,425 INFO 88324 [master] Agent Worker started (562ms)
2017-03-10 17:44:49,430 INFO 88324 [master] App Worker#1:88326 start, state: none, current workers: ["1"]
2017-03-10 17:44:50,297 WARN 88324 [master] App Worker#1:88326 started at 7003, remain 0 (872ms)
2017-03-10 17:44:50,297 INFO 88324 [master] egg started on http://127.0.0.1:7003 (1456ms)
2017-03-10 17:44:50,319 ERROR 88326 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'DBSA1'@'10.167.11.82' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.2.6.1@ali-rds/lib/client.js:28:10
    at /Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:136:8
    at thunkToPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:135:10)
    at toPromise (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/johnnychq/workbench/cxinscn_cathay_portal/private/node_modules/.4.6.0@co/index.js:99:29)
    sql: select now() as currentTime;
code: 'ER_ACCESS_DENIED_ERROR'
errno: 1045
sqlState: '28000'
fatal: true
name: 'ER_ACCESS_DENIED_ERRORError'
pid: 88326
hostname: johnnychq-MacBook-Pro.local
```

**Comment by johnnychen** [comment]
@atian25 呃，提醒的好，问题复杂化了，直接在config中decipher根本就不需要动态创建实例这个事情了。。
 
https://github.com/eggjs/egg/issues/493 这个issue把自己误导了

**Comment by jtyjty99999** [comment]
厄，你是动态创建的，就不要指定 exports.mysql 内的client了，搞个其他的配置项保存一下就好了，还是那个例子，搞了个mysql1 保存到 https://github.com/eggjs/egg-mysql/blob/master/test/fixtures/apps/mysqlapp-dynamic/config/config.default.js#L7  建议你还是再仔细看看这个例子

**Comment by atian25** [comment]
@johnnychen 典型的 X-Y 问题，😁
