### ISSUE TITLE
service 例子有误。

### ISSUE THREAD

**Issue by pursonchen** [eggjs/egg#580]
exports.info = function* () {

	const userId = this.params.id;
    const userInfo = yield this.service.admin.find(userId);
  this.body = userInfo;
  
};

####报错#############

You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"

TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:101:25)
    at onFulfilled (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:69:7)
    at C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:54:5
    at Object.co (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:50:10)
    at Object.toPromise (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:118:63)
    at next (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:69:7)
    at C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:54:5
    at Object.co (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:50:10)
    at Object.toPromise (C:\Users\clic\Desktop\nodejs\egg-mmping\node_modules\co\index.js:118:63)

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
`this.service.admin.find` 没有定义

**Comment by pursonchen** [comment]
那个我在service定义了，出问题的是this.params.id吧

**Comment by pursonchen** [comment]
问题是在yield中传了没有定义的id

**Comment by pursonchen** [comment]
是的，我错了
