### ISSUE TITLE
如果我想在egg 里面引用第三方模版引擎我改如何做？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#587]
例如我想把egg 的模版引擎改为 art-template
 https://github.com/aui/artTemplate
看了文档不太明白，请指教。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view-xtpl

**Comment by a526672351** [comment]
任何第三方插件，都必须另外开发吗？egg到底是如何才能快捷的引入第三方插件？

**Comment by atian25** [comment]
绝大部分场景不需要：
- view 是特殊的，因为有统一的规范。
- Middleware 很简单的 require 下就 ok 了，在文档里面有
- 其他 node 类库，koa 该怎么用就这么用，如果有一定范式的，就可以抽插件

**Comment by a526672351** [comment]
Message
Can't find viewEngine for F:\egg\egg-example\app\view\hello.xtpl

AssertionError: Can't find viewEngine for F:\egg\egg-example\app\view\hello.xtpl
    at ContextView.[contextView#render] (F:\egg\egg-example\node_modules\egg\node_modules\egg-view\lib\context_view.js:69:5)
    at next (native)
    at onFulfilled (F:\egg\egg-example\node_modules\egg\node_modules\co\index.js:65:19)

按照文档配置无法跑起来啊？

**Comment by popomore** [comment]
config 写错了吧，要用 config.view

**Comment by atian25** [comment]
这个问题遇到最多了 -.-

**Comment by a526672351** [comment]
配套文档跟不上，官方文档
![image](https://cloud.githubusercontent.com/assets/5345266/24033167/832edb6c-0b26-11e7-8ae1-5dd0289ea27e.png)
我应该meiyou没有看错

**Comment by ngot** [comment]
文档写的没错。配置有很多方法，你自己的配置改了方法，要自己根据实际情况去更改。

比如，config.js 里面默认都是：
```js
exports.xx = yyy
```

如果，改成了 
```js
module.exports = appInfo => {
  const config = {};
  config.xx = yy;
}
```

就要自己去转变思路。

**Comment by atian25** [comment]
@a526672351 ... 你应该去看下 `module.exports` 和 `exports` 的入门介绍。

**Comment by a526672351** [comment]
额，已经看了N遍了，已经改为还是不行
![image](https://cloud.githubusercontent.com/assets/5345266/24033330/57f9486e-0b27-11e7-8c15-3cecb5dd64ea.png)
2017-03-17 15:33:49,686 ERROR 5276 nodejs.AppWorkerDiedError: [master] App Worker#1:4412 died (code: 1, signal: 1, suicide: false, st
ate: dead), current workers: []
    at Master.onAppExit (F:\egg\egg-example\node_modules\egg\node_modules\egg-cluster\lib\master.js:280:19)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:188:7)
    at Messenger.sendToMaster (F:\egg\egg-example\node_modules\egg\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (F:\egg\egg-example\node_modules\egg\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at EventEmitter.cluster.on (F:\egg\egg-example\node_modules\egg\node_modules\egg-cluster\lib\master.js:190:22)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:379:15)
    at ChildProcess.g (events.js:291:16)
name: 'AppWorkerDiedError'
pid: 5276

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! shopManage@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopManage@1.0.0 dev script 'egg-bin dev'.
npm ERR! This is most likely a problem with the shopManage package,
npm ERR! not with npm itself.

**Comment by ngot** [comment]
这个日志 和 egg-view 一点关系也没有

**Comment by a526672351** [comment]
各位，大大是我的错，可以了

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/24033467/f94c847e-0b27-11e7-8c29-b8a4435190cb.png)

我指的是这段，一个 node 模块其实是会自动包裹

```js
function(module, exports, __filename, __dirname) {
  // exports  就是 module.exports
  // 而这里你的代码把 module.exports 重新赋值了，exports 就不在等于 module.exports
  module.exports = appInfo => {
    const config = {};
    config.xx = yy;

   return config;
  };

  // 这段代码自然不会生效
  exports.abc = {};
}
```

把你改完后的 plugin.js ， config.default.js 还有具体报错信息再贴下，最新贴的那段报错不全。

**Comment by a526672351** [comment]
还想请教个问题，为什么每次修改重新编译都会报这样的错？
2017-03-17 15:49:18,453 INFO 8868 [master] App Worker#3:10392 disconnect, suicide: true, state: disconnected, current workers: ["4"]
2017-03-17 15:49:18,452 ERROR 10352 nodejs.ECONNRESETError: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 10352
hostname: sea-PC

**Comment by atian25** [comment]
有可能跟 https://github.com/eggjs/egg/issues/466 有关, cc @gxcsoccer

**Comment by a526672351** [comment]
整个 common-error.log 都是这个错误。

**Comment by xjchenhao** [comment]
![image](https://cloud.githubusercontent.com/assets/5373111/26056031/19ef9962-39a6-11e7-8f2e-747c059378ba.png)
![image](https://cloud.githubusercontent.com/assets/5373111/26056041/1ff63d8e-39a6-11e7-9c55-69cbdd703686.png)
![image](https://cloud.githubusercontent.com/assets/5373111/26056060/3e11f7ea-39a6-11e7-972c-933e5ab683e9.png)
你好，出现了类似楼主的错误，但是看着没有语法错误啊。求解。

**Comment by atian25** [comment]
重新安装依赖，这个问题应该已经修复了。
