### ISSUE TITLE
关于单元测试  

### ISSUE THREAD

**Issue by jeremy16601** [eggjs/egg#594]
1) test/app/controller/login.test.js "before all" hook:
     Error: ENOTEMPTY: directory not empty, rmdir 'D:\nodejs-Project\xxx\logs\luojiweiye'
      at Object.fs.rmdirSync (fs.js:818:18)
      at rmkidsSync (node_modules\rimraf\rimraf.js:355:25)
      at rmdirSync (node_modules\rimraf\rimraf.js:333:7)
      at rimrafSync (node_modules\rimraf\rimraf.js:303:9)
      at node_modules\rimraf\rimraf.js:341:5
      at Array.forEach (native)
      at rmkidsSync (node_modules\rimraf\rimraf.js:340:26)
      at rmdirSync (node_modules\rimraf\rimraf.js:333:7)
      at Function.rimrafSync [as sync] (node_modules\rimraf\rimraf.js:303:9)
      at Function.module.exports [as app] (node_modules\egg-mock\lib\app.js:163:12)
      at Context.before (test\app\controller\login.test.js:11:20)
      at Hook.Runnable.run (node_modules\co-mocha\lib\co-mocha.js:43:16)

**Comment by atian25** [comment]
前面的日志呢？

发自我的 iPhone

**Comment by wsw0108** [comment]
app.close()返回的是Promise，所以单元测试代码里要写成如下：
```
after(() => {
  return app.close();
});
```
或者其他mocha支持的thunk，generator之类的形式。

**Comment by atian25** [comment]
额... 到底问题是什么，一开始不是启动问题么，现在怎么变为单元测试了？

**Comment by atian25** [comment]
看起来像 win 下 rimraf 删除目录失败，

`at Context.before (test\app\controller\login.test.js:11:20)` 这段代码贴下

**Comment by wsw0108** [comment]
碰到过这样的问题，windows下的ENOTEMPTY。
起因是测试代码里开始写成如下：
```
after(() => {
  app.close();
});
```
而因为app.close()返回的是Promise(经过最近的某次提交后)，所以清除工作可能没有正确完成。
改为`return app.close()`之后，问题目前没有再出现。

**Comment by atian25** [comment]
嗯，所以要贴代码看看才知道。

因为 `app.close` 里面做了 logger 的关闭，如果没有这段的话，可能文件句柄没释放会导致无法删除。

**Comment by popomore** [comment]
是的，每次都要被 close 后再启动一个新的
