### ISSUE TITLE
win下运行报错

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#601]
* **Node Version**:6.2.0
* **Egg Version**:0.11.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:windows

[Mon Mar 20 2017 15:47:28 GMT+0800 (中国标准时间)] [cfork:master:4644] worker:4272 exit (code: null, suicide: true, state: d
ead, isDead: true, isExpected: true)

[Mon Mar 20 2017 15:47:28 GMT+0800 (中国标准时间)][pid: 5984][Leader] Error: read ECONNRESET
Error Stack:
  Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TCP.onread (net.js:563:26)
Error Additions:
  code: "ECONNRESET"
  errno: "ECONNRESET"
  syscall: "read"

2017-03-20 15:47:28,294 ERROR 5984 nodejs.ECONNRESETError: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TCP.onread (net.js:563:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 5984
hostname: PCPPCUN8HHDDWAX

**Comment by atian25** [comment]
应该跟 https://github.com/eggjs/egg/issues/466 是同个问题

**Comment by jamesliauw** [comment]
试了一下，不一样的

common-error.log============================
2017-03-20 18:57:01,726 ERROR 5692 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TCP.onread (net.js:563:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 5692
hostname: PCPPCUN8HHDDWAX

2017-03-20 18:57:01,729 ERROR 5692 nodejs.ECONNRESETError: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TCP.onread (net.js:563:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 5692
hostname: PCPPCUN8HHDDWAX

egg-agent.log==========================
2017-03-20 18:56:51,197 INFO 5692 [egg:logger] init all loggers with options: {"dir":"F:\\H5Workstation\\diagram-hackernews\\logs\\egg-hackernews","encoding":"utf8","env":"local","level":"DEBUG","consoleLevel":"INFO","outputJSON":false,"buffer":false,"appLogName":"egg-hackernews-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"type":"agent"}
2017-03-20 18:56:51,219 INFO 5692 [ClusterClient#Watcher] subscribe ["F:\\H5Workstation\\diagram-hackernews\\app","F:\\H5Workstation\\diagram-hackernews\\config","F:\\H5Workstation\\diagram-hackernews\\mocks","F:\\H5Workstation\\diagram-hackernews\\mocks_proxy"]
2017-03-20 18:56:51,273 INFO 5692 [ClusterClient#Watcher] has seized port 58197, and serves as leader client.
2017-03-20 18:56:51,276 INFO 5692 [egg-watcher:agent] watcher start success
2017-03-20 18:56:52,328 INFO 5692 [Leader#Watcher] socket connected, port: 58199
2017-03-20 18:57:00,421 INFO 5692 [Leader#Watcher] push subscribe data to cluster client#Watcher_mock_conn_1
2017-03-20 18:57:00,424 INFO 5692 [Leader#Watcher] push subscribe data to cluster client#Watcher_mock_conn_1
2017-03-20 18:57:00,631 WARN 5692 [agent:development] reload worker because F:\H5Workstation\diagram-hackernews\app\client\view\news\news.html change
2017-03-20 18:57:01,706 INFO 5692 [Leader#Watcher] socket connected, port: 58204

egg-web.log=======================
2017-03-20 18:56:52,186 INFO 5924 [egg:logger] init all loggers with options: {"dir":"F:\\H5Workstation\\diagram-hackernews\\logs\\egg-hackernews","encoding":"utf8","env":"local","level":"DEBUG","consoleLevel":"INFO","outputJSON":false,"buffer":false,"appLogName":"egg-hackernews-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"type":"application"}
2017-03-20 18:56:52,238 INFO 5924 [egg-schedule]: register schedule egg-schedule:F:\H5Workstation\diagram-hackernews\node_modules\.2.2.2@egg-logrotator\app\schedule\clean_log.js
2017-03-20 18:56:52,239 INFO 5924 [egg-schedule]: register schedule egg-schedule:F:\H5Workstation\diagram-hackernews\node_modules\.2.2.2@egg-logrotator\app\schedule\rotate_by_file.js
2017-03-20 18:56:52,289 INFO 5924 [egg-static] starting static serve /public/ -> F:\H5Workstation\diagram-hackernews\app\public
2017-03-20 18:56:52,295 INFO 5924 [egg-security] use csrf middleware
2017-03-20 18:56:52,297 INFO 5924 [egg-security] use methodnoallow middleware
2017-03-20 18:56:52,298 INFO 5924 [egg-security] use noopen middleware
2017-03-20 18:56:52,298 INFO 5924 [egg-security] use nosniff middleware
2017-03-20 18:56:52,299 INFO 5924 [egg-security] use xssProtection middleware
2017-03-20 18:56:52,299 INFO 5924 [egg-security] use xframe middleware
2017-03-20 18:56:52,300 INFO 5924 [egg-security] compose 6 middlewares into one security middleware
2017-03-20 18:56:52,319 INFO 5924 [ClusterClient#Watcher] gives up seizing port 58197, and serves as follower client.
2017-03-20 18:56:52,332 INFO 5924 [Follower#Watcher] register to channel: Watcher success
2017-03-20 18:56:52,332 INFO 5924 [egg-watcher:app] watcher start success
2017-03-20 18:57:01,564 INFO 4860 [egg:logger] init all loggers with options: {"dir":"F:\\H5Workstation\\diagram-hackernews\\logs\\egg-hackernews","encoding":"utf8","env":"local","level":"DEBUG","consoleLevel":"INFO","outputJSON":false,"buffer":false,"appLogName":"egg-hackernews-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"type":"application"}
2017-03-20 18:57:01,615 INFO 4860 [egg-schedule]: register schedule egg-schedule:F:\H5Workstation\diagram-hackernews\node_modules\.2.2.2@egg-logrotator\app\schedule\clean_log.js
2017-03-20 18:57:01,615 INFO 4860 [egg-schedule]: register schedule egg-schedule:F:\H5Workstation\diagram-hackernews\node_modules\.2.2.2@egg-logrotator\app\schedule\rotate_by_file.js
2017-03-20 18:57:01,670 INFO 4860 [egg-static] starting static serve /public/ -> F:\H5Workstation\diagram-hackernews\app\public
2017-03-20 18:57:01,676 INFO 4860 [egg-security] use csrf middleware
2017-03-20 18:57:01,678 INFO 4860 [egg-security] use methodnoallow middleware
2017-03-20 18:57:01,679 INFO 4860 [egg-security] use noopen middleware
2017-03-20 18:57:01,679 INFO 4860 [egg-security] use nosniff middleware
2017-03-20 18:57:01,680 INFO 4860 [egg-security] use xssProtection middleware
2017-03-20 18:57:01,680 INFO 4860 [egg-security] use xframe middleware
2017-03-20 18:57:01,681 INFO 4860 [egg-security] compose 6 middlewares into one security middleware
2017-03-20 18:57:01,702 INFO 4860 [ClusterClient#Watcher] gives up seizing port 58197, and serves as follower client.
2017-03-20 18:57:01,711 INFO 4860 [Follower#Watcher] register to channel: Watcher success
2017-03-20 18:57:01,712 INFO 4860 [egg-watcher:app] watcher start success

**Comment by jamesliauw** [comment]
有没有办法通过配置，设置不监控某个目录文件理更改而重启WORKER，即不reload?

[agent:development] reload worker because F:\H5Workstation\diagram-hackernews\app\client\view\news\news.html change

**Comment by atian25** [comment]
https://github.com/eggjs/egg-development/blob/master/config/config.default.js

配置下即可

**Comment by jamesliauw** [comment]
只要reload,必报ERROR 5984 nodejs.ECONNRESETError: read ECONNRESET

**Comment by jamesliauw** [comment]
解决，不能引入前端文件到APP，和加载debug依赖。

**Comment by atian25** [comment]
啥叫引入前端文件到 APP ?

**Comment by jamesliauw** [comment]
就是app目录把存放的前端源文件移走，WIN下就不报了，MAC下是不移也不会报的。

**Comment by atian25** [comment]
为什么会放前端文件到 app 下呢? 前端文件编译后放到 public 就好了.

**Comment by jamesliauw** [comment]
放错目录，这个是之前我没意识到的原因。其实这个问题是WIN下通病，只要有文件更改，重启WORKER的时候都会异常退出。
https://github.com/eggjs/egg/issues/432
跟这个问题一样的，希望你们能快速修好了。并且麻烦附上实际的更新方法。

**Comment by jamesliauw** [comment]
同样的代码，我在MAC上跑是没问题的，但有些人用WIN没办法统一硬件。

**Comment by ngot** [comment]
环境不同，要加 CI

**Comment by sasbsd** [comment]
我的也是这个问题
