### ISSUE TITLE
cookies设置encrypt

### ISSUE THREAD

**Issue by spiroo** [eggjs/egg#613]
* **Node Version**: 6.9.2
* **Egg Version**: 2.3.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows10

在保存cookies时，设置encrypt: true，
```
          const minute = 7 * 24 * 60 * 60 * 1000;
          const options = {
            maxAge: minute,
            httpOnly: true, // 默认就是 true
            encrypt: true, // 加密传输
          }
          this.ctx.cookies.set('loginUserName', query.loginName, options);
          this.ctx.cookies.set('loginUserPwd', query.userPwd, options);
```
报以下错误：
```
ejs.TypeError: Cipher data must be a string or a buffer
    at TypeError (native)
    at Cipher.update (crypto.js:144:26)
    at crypt (G:\project\WisdomCampusEntrance\node_modules\egg-cookies\lib\keygrip.js:78:23)
    at Keygrip.encrypt (G:\project\WisdomCampusEntrance\node_modules\egg-cookies\lib\keygrip.js:29:12)
    at Cookies.set (G:\project\WisdomCampusEntrance\node_modules\egg-cookies\lib\cookies.js:101:55)
    at HomeController.userLogin (G:\project\WisdomCampusEntrance\app\controller\home.js:59:28)
    at next (native)
    at onFulfilled (G:\project\WisdomCampusEntrance\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by dead-horse** [comment]
query.loginName 或者 query.userPwd 是 undefined
