### ISSUE TITLE
在使用 this.ctx.curl() 进行方法扩展时遇到的 this 指向问题

### ISSUE THREAD

**Issue by Carrotzpc** [eggjs/egg#615]
* **Node Version**: v6.9.5
* **Egg Version**: 1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Windows 10

最近有一个业务场景需要多次发送请求，直到请求成功或者达到最大请求次数，看了 egg [框架扩展](https://eggjs.org/zh-cn/basics/extend.html) 相关文档后，写了一个简单的 `context` 扩展：
```js
// app/extend/context.js
'use strict'

module.exports = {
  fetch(url, options) {
    const method = 'fetch'
    const { max } = this.app.config.fetch
    let n = 0
    const _curl = () => {
      n++
      return this.curl(url, options).then(res => {
        const { status, data } = res
        if (status >= 300) {
          this.logger.error(method, data)
          throw new Error(`${method} failed`)
        }
        return res
      }).catch(error => {
        if (n < max) {
          return _curl()
        }
        throw error
      })
    }
    return _curl()
  },
}
```
```js
// app/service/chrome/ext.js
'use strict'

module.exports = app => {
  class Ext extends app.Service {
    * getQuery() {
      const { url } = app.config.chromeExt
      const { fetch } = this.ctx
      return fetch(url, {
        dataType: 'text',
        timeout: '10000',
      })
    }
  }
  return Ext
}
```
在 service 中调用时发生错误：
```
2017-03-22 15:02:00,887 INFO 20120 [master] App Worker#1:20312 start, state: none, current workers: ["1"]
2017-03-22 15:02:01,692 ERROR 20312 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'app' of undefined
    at fetch (app\extend\context.js:6:25)
    at Ext.getQuery (app\service\chrome\ext.js:8:14)
    at next (native)
    at onFulfilled (node_modules\co\index.js:65:19)
    at node_modules\co\index.js:54:5
    at Object.co (node_modules\co\index.js:50:10)
    at Object.toPromise (node_modules\co\index.js:118:63)
    at next (node_modules\co\index.js:99:29)
    at onFulfilled (node_modules\co\index.js:69:7)
    at node_modules\co\index.js:54:5
pid: 20312
```
改变 `app/service/chrome/ext.js` 调用 `fetch` 的方式为 `return this.ctx.fetch(url ...` 后结果正常，对 egg 的 loader 还不是很熟悉，所以请教一下应该如何编写扩展才能避免此类问题？

**Comment by ngot** [comment]
```js
const { fetch } = this.ctx
fetch();
```

```js
this.ctx.fetch()
```

建议研究下这个JS语法上的区别。

Demo:

```js

var a = {
  v : 1,
  f() {
       console.log(this.v)
   }
}

a.f();

var f = a.f()
f();
```

**Comment by Carrotzpc** [comment]
想错了，我还以为 `this.ctx.curl()` 支持这种方式的调用：
```js
const { curl } = this.ctx
curl()
```
我看我扩展的 `fetch` 方法不支持，还以为自己哪里写的不对。。。
