### ISSUE TITLE
egg-sequelize 使用报错

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#645]
使用egg-sequelize 进行表关联时报错
官方例子：
```
module.exports = app => {
  const { STRING, INTEGER, DATE } = app.Sequelize;

  return app.model.define('Post', {
    name: STRING(30),
    user_id: INTEGER,
    created_at: DATE,
    updated_at: DATE,
  }, {
    classMethods: {
      associate() {
        app.model.Post.belongsTo(app.model.User, { as: 'user' });
      }
    }
  });
};
```

一直报如下错误：
```
TypeError: Cannot read property 'belongsTo' of undefined
```

求解，不然都不知道把表关联放在哪里了

**Comment by dead-horse** [comment]
堆栈给一下，不要只给错误 message

**Comment by callmesoul** [comment]
/Users/benz/egg-example/node_modules/egg/lib/application.js:38
      throw e;
      ^

TypeError: Cannot read property 'belongsTo' of undefined
    at Model.associate (/Users/benz/egg-example/app/model/article.js:15:31)
    at loadModel (/Users/benz/egg-example/node_modules/egg-sequelize/lib/loader.js:66:16)
    at module.exports.app (/Users/benz/egg-example/node_modules/egg-sequelize/lib/loader.js:39:3)
    at module.exports.app (/Users/benz/egg-example/node_modules/egg-sequelize/app.js:4:26)
    at AppWorkerLoader.loadFile (/Users/benz/egg-example/node_modules/egg-core/lib/loader/egg_loader.js:259:34)
    at getLoadUnits.forEach.unit (/Users/benz/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:29)
    at Array.forEach (native)
    at AppWorkerLoader.loadCustomApp (/Users/benz/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:8)
    at AppWorkerLoader.load (/Users/benz/egg-example/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
    at new Application (/Users/benz/egg-example/node_modules/egg/lib/application.js:34:19)
    at Object.<anonymous> (/Users/benz/egg-example/node_modules/egg-cluster/lib/app_worker.js:12:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] worker:22836 disconnect (suicide: false, state: disconnected, isDead: false)
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] don't fork new work (refork: false)
2017-03-25 12:58:13,515 INFO 22364 [master] App Worker#30:22836 disconnect, suicide: false, state: disconnected, current workers: ["29","30"]
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] worker:22836 exit (code: 1, suicide: false, state: dead, isDead: true, isExpected: true)

**Comment by callmesoul** [comment]
@dead-horse 
`
/Users/benz/egg-example/node_modules/egg/lib/application.js:38
      throw e;
      ^

TypeError: Cannot read property 'belongsTo' of undefined
    at Model.associate (/Users/benz/egg-example/app/model/article.js:15:31)
    at loadModel (/Users/benz/egg-example/node_modules/egg-sequelize/lib/loader.js:66:16)
    at module.exports.app (/Users/benz/egg-example/node_modules/egg-sequelize/lib/loader.js:39:3)
    at module.exports.app (/Users/benz/egg-example/node_modules/egg-sequelize/app.js:4:26)
    at AppWorkerLoader.loadFile (/Users/benz/egg-example/node_modules/egg-core/lib/loader/egg_loader.js:259:34)
    at getLoadUnits.forEach.unit (/Users/benz/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:29)
    at Array.forEach (native)
    at AppWorkerLoader.loadCustomApp (/Users/benz/egg-example/node_modules/egg-core/lib/loader/mixin/custom.js:25:8)
    at AppWorkerLoader.load (/Users/benz/egg-example/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
    at new Application (/Users/benz/egg-example/node_modules/egg/lib/application.js:34:19)
    at Object.<anonymous> (/Users/benz/egg-example/node_modules/egg-cluster/lib/app_worker.js:12:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] worker:22836 disconnect (suicide: false, state: disconnected, isDead: false)
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] don't fork new work (refork: false)
2017-03-25 12:58:13,515 INFO 22364 [master] App Worker#30:22836 disconnect, suicide: false, state: disconnected, current workers: ["29","30"]
[Sat Mar 25 2017 12:58:13 GMT+0800 (CST)] [cfork:master:22364] worker:22836 exit (code: 1, suicide: false, state: dead, isDead: true, isExpected: true)

`

**Comment by callmesoul** [comment]
自己问题

**Comment by atian25** [comment]
最好描述下原因，方便后人

**Comment by callmesoul** [comment]
1.文件名要跟模型名必须一致啊，文件名小写，模型名首字母是大写。
2.模型最后加上.sync()可以同步到数据库。但是控制器获取数据报错。所以同步完要删了模型得.sync()，具体原型不大清楚。
感觉可以一次把所有模型同步到数据库，但是不知道写再哪里。有人知道得话告诉下！
1. File name to be consistent with the model name ah, the file name lowercase, the first letter of the model name is capital.
2. The model finally adds .sync () to be synchronized to the database. But the controller gets the data error. So the synchronization finished to delete the model was. Sync (), the specific prototype is not clear.
Feeling can synchronize all the models to the database at once, but do not know where to write again. Somebody knows the words tell!
