### ISSUE TITLE
改动plugin.js 后加载的时候加报错

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#654]
```
2017-03-26 23:34:01,525 WARN 4460 [agent:development] reload worker because C:\example\config\plugin.js change
2017-03-26 23:34:01,551 INFO 16264 [master] reload workers...
2017-03-26 23:34:01,572 INFO 16264 [master] App Worker#2:1416 start, state: none, current workers: ["1","2"]
2017-03-26 23:34:01,751 WARN 4460 [agent:development] reload worker because C:\example\config\plugin.js change
2017-03-26 23:34:01,755 INFO 16264 [master] reload workers...
2017-03-26 23:34:03,791 WARN 16264 [master] App Worker#2:1416 started at 7001, remain 0 (11704ms)
2017-03-26 23:34:03,792 INFO 16264 [master] App Worker#3:3748 start, state: none, current workers: ["2","3"]
[Sun Mar 26 2017 23:34:03 GMT+0800 (中国标准时间)] [cfork:master:16264] worker:16432 disconnect (suicide: true, state: disconnected, isDead: false)
[Sun Mar 26 2017 23:34:03 GMT+0800 (中国标准时间)] [cfork:master:16264] don't fork new work (refork: false)
2017-03-26 23:34:03,805 INFO 16264 [master] App Worker#1:16432 disconnect, suicide: true, state: disconnected, current workers: ["2","3"]
(node:16264) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2017-03-26 23:34:03,815 ERROR 4460 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4460
hostname: DESKTOP-OMTCPHI

```

**Comment by popomore** [comment]
关注下 https://github.com/eggjs/egg/issues/432
