### ISSUE TITLE
请教用async.map方法的话返回不了回调结果是怎么回事呢

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#700]
async.map(arr,function(item,cb){
  dosomething
 cb(err,item)
},
function(err,results){
  ctx.body = results;
})

这里不等待 map的回调就返回了404是为什么呢

**Comment by atian25** [comment]
koa 不是 express，去看看 koa 的洋葱模型。

另外，有了 generator 和 async await，为什么还要用 async.js 呢？

**Comment by JacksonTian** [comment]
```js
function map(arr, callback) {
  return new Promise((resolve, reject) => {
    async.map(arr, callback, (err, results) => {
      if (err) {
        return reject(err);
      }
      resolve(results);
    });
  });
}


var results = yield map(arr, function(item,cb){
  // dosomething
  cb(err,item);
});

ctx.body = results;
```

不谢。

**Comment by buzai** [comment]
@atian25 @JacksonTian 谢谢了

**Comment by JacksonTian** [comment]
更简单的：

```js
ctx.body = yield Promise.all(arr.map((item) => {
  return new Promise((resolve, reject) => {
    // dosomething
    if (err) {
      return reject(err);
    }

    resolve(item);
  });
}));
```

**Comment by buzai** [comment]
at Promise (/home/someuser/study/egg-serve-vue-view/app/controller/trend.js:75:15)
at ctx.body.Promise.all.addresslists.map (/home/someuser/study/egg-serve-vue-view/app/controller/trend.js:73:16)
at Array.map (native)
at trendController.getchanglist (/home/someuser/study/egg-serve-vue-view/app/controller/trend.js:72:54)
at getchanglist.next (<anonymous>)
at onFulfilled (/home/someuser/study/egg-serve-vue-view/node_modules/.4.6.0@co/index.js:65:19)
at newTickHandler (/home/someuser/study/egg-serve-vue-view/node_modules/.0.5.5@mpromise/lib/promise.js:234:18)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

pid: 20301

@JacksonTian 你好为啥会出现这个错呢

**Comment by atian25** [comment]
@buzai 这个属于 Promise 的问题了，去看看相关的教程吧。

**Comment by atian25** [comment]
async 真的没必要用了，用 promise + generator + async await 就 ok 了。

实在要用 utils 的话，考虑 http://fitzgen.github.io/wu.js/

**Comment by buzai** [comment]
@atian25 谢谢因为用了好久express 这些都没怎么用过，我去补补，万分感谢

**Comment by ngot** [comment]
感觉穿越了

**Comment by buzai** [comment]
@ngot 让您见笑了
