### ISSUE TITLE
egg-view-react 的npm代码无法正常运行

### ISSUE THREAD

**Issue by Edward67** [eggjs/egg#717]
1.首先有报错
```bash
/Users/edward67/Desktop/work/test/egg-example/node_modules/egg-view-react/config/config.default.js:8
exports.view-react = {
^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.loadFile (/Users/edward67/Desktop/work/test/egg-example/node_modules/egg/node_modules/egg-core/lib/utils/index.js:12:19)
```
如图所示，来自于egg-view-react

2.检查到依赖中没有`lib`文件夹（即核心代码）

* **Node Version**: 6.10.2
* **Egg Version**: 1.0.0
* **Plugin Name**: egg-view-react
* **Plugin Version**: 0.0.1
* **Platform**: mac

**Comment by atian25** [comment]
升级你的 egg-view-react 版本

**Comment by Edward67** [comment]
```base
ali-e0accb666494:egg-example edward67$ npm info egg-view-react
 
{ name: 'egg-view-react',
  description: 'egg view plugin for react',
  'dist-tags': { latest: '0.0.1' },
  versions: [ '0.0.1' ],
  maintainers: [ 'atian25 <atian25@qq.com>' ],
  time: 
   { modified: '2017-01-24T08:42:57.755Z',
     created: '2017-01-20T08:47:30.140Z',
     '0.0.1': '2017-01-20T08:47:30.140Z' },
  homepage: 'https://github.com/eggjs/egg-view-react#readme',
  keywords: [ 'egg', 'eggPlugin', 'egg-plugin', 'egg-plugin-view' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/eggjs/egg-view-react.git' },
  author: 'TZ <atian25@qq.com>',
  bugs: { url: 'https://github.com/eggjs/egg/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '0.0.1',
  eggPlugin: 'view',
  dependencies: {},
  devDependencies: 
   { autod: '^2.7.1',
     egg: '^0.7.0',
     'egg-bin': '^1.10.0',
     'egg-ci': '^1.1.0',
     'egg-mock': '^2.0.0',
     eslint: '^3.13.1',
     'eslint-config-egg': '^3.2.0',
     supertest: '^2.0.1',
     'webstorm-disable-index': '^1.1.2' },
  engines: { node: '>=6.0.0' },
  scripts: 
   { test: 'npm run lint -- --fix && npm run test-local',
     'test-local': 'egg-bin test',
     cov: 'egg-bin cov',
     lint: 'eslint .',
     ci: 'npm run lint && npm run cov',
     autod: 'autod' },
  files: [ 'index.js', 'app.js', 'agent.js', 'config', 'app', 'lib' ],
  ci: { version: '6, 7' },
  boilerplate: 
   { name: 'egg-boilerplate-plugin',
     version: '1.7.0',
     description: 'boilerplate for egg plugin',
     repository: 
      { type: 'git',
        url: 'git@github.com:eggjs/egg-boilerplate-plugin.git' },
     homepage: 'https://github.com/eggjs/egg-boilerplate-plugin' },
  dist: 
   { shasum: 'badca71bbf20ed19538ba86728668461039c08af',
     tarball: 'https://registry.npmjs.org/egg-view-react/-/egg-view-react-0.0.1.tgz' },
  directories: {} }

```

npm上只有这一个版本

**Comment by atian25** [comment]
额....

**Comment by atian25** [comment]
@jtyjty99999 egg-view-react 这个还没改完发版本么?

**Comment by popomore** [comment]
这个还没发布呢

**Comment by popomore** [comment]
还是关了，等 @jtyjty99999 完成就可以使用

**Comment by Runrioter** [comment]
@Edward67 如果你着急用的话，可以先 `npm i eggjs/egg-view-react -S`

**Comment by atian25** [comment]
master 分支的代码，用不了，不是 egg 1.0 的 view 模式。

ping @jtyjty99999 啥时有空先适配下发个版本？

**Comment by Edward67** [comment]
ok，不急，只是先试试。

**Comment by jtyjty99999** [comment]
@atian25 今天抽时间发掉，最近太忙了@atian25 今天抽时间发掉，最近太忙了

**Comment by chengnuo** [comment]
egg-view-react 怎么配页面啊。

**Comment by atian25** [comment]
ping @jtyjty99999

**Comment by chengnuo** [comment]
@jtyjty99999 我多次配置 egg-view-react 都不成功啊。是我召唤问题，还是稳定问题。

**Comment by Runrioter** [comment]
这个项目还没有完成 不能用 @chengnuo

**Comment by chengnuo** [comment]
@Runrioter 谢谢老哥，那我先去搞别的模块，看到react，很欢乐啊。

**Comment by hubcarl** [comment]
@Runrioter @Edward67    React 服务端渲染：https://github.com/hubcarl/egg-react-webpack-boilerplate  可以作为参考

使用 https://github.com/eggjs/egg-view-react  和 https://github.com/hubcarl/egg-view-react-ssr
