### ISSUE TITLE
求解：egg-socket.io 关于namespaces 的测试用例的问题

### ISSUE THREAD

**Issue by joehecn** [eggjs/egg#752]
Node Version: 7
Egg Version: 1.1.0
Plugin Name: egg-socket.io
Plugin Version: 1.2.0
Platform: Mac OS

---
### 问题： 为什么当命名空间为` '/'`根目录时，测试用例通过，但是命名空间为`'/nspzx'`时，测试失败

``` javascript
// config/config.default.js
...
exports.io = {
  '/': {
    connectionMiddleware: [],
    packetMiddleware: []
  },
  '/nspzx': {
    connectionMiddleware: [],
    packetMiddleware: []
  }
}
...

// app/router.js
...
module.exports = app => {
  app.get('/', 'home')

  app.io.route('nspzx', app.io.controllers.nspzx)
  app.io.of('/nspzx').route('nspzx', app.io.controllers.nspzx)
}
...

// app/io/controller/nspzx.js
...
module.exports = () => {
  return function* () {
    const message = this.args[0]
    this.socket.emit('nspzx-res', message)
  }
}
...
```
测试成功的用例：
``` javascript
// test/app/io/controller/nspzx.test.js
...
describe('test/app/io/controller/nspzx.test.js', () => {

  afterEach(mock.restore)

  it('should ok', done => {
    const app = mock.cluster()

    app.ready().then(() => {
      const socket = ioc('http://localhost:17001')
      socket.on('connect', () => socket.emit('nspzx', 'hello1'))
      socket.on('nspzx-res', msg => {
        assert(msg === 'hello1')
        socket.close()
      })
      socket.on('disconnect', () => app.close().then(done, done))
    })
  })
})
...
```
测试成功
``` bash
test/app/io/controller/nspzx.test.js
    ✓ should ok (911ms)
```
测试失败的用例，就是改了一句：`const socket = ioc('http://localhost:17001/nspzx')`，其它地方完全一样：
``` javascript
// test/app/io/controller/nspzx.test.js
...
describe('test/app/io/controller/nspzx.test.js', () => {

  afterEach(mock.restore)

  it('should ok', done => {
    const app = mock.cluster()

    app.ready().then(() => {
      const socket = ioc('http://localhost:17001/nspzx')
      socket.on('connect', () => socket.emit('nspzx', 'hello1'))
      socket.on('nspzx-res', msg => {
        assert(msg === 'hello1')
        socket.close()
      })
      socket.on('disconnect', () => app.close().then(done, done))
    })
  })
})
...
```
测试失败
``` bash
1) test/app/io/controller/nspzx.test.js should ok:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

⚠️ run command  got error: /Users/hemiao/egg/exam/socketio/node_modules/mocha/bin/_mocha --require=/Users/hemiao/egg/exam/socketio/node_modules/co-mocha/
lib/co-mocha.js,--require=/Users/hemiao/egg/exam/socketio/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=30000,test/app/control
ler/home.test.js,test/app/io/controller/nspzx.test.js exit with code 1
Error: /Users/hemiao/egg/exam/socketio/node_modules/mocha/bin/_mocha --require=/Users/hemiao/egg/exam/socketio/node_modules/co-mocha/lib/co-mocha.js,--r
equire=/Users/hemiao/egg/exam/socketio/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=30000,test/app/controller/home.test.js,te
st/app/io/controller/nspzx.test.js exit with code 1
    at ChildProcess.proc.once.code (/Users/hemiao/egg/exam/socketio/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/hemiao/.nvm/versions/node/v7.7.4/bin/node" "/Users/hemiao/.nvm/versions/node/v7.7.4/bin/npm" "run" "test-local"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! socketio@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketio@1.0.0 test-local script 'egg-bin test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socketio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     egg-bin test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socketio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socketio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hemiao/egg/exam/socketio/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by ngot** [comment]
我来看看

**Comment by ngot** [comment]
配置文件写错了，这么写：

```js
exports.io = {
  namespace: {
    '/nspzx': {
      connectionMiddleware: [],
      packetMiddleware: [],
    },
  },
};
```

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io#configuration
