### ISSUE TITLE
how to stop egg application in prod env

### ISSUE THREAD

**Issue by inRush** [eggjs/egg#765]
* **Node Version**: 7.9
* **Egg Version**:1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Linux

我按照官网中的生产环境中执行
EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log
在我把上面开启的进程给关了以后 stderr.log不断打印下面的内容

[Mon Apr 17 2017 13:56:14 GMT+0800 (CST)][sendmessage] WARN pid#7431 channel closed, nothing send
stack: Error: channel closed
    at send (/home/hwj/WORK/WorkSpace/Projects/imoocCrawler-Egg/test-demo/node_modules/.1.1.0@sendmessage/index.js:44:13)
    at Messenger.sendTo (/home/hwj/WORK/WorkSpace/Projects/imoocCrawler-Egg/test-demo/node_modules/.1.1.0@egg/lib/core/messenger.js:46:5)
    at Messenger.sendRandom (/home/hwj/WORK/WorkSpace/Projects/imoocCrawler-Egg/test-demo/node_modules/.1.1.0@egg/lib/core/messenger.js:66:10)
    at sendMessage (/home/hwj/WORK/WorkSpace/Projects/imoocCrawler-Egg/test-demo/node_modules/.2.3.0@egg-schedule/agent.js:57:26)
    at Timeout.one [as _onTimeout] (/home/hwj/WORK/WorkSpace/Projects/imoocCrawler-Egg/test-demo/node_modules/.2.3.0@egg-schedule/agent.js:36:11)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by dead-horse** [comment]
进程间通信的信道被关闭了。你看看是不是有进程退出了。

**Comment by inRush** [comment]
我在其他的issues找到问题了，我是直接kill -9 master进程，导致agent，worker进程没有关闭，所以就会出现这个问题
我本来想在生产环境下重启服务器的，但是找不到方法，只能kill主进程，这个框架没有生产环境重启服务器的方法的么？？？

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-scripts/pull/1/files  /cc @atian25

**Comment by atian25** [comment]
争取本周搞完... 有点忙最近。

@inRush 永远不要用 `kill -9` ，直接 kill master，然后它会优雅退出，自己杀掉 agent 和 worker

**Comment by inRush** [comment]
@atian25 嗯嗯，之前习惯直接kill -9 了，这是个很大的教训
这个issues结束了
