### ISSUE TITLE
用typescript开发egg的controller，路由不能访问controller父类里的方法

### ISSUE THREAD

**Issue by lnngle** [eggjs/egg#793]
router.ts:
```
import { RouterConsts } from './router.consts';
import { Application } from 'egg';
module.exports = (app: Application) => {
  app.get(RouterConsts.eavPathPrefix + RouterConsts.modulePath.attribute, 'eav.attribute.getByCode');
};
```
controller父类：
```
import { Controller, Context } from 'egg';
export abstract class BaseController<s extends BaseService> extends Controller {
  constructor(ctx: Context) {
    super(ctx);
  }
  getByCode() {
    this.ctx.body = '';
  }
}
```

controller类：
```
import { AttributeService } from './../../service/eav/attribute';
import { BaseController } from '../base-controller';
import { Context } from 'egg';
export default class AttributeController extends BaseController<AttributeService> {
  constructor(ctx: Context) {
    super(ctx);
  }

  public getAll() {
    this.ctx.body = 'ok';
  }
}
```

执行测试用例时，AttributeController的方法可以访问，但是其继承父类里的方法都不能访问，报错：
```
 1) test/app/controller/eav/attribute.test.js "before all" hook:
     Error: controller 'eav.attribute.getByCode' not exists
      at actions.forEach.key (node_modules/egg-core/lib/utils/router.js:297:23)
      at Array.forEach (native)
      at convertMiddlewares (node_modules/egg-core/lib/utils/router.js:295:13)
      at Router.(anonymous function) [as get] (node_modules/egg-core/lib/utils/router.js:73:38)
      at MeesengerApplication.EggCore.(anonymous function) [as get] (node_modules/egg-core/lib/egg.js:338:24)
      at module.exports (app/router.ts:4:7)
      at AppWorkerLoader.loadFile (node_modules/egg-core/lib/loader/egg_loader.js:259:34)
      at AppWorkerLoader.loadRouter (node_modules/egg-core/lib/loader/mixin/router.js:15:10)
      at AppWorkerLoader.load (node_modules/egg/lib/loader/app_worker_loader.js:41:10)
      at MeesengerApplication.Application (node_modules/egg/lib/application.js:34:19)
      at MeesengerApplication (node_modules/egg-mock/lib/app.js:230:7)
      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:68:29)
      at EventEmitter.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
如果把getByCode方法移到AttributeController里则用例通过

**Comment by shepherdwind** [comment]
我先试下这种方式

**Comment by shepherdwind** [comment]
我这边 controller 继承应该是没问题的，我这样改的

新增 `app/baseController.ts`

```ts
import { Controller } from 'egg';

export abstract class BaseController extends Controller {
  getByCode() {
    this.ctx.body = '';
    return this.ctx.request.headers;
  }
}
```

然后修改 Controller 文件  `app/controller/news.ts`，下面是 diff

```diff
@@ -1,4 +1,4 @@
-import { Controller } from 'egg';
+import { BaseController } from '../baseController';

 declare module 'egg' {
   export interface Controllers {
@@ -6,11 +6,12 @@ declare module 'egg' {
   }
 }

-export default class NewsController extends Controller {
+export default class NewsController extends BaseController {
   public async list() {
     const { ctx, app } = this;
     const pageSize = app.config.news.pageSize;
     const page = parseInt(ctx.query.page, 10) || 1;
+    console.log(this.getByCode());
```

然后执行 `npm run tsc && npm test` ，终端正常调用 `getByCode` 方法。

@lnngle 你要不改下我那个分支，重现一下的场景。或者给一个完整的 demo 。
