### ISSUE TITLE
egg-redis app.redis.set is not a function

### ISSUE THREAD

**Issue by Xib1uvXi** [eggjs/egg#800]
* **Node Version**:  v7.8.0
* **Egg Version**:  v1.1.0
* **Plugin Name**:  egg-redis
* **Plugin Version**:  v1.0.1
* **OS**:  OSX 10.12

  
  
#### config/plugin.js  
````
'use strict';

// had enabled by egg
// exports.static = true;

exports.redis = {
  enable: true,
  package: 'egg-redis',
};
````

#### config/config.default.js
````
'use strict';

module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1493004692975_1601';

  return config;
};

exports.redis = {
  client: {
    host: '127.0.0.1',
    port: 6379,
    password: '',
    db: '0',
  },
  agent: true,
};
````  

#### package.json
````
....
"dependencies": {
    "egg": "^1.1.0",
    "egg-redis": "^1.0.1"
  },
  "devDependencies": {
    "autod": "^2.8.0",
    "egg-bin": "^3.3.0",
    "egg-ci": "^1.6.0",
    "egg-mock": "^3.4.0",
    "eslint": "^3.19.0",
    "eslint-config-egg": "^3.2.0",
    "webstorm-disable-index": "^1.1.2"
  },
....
````

#### controller/home.js
````
'use strict';

module.exports = app => {
  class HomeController extends app.Controller {
    * index() {
      // this.ctx.body = 'hi, xi';
      const { ctx, app } = this;
      // console.log(app.redis);
      yield app.redis.set('test_key', 'test_result');
      ctx.body = yield app.redis.get('test_key');
    }
  }
  return HomeController;
};
````

#### test/app/controller/home.test.js
````
.....
 it('should assert', () => {
    const pkg = require('../../../package.json');
    assert(app.config.keys.startsWith(pkg.name));
  });

  it('should GET /', () => {
    return app.httpRequest()
      .get('/')
      .expect('test_result')
      .expect(200);
.....
````

####  当我在命令行执行:
````
npm run test
````

#### 会抛出nodejs.TypeError  ：app.redis.set is not a function 
````
2017-04-24 14:47:28,158 ERROR 4347 [-/127.0.0.1/-/7ms GET /] nodejs.TypeError: app.redis.set is not a function
    at HomeController.index (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/app/controller/home.js:9:23)
    at index.next (<anonymous>)
    at onFulfilled (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:118:63)
    at next (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:69:7)
    at /Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/xib/Desktop/NodeJsWorkSpaces/N7/sf_sys/node_modules/._co@4.6.0@co/index.js:118:63)
....
````

是我哪里配置错了吗？

**Comment by atian25** [comment]
home.test.js 贴下 before

**Comment by Xib1uvXi** [comment]
@atian25 
#### home.test.js
````
'use strict';
const mm = require('egg-mock');
const assert = require('assert');

describe('test/app/controller/home.test.js', () => {
  let app;
  before(() => {
    app = mm.app();
    return app.ready();
  });

  afterEach(mm.restore);
  after(() => app.close());

  it('should assert', () => {
    const pkg = require('../../../package.json');
    assert(app.config.keys.startsWith(pkg.name));
  });

  it('should GET /', () => {
    return app.httpRequest()
      .get('/')
      .expect('test_result')
      .expect(200);
  });
});
````

**Comment by dead-horse** [comment]
这段配置有问题，先去了解 module.exports 和 exports 的关系

```js
'use strict';

module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1493004692975_1601';

  return config;
};

exports.redis = {
  client: {
    host: '127.0.0.1',
    port: 6379,
    password: '',
    db: '0',
  },
  agent: true,
};
```

**Comment by jtyjty99999** [comment]
又是这个问题－ －

**Comment by atian25** [comment]
额... 第 7 次

**Comment by ngot** [comment]
感觉，这种问题真是...

**Comment by ngot** [comment]
感觉这个需要加到QA第一个了

**Comment by atian25** [comment]
@ngot 加吧加吧 -.-
