### ISSUE TITLE
Agent worker died, but can't find any useful debug information. 

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#825]
Here is the log
```
2017-04-29 18:33:28,448 WARN 38061 [ClusterClient#Watcher] follower closed, and try to init it again
2017-04-29 18:33:28,451 ERROR 38059 nodejs.AgentWorkerDiedError: [master] Agent Worker 38060 died (code: null, signal: SIGABRT)
    at Master.onAgentExit (/Users/abuladabula/xxxxx/node_modules/egg-cluster/lib/master.js:231:17)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:188:7)
    at Messenger.sendToMaster (/Users/abuladabula/xxxxx/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/abuladabula/xxxxx/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at ChildProcess.agentWorker.once (/Users/abuladabula/xxxxx/node_modules/egg-cluster/lib/master.js:147:22)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
name: 'AgentWorkerDiedError'
pid: 38059
hostname: server.zitao.org

2017-04-29 18:33:29,456 INFO 38059 [master] Agent Worker restarting
2017-04-29 18:33:29,461 INFO 38059 [master] Agent Worker:23896 start with ["{\"framework\":\"/Users/abuladabula/xxxxx/node_modules/egg\",\"baseDir\":\"/Users/abuladabula/xxxxx\",\"port\":7001,\"workers\":1,\"plugins\":null,\"https\":false,\"key\":\"\",\"cert\":\"\",\"clusterPort\":62468}"]
ready to rock n roll
```

Agent worker died, but I can't tell what's wrong from the log information above, any tips on how to debug it? It died randomly in around 1 hour. 

Also, I have some initialization code in   agent.messenger.on('egg-ready', () => {}). After the agent died, it did restart, but the egg-ready event will not be fired since egg is already started a while ago. Is there an 'agent' restart event I can use? or any other solution to it.

**Comment by atian25** [comment]
any error log at `common-error.log`？

and did you have any schedule job？

**Comment by popomore** [comment]
See singal SIGABRT, maybe you have memory issue.

**Comment by caoer** [comment]
@atian25 @popomore found the issue in `common-error.log`. It appears that is an unhandled JSON.parse() error. Thanks for pointing it out!

Do you guys have any notes on my second question? By reading the documentation, I understand that the agent worker is mean to be running stable, if an error occurs, manual lookup should be involved. However, does it mean that agent should never be recovered automatically? If it can be recovered, how should I organize the code to do that?

**Comment by popomore** [comment]
@caoer agent will be restarted if it had exited, you can see [the code in egg-cluster](https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L71).

**Comment by JayenLee** [comment]
我也出现这个问题common-error.log
```
2019-09-06 09:02:01,748 ERROR 77 [-/127.0.0.1/-/0ms GET /] nodejs.EFAULTError: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at loadFile (/www/node_modules/koa-static-cache/index.js:196:19)
    at /www/node_modules/koa-static-cache/index.js:33:7
    at Array.forEach (<anonymous>)
    at staticCache (/www/node_modules/koa-static-cache/index.js:32:37)
    at basicRouterRegister (/www/node_modules/egg-doc/lib/router/index.js:23:13)
    at module.exports.swaggerInit.app (/www/node_modules/egg-doc/lib/index.js:18:5)
    at app.beforeStart (/www/node_modules/egg-doc/app.js:8:5)
    at Object.callFn (/www/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/www/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by shotforsky** [comment]
Same error for me, switching to a higher version of node/npm worked for me!

Error:
![image](https://user-images.githubusercontent.com/14038117/71238916-39a1b700-2340-11ea-82d3-397ddc4c6223.png)

Error versions:
* node version v8.9.4
* egg version 2.24.0

After switching to a higher version it works!

Working versions:
* node version v10.13.0
* npm version 6.4.1

**Comment by atian25** [comment]
> 我也出现这个问题common-error.log
> 
> ```
> 2019-09-06 09:02:01,748 ERROR 77 [-/127.0.0.1/-/0ms GET /] nodejs.EFAULTError: EFAULT: bad address in system call argument, read
>     at Object.readSync (fs.js:493:3)
>     at tryReadSync (fs.js:332:20)
>     at Object.readFileSync (fs.js:361:19)
>     at loadFile (/www/node_modules/koa-static-cache/index.js:196:19)
>     at /www/node_modules/koa-static-cache/index.js:33:7
>     at Array.forEach (<anonymous>)
>     at staticCache (/www/node_modules/koa-static-cache/index.js:32:37)
>     at basicRouterRegister (/www/node_modules/egg-doc/lib/router/index.js:23:13)
>     at module.exports.swaggerInit.app (/www/node_modules/egg-doc/lib/index.js:18:5)
>     at app.beforeStart (/www/node_modules/egg-doc/app.js:8:5)
>     at Object.callFn (/www/node_modules/egg-core/lib/utils/index.js:44:42)
>     at process.nextTick (/www/node_modules/egg-core/lib/lifecycle.js:262:13)
>     at process._tickCallback (internal/process/next_tick.js:61:11)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> ```

seems you put too much file at public dir
