### ISSUE TITLE
egg-sequelize 如何使用事务

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#864]
* **Node Version**: 1.2.1
* **Egg Version**: 7.9
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 2.0.2

执行代码
```
const result = yield this.ctx.model.Sequelize.Transaction(function* (t) {
    const order = yield this.ctx.model.Orders.findAll({ transaction: t });
    const user = yield this.ctx.model.user.findAll({ transaction: t });
    return {
      order,
      user,
    };
}, this);
```

报错信息
```
Cannot read property 'QueryGenerator' of undefined
    at Function.Transaction (/Users/TDiDa/ChainService/node_modules/._sequelize@3.30.4@sequelize/lib/transaction.js:24:53)
    at Order.list (/Users/TDiDa/ChainService/app/service/order.js:42:53)
    at list.next (<anonymous>)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)

```
是不是我使用的方式错了，请问下如何使用

**Comment by popomore** [comment]
Transaction 应该不支持 generator function 吧，试试

```js
const t = yield this.ctx.model.Sequelize.Transaction();
try {
  const order = yield this.ctx.model.Orders.findAll({ transaction: t });
  const user = yield this.ctx.model.user.findAll({ transaction: t });
  yield t.commit();
  return {
    order,
    user,
  };
} catch (err) {
  yield t.rollback();  
}
```

**Comment by popomore** [comment]
@huacnlee 事务要不要也在文档上写个例子?

**Comment by huacnlee** [comment]
@popomore 那个我还没用过，需要试试

**Comment by popomore** [comment]
我们也可以包一下 transaction 支持 generator function，这样就可以自动 commit 和 rollback 了。

**Comment by TDiDa** [comment]
@popomore 报错
```
Cannot read property 'dialect' of undefined
    at Function.Transaction (/Users/TDiDa/ChainService/node_modules/._sequelize@3.30.4@sequelize/lib/transaction.js:24:45)
    at Order.list (/Users/TDiDa/ChainService/app/service/order.js:42:48)
    at list.next (<anonymous>)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:118:63)
    at next (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:69:7)
    at /Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:54:5
    at Object.co (/Users/TDiDa/ChainService/node_modules/._co@4.6.0@co/index.js:50:10)
```

**Comment by huacnlee** [comment]
@TDiDa 你 find 方法带 Transaction 干嘛？

**Comment by TDiDa** [comment]
@huacnlee 只是写个例子

**Comment by popomore** [comment]
好像是小写，改了一下

**Comment by popomore** [comment]
还应该暴露 `app.sequelize` 实例

**Comment by huacnlee** [comment]
app.model 就是 Sequelize 的 instance 目前

**Comment by popomore** [comment]
@huacnlee 我说说 sequelize 本身的实例，不是 model 的实例 https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L31

**Comment by huacnlee** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L34

**Comment by popomore** [comment]
我觉得暴露到 app 或 ctx 上没什么不好，放一个 Sequelize 类好像没啥用。

**Comment by iyuq** [comment]
正确的书写方式应该是
```
const t = yield this.ctx.model.transaction();
try {
  const order = yield this.ctx.model.Orders.findAll({ transaction: t });
  const user = yield this.ctx.model.user.findAll({ transaction: t });
  yield t.commit();
  return {
    order,
    user,
  };
} catch (err) {
  yield t.rollback();  
}
```

**Comment by superlbr** [comment]
@iyuq await/async 怎么写法

**Comment by superlbr** [comment]
async/await 写法参考 https://stackoverflow.com/questions/42870374/node-js-7-how-to-use-sequelize-transaction-with-async-await

**Comment by superlbr** [comment]
@shileiyuan sequelize配置项里有一个dialect: 'mysql'，别落下
