### ISSUE TITLE
调试时怎么设置请求无限等待

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#876]
有web请求进入到controller后，这时断点调试，然后一会程序就结束了，应该是有个地方做了超时检测，这个可以设置成无限等待吗，或者在开发环境下无限等待。

**Comment by okoala** [comment]
@a304885433  程序结束是什么意思？

**Comment by atian25** [comment]
你用什么 IDE 调试的？ 我这边 WebStorm 和 VSCode 都能监听不会主动断的。

**Comment by a304885433** [comment]
不好意思，提问不太仔细。调试是用的vscode。
```
2017-05-10 10:05:51,687 ERROR 16476 nodejs.ClusterClientNoResponseError: client no response in 30285ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\git\mab\egg-example\node_modules\.1.6.3@cluster-client\lib\leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 16476
```
看到有个maxIdleTime配置，我还以为是egg里的呢，数据库访问用的 egg-sequelize

**Comment by atian25** [comment]
这个是不关事的， @shaoshuai0102 看看 cluster client 由于断点导致的阻塞超时， 要不要优化下？

**Comment by shaoshuai0102** [comment]
cc @gxcsoccer 

应该是 leader 和 follower 之间心跳监测因为断点超时了。

断点在代码里有标识么？

**Comment by popomore** [comment]
用了 brk 断点？
Shawn <notifications@github.com>于2017年5月10日 周三10:12写道：

**Comment by shaoshuai0102** [comment]
vscode

**Comment by atian25** [comment]
@popomore 不是启动期的，是运行期的。很容易复现

**Comment by shaoshuai0102** [comment]
- 如果断点有标识，判断断点状态不做心跳
- 如果没有标识，local 环境就不做心跳了

@gxcsoccer 没问题吧

**Comment by atian25** [comment]
断点标识指是否有任意一个断点? 这个估计没有吧.

简单的就是判断 `process.debugPort` 存在与否

**Comment by popomore** [comment]
这个一直存在的吧

**Comment by popomore** [comment]
这个还要处理么

**Comment by qiuzhis** [comment]
这个心跳检测可以配置吗？有些跑批任务耗时又耗cpu，不知是否可以配置
