### ISSUE TITLE
生产环境部署失败

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#887]
* **Node Version**: 7.7.1
* **Egg Version**: 1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: centos-release-7-3.1611.el7.centos.x86_64
* **Mini Showcase Repository**:

在本地开发跑 EGG_SERVER_ENV=local egg-bin dev 脚本一切正常可以执行。
可是部署到linux服务器上执行 EGG_SERVER_ENV=prod node dispatch.js 脚本就报错了。以下是报错日志：
![5f15befa-d112-49e2-985b-98bfaf62ed1b](https://cloud.githubusercontent.com/assets/16955472/25928704/3e2298bc-3630-11e7-8124-974094ffa1d1.png)
![77577caf-0e77-4f88-a8b4-7b5e73381c71](https://cloud.githubusercontent.com/assets/16955472/25928708/479f3940-3630-11e7-9fac-0fda3843e936.png)

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'localStart' ]
2 info using npm@4.1.2
3 info using node@v7.7.1
4 verbose run-script [ 'prelocalStart', 'localStart', 'postlocalStart' ]
5 info lifecycle longhubang@1.0.0~prelocalStart: longhubang@1.0.0
6 silly lifecycle longhubang@1.0.0~prelocalStart: no script for prelocalStart, continuing
7 info lifecycle longhubang@1.0.0~localStart: longhubang@1.0.0
8 verbose lifecycle longhubang@1.0.0~localStart: unsafe-perm in lifecycle true
9 verbose lifecycle longhubang@1.0.0~localStart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/honghaiweb/Desktop/Web_Project/duanxianbaba/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/usr/local/mysql/bin
10 verbose lifecycle longhubang@1.0.0~localStart: CWD: /Users/honghaiweb/Desktop/Web_Project/duanxianbaba
11 silly lifecycle longhubang@1.0.0~localStart: Args: [ '-c', 'EGG_SERVER_ENV=prod node dispatch.js' ]
12 silly lifecycle longhubang@1.0.0~localStart: Returned: code: 1  signal: null
13 info lifecycle longhubang@1.0.0~localStart: Failed to exec localStart script
14 verbose stack Error: longhubang@1.0.0 localStart: `EGG_SERVER_ENV=prod node dispatch.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid longhubang@1.0.0
16 verbose cwd /Users/honghaiweb/Desktop/Web_Project/duanxianbaba
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "localStart"
19 error node v7.7.1
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error longhubang@1.0.0 localStart: `EGG_SERVER_ENV=prod node dispatch.js`
22 error Exit status 1
23 error Failed at the longhubang@1.0.0 localStart script 'EGG_SERVER_ENV=prod node dispatch.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the longhubang package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     EGG_SERVER_ENV=prod node dispatch.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs longhubang
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls longhubang
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
请问一下为什么会报这个错，该如何解决？我查了下目前其中一个issue好像跟我描述的情况有点相似：https://github.com/eggjs/egg/issues/445
但是这里并没有提供解决问题的思路或方法，请问这种情况该怎么处理呢？谢谢。

**Comment by atian25** [comment]
本地跑 `EGG_SERVER_ENV=prod node dispatch.js` 呢?

另外，本地先 `rm -rf node_modules & npm i ` 更新下依赖

**Comment by fengmk2** [comment]
你的服务器 7001 端口被占用。。。

![image](https://cloud.githubusercontent.com/assets/156269/25929889/7d8dcd14-3635-11e7-83b8-a45896afcfdf.png)

**Comment by popomore** [comment]
端口被占用。
