### ISSUE TITLE
egg-mock cluster 异常

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#888]
cluster 的 mockRestore 会再次调用服务去关闭，如果写在了 close 后面就会有现在这样的异常，这个可以忽略。

```js
after(() => app.close());
after(mm.restore);
```

附错误日志

```
POST http://127.0.0.1:17003/__egg_mock_call_function error, method: mockRestore, args: []
Error: connect ECONNREFUSED 127.0.0.1:17003
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
      1) "after each" hook: restore for "should handle uncaughtException and log it"


 1) test/lib/application.test.js "after each" hook: restore for "should handle uncaughtException and log it":
     Error: POST http://127.0.0.1:17003/__egg_mock_call_function error, method: mockRestore, args: []
Error: connect ECONNREFUSED 127.0.0.1:17003
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
      at ClusterApplication._callFunctionOnAppWorker (node_modules/_egg-mock@3.6.0@egg-mock/lib/cluster.js:228:13)
      at Proxy.mockProxy (node_modules/_egg-mock@3.6.0@egg-mock/lib/cluster.js:261:18)
      at Function.module.exports.restore (node_modules/_egg-mock@3.6.0@egg-mock/lib/cluster.js:276:16)
      at Context.restore (node_modules/_egg-mock@3.6.0@egg-mock/index.js:19:13)
      at callFn (node_modules/_mocha@3.3.0@mocha/lib/runnable.js:345:21)
      at Hook.Runnable.run (node_modules/_mocha@3.3.0@mocha/lib/runnable.js:337:7)
      at Hook.Runnable.run (node_modules/_co-mocha@1.2.0@co-mocha/lib/co-mocha.js:43:16)
      at next (node_modules/_mocha@3.3.0@mocha/lib/runner.js:309:10)
      at Immediate.<anonymous> (node_modules/_mocha@3.3.0@mocha/lib/runner.js:339:5)

```

**Comment by popomore** [comment]
现在会导致 egg 用例挂掉

https://travis-ci.org/eggjs/egg/jobs/230864583
