### ISSUE TITLE
[singleton]throw errer when client is not extensible

### ISSUE THREAD

**Issue by Rwing** [eggjs/egg#892]
```
// alias app[name] as client, but still support createInstance method
if (options.client) {
  const client = this.createInstance(options.client);
  this.app[this.name] = client;
  assert(!client.createInstance, 'singleton instance should not have createInstance method');
  client.createInstance = this.createInstance.bind(this);
  return;
}
```
https://github.com/eggjs/egg/blob/master/lib/core/singleton.js#L29

> /Users/Rwing/Project/***/node_modules/egg/lib/core/singleton.js:29
      client.createInstance = this.createInstance.bind(this);
                            ^
TypeError: Can't add property createInstance, object is not extensible
    at Singleton.init (/Users/Rwing/Project/***/node_modules/egg/lib/core/singleton.js:29:29)
    at Application.addSingleton (/Users/Rwing/Project/***/node_modules/egg/lib/egg.js:377:15)
    at module.exports.app (/Users/Rwing/Project/***/node_modules/egg-pg/lib/pg.js:9:7)
    at module.exports.app (/Users/Rwing/Project/***/node_modules/egg-pg/app.js:6:26)
    at AppWorkerLoader.loadFile (/Users/Rwing/Project/***/node_modules/egg-core/lib/loader/egg_loader.js:270:34)
    at getLoadUnits.forEach.unit (/Users/Rwing/Project/***/node_modules/egg-core/lib/loader/mixin/custom.js:25:29)
    at Array.forEach (native)
    at AppWorkerLoader.loadCustomApp (/Users/Rwing/Project/***/node_modules/egg-core/lib/loader/mixin/custom.js:25:8)
    at AppWorkerLoader.load (/Users/Rwing/Project/***/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
    at new Application (/Users/Rwing/Project/***/node_modules/egg/lib/application.js:34:19)

**Comment by dead-horse** [comment]
ensure your client is extensible.
