### ISSUE TITLE
app.js 是否不支持await写法

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#911]
* **Node Version**:  7.71
* **Plugin Name**:  
* **Plugin Version**:
* **Platform**:  windows
* **Mini Showcase Repository**:

app.js里想做一些数据库数据初始化，发现不支持await写法，用promise代码是没有报错的。

promise写法 
```
    app.model.Company.create({
      companyId: 'dddd',
    }).then( ()=>{
      console.log('初始化公司数据');
    });
```

await 写法
```
    await app.model.Company.create({
      companyId: 'dddddd',
    });
    console.log('初始化公司数据');
```
错误信息如下：
```
app.js:30
    await app.model.Company.create({
          ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.loadFile (d:\git\mab\egg-example\node_modules\egg-core\lib\utils\index.js:11:19)
    at AppWorkerLoader.loadFile (d:\git\mab\egg-example\node_modules\egg-core\lib\loader\egg_loader.js:266:23)
    at getLoadUnits.forEach.unit (d:\git\mab\egg-example\node_modules\egg-core\lib\loader\mixin\custom.js:25:29)
    at Array.forEach (native)
    at AppWorkerLoader.loadCustomApp (d:\git\mab\egg-example\node_modules\egg-core\lib\loader\mixin\custom.js:25:8)
    at AppWorkerLoader.load (d:\git\mab\egg-example\node_modules\egg\lib\loader\app_worker_loader.js:33:10)
    at new Application (d:\git\mab\egg-example\node_modules\egg\lib\application.js:34:19)
 
```

**Comment by dead-horse** [comment]
await 必须要在 async function 中，参考 https://eggjs.org/zh-cn/basics/app-start.html ，将 function* 和 yield 改成 async function 和 await

**Comment by a304885433** [comment]
@dead-horse  谢谢，已经解决。
