### ISSUE TITLE
为什么使用自定义配置文件，项目运行不起来？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#954]
我在config目录下自己创建了一个config.server.js自定义配置文件，然后用如下命令：

`EGG_SERVER_ENV=server npm run dev`

为什么老是运行不起来？不是说可以支持自定义配置文件吗？

```
2017-05-23 19:26:24,745 ERROR 16728 [app_worker] App Worker start error, exiting now!
[Tue May 23 2017 19:26:24 GMT+0800 (中国标准时间)] [cfork:master:12324] worker:16728 disconnect (suicide: false, state: disconnected, isDead: false)
[Tue May 23 2017 19:26:24 GMT+0800 (中国标准时间)] [cfork:master:12324] new worker:22404 fork (state: none)
2017-05-23 19:26:24,777 INFO 12324 [master] App Worker#1:16728 disconnect, suicide: false, state: disconnected, current workers: ["1","2"]
(node:12324) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2017-05-23 19:26:24,779 INFO 12324 [master] App Worker#2:22404 start, state: none, current workers: ["1","2"]
[Tue May 23 2017 19:26:24 GMT+0800 (中国标准时间)] [cfork:master:12324] worker:16728 exit (code: 1, suicide: false, state: dead, isDead: true, isExpected: true)
2017-05-23 19:26:24,792 ERROR 12324 nodejs.AppWorkerDiedError: [master] App Worker#1:16728 died (code: 1, signal: 1, suicide: false, state: dead), current workers: ["2"]
    at Master.onAppExit (G:\repository\ra\ra-api\node_modules\egg-cluster\lib\master.js:280:19)
    at emitOne (events.js:96:13)
    at Master.emit (events.js:191:7)
    at Messenger.sendToMaster (G:\repository\ra\ra-api\node_modules\egg-cluster\lib\utils\messenger.js:122:17)
    at Messenger.send (G:\repository\ra\ra-api\node_modules\egg-cluster\lib\utils\messenger.js:87:12)
    at EventEmitter.cluster.on (G:\repository\ra\ra-api\node_modules\egg-cluster\lib\master.js:190:22)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:197:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:293:19)
name: 'AppWorkerDiedError'
pid: 12324
hostname: yaochen

2017-05-23 19:26:24,812 ERROR 12324 [master] worker start fail, exit now
2017-05-23 19:26:24,814 INFO 12324 [master] exit with code: 1
⚠️ run command  got error: G:\repository\ra\ra-api\node_modules\egg-bin\lib\start-cluster {"baseDir":"G:\\repository\\ra\\ra-api","framework":"G:\\repository\\ra\\ra-api\\node_modules\\egg","workers":1} exit with code 1
Error: G:\repository\ra\ra-api\node_modules\egg-bin\lib\start-cluster {"baseDir":"G:\\repository\\ra\\ra-api","framework":"G:\\repository\\ra\\ra-api\\node_modules\\egg","workers":1} exit with code 1
    at ChildProcess.proc.once.code (G:\repository\ra\ra-api\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ra-api@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ra-api@1.0.0 dev script 'egg-bin dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ra-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     egg-bin dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ra-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ra-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\arden\AppData\Roaming\npm-cache\_logs\2017-05-23T11_26_24_925Z-debug.log
```

**Comment by atian25** [comment]
检查你的 `config.server.js` 是不是有语法错误，或者提供最小可复现代码。

**Comment by arden** [comment]
@atian25 我直接从config.local.js文件里拷过来的，一模一样，用 EGG_SERVER_ENV=local npm run dev 是没问题的。

**Comment by dead-horse** [comment]
是否有其他错误日志，common-error.log 或者 stderr.log

**Comment by atian25** [comment]
@arden 用 `egg-init --type=simple bug-report` 创建一个最小可复现代码提交下，我本地无法复现。

**Comment by arden** [comment]
@atian25
我知道是什么原因了：
1、是因为egg-redis这个plugin引起的，由于我用两个Redis，一个是3.0版本的，一个是3.2版的，而3.0版本好像不支持client.time()这个命令，\node_modules\egg-redis\lib\redis.js:49:33 在49行。所以报错了。
但是我有一个疑问，为什么在local模式下就没问题。我想应该是自定义配置文件模式下会强制以production生产模式运行，所以碰到这个问题。
另外我想问一下：为什么自定义配置文件下要强制以production环境运行。很多时候配置文件只是方便调试，我的项目想在服务器上做测试，需要一份配置文件，但是在服务器上做测试的时候也是希望以dev的环境运行。

**Comment by dead-horse** [comment]
> 我想应该是自定义配置文件模式下会强制以production生产模式运行，所以碰到这个问题。

你的猜测是错的，自定义配置与 NODE_ENV 没有关系。

**Comment by atian25** [comment]
没看懂你的回复，前面提到 redis 版本问题，后面变为环境变量了。

你指的 `production` 是 `NODE_ENV` ?

服务器环境下，这个变量应该永远是 `production`，如果你想自定义的话，可以在启动时加在前面。

而 `config.server.js` 是 `EGG_SERVER_ENV` 对应的 app.env 是 `server`，两者没有任何关系。

**Comment by arden** [comment]
1、这个问题是因为egg-redis这个plugin引起的，因为我把egg-redis这个插件里的client.time()去掉就可以了。只是我不明白为什么npm run dev的时候能够正常运行，但是在EGG-SERVER_ENV=server的时候就会报错。
2、环境变量的问题。我的意思是说为什么我用自定义配置文件的时候修改代码不能热加载(启动的时候是dev模式)，因为我只是想把代码放在服务器上做一测试，既然是做测试就希望能够代码实现热加载。

**Comment by atian25** [comment]
1. 第一个问题你试下 `NODE_ENV=production EGG_SERVER_ENV=server node index.js` 看看
2. 第二个问题，因为 `egg-development` 本身的设计，只在 `locals` 模式下运行。
如果你确实想在特定的 env 下运行它的话，试下下：

```js
// config/plugin.js
exports.development = {
  enable: true,
  env: [ 'local', 'MY_ENV'],
}
```

**Comment by arden** [comment]
@atian25
不行。

**Comment by atian25** [comment]
什么不行? 不行的具体是什么.... 说话不要说一半嘛
