### ISSUE TITLE
nodejs.ECONNRESETError: write ECONNRESET

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#957]
* **Node Version**:
v7.6.0
* **Egg Version**:
v1.3.0
* **Plugin Name**:
<video></video>
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

```
      <video
             id="vedio"
            controls
             width="300"
             height="180"
             preload="metadata"
            src="https://app.rarcbank.com/study/public/vedio/8581234/6.mp4"
             poster=""
      >
2017-05-24 08:54:49,610 ERROR 10600 [-/undefined/-/62ms GET /public/vedio/8581234/6.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'write'
headerSent: true
name: 'ECONNRESETError'
pid: 10600
hostname: WXWeb

在ios微信自带浏览器内发生如上错误 在安桌微信浏览器内就不会发生上述情况
```

**Comment by jinchaoxiang** [comment]
我放在代理服务器apache的公共文件夹里就可以反问了
放在egg的public里就不行 是不是反向代理的问题

**Comment by jinchaoxiang** [comment]
就video视频不行 img和audio都可以的

**Comment by dead-horse** [comment]
是文件太大了么？

**Comment by jinchaoxiang** [comment]
并不是 我使用了900k都不可以 现在只好将视频存在apache代理服务器下来访问了 不知道其他人有没有遇到

**Comment by dead-horse** [comment]
出现这个错误报错的原因一般是浏览器在接受响应的过程中断开了连接。先关了。

**Comment by andysjt** [comment]
我也碰到了这个问题
