### ISSUE TITLE
初始化项目出错 read ECONNRESET

### ISSUE THREAD

**Issue by berwin** [eggjs/egg#96]
```base
[test] egg-init --type simple showcase
[egg-init] /Users/xx/test/showcase is not exists, now create it.
[egg-init] dest dir is /Users/xx/test/showcase
Error: read ECONNRESET
    at exports._errnoException (util.js:896:11)
    at TLSWrap.onread (net.js:556:26)
```

**Comment by atian25** [comment]
ECONNRESET 是网络问题, 多试十几次看看.

现在应该还没支持国内的 npm 地址, cc @fengmk2

**Comment by atian25** [comment]
看了下, 默认已经是中国的了, `const REGISTRY = 'https://registry.npm.taobao.org';`

@berwin 你再试试

**Comment by berwin** [comment]
恩呢，可以啦。。多谢~
